import { Word } from './types';

export const a1Words: Word[] = [
    { word: "about", type: "prep., adv.", meaning: "เกี่ยวกับ, ประมาณ" },
    { word: "above", type: "prep., adv.", meaning: "เหนือ, ข้างบน" },
    { word: "across", type: "prep., adv.", meaning: "ข้าม, ตรงข้าม" },
    { word: "action", type: "n.", meaning: "การกระทำ" },
    { word: "activity", type: "n.", meaning: "กิจกรรม" },
    { word: "actor", type: "n.", meaning: "นักแสดงชาย" },
    { word: "actress", type: "n.", meaning: "นักแสดงหญิง" },
    { word: "add", type: "v.", meaning: "เพิ่ม" },
    { word: "address", type: "n.", meaning: "ที่อยู่" },
    { word: "adult", type: "n.", meaning: "ผู้ใหญ่" },
    { word: "advice", type: "n.", meaning: "คำแนะนำ" },
    { word: "afraid", type: "adj.", meaning: "กลัว" },
    { word: "after", type: "prep., adv., conj.", meaning: "หลังจาก" },
    { word: "afternoon", type: "n.", meaning: "ช่วงบ่าย" },
    { word: "again", type: "adv.", meaning: "อีกครั้ง" },
    { word: "age", type: "n.", meaning: "อายุ" },
    { word: "ago", type: "adv.", meaning: "ที่ผ่านมา" },
    { word: "agree", type: "v.", meaning: "เห็นด้วย" },
    { word: "air", type: "n.", meaning: "อากาศ" },
    { word: "airport", type: "n.", meaning: "สนามบิน" },
    { word: "all", type: "det., pron., adv.", meaning: "ทั้งหมด" },
    { word: "also", type: "adv.", meaning: "ด้วย, เช่นกัน" },
    { word: "always", type: "adv.", meaning: "เสมอ" },
    { word: "amazing", type: "adj.", meaning: "น่าทึ่ง" },
    { word: "and", type: "conj.", meaning: "และ" },
    { word: "angry", type: "adj.", meaning: "โกรธ" },
    { word: "animal", type: "n.", meaning: "สัตว์" },
    { word: "another", type: "det., pron.", meaning: "อีกหนึ่ง" },
    { word: "answer", type: "n., v.", meaning: "คำตอบ, ตอบ" },
    { word: "any", type: "det., pron.", meaning: "ใด ๆ" },
    { word: "anyone", type: "pron.", meaning: "ใครก็ได้" },
    { word: "anything", type: "pron.", meaning: "อะไรก็ได้" },
    { word: "apartment", type: "n.", meaning: "อพาร์ตเมนต์" },
    { word: "apple", type: "n.", meaning: "แอปเปิล" },
    { word: "April", type: "n.", meaning: "เดือนเมษายน" },
    { word: "area", type: "n.", meaning: "พื้นที่" },
    { word: "arm", type: "n.", meaning: "แขน" },
    { word: "around", type: "prep., adv.", meaning: "รอบ ๆ" },
    { word: "arrive", type: "v.", meaning: "มาถึง" },
    { word: "art", type: "n.", meaning: "ศิลปะ" },
    { word: "article", type: "n.", meaning: "บทความ" },
    { word: "artist", type: "n.", meaning: "ศิลปิน" },
    { word: "ask", type: "v.", meaning: "ถาม" },
    { word: "at", type: "prep.", meaning: "ที่" },
    { word: "August", type: "n.", meaning: "เดือนสิงหาคม" },
    { word: "aunt", type: "n.", meaning: "ป้า, น้า, อา (ผู้หญิง)" },
    { word: "autumn", type: "n.", meaning: "ฤดูใบไม้ร่วง" },
    { word: "away", type: "adv.", meaning: "ออกไป, ห่างออกไป" },
    { word: "baby", type: "n.", meaning: "ทารก" },
    { word: "back", type: "n., adv., adj.", meaning: "หลัง, กลับ" },
    { word: "bad", type: "adj.", meaning: "ไม่ดี" },
    { word: "bag", type: "n.", meaning: "กระเป๋า" },
    { word: "ball", type: "n.", meaning: "ลูกบอล" },
    { word: "banana", type: "n.", meaning: "กล้วย" },
    { word: "band", type: "n.", meaning: "วงดนตรี" },
    { word: "bank", type: "n.", meaning: "ธนาคาร" },
    { word: "bath", type: "n.", meaning: "อาบน้ำ" },
    { word: "bathroom", type: "n.", meaning: "ห้องน้ำ" },
    { word: "be", type: "v.", meaning: "เป็น, อยู่, คือ" },
    { word: "beach", type: "n.", meaning: "ชายหาด" },
    { word: "bear", type: "n.", meaning: "หมี" },
    { word: "beautiful", type: "adj.", meaning: "สวยงาม" },
    { word: "because", type: "conj.", meaning: "เพราะว่า" },
    { word: "become", type: "v.", meaning: "กลายเป็น" },
    { word: "bed", type: "n.", meaning: "เตียง" },
    { word: "bedroom", type: "n.", meaning: "ห้องนอน" },
    { word: "beer", type: "n.", meaning: "เบียร์" },
    { word: "before", type: "prep., conj., adv.", meaning: "ก่อน" },
    { word: "begin", type: "v.", meaning: "เริ่มต้น" },
    { word: "beginning", type: "n.", meaning: "จุดเริ่มต้น" },
    { word: "behind", type: "prep., adv.", meaning: "ข้างหลัง" },
    { word: "believe", type: "v.", meaning: "เชื่อ" },
    { word: "below", type: "prep., adv.", meaning: "ข้างล่าง" },
    { word: "best", type: "adj., adv., n.", meaning: "ดีที่สุด" },
    { word: "better", type: "adj., adv.", meaning: "ดีกว่า" },
    { word: "between", type: "prep., adv.", meaning: "ระหว่าง" },
    { word: "bicycle", type: "n.", meaning: "จักรยาน" },
    { word: "big", type: "adj.", meaning: "ใหญ่" },
    { word: "bike", type: "n.", meaning: "จักรยาน" },
    { word: "bill", type: "n.", meaning: "ใบเสร็จ, บิล" },
    { word: "bird", type: "n.", meaning: "นก" },
    { word: "birthday", type: "n.", meaning: "วันเกิด" },
    { word: "black", type: "adj.", meaning: "สีดำ" },
    { word: "blog", type: "n.", meaning: "บล็อก (เว็บไซต์ส่วนตัว)" },
    { word: "blonde", type: "adj.", meaning: "ผมสีบลอนด์" },
    { word: "blood", type: "n.", meaning: "เลือด" },
    { word: "blanket", type: "n.", meaning: "ผ้าห่ม" },
    { word: "blind", type: "adj.", meaning: "ตาบอด" },
    { word: "block", type: "n.", meaning: "บล็อก, ก้อน" },
    { word: "blood", type: "n.", meaning: "เลือด" },
    { word: "blue", type: "adj., n.", meaning: "สีน้ำเงิน" },
    { word: "boat", type: "n.", meaning: "เรือ" },
    { word: "body", type: "n.", meaning: "ร่างกาย" },
    { word: "book", type: "n.", meaning: "หนังสือ" },
    { word: "boot", type: "n.", meaning: "รองเท้าบู๊ต" },
    { word: "bored", type: "adj.", meaning: "เบื่อหน่าย" },
    { word: "boring", type: "adj.", meaning: "น่าเบื่อ" },
    { word: "born", type: "v.", meaning: "เกิด" },
    { word: "both", type: "det., pron.", meaning: "ทั้งสอง" },
    { word: "bottle", type: "n.", meaning: "ขวด" },
    { word: "box", type: "n.", meaning: "กล่อง" },
    { word: "boy", type: "n.", meaning: "เด็กผู้ชาย" },
    { word: "boyfriend", type: "n.", meaning: "แฟน (ผู้ชาย)" },
    { word: "bread", type: "n.", meaning: "ขนมปัง" },
    { word: "break", type: "v., n.", meaning: "ทำลาย, แตก, การพัก" },
    { word: "breakfast", type: "n.", meaning: "อาหารเช้า" },
    { word: "bring", type: "v.", meaning: "นำมา" },
    { word: "brother", type: "n.", meaning: "พี่ชาย, น้องชาย" },
    { word: "brown", type: "adj., n.", meaning: "สีน้ำตาล" },
    { word: "build", type: "v.", meaning: "สร้าง" },
    { word: "building", type: "n.", meaning: "อาคาร" },
    { word: "bus", type: "n.", meaning: "รถประจำทาง" },
    { word: "business", type: "n.", meaning: "ธุรกิจ" },
    { word: "busy", type: "adj.", meaning: "ยุ่ง" },
    { word: "but", type: "conj.", meaning: "แต่" },
    { word: "butter", type: "n.", meaning: "เนย" },
    { word: "buy", type: "v.", meaning: "ซื้อ" },
    { word: "by", type: "prep.", meaning: "โดย, ข้างๆ" },
    { word: "bye", type: "exclam.", meaning: "ลาก่อน" },
    { word: "cafe", type: "n.", meaning: "ร้านกาแฟ" },
    { word: "cake", type: "n.", meaning: "เค้ก" },
    { word: "call", type: "v., n.", meaning: "เรียก, โทรศัพท์, การเรียก" },
    { word: "camera", type: "n.", meaning: "กล้องถ่ายรูป" },
    { word: "can", type: "modal v.", meaning: "สามารถ" },
    { word: "cannot", type: "modal v.", meaning: "ไม่สามารถ" },
    { word: "capital", type: "n., adj.", meaning: "เมืองหลวง, ตัวพิมพ์ใหญ่" },
    { word: "car", type: "n.", meaning: "รถยนต์" },
    { word: "card", type: "n.", meaning: "บัตร" },
    { word: "career", type: "n.", meaning: "อาชีพ" },
    { word: "carrot", type: "n.", meaning: "แครอท" },
    { word: "carry", type: "v.", meaning: "ถือ, แบก" },
    { word: "cat", type: "n.", meaning: "แมว" },
    { word: "CD", type: "n.", meaning: "ซีดี" },
    { word: "cent", type: "n.", meaning: "เซ็นต์ (หน่วยเงิน)" },
    { word: "centre", type: "n.", meaning: "ศูนย์กลาง" },
    { word: "century", type: "n.", meaning: "ศตวรรษ" },
    { word: "chair", type: "n.", meaning: "เก้าอี้" },
    { word: "change", type: "v., n.", meaning: "เปลี่ยน, การเปลี่ยนแปลง" },
    { word: "chart", type: "n.", meaning: "แผนภูมิ" },
    { word: "cheap", type: "adj.", meaning: "ราคาถูก" },
    { word: "check", type: "v.", meaning: "ตรวจสอบ" },
    { word: "cheese", type: "n.", meaning: "ชีส" },
    { word: "chicken", type: "n.", meaning: "ไก่" },
    { word: "child", type: "n.", meaning: "เด็ก" },
    { word: "chocolate", type: "n.", meaning: "ช็อกโกแลต" },
    { word: "choose", type: "v.", meaning: "เลือก" },
    { word: "cinema", type: "n.", meaning: "โรงภาพยนตร์" },
    { word: "city", type: "n.", meaning: "เมือง" },
    { word: "class", type: "n.", meaning: "ชั้นเรียน, ชนชั้น" },
    { word: "classroom", type: "n.", meaning: "ห้องเรียน" },
    { word: "clean", type: "adj., v.", meaning: "สะอาด, ทำความสะอาด" },
    { word: "climb", type: "v.", meaning: "ปีน" },
    { word: "clock", type: "n.", meaning: "นาฬิกา" },
    { word: "close", type: "v.", meaning: "ปิด" },
    { word: "clothes", type: "n.", meaning: "เสื้อผ้า" },
    { word: "club", type: "n.", meaning: "ชมรม, สโมสร" },
    { word: "coat", type: "n.", meaning: "เสื้อโค้ท" },
    { word: "coffee", type: "n.", meaning: "กาแฟ" },
    { word: "cold", type: "adj., n.", meaning: "หนาว, เย็น, โรคหวัด" },
    { word: "college", type: "n.", meaning: "วิทยาลัย" },
    { word: "colour", type: "n.", meaning: "สี" },
    { word: "come", type: "v.", meaning: "มา" },
    { word: "common", type: "adj.", meaning: "ทั่วไป, ธรรมดา" },
    { word: "company", type: "n.", meaning: "บริษัท, เพื่อน" },
    { word: "compare", type: "v.", meaning: "เปรียบเทียบ" },
    { word: "complete", type: "adj., v.", meaning: "สมบูรณ์, ทำให้สมบูรณ์" },
    { word: "computer", type: "n.", meaning: "คอมพิวเตอร์" },
    { word: "concert", type: "n.", meaning: "คอนเสิร์ต" },
    { word: "conversation", type: "n.", meaning: "การสนทนา" },
    { word: "cook", type: "v.", meaning: "ทำอาหาร" },
    { word: "cooking", type: "n.", meaning: "การทำอาหาร" },
    { word: "cool", type: "adj.", meaning: "เย็น, เจ๋ง" },
    { word: "correct", type: "adj., v.", meaning: "ถูกต้อง, แก้ไขให้ถูกต้อง" },
    { word: "cost", type: "n., v.", meaning: "ราคา, มีราคา" },
    { word: "could", type: "modal v.", meaning: "สามารถ (รูปอดีตของ can)" },
    { word: "country", type: "n.", meaning: "ประเทศ, ชนบท" },
    { word: "course", type: "n.", meaning: "หลักสูตร, แขนงวิชา" },
    { word: "cousin", type: "n.", meaning: "ลูกพี่ลูกน้อง" },
    { word: "cow", type: "n.", meaning: "วัว" },
    { word: "cream", type: "n.", meaning: "ครีม" },
    { word: "create", type: "v.", meaning: "สร้าง" },
    { word: "culture", type: "n.", meaning: "วัฒนธรรม" },
    { word: "cup", type: "n.", meaning: "ถ้วย" },
    { word: "customer", type: "n.", meaning: "ลูกค้า" },
    { word: "cut", type: "v.", meaning: "ตัด" },
    { word: "dad", type: "n.", meaning: "พ่อ" },
    { word: "dance", type: "n., v.", meaning: "การเต้นรำ, เต้นรำ" },
    { word: "dancer", type: "n.", meaning: "นักเต้น" },
    { word: "dancing", type: "n.", meaning: "การเต้นรำ" },
    { word: "dangerous", type: "adj.", meaning: "อันตราย" },
    { word: "dark", type: "adj.", meaning: "มืด, เข้ม" },
    { word: "date", type: "n.", meaning: "วันที่, เดท" },
    { word: "daughter", type: "n.", meaning: "ลูกสาว" },
    { word: "day", type: "n.", meaning: "วัน" },
    { word: "dear", type: "adj.", meaning: "ที่รัก, แพง" },
    { word: "December", type: "n.", meaning: "เดือนธันวาคม" },
    { word: "decide", type: "v.", meaning: "ตัดสินใจ" },
    { word: "delicious", type: "adj.", meaning: "อร่อย" },
    { word: "describe", type: "v.", meaning: "บรรยาย, อธิบาย" },
    { word: "description", type: "n.", meaning: "คำบรรยาย, รายละเอียด" },
    { word: "design", type: "n., v.", meaning: "การออกแบบ, ออกแบบ" },
    { word: "desk", type: "n.", meaning: "โต๊ะทำงาน" },
    { word: "detail", type: "n.", meaning: "รายละเอียด" },
    { word: "dialogue", type: "n.", meaning: "บทสนทนา" },
    { word: "dictionary", type: "n.", meaning: "พจนานุกรม" },
    { word: "die", type: "v.", meaning: "ตาย" },
    { word: "diet", type: "n.", meaning: "อาหาร, การควบคุมอาหาร" },
    { word: "difference", type: "n.", meaning: "ความแตกต่าง" },
    { word: "different", type: "adj.", meaning: "แตกต่างกัน" },
    { word: "difficult", type: "adj.", meaning: "ยาก" },
    { word: "dinner", type: "n.", meaning: "อาหารเย็น" },
    { word: "dirty", type: "adj.", meaning: "สกปรก" },
    { word: "discuss", type: "v.", meaning: "อภิปราย, ถกเถียง" },
    { word: "dish", type: "n.", meaning: "จาน, อาหาร" },
    { word: "do", type: "v., auxiliary v.", meaning: "ทำ, กริยาช่วย" },
    { word: "doctor", type: "n.", meaning: "หมอ, แพทย์" },
    { word: "dog", type: "n.", meaning: "สุนัข" },
    { word: "dollar", type: "n.", meaning: "ดอลลาร์" },
    { word: "door", type: "n.", meaning: "ประตู" },
    { word: "down", type: "adv., prep.", meaning: "ลง, ข้างล่าง" },
    { word: "downstairs", type: "adv.", meaning: "ชั้นล่าง" },
    { word: "draw", type: "v.", meaning: "วาด" },
    { word: "dress", type: "n., v.", meaning: "ชุดกระโปรง, แต่งตัว" },
    { word: "drink", type: "n., v.", meaning: "เครื่องดื่ม, ดื่ม" },
    { word: "drive", type: "v.", meaning: "ขับรถ" },
    { word: "driver", type: "n.", meaning: "คนขับรถ" },
    { word: "during", type: "prep.", meaning: "ระหว่าง" },
    { word: "DVD", type: "n.", meaning: "ดีวีดี" },
    { word: "each", type: "det./pron./adv.", meaning: "แต่ละ" },
    { word: "ear", type: "n.", meaning: "หู" },
    { word: "early", type: "adj., adv.", meaning: "แต่เช้า, ก่อนเวลา" },
    { word: "east", type: "n., adj., adv.", meaning: "ทิศตะวันออก, ทางทิศตะวันออก" },
    { word: "easy", type: "adj.", meaning: "ง่าย" },
    { word: "eat", type: "v.", meaning: "กิน" },
    { word: "egg", type: "n.", meaning: "ไข่" },
    { word: "eight", type: "number", meaning: "แปด" },
    { word: "eighteen", type: "number", meaning: "สิบแปด" },
    { word: "eighty", type: "number", meaning: "แปดสิบ" },
    { word: "elephant", type: "n.", meaning: "ช้าง" },
    { word: "eleven", type: "number", meaning: "สิบเอ็ด" },
    { word: "else", type: "adv.", meaning: "อื่น, อย่างอื่น" },
    { word: "email", type: "n., v.", meaning: "อีเมล, ส่งอีเมล" },
    { word: "end", type: "n., v.", meaning: "จุดสิ้นสุด, สิ้นสุด" },
    { word: "enjoy", type: "v.", meaning: "สนุกกับ" },
    { word: "enough", type: "det., pron., adv.", meaning: "พอ, เพียงพอ" },
    { word: "euro", type: "n.", meaning: "ยูโร (หน่วยเงิน)" },
    { word: "even", type: "adv.", meaning: "แม้แต่, เสมอกัน" },
    { word: "evening", type: "n.", meaning: "ตอนเย็น, ค่ำ" },
    { word: "event", type: "n.", meaning: "เหตุการณ์, งาน" },
    { word: "ever", type: "adv.", meaning: "เคย, ตลอดไป" },
    { word: "every", type: "det.", meaning: "ทุกๆ" },
    { word: "everybody", type: "pron.", meaning: "ทุกคน" },
    { word: "everyone", type: "pron.", meaning: "ทุกคน" },
    { word: "everything", type: "pron.", meaning: "ทุกสิ่งทุกอย่าง" },
    { word: "exam", type: "n.", meaning: "การสอบ" },
    { word: "example", type: "n.", meaning: "ตัวอย่าง" },
    { word: "excited", type: "adj.", meaning: "ตื่นเต้น" },
    { word: "exciting", type: "adj.", meaning: "น่าตื่นเต้น" },
    { word: "exercise", type: "n., v.", meaning: "การออกกำลังกาย, ออกกำลังกาย" },
    { word: "expensive", type: "adj.", meaning: "แพง" },
    { word: "explain", type: "v.", meaning: "อธิบาย" },
    { word: "extra", type: "adj.", meaning: "เพิ่มเติม, พิเศษ" },
    { word: "eye", type: "n.", meaning: "ตา" },
    { word: "face", type: "n.", meaning: "ใบหน้า, เผชิญหน้า" },
    { word: "fact", type: "n.", meaning: "ความจริง" },
    { word: "fall", type: "v.", meaning: "ตก, ล้ม" },
    { word: "false", type: "adj.", meaning: "เท็จ, ไม่จริง" },
    { word: "family", type: "n., adj.", meaning: "ครอบครัว, เกี่ยวกับครอบครัว" },
    { word: "famous", type: "adj.", meaning: "มีชื่อเสียง" },
    { word: "fantastic", type: "adj.", meaning: "ยอดเยี่ยม, มหัศจรรย์" },
    { word: "far", type: "adv.", meaning: "ไกล" },
    { word: "farm", type: "n.", meaning: "ฟาร์ม" },
    { word: "farmer", type: "n.", meaning: "ชาวนา, เกษตรกร" },
    { word: "fast", type: "adj., adv.", meaning: "เร็ว, รวดเร็ว" },
    { word: "fat", type: "adj.", meaning: "อ้วน, ไขมัน" },
    { word: "father", type: "n.", meaning: "พ่อ" },
    { word: "favourite", type: "adj., n.", meaning: "ที่ชื่นชอบ, สิ่งที่ชื่นชอบ" },
    { word: "February", type: "n.", meaning: "เดือนกุมภาพันธ์" },
    { word: "feel", type: "v.", meaning: "รู้สึก" },
    { word: "feeling", type: "n.", meaning: "ความรู้สึก" },
    { word: "festival", type: "n.", meaning: "เทศกาล" },
    { word: "few", type: "det./adj., pron.", meaning: "สองสาม, เล็กน้อย" },
    { word: "fifteen", type: "number", meaning: "สิบห้า" },
    { word: "fifth", type: "number", meaning: "ที่ห้า" },
    { word: "fifty", type: "number", meaning: "ห้าสิบ" },
    { word: "fill", type: "v.", meaning: "เติมให้เต็ม" },
    { word: "film", type: "n.", meaning: "ภาพยนตร์" },
    { word: "final", type: "adj.", meaning: "สุดท้าย, รอบสุดท้าย" },
    { word: "find", type: "v.", meaning: "หา, พบ" },
    { word: "fine", type: "adj.", meaning: "สบายดี, ดี, ปรับไหม" },
    { word: "finish", type: "v.", meaning: "เสร็จสิ้น, จบ" },
    { word: "fire", type: "n.", meaning: "ไฟ" },
    { word: "first", type: "det./number, adv.", meaning: "ที่หนึ่ง, ครั้งแรก" },
    { word: "fish", type: "n.", meaning: "ปลา" },
    { word: "five", type: "number", meaning: "ห้า" },
    { word: "flat", type: "n.", meaning: "อพาร์ตเมนต์ (UK), แบน" },
    { word: "flight", type: "n.", meaning: "เที่ยวบิน" },
    { word: "floor", type: "n.", meaning: "พื้น, ชั้น" },
    { word: "flower", type: "n.", meaning: "ดอกไม้" },
    { word: "fly", type: "v.", meaning: "บิน" },
    { word: "follow", type: "v.", meaning: "ติดตาม, ทำตาม" },
    { word: "food", type: "n.", meaning: "อาหาร" },
    { word: "foot", type: "n.", meaning: "เท้า" },
    { word: "football", type: "n.", meaning: "ฟุตบอล" },
    { word: "for", type: "prep.", meaning: "สำหรับ, เป็นเวลา" },
    { word: "forget", type: "v.", meaning: "ลืม" },
    { word: "form", type: "n., v.", meaning: "แบบฟอร์ม, รูปแบบ, ก่อตัว" },
    { word: "forty", type: "number", meaning: "สี่สิบ" },
    { word: "four", type: "number", meaning: "สี่" },
    { word: "fourteen", type: "number", meaning: "สิบสี่" },
    { word: "fourth", type: "number", meaning: "ที่สี่" },
    { word: "free", type: "adj.", meaning: "ฟรี, อิสระ" },
    { word: "Friday", type: "n.", meaning: "วันศุกร์" },
    { word: "friend", type: "n.", meaning: "เพื่อน" },
    { word: "friendly", type: "adj.", meaning: "เป็นกันเอง" },
    { word: "from", type: "prep.", meaning: "จาก" },
    { word: "front", type: "n., adj.", meaning: "ด้านหน้า, ข้างหน้า" },
    { word: "fruit", type: "n.", meaning: "ผลไม้" },
    { word: "full", type: "adj.", meaning: "เต็ม" },
    { word: "fun", type: "n.", meaning: "ความสนุกสนาน" },
    { word: "funny", type: "adj.", meaning: "ตลก" },
    { word: "future", type: "n.", meaning: "อนาคต" },
    { word: "game", type: "n.", meaning: "เกม" },
    { word: "garden", type: "n.", meaning: "สวน" },
    { word: "geography", type: "n.", meaning: "ภูมิศาสตร์" },
    { word: "get", type: "v.", meaning: "ได้รับ, ไปถึง" },
    { word: "girl", type: "n.", meaning: "เด็กผู้หญิง" },
    { word: "girlfriend", type: "n.", meaning: "แฟน (ผู้หญิง)" },
    { word: "give", type: "v.", meaning: "ให้" },
    { word: "glass", type: "n.", meaning: "แก้ว, กระจก" },
    { word: "go", type: "v.", meaning: "ไป" },
    { word: "good", type: "adj.", meaning: "ดี" },
    { word: "goodbye", type: "exclam./n.", meaning: "ลาก่อน" },
    { word: "grandfather", type: "n.", meaning: "ปู่, ตา" },
    { word: "grandmother", type: "n.", meaning: "ย่า, ยาย" },
    { word: "grandparent", type: "n.", meaning: "ปู่ย่าตายาย" },
    { word: "great", type: "adj.", meaning: "ยอดเยี่ยม, ดีมาก" },
    { word: "green", type: "adj., n.", meaning: "สีเขียว" },
    { word: "grey", type: "adj., n.", meaning: "สีเทา" },
    { word: "group", type: "n.", meaning: "กลุ่ม" },
    { word: "grow", type: "v.", meaning: "เติบโต, ปลูก" },
    { word: "guess", type: "v., n.", meaning: "เดา, การเดา" },
    { word: "guitar", type: "n.", meaning: "กีตาร์" },
    { word: "gym", type: "n.", meaning: "โรงยิม" },
    { word: "hair", type: "n.", meaning: "ผม" },
    { word: "half", type: "n., det./pron.", meaning: "ครึ่ง" },
    { word: "hand", type: "n.", meaning: "มือ" },
    { word: "happen", type: "v.", meaning: "เกิดขึ้น" },
    { word: "happy", type: "adj.", meaning: "มีความสุข" },
    { word: "hard", type: "adj., adv.", meaning: "ยาก, แข็ง, อย่างหนัก" },
    { word: "hat", type: "n.", meaning: "หมวก" },
    { word: "hate", type: "v.", meaning: "เกลียด" },
    { word: "have", type: "v.", meaning: "มี" },
    { word: "have to", type: "modal v.", meaning: "ต้อง" },
    { word: "he", type: "pron.", meaning: "เขา (ผู้ชาย)" },
    { word: "head", type: "n.", meaning: "ศีรษะ" },
    { word: "health", type: "n.", meaning: "สุขภาพ" },
    { word: "healthy", type: "adj.", meaning: "มีสุขภาพดี" },
    { word: "hear", type: "v.", meaning: "ได้ยิน" },
    { word: "hello", type: "exclam./n.", meaning: "สวัสดี" },
    { word: "help", type: "v., n.", meaning: "ช่วย, ความช่วยเหลือ" },
    { word: "her", type: "pron., det.", meaning: "ของเธอ (ผู้หญิง), เธอ (กรรม)" },
    { word: "here", type: "adv.", meaning: "ที่นี่" },
    { word: "hey", type: "exclam.", meaning: "เฮ้" },
    { word: "hi", type: "exclam.", meaning: "สวัสดี" },
    { word: "high", type: "adj.", meaning: "สูง" },
    { word: "him", type: "pron.", meaning: "เขา (ผู้ชาย, กรรม)" },
    { word: "his", type: "det.", meaning: "ของเขา (ผู้ชาย)" },
    { word: "history", type: "n.", meaning: "ประวัติศาสตร์" },
    { word: "hobby", type: "n.", meaning: "งานอดิเรก" },
    { word: "holiday", type: "n.", meaning: "วันหยุด" },
    { word: "home", type: "n., adv.", meaning: "บ้าน, ที่บ้าน" },
    { word: "homework", type: "n.", meaning: "การบ้าน" },
    { word: "hope", type: "v.", meaning: "หวัง" },
    { word: "horse", type: "n.", meaning: "ม้า" },
    { word: "hospital", type: "n.", meaning: "โรงพยาบาล" },
    { word: "hot", type: "adj.", meaning: "ร้อน" },
    { word: "hotel", type: "n.", meaning: "โรงแรม" },
    { word: "hour", type: "n.", meaning: "ชั่วโมง" },
    { word: "house", type: "n.", meaning: "บ้าน" },
    { word: "how", type: "adv.", meaning: "อย่างไร" },
    { word: "however", type: "adv.", meaning: "อย่างไรก็ตาม" },
    { word: "hundred", type: "number", meaning: "ร้อย" },
    { word: "hungry", type: "adj.", meaning: "หิว" },
    { word: "husband", type: "n.", meaning: "สามี" },
    { word: "ice", type: "n.", meaning: "น้ำแข็ง" },
    { word: "ice cream", type: "n.", meaning: "ไอศกรีม" },
    { word: "idea", type: "n.", meaning: "ความคิด, แนวคิด" },
    { word: "if", type: "conj.", meaning: "ถ้า" },
    { word: "imagine", type: "v.", meaning: "จินตนาการ" },
    { word: "important", type: "adj.", meaning: "สำคัญ" },
    { word: "improve", type: "v.", meaning: "ปรับปรุง, ทำให้ดีขึ้น" },
    { word: "in", type: "prep., adv.", meaning: "ใน, ข้างใน" },
    { word: "include", type: "v.", meaning: "รวมถึง" },
    { word: "information", type: "n.", meaning: "ข้อมูล" },
    { word: "interest", type: "n., v.", meaning: "ความสนใจ, ทำให้สนใจ" },
    { word: "interested", type: "adj.", meaning: "สนใจ" },
    { word: "interesting", type: "adj.", meaning: "น่าสนใจ" },
    { word: "internet", type: "n.", meaning: "อินเทอร์เน็ต" },
    { word: "interview", type: "n., v.", meaning: "การสัมภาษณ์, สัมภาษณ์" },
    { word: "into", type: "prep.", meaning: "เข้าไปใน" },
    { word: "introduce", type: "v.", meaning: "แนะนำ" },
    { word: "island", type: "n.", meaning: "เกาะ" },
    { word: "it", type: "pron.", meaning: "มัน" },
    { word: "its", type: "det.", meaning: "ของมัน" },
    { word: "jacket", type: "n.", meaning: "เสื้อแจ็กเก็ต" },
    { word: "January", type: "n.", meaning: "เดือนมกราคม" },
    { word: "jeans", type: "n.", meaning: "กางเกงยีนส์" },
    { word: "job", type: "n.", meaning: "งาน, อาชีพ" },
    { word: "join", type: "v.", meaning: "เข้าร่วม" },
    { word: "journey", type: "n.", meaning: "การเดินทาง" },
    { word: "juice", type: "n.", meaning: "น้ำผลไม้" },
    { word: "July", type: "n.", meaning: "เดือนกรกฎาคม" },
    { word: "June", type: "n.", meaning: "เดือนมิถุนายน" },
    { word: "just", type: "adv.", meaning: "เพิ่งจะ, แค่" },
    { word: "keep", type: "v.", meaning: "เก็บ, รักษา" },
    { word: "key", type: "n., adj.", meaning: "กุญแจ, สำคัญ" },
    { word: "kilometre", type: "n.", meaning: "กิโลเมตร" },
    { word: "kind", type: "n.", meaning: "ชนิด, ประเภท" },
    { word: "kitchen", type: "n.", meaning: "ห้องครัว" },
    { word: "know", type: "v.", meaning: "รู้, รู้จัก" },
    { word: "land", type: "n.", meaning: "แผ่นดิน, ที่ดิน" },
    { word: "language", type: "n.", meaning: "ภาษา" },
    { word: "large", type: "adj.", meaning: "ใหญ่" },
    { word: "last", type: "det.", meaning: "สุดท้าย, ที่แล้ว" },
    { word: "late", type: "adj., adv.", meaning: "สาย, ช้า" },
    { word: "later", type: "adv.", meaning: "ภายหลัง" },
    { word: "laugh", type: "v., n.", meaning: "หัวเราะ, เสียงหัวเราะ" },
    { word: "learn", type: "v.", meaning: "เรียนรู้" },
    { word: "leave", type: "v.", meaning: "ออกไป, ทิ้งไว้" },
    { word: "left", type: "adj., adv., n.", meaning: "ซ้าย, เหลือ, ข้างซ้าย" },
    { word: "leg", type: "n.", meaning: "ขา" },
    { word: "lesson", type: "n.", meaning: "บทเรียน" },
    { word: "let", type: "v.", meaning: "อนุญาต" },
    { word: "letter", type: "n.", meaning: "ตัวอักษร, จดหมาย" },
    { word: "library", type: "n.", meaning: "ห้องสมุด" },
    { word: "lie", type: "v.", meaning: "นอน, วาง, โกหก" },
    { word: "life", type: "n.", meaning: "ชีวิต" },
    { word: "light", type: "n., adj.", meaning: "แสง, เบา" },
    { word: "like", type: "prep., v.", meaning: "เหมือน, เช่น, ชอบ" },
    { word: "line", type: "n.", meaning: "เส้น, แถว" },
    { word: "lion", type: "n.", meaning: "สิงโต" },
    { word: "list", type: "n., v.", meaning: "รายการ, ทำรายการ" },
    { word: "listen", type: "v.", meaning: "ฟัง" },
    { word: "little", type: "adj., det./pron.", meaning: "เล็กน้อย, น้อย" },
    { word: "live", type: "v.", meaning: "อาศัยอยู่" },
    { word: "local", type: "adj.", meaning: "ท้องถิ่น" },
    { word: "long", type: "adj., adv.", meaning: "ยาว, นาน" },
    { word: "look", type: "v.", meaning: "มอง, ดู" },
    { word: "lose", type: "v.", meaning: "แพ้, ทำหาย" },
    { word: "lot", type: "pron., det., adv.", meaning: "มาก" },
    { word: "love", type: "n., v.", meaning: "ความรัก, รัก" },
    { word: "lunch", type: "n.", meaning: "อาหารกลางวัน" },
    { word: "machine", type: "n.", meaning: "เครื่องจักร" },
    { word: "magazine", type: "n.", meaning: "นิตยสาร" },
    { word: "main", type: "adj.", meaning: "หลัก, สำคัญ" },
    { word: "make", type: "v.", meaning: "ทำ, สร้าง" },
    { word: "man", type: "n.", meaning: "ผู้ชาย" },
    { word: "many", type: "det./pron.", meaning: "มาก (นับได้)" },
    { word: "map", type: "n.", meaning: "แผนที่" },
    { word: "March", type: "n.", meaning: "เดือนมีนาคม" },
    { word: "market", type: "n.", meaning: "ตลาด" },
    { word: "married", type: "adj.", meaning: "แต่งงานแล้ว" },
    { word: "match", type: "n., v.", meaning: "การแข่งขัน, เข้าคู่, ตรงกัน" },
    { word: "May", type: "n.", meaning: "เดือนพฤษภาคม, อาจจะ" },
    { word: "maybe", type: "adv.", meaning: "อาจจะ" },
    { word: "me", type: "pron.", meaning: "ฉัน (กรรม)" },
    { word: "meal", type: "n.", meaning: "มื้ออาหาร" },
    { word: "mean", type: "v.", meaning: "หมายความว่า" },
    { word: "meaning", type: "n.", meaning: "ความหมาย" },
    { word: "meat", type: "n.", meaning: "เนื้อ" },
    { word: "meet", type: "v.", meaning: "พบ, เจอ" },
    { word: "meeting", type: "n.", meaning: "การประชุม" },
    { word: "member", type: "n.", meaning: "สมาชิก" },
    { word: "menu", type: "n.", meaning: "เมนู" },
    { word: "message", type: "n.", meaning: "ข้อความ" },
    { word: "metre", type: "n.", meaning: "เมตร" },
    { word: "midnight", type: "n.", meaning: "เที่ยงคืน" },
    { word: "mile", type: "n.", meaning: "ไมล์" },
    { word: "milk", type: "n.", meaning: "นม" },
    { word: "million", type: "number", meaning: "ล้าน" },
    { word: "minute", type: "n.", meaning: "นาที" },
    { word: "miss", type: "v.", meaning: "คิดถึง, พลาด" },
    { word: "mistake", type: "n.", meaning: "ความผิดพลาด" },
    { word: "model", type: "n.", meaning: "แบบจำลอง, นางแบบ" },
    { word: "modern", type: "adj.", meaning: "ทันสมัย" },
    { word: "moment", type: "n.", meaning: "ชั่วขณะ, ขณะนี้" },
    { word: "Monday", type: "n.", meaning: "วันจันทร์" },
    { word: "money", type: "n.", meaning: "เงิน" },
    { word: "month", type: "n.", meaning: "เดือน" },
    { word: "more", type: "det./pron., adv.", meaning: "มากกว่า" },
    { word: "morning", type: "n.", meaning: "ตอนเช้า" },
    { word: "most", type: "det./pron., adv.", meaning: "ส่วนใหญ่, มากที่สุด" },
    { word: "mother", type: "n.", meaning: "แม่" },
    { word: "mountain", type: "n.", meaning: "ภูเขา" },
    { word: "mouse", type: "n.", meaning: "หนู" },
    { word: "mouth", type: "n.", meaning: "ปาก" },
    { word: "move", type: "v.", meaning: "เคลื่อนไหว, ย้าย" },
    { word: "movie", type: "n.", meaning: "ภาพยนตร์" },
    { word: "much", type: "det./pron., adv.", meaning: "มาก (นับไม่ได้)" },
    { word: "mum", type: "n.", meaning: "แม่ (UK)" },
    { word: "museum", type: "n.", meaning: "พิพิธภัณฑ์" },
    { word: "music", type: "n.", meaning: "ดนตรี" },
    { word: "must", type: "modal v.", meaning: "ต้อง" },
    { word: "my", type: "det.", meaning: "ของฉัน" },
    { word: "name", type: "n., v.", meaning: "ชื่อ, ตั้งชื่อ" },
    { word: "natural", type: "adj.", meaning: "ธรรมชาติ" },
    { word: "near", type: "prep., adj., adv.", meaning: "ใกล้, ใกล้เคียง" },
    { word: "need", type: "v.", meaning: "ต้องการ" },
    { word: "negative", type: "adj.", meaning: "เชิงลบ" },
    { word: "neighbour", type: "n.", meaning: "เพื่อนบ้าน" },
    { word: "never", type: "adv.", meaning: "ไม่เคย" },
    { word: "new", type: "adj.", meaning: "ใหม่" },
    { word: "news", type: "n.", meaning: "ข่าว" },
    { word: "newspaper", type: "n.", meaning: "หนังสือพิมพ์" },
    { word: "next", type: "adj., adv.", meaning: "ถัดไป, ต่อไป" },
    { word: "next to", type: "prep.", meaning: "ถัดจาก" },
    { word: "nice", type: "adj.", meaning: "ดี, สวยงาม, น่ารัก" },
    { word: "night", type: "n.", meaning: "กลางคืน" },
    { word: "nine", type: "number", meaning: "เก้า" },
    { word: "nineteen", type: "number", meaning: "สิบเก้า" },
    { word: "ninety", type: "number", meaning: "เก้าสิบ" },
    { word: "no one", type: "pron.", meaning: "ไม่มีใคร" },
    { word: "nobody", type: "pron.", meaning: "ไม่มีใคร" },
    { word: "north", type: "n., adj., adv.", meaning: "ทิศเหนือ, ทางเหนือ" },
    { word: "nose", type: "n.", meaning: "จมูก" },
    { word: "not", type: "adv.", meaning: "ไม่" },
    { word: "note", type: "n.", meaning: "บันทึก, โน้ต" },
    { word: "nothing", type: "pron.", meaning: "ไม่มีอะไร" },
    { word: "November", type: "n.", meaning: "เดือนพฤศจิกายน" },
    { word: "now", type: "adv.", meaning: "ตอนนี้" },
    { word: "number", type: "n.", meaning: "ตัวเลข, จำนวน" },
    { word: "nurse", type: "n.", meaning: "พยาบาล" },
    { word: "object", type: "n.", meaning: "วัตถุ, เป้าหมาย" },
    { word: "o’clock", type: "adv.", meaning: "นาฬิกา (ใช้บอกเวลา)" },
    { word: "October", type: "n.", meaning: "เดือนตุลาคม" },
    { word: "of", type: "prep.", meaning: "ของ" },
    { word: "off", type: "adv., prep.", meaning: "ปิด, ออกไป, ไม่ทำงาน" },
    { word: "office", type: "n.", meaning: "สำนักงาน" },
    { word: "often", type: "adv.", meaning: "บ่อยครั้ง" },
    { word: "old", type: "adj.", meaning: "เก่า, แก่" },
    { word: "on", type: "prep., adv.", meaning: "บน, เปิด, ทำงานอยู่" },
    { word: "once", type: "adv.", meaning: "ครั้งหนึ่ง, ครั้งเดียว" },
    { word: "one", type: "number/det., pron.", meaning: "หนึ่ง" },
    { word: "onion", type: "n.", meaning: "หัวหอม" },
    { word: "online", type: "adj., adv.", meaning: "ออนไลน์" },
    { word: "only", type: "adj., adv.", meaning: "เท่านั้น, เพียงแค่" },
    { word: "open", type: "adj., v.", meaning: "เปิด, เปิดอยู่" },
    { word: "opinion", type: "n.", meaning: "ความคิดเห็น" },
    { word: "opposite", type: "adj., n., prep., adv.", meaning: "ตรงข้าม, สิ่งที่ตรงข้าม" },
    { word: "or", type: "conj.", meaning: "หรือ" },
    { word: "orange", type: "n., adj.", meaning: "ส้ม, สีส้ม" },
    { word: "order", type: "n., v.", meaning: "คำสั่ง, ลำดับ, สั่งซื้อ" },
    { word: "other", type: "adj./pron.", meaning: "อื่นๆ, คนอื่น" },
    { word: "our", type: "det.", meaning: "ของเรา" },
    { word: "out", type: "adv./prep.", meaning: "ออกไป, ข้างนอก" },
    { word: "outside", type: "adv.", meaning: "ข้างนอก" },
    { word: "over", type: "prep., adv.", meaning: "เหนือ, จบ, ข้าม" },
    { word: "own", type: "adj./pron.", meaning: "ของตัวเอง, เป็นเจ้าของ" },
    { word: "page", type: "n.", meaning: "หน้ากระดาษ" },
    { word: "paint", type: "v., n.", meaning: "ทาสี, วาดภาพ, สี" },
    { word: "painting", type: "n.", meaning: "ภาพวาด" },
    { word: "pair", type: "n.", meaning: "คู่" },
    { word: "paper", type: "n.", meaning: "กระดาษ, หนังสือพิมพ์" },
    { word: "paragraph", type: "n.", meaning: "ย่อหน้า" },
    { word: "parent", type: "n.", meaning: "พ่อแม่" },
    { word: "park", type: "n., v.", meaning: "สวนสาธารณะ, จอดรถ" },
    { word: "part", type: "n.", meaning: "ส่วน" },
    { word: "partner", type: "n.", meaning: "หุ้นส่วน, คู่ชีวิต" },
    { word: "party", type: "n.", meaning: "งานเลี้ยง, พรรค" },
    { word: "passport", type: "n.", meaning: "หนังสือเดินทาง" },
    { word: "past", type: "adj., n., prep.", meaning: "ที่ผ่านมา, อดีต, ผ่าน" },
    { word: "pay", type: "v.", meaning: "จ่าย" },
    { word: "pen", type: "n.", meaning: "ปากกา" },
    { word: "pencil", type: "n.", meaning: "ดินสอ" },
    { word: "people", type: "n.", meaning: "ผู้คน" },
    { word: "pepper", type: "n.", meaning: "พริกไทย, พริก" },
    { word: "perfect", type: "adj.", meaning: "สมบูรณ์แบบ" },
    { word: "period", type: "n.", meaning: "ช่วงเวลา, จุด (ในประโยค)" },
    { word: "person", type: "n.", meaning: "บุคคล" },
    { word: "personal", type: "adj.", meaning: "ส่วนตัว" },
    { word: "phone", type: "n., v.", meaning: "โทรศัพท์, โทรออก" },
    { word: "photo", type: "n.", meaning: "รูปถ่าย" },
    { word: "photograph", type: "n.", meaning: "รูปถ่าย" },
    { word: "phrase", type: "n.", meaning: "วลี" },
    { word: "piano", type: "n.", meaning: "เปียโน" },
    { word: "picture", type: "n.", meaning: "รูปภาพ" },
    { word: "piece", type: "n.", meaning: "ชิ้น" },
    { word: "pig", type: "n.", meaning: "หมู" },
    { word: "pink", type: "adj., n.", meaning: "สีชมพู" },
    { word: "place", type: "n.", meaning: "สถานที่" },
    { word: "plan", type: "n., v.", meaning: "แผน, วางแผน" },
    { word: "plane", type: "n.", meaning: "เครื่องบิน" },
    { word: "plant", type: "n.", meaning: "พืช, ต้นไม้" },
    { word: "play", type: "v., n.", meaning: "เล่น, การเล่น" },
    { word: "player", type: "n.", meaning: "ผู้เล่น" },
    { word: "please", type: "exclam.", meaning: "ได้โปรด" },
    { word: "point", type: "n.", meaning: "จุด, ประเด็น, คะแนน" },
    { word: "police", type: "n.", meaning: "ตำรวจ" },
    { word: "policeman", type: "n.", meaning: "ตำรวจ (ชาย)" },
    { word: "pool", type: "n.", meaning: "สระว่ายน้ำ, บ่อน้ำ" },
    { word: "poor", type: "adj.", meaning: "ยากจน, น่าสงสาร" },
    { word: "popular", type: "adj.", meaning: "เป็นที่นิยม" },
    { word: "positive", type: "adj.", meaning: "เชิงบวก" },
    { word: "possible", type: "adj.", meaning: "เป็นไปได้" },
    { word: "post", type: "n., v.", meaning: "ไปรษณีย์, ส่งจดหมาย/พัสดุ, โพสต์" },
    { word: "potato", type: "n.", meaning: "มันฝรั่ง" },
    { word: "pound", type: "n.", meaning: "ปอนด์ (หน่วยเงิน/น้ำหนัก)" },
    { word: "practice", type: "n.", meaning: "การฝึกฝน" },
    { word: "practise", type: "v.", meaning: "ฝึกฝน" },
    { word: "prefer", type: "v.", meaning: "ชอบมากกว่า" },
    { word: "prepare", type: "v.", meaning: "เตรียม" },
    { word: "present", type: "adj., n.", meaning: "ปัจจุบัน, ของขวัญ" },
    { word: "pretty", type: "adj., adv.", meaning: "น่ารัก, ค่อนข้าง" },
    { word: "price", type: "n.", meaning: "ราคา" },
    { word: "probably", type: "adv.", meaning: "น่าจะ, เป็นไปได้" },
    { word: "problem", type: "n.", meaning: "ปัญหา" },
    { word: "product", type: "n.", meaning: "ผลิตภัณฑ์" },
    { word: "programme", type: "n.", meaning: "รายการ, โปรแกรม" },
    { word: "project", type: "n.", meaning: "โครงการ" },
    { word: "purple", type: "adj., n.", meaning: "สีม่วง" },
    { word: "put", type: "v.", meaning: "วาง, ใส่" },
    { word: "quarter", type: "n.", meaning: "หนึ่งในสี่, สี่ส่วน" },
    { word: "question", type: "n.", meaning: "คำถาม" },
    { word: "quick", type: "adj.", meaning: "เร็ว" },
    { word: "quickly", type: "adv.", meaning: "อย่างรวดเร็ว" },
    { word: "quiet", type: "adj.", meaning: "เงียบ" },
    { word: "quite", type: "adv.", meaning: "ค่อนข้าง" },
    { word: "radio", type: "n.", meaning: "วิทยุ" },
    { word: "rain", type: "n., v.", meaning: "ฝน, ฝนตก" },
    { word: "read", type: "v.", meaning: "อ่าน" },
    { word: "reader", type: "n.", meaning: "ผู้อ่าน" },
    { word: "reading", type: "n.", meaning: "การอ่าน" },
    { word: "ready", type: "adj.", meaning: "พร้อม" },
    { word: "real", type: "adj.", meaning: "จริง" },
    { word: "really", type: "adv.", meaning: "จริงๆ" },
    { word: "reason", type: "n.", meaning: "เหตุผล" },
    { word: "red", type: "adj., n.", meaning: "สีแดง" },
    { word: "relax", type: "v.", meaning: "ผ่อนคลาย" },
    { word: "remember", type: "v.", meaning: "จำ" },
    { word: "repeat", type: "v.", meaning: "ทำซ้ำ" },
    { word: "report", type: "n.", meaning: "รายงาน" },
    { word: "restaurant", type: "n.", meaning: "ร้านอาหาร" },
    { word: "result", type: "n.", meaning: "ผลลัพธ์" },
    { word: "return", type: "v., n.", meaning: "กลับ, คืน, การกลับ" },
    { word: "rice", type: "n.", meaning: "ข้าว" },
    { word: "rich", type: "adj.", meaning: "รวย, อุดมสมบูรณ์" },
    { word: "ride", type: "v.", meaning: "ขี่ (เช่น จักรยาน, ม้า)" },
    { word: "right", type: "adj., adv., n.", meaning: "ถูกต้อง, ขวา, สิทธิ์" },
    { word: "river", type: "n.", meaning: "แม่น้ำ" },
    { word: "road", type: "n.", meaning: "ถนน" },
    { word: "room", type: "n.", meaning: "ห้อง" },
    { word: "routine", type: "n.", meaning: "กิจวัตร" },
    { word: "rule", type: "n.", meaning: "กฎ" },
    { word: "run", type: "v.", meaning: "วิ่ง" },
    { word: "sad", type: "adj.", meaning: "เศร้า" },
    { word: "salad", type: "n.", meaning: "สลัด" },
    { word: "salt", type: "n.", meaning: "เกลือ" },
    { word: "same", type: "adj., pron., adv.", meaning: "เหมือนกัน" },
    { word: "sandwich", type: "n.", meaning: "แซนด์วิช" },
    { word: "Saturday", type: "n.", meaning: "วันเสาร์" },
    { word: "say", type: "v.", meaning: "พูด, กล่าว" },
    { word: "school", type: "n.", meaning: "โรงเรียน" },
    { word: "science", type: "n.", meaning: "วิทยาศาสตร์" },
    { word: "scientist", type: "n.", meaning: "นักวิทยาศาสตร์" },
    { word: "sea", type: "n.", meaning: "ทะเล" },
    { word: "second", type: "det./number, n.", meaning: "ที่สอง, วินาที" },
    { word: "section", type: "n.", meaning: "ส่วน, แผนก" },
    { word: "see", type: "v.", meaning: "เห็น" },
    { word: "sell", type: "v.", meaning: "ขาย" },
    { word: "send", type: "v.", meaning: "ส่ง" },
    { word: "sentence", type: "n.", meaning: "ประโยค" },
    { word: "September", type: "n.", meaning: "เดือนกันยายน" },
    { word: "seven", type: "number", meaning: "เจ็ด" },
    { word: "seventeen", type: "number", meaning: "สิบเจ็ด" },
    { word: "seventy", type: "number", meaning: "เจ็ดสิบ" },
    { word: "share", type: "v.", meaning: "แบ่งปัน" },
    { word: "she", type: "pron.", meaning: "เธอ (ผู้หญิง)" },
    { word: "sheep", type: "n.", meaning: "แกะ" },
    { word: "shirt", type: "n.", meaning: "เสื้อเชิ้ต" },
    { word: "shoe", type: "n.", meaning: "รองเท้า" },
    { word: "shop", type: "n., v.", meaning: "ร้านค้า, ซื้อของ" },
    { word: "shopping", type: "n.", meaning: "การซื้อของ" },
    { word: "short", type: "adj.", meaning: "สั้น, เตี้ย" },
    { word: "should", type: "modal v.", meaning: "ควรจะ" },
    { word: "show", type: "v., n.", meaning: "แสดง, การแสดง" },
    { word: "shower", type: "n.", meaning: "ฝักบัว, การอาบน้ำฝักบัว" },
    { word: "sick", type: "adj.", meaning: "ป่วย" },
    { word: "similar", type: "adj.", meaning: "คล้ายกัน" },
    { word: "sing", type: "v.", meaning: "ร้องเพลง" },
    { word: "singer", type: "n.", meaning: "นักร้อง" },
    { word: "sister", type: "n.", meaning: "พี่สาว, น้องสาว" },
    { word: "sit", type: "v.", meaning: "นั่ง" },
    { word: "situation", type: "n.", meaning: "สถานการณ์" },
    { word: "six", type: "number", meaning: "หก" },
    { word: "sixteen", type: "number", meaning: "สิบหก" },
    { word: "sixty", type: "number", meaning: "หกสิบ" },
    { word: "skill", type: "n.", meaning: "ทักษะ" },
    { word: "skirt", type: "n.", meaning: "กระโปรง" },
    { word: "sleep", type: "v.", meaning: "นอน" },
    { word: "slow", type: "adj.", meaning: "ช้า" },
    { word: "small", type: "adj.", meaning: "เล็ก" },
    { word: "snake", type: "n.", meaning: "งู" },
    { word: "snow", type: "n., v.", meaning: "หิมะ, หิมะตก" },
    { word: "so", type: "adv., conj.", meaning: "ดังนั้น, มาก" },
    { word: "some", type: "det., pron.", meaning: "บางส่วน, บ้าง" },
    { word: "somebody", type: "pron.", meaning: "บางคน" },
    { word: "someone", type: "pron.", meaning: "บางคน" },
    { word: "something", type: "pron.", meaning: "บางสิ่งบางอย่าง" },
    { word: "sometimes", type: "adv.", meaning: "บางครั้ง" },
    { word: "son", type: "n.", meaning: "ลูกชาย" },
    { word: "song", type: "n.", meaning: "เพลง" },
    { word: "soon", type: "adv.", meaning: "ในไม่ช้า, เร็วๆ นี้" },
    { word: "sorry", type: "adj., exclam.", meaning: "เสียใจ, ขอโทษ" },
    { word: "sound", type: "n., v.", meaning: "เสียง, ฟังดู" },
    { word: "soup", type: "n.", meaning: "ซุป" },
    { word: "south", type: "n., adj., adv.", meaning: "ทิศใต้, ทางใต้" },
    { word: "space", type: "n.", meaning: "อวกาศ, พื้นที่" },
    { word: "speak", type: "v.", meaning: "พูด" },
    { word: "special", type: "adj.", meaning: "พิเศษ" },
    { word: "spell", type: "v.", meaning: "สะกดคำ" },
    { word: "spelling", type: "n.", meaning: "การสะกดคำ" },
    { word: "spend", type: "v.", meaning: "ใช้ (เงิน, เวลา)" },
    { word: "sport", type: "n.", meaning: "กีฬา" },
    { word: "spring", type: "n.", meaning: "ฤดูใบไม้ผลิ, สปริง" },
    { word: "stand", type: "v.", meaning: "ยืน" },
    { word: "star", type: "n.", meaning: "ดาว, ดารา" },
    { word: "start", type: "v.", meaning: "เริ่ม" },
    { word: "statement", type: "n.", meaning: "ข้อความ, แถลงการณ์" },
    { word: "station", type: "n.", meaning: "สถานี" },
    { word: "stay", type: "v.", meaning: "อยู่, พัก" },
    { word: "still", type: "adv.", meaning: "ยังคง, นิ่ง" },
    { word: "stop", type: "v., n.", meaning: "หยุด, การหยุด" },
    { word: "story", type: "n.", meaning: "เรื่องราว" },
    { word: "street", type: "n.", meaning: "ถนน" },
    { word: "strong", type: "adj.", meaning: "แข็งแรง" },
    { word: "student", type: "n.", meaning: "นักเรียน" },
    { word: "study", type: "n., v.", meaning: "การเรียน, เรียน" },
    { word: "style", type: "n.", meaning: "รูปแบบ, สไตล์" },
    { word: "subject", type: "n.", meaning: "วิชา, หัวข้อ" },
    { word: "success", type: "n.", meaning: "ความสำเร็จ" },
    { word: "sugar", type: "n.", meaning: "น้ำตาล" },
    { word: "summer", type: "n.", meaning: "ฤดูร้อน" },
    { word: "sun", type: "n.", meaning: "พระอาทิตย์" },
    { word: "Sunday", type: "n.", meaning: "วันอาทิตย์" },
    { word: "supermarket", type: "n.", meaning: "ซูเปอร์มาร์เก็ต" },
    { word: "sure", type: "adj.", meaning: "แน่นอน, มั่นใจ" },
    { word: "sweater", type: "n.", meaning: "เสื้อกันหนาว" },
    { word: "swim", type: "v.", meaning: "ว่ายน้ำ" },
    { word: "swimming", type: "n.", meaning: "การว่ายน้ำ" },
    { word: "table", type: "n.", meaning: "โต๊ะ, ตาราง" },
    { word: "take", type: "v.", meaning: "เอา, พาไป" },
    { word: "talk", type: "v.", meaning: "พูดคุย" },
    { word: "tall", type: "adj.", meaning: "สูง (สำหรับคน/สิ่งของตั้งตรง)" },
    { word: "taxi", type: "n.", meaning: "แท็กซี่" },
    { word: "tea", type: "n.", meaning: "ชา" },
    { word: "teach", type: "v.", meaning: "สอน" },
    { word: "teacher", type: "n.", meaning: "ครู" },
    { word: "team", type: "n.", meaning: "ทีม" },
    { word: "teenager", type: "n.", meaning: "วัยรุ่น" },
    { word: "telephone", type: "n., v.", meaning: "โทรศัพท์, โทรศัพท์" },
    { word: "television", type: "n.", meaning: "โทรทัศน์" },
    { word: "tell", type: "v.", meaning: "บอก" },
    { word: "ten", type: "number", meaning: "สิบ" },
    { word: "tennis", type: "n.", meaning: "เทนนิส" },
    { word: "terrible", type: "adj.", meaning: "แย่มาก, น่ากลัว" },
    { word: "test", type: "n., v.", meaning: "การทดสอบ, ทดสอบ" },
    { word: "text", type: "n.", meaning: "ข้อความ" },
    { word: "than", type: "conj.", meaning: "กว่า" },
    { word: "thank", type: "v.", meaning: "ขอบคุณ" },
    { word: "thanks", type: "exclam., n.", meaning: "ขอบคุณ" },
    { word: "that", type: "det., pron., conj.", meaning: "นั้น, นั่น, ที่ว่า" },
    { word: "the", type: "definite article", meaning: "คำนำหน้าคำนามชี้เฉพาะ" },
    { word: "theatre", type: "n.", meaning: "โรงละคร" },
    { word: "their", type: "det.", meaning: "ของพวกเขา" },
    { word: "them", type: "pron.", meaning: "พวกเขา (กรรม)" },
    { word: "then", type: "adv.", meaning: "จากนั้น, แล้ว" },
    { word: "there", type: "adv.", meaning: "ที่นั่น" },
    { word: "they", type: "pron.", meaning: "พวกเขา" },
    { word: "thing", type: "n.", meaning: "สิ่งของ" },
    { word: "think", type: "v.", meaning: "คิด" },
    { word: "third", type: "number", meaning: "ที่สาม" },
    { word: "thirsty", type: "adj.", meaning: "กระหายน้ำ" },
    { word: "thirteen", type: "number", meaning: "สิบสาม" },
    { word: "thirty", type: "number", meaning: "สามสิบ" },
    { word: "this", type: "det./pron.", meaning: "นี้, นี่" },
    { word: "thousand", type: "number", meaning: "พัน" },
    { word: "three", type: "number", meaning: "สาม" },
    { word: "through", type: "prep., adv.", meaning: "ผ่าน" },
    { word: "Thursday", type: "n.", meaning: "วันพฤหัสบดี" },
    { word: "ticket", type: "n.", meaning: "ตั๋ว" },
    { word: "time", type: "n.", meaning: "เวลา, ครั้ง" },
    { word: "tired", type: "adj.", meaning: "เหนื่อย" },
    { word: "title", type: "n", meaning: "ชื่อเรื่อง, ตำแหน่ง" },
    { word: "today", type: "adv., n.", meaning: "วันนี้" },
    { word: "together", type: "adv.", meaning: "ด้วยกัน" },
    { word: "toilet", type: "n", meaning: "ห้องน้ำ, สุขา" },
    { word: "tomato", type: "n.", meaning: "มะเขือเทศ" },
    { word: "tomorrow", type: "adv., n.", meaning: "พรุ่งนี้" },
    { word: "tonight", type: "adv., n.", meaning: "คืนนี้" },
    { word: "too", type: "adv.", meaning: "ด้วย, มากเกินไป" },
    { word: "tooth", type: "n.", meaning: "ฟัน" },
    { word: "topic", type: "n.", meaning: "หัวข้อ" },
    { word: "tourist", type: "n.", meaning: "นักท่องเที่ยว" },
    { word: "town", type: "n.", meaning: "เมือง" },
    { word: "traffic", type: "n.", meaning: "การจราจร" },
    { word: "train", type: "n.", meaning: "รถไฟ, ฝึกฝน" },
    { word: "travel", type: "v., n.", meaning: "เดินทาง, การเดินทาง" },
    { word: "tree", type: "n.", meaning: "ต้นไม้" },
    { word: "trip", type: "n.", meaning: "การเดินทาง, ทริป" },
    { word: "trousers", type: "n.", meaning: "กางเกงขายาว" },
    { word: "true", type: "adj.", meaning: "จริง, ถูกต้อง" },
    { word: "try", type: "v.", meaning: "พยายาม, ลอง" },
    { word: "T-shirt", type: "n.", meaning: "เสื้อยืด" },
    { word: "Tuesday", type: "n.", meaning: "วันอังคาร" },
    { word: "turn", type: "v., n.", meaning: "หมุน, หัน, เลี้ยว, ตา (ในเกม)" },
    { word: "TV", type: "n.", meaning: "โทรทัศน์" },
    { word: "twelve", type: "number", meaning: "สิบสอง" },
    { word: "twenty", type: "number", meaning: "ยี่สิบ" },
    { word: "twice", type: "adv.", meaning: "สองครั้ง" },
    { word: "two", type: "number", meaning: "สอง" },
    { word: "type", type: "n.", meaning: "ชนิด, ประเภท" },
    { word: "umbrella", type: "n.", meaning: "ร่ม" },
    { word: "uncle", type: "n.", meaning: "ลุง, อา, น้า (ผู้ชาย)" },
    { word: "under", type: "prep., adv.", meaning: "ใต้, ข้างใต้" },
    { word: "understand", type: "v.", meaning: "เข้าใจ" },
    { word: "university", type: "n.", meaning: "มหาวิทยาลัย" },
    { word: "until", type: "conj./prep.", meaning: "จนกระทั่ง" },
    { word: "up", type: "adv., prep.", meaning: "ขึ้นไป, ข้างบน" },
    { word: "upstairs", type: "adv.", meaning: "ชั้นบน" },
    { word: "us", type: "pron.", meaning: "พวกเรา (กรรม)" },
    { word: "use", type: "v.", meaning: "ใช้" },
    { word: "useful", type: "adj.", meaning: "มีประโยชน์" },
    { word: "usually", type: "adv.", meaning: "โดยปกติ, โดยทั่วไป" },
    { word: "vacation", type: "n.", meaning: "วันหยุดพักผ่อน" },
    { word: "vegetable", type: "n.", meaning: "ผัก" },
    { word: "very", type: "adv.", meaning: "มาก" },
    { word: "video", type: "n.", meaning: "วิดีโอ" },
    { word: "village", type: "n.", meaning: "หมู่บ้าน" },
    { word: "visit", type: "v., n.", meaning: "เยี่ยมชม, การเยี่ยมชม" },
    { word: "visitor", type: "n.", meaning: "ผู้เยี่ยมชม" },
    { word: "wait", type: "v.", meaning: "รอ" },
    { word: "waiter", type: "n.", meaning: "บริกร (ชาย)" },
    { word: "wake", type: "v.", meaning: "ตื่น" },
    { word: "walk", type: "v., n.", meaning: "เดิน, การเดิน" },
    { word: "wall", type: "n.", meaning: "กำแพง, ผนัง" },
    { word: "want", type: "v.", meaning: "ต้องการ" },
    { word: "warm", type: "adj.", meaning: "อบอุ่น" },
    { word: "wash", type: "v.", meaning: "ล้าง" },
    { word: "watch", type: "v., n.", meaning: "ดู, นาฬิกาข้อมือ" },
    { word: "water", type: "n.", meaning: "น้ำ" },
    { word: "way", type: "n.", meaning: "ทาง, วิธี" },
    { word: "we", type: "pron.", meaning: "พวกเรา" },
    { word: "wear", type: "v.", meaning: "สวม, ใส่" },
    { word: "weather", type: "n.", meaning: "สภาพอากาศ" },
    { word: "website", type: "n.", meaning: "เว็บไซต์" },
    { word: "Wednesday", type: "n.", meaning: "วันพุธ" },
    { word: "week", type: "n.", meaning: "สัปดาห์" },
    { word: "weekend", type: "n.", meaning: "วันหยุดสุดสัปดาห์" },
    { word: "welcome", type: "exclam., v., adj.", meaning: "ยินดีต้อนรับ" },
    { word: "well", type: "adv., adj., exclam.", meaning: "ดี, สบายดี, อืม" },
    { word: "west", type: "n., adj., adv.", meaning: "ทิศตะวันตก, ทางตะวันตก" },
    { word: "what", type: "pron./det.", meaning: "อะไร" },
    { word: "when", type: "adv., pron., conj.", meaning: "เมื่อไร" },
    { word: "where", type: "adv., conj.", meaning: "ที่ไหน" },
    { word: "which", type: "pron./det.", meaning: "อันไหน" },
    { word: "white", type: "adj., n.", meaning: "สีขาว" },
    { word: "who", type: "pron.", meaning: "ใคร" },
    { word: "why", type: "adv.", meaning: "ทำไม" },
    { word: "wife", type: "n.", meaning: "ภรรยา" },
    { word: "will", type: "modal v.", meaning: "จะ" },
    { word: "win", type: "v.", meaning: "ชนะ" },
    { word: "window", type: "n.", meaning: "หน้าต่าง" },
    { word: "wine", type: "n.", meaning: "ไวน์" },
    { word: "winter", type: "n.", meaning: "ฤดูหนาว" },
    { word: "with", type: "prep.", meaning: "กับ, ด้วย" },
    { word: "without", type: "prep.", meaning: "ปราศจาก, ไม่มี" },
    { word: "woman", type: "n.", meaning: "ผู้หญิง" },
    { word: "wonderful", type: "adj.", meaning: "ยอดเยี่ยม, มหัศจรรย์" },
    { word: "word", type: "n.", meaning: "คำ" },
    { word: "work", type: "v., n.", meaning: "ทำงาน, งาน" },
    { word: "worker", type: "n.", meaning: "คนงาน" },
    { word: "world", type: "n.", meaning: "โลก" },
    { word: "would", type: "modal v.", meaning: "จะ (รูปอดีตของ will, ใช้ในประโยคเงื่อนไข)" },
    { word: "write", type: "v.", meaning: "เขียน" },
    { word: "writer", type: "n.", meaning: "นักเขียน" },
    { word: "writing", type: "n.", meaning: "การเขียน" },
    { word: "wrong", type: "adj.", meaning: "ผิด" },
    { word: "yeah", type: "exclam.", meaning: "ใช่ (ไม่เป็นทางการ)" },
    { word: "year", type: "n.", meaning: "ปี" },
    { word: "yellow", type: "adj., n.", meaning: "สีเหลือง" },
    { word: "yes", type: "exclam.", meaning: "ใช่" },
    { word: "yesterday", type: "adv., n.", meaning: "เมื่อวานนี้" },
    { word: "you", type: "pron.", meaning: "คุณ, พวกคุณ" },
    { word: "young", type: "adj.", meaning: "หนุ่มสาว, อ่อนเยาว์" },
    { word: "your", type: "det.", meaning: "ของคุณ" },
    { word: "yourself", type: "pron.", meaning: "ตัวคุณเอง" },
];
