import { Word } from './types';

export const a2Words: Word[] = [
    { word: "ability", type: "n.", meaning: "ความสามารถ" },
    { word: "able", type: "adj.", meaning: "สามารถ" },
    { word: "abroad", type: "adv.", meaning: "ในต่างประเทศ" },
    { word: "accept", type: "v.", meaning: "ยอมรับ" },
    { word: "accident", type: "n.", meaning: "อุบัติเหตุ" },
    { word: "according to", type: "prep.", meaning: "ตามที่" },
    { word: "achieve", type: "v.", meaning: "ประสบความสำเร็จ" },
    { word: "act", type: "v.", meaning: "แสดง, กระทำ" },
    { word: "active", type: "adj.", meaning: "กระตือรือร้น, คล่องแคล่ว" },
    { word: "actually", type: "adv.", meaning: "จริงๆ แล้ว" },
    { word: "adult", type: "adj.", meaning: "ที่เป็นผู้ใหญ่" },
    { word: "advantage", type: "n.", meaning: "ข้อดี, ข้อได้เปรียบ" },
    { word: "adventure", type: "n.", meaning: "การผจญภัย" },
    { word: "advertise", type: "v.", meaning: "โฆษณา" },
    { word: "advertisement", type: "n.", meaning: "โฆษณา" },
    { word: "advertising", type: "n.", meaning: "การโฆษณา" },
    { word: "affect", type: "v.", meaning: "ส่งผลกระทบต่อ" },
    { word: "after", type: "conj., adv.", meaning: "หลังจากนั้น" },
    { word: "against", type: "prep.", meaning: "ต่อต้าน, ตรงกันข้ามกับ" },
    { word: "airline", type: "n.", meaning: "สายการบิน" },
    { word: "alive", type: "adj.", meaning: "มีชีวิตอยู่" },
    { word: "all", type: "adv.", meaning: "ทั้งหมด" },
    { word: "all right", type: "adj./adv., exclam.", meaning: "เรียบร้อย, โอเค" },
    { word: "allow", type: "v.", meaning: "อนุญาต" },
    { word: "almost", type: "adv.", meaning: "เกือบจะ" },
    { word: "alone", type: "adj./adv.", meaning: "อยู่คนเดียว" },
    { word: "along", type: "prep., adv.", meaning: "ตาม, ไปตาม" },
    { word: "already", type: "adv.", meaning: "เรียบร้อยแล้ว" },
    { word: "alternative", type: "n.", meaning: "ทางเลือก" },
    { word: "although", type: "conj.", meaning: "แม้ว่า" },
    { word: "among", type: "prep.", meaning: "ในหมู่, ระหว่าง (หลายสิ่ง)" },
    { word: "amount", type: "n.", meaning: "จำนวน" },
    { word: "ancient", type: "adj.", meaning: "โบราณ" },
    { word: "ankle", type: "n.", meaning: "ข้อเท้า" },
    { word: "any", type: "adv.", meaning: "บ้าง (ใช้ในประโยคคำถาม/ปฏิเสธ), เลย" },
    { word: "anybody", type: "pron.", meaning: "ใครก็ตาม" },
    { word: "any more", type: "adv.", meaning: "อีกต่อไป (ใช้ในประโยคปฏิเสธ)" },
    { word: "anyway", type: "adv.", meaning: "อย่างไรก็ตาม, ช่างเถอะ" },
    { word: "anywhere", type: "adv., pron.", meaning: "ที่ไหนก็ได้" },
    { word: "app", type: "n.", meaning: "แอปพลิเคชัน" },
    { word: "appear", type: "v.", meaning: "ปรากฏ, ดูเหมือนว่า" },
    { word: "appearance", type: "n.", meaning: "รูปร่างหน้าตา, การปรากฏ" },
    { word: "apply", type: "v.", meaning: "สมัคร, ประยุกต์ใช้" },
    { word: "architect", type: "n.", meaning: "สถาปนิก" },
    { word: "architecture", type: "n.", meaning: "สถาปัตยกรรม" },
    { word: "argue", type: "v.", meaning: "โต้เถียง" },
    { word: "argument", type: "n.", meaning: "การโต้เถียง" },
    { word: "army", type: "n.", meaning: "กองทัพ" },
    { word: "arrange", type: "v.", meaning: "จัดการ, จัดเรียง" },
    { word: "arrangement", type: "n.", meaning: "การจัดการ, ข้อตกลง" },
    { word: "as", type: "adv., conj.", meaning: "ในฐานะที่, ขณะที่, เหมือนกับ" },
    { word: "asleep", type: "adj.", meaning: "หลับ" },
    { word: "assistant", type: "n., adj.", meaning: "ผู้ช่วย, ผู้ช่วย" },
    { word: "athlete", type: "n.", meaning: "นักกีฬา" },
    { word: "attack", type: "n., v.", meaning: "การโจมตี, โจมตี" },
    { word: "attend", type: "v.", meaning: "เข้าร่วม" },
    { word: "attention", type: "n., exclam.", meaning: "ความสนใจ, ตั้งใจ!" },
    { word: "attractive", type: "adj.", meaning: "มีเสน่ห์, ดึงดูดใจ" },
    { word: "audience", type: "n.", meaning: "ผู้ชม, ผู้ฟัง" },
    { word: "author", type: "n.", meaning: "ผู้เขียน, นักประพันธ์" },
    { word: "available", type: "adj.", meaning: "ว่าง, มีอยู่" },
    { word: "average", type: "adj., n.", meaning: "เฉลี่ย, ค่าเฉลี่ย" },
    { word: "avoid", type: "v.", meaning: "หลีกเลี่ยง" },
    { word: "award", type: "n.", meaning: "รางวัล" },
    { word: "awful", type: "adj.", meaning: "แย่มาก, น่ากลัว" },
    { word: "back", type: "adj.", meaning: "หลัง, กลับ" },
    { word: "background", type: "n.", meaning: "พื้นหลัง, ภูมิหลัง" },
    { word: "badly", type: "adv.", meaning: "แย่มาก" },
    { word: "bar", type: "n.", meaning: "บาร์, แท่ง" },
    { word: "baseball", type: "n.", meaning: "เบสบอล" },
    { word: "based", type: "adj.", meaning: "ตั้งอยู่บนพื้นฐานของ" },
    { word: "basketball", type: "n.", meaning: "บาสเกตบอล" },
    { word: "bean", type: "n.", meaning: "ถั่ว" },
    { word: "bear", type: "n.", meaning: "หมี" },
    { word: "beat", type: "v.", meaning: "เอาชนะ, ตี" },
    { word: "beef", type: "n.", meaning: "เนื้อวัว" },
    { word: "before", type: "conj., adv.", meaning: "ก่อนหน้านี้" },
    { word: "behave", type: "v.", meaning: "ประพฤติตัว" },
    { word: "behaviour", type: "n.", meaning: "พฤติกรรม" },
    { word: "belong", type: "v.", meaning: "เป็นของ" },
    { word: "belt", type: "n.", meaning: "เข็มขัด" },
    { word: "benefit", type: "n.", meaning: "ผลประโยชน์" },
    { word: "best", type: "adv., n.", meaning: "ดีที่สุด" },
    { word: "better", type: "adv.", meaning: "ดีกว่า" },
    { word: "between", type: "adv.", meaning: "ระหว่าง" },
    { word: "billion", type: "number", meaning: "พันล้าน" },
    { word: "bin", type: "n.", meaning: "ถังขยะ" },
    { word: "biology", type: "n.", meaning: "ชีววิทยา" },
    { word: "birth", type: "n.", meaning: "การเกิด" },
    { word: "biscuit", type: "n.", meaning: "บิสกิต (UK), คุกกี้" },
    { word: "bit", type: "n.", meaning: "เล็กน้อย, ชิ้นส่วน" },
    { word: "blank", type: "adj., n.", meaning: "ว่างเปล่า, ช่องว่าง" },
    { word: "blood", type: "n.", meaning: "เลือด" },
    { word: "blow", type: "v.", meaning: "เป่า" },
    { word: "board", type: "n.", meaning: "กระดาน, คณะกรรมการ" },
    { word: "boil", type: "v.", meaning: "ต้ม" },
    { word: "bone", type: "n.", meaning: "กระดูก" },
    { word: "book", type: "v.", meaning: "จอง" },
    { word: "borrow", type: "v.", meaning: "ยืม" },
    { word: "boss", type: "n.", meaning: "เจ้านาย" },
    { word: "bottom", type: "n., adj.", meaning: "ก้น, ล่างสุด" },
    { word: "bowl", type: "n.", meaning: "ชาม" },
    { word: "brain", type: "n.", meaning: "สมอง" },
    { word: "bridge", type: "n.", meaning: "สะพาน" },
    { word: "bright", type: "adj.", meaning: "สดใส, สว่าง" },
    { word: "brilliant", type: "adj.", meaning: "ยอดเยี่ยม, ฉลาดมาก" },
    { word: "broken", type: "adj.", meaning: "แตก, หัก" },
    { word: "brush", type: "v., n.", meaning: "แปรง, แปรง (คำนาม)" },
    { word: "burn", type: "v.", meaning: "ไหม้, เผา" },
    { word: "businessman", type: "n.", meaning: "นักธุรกิจชาย" },
    { word: "button", type: "n.", meaning: "กระดุม, ปุ่ม" },
    { word: "camp", type: "n., v.", meaning: "ค่าย, ตั้งแคมป์" },
    { word: "camping", type: "n.", meaning: "การตั้งแคมป์" },
    { word: "can", type: "n.", meaning: "กระป๋อง" },
    { word: "care", type: "n., v.", meaning: "ความเอาใจใส่, ดูแล" },
    { word: "careful", type: "adj.", meaning: "ระมัดระวัง" },
    { word: "carefully", type: "adv.", meaning: "อย่างระมัดระวัง" },
    { word: "carpet", type: "n.", meaning: "พรม" },
    { word: "cartoon", type: "n.", meaning: "การ์ตูน" },
    { word: "case", type: "n.", meaning: "กรณี, คดี, กล่อง" },
    { word: "cash", type: "n.", meaning: "เงินสด" },
    { word: "castle", type: "n.", meaning: "ปราสาท" },
    { word: "catch", type: "v.", meaning: "จับ" },
    { word: "cause", type: "n., v.", meaning: "สาเหตุ, ก่อให้เกิด" },
    { word: "celebrate", type: "v.", meaning: "เฉลิมฉลอง" },
    { word: "celebrity", type: "n.", meaning: "คนดัง" },
    { word: "certain", type: "adj.", meaning: "แน่นอน, บางสิ่งบางอย่าง" },
    { word: "certainly", type: "adv.", meaning: "อย่างแน่นอน" },
    { word: "chance", type: "n.", meaning: "โอกาส, โชค" },
    { word: "character", type: "n.", meaning: "ตัวละคร, นิสัย" },
    { word: "charity", type: "n.", meaning: "องค์กรการกุศล, การกุศล" },
    { word: "chat", type: "v., n.", meaning: "คุยเล่น, การคุยเล่น" },
    { word: "check", type: "n.", meaning: "การตรวจสอบ, เช็ค" },
    { word: "chef", type: "n.", meaning: "พ่อครัว" },
    { word: "chemistry", type: "n.", meaning: "เคมี" },
    { word: "chip", type: "n.", meaning: "มันฝรั่งทอด (UK), แผ่นวงจร" },
    { word: "choice", type: "n.", meaning: "ทางเลือก" },
    { word: "church", type: "n.", meaning: "โบสถ์" },
    { word: "cigarette", type: "n.", meaning: "บุหรี่" },
    { word: "circle", type: "n., v.", meaning: "วงกลม, วนรอบ" },
    { word: "classical", type: "adj.", meaning: "คลาสสิก" },
    { word: "clear", type: "adj.", meaning: "ชัดเจน, ใส" },
    { word: "clearly", type: "adv.", meaning: "อย่างชัดเจน" },
    { word: "clever", type: "adj.", meaning: "ฉลาด" },
    { word: "climate", type: "n.", meaning: "สภาพอากาศ" },
    { word: "close", type: "adj.", meaning: "ใกล้" },
    { word: "closed", type: "adj.", meaning: "ปิดแล้ว" },
    { word: "clothing", type: "n.", meaning: "เสื้อผ้า" },
    { word: "cloud", type: "n.", meaning: "เมฆ" },
    { word: "coach", type: "n.", meaning: "โค้ช, รถโค้ช" },
    { word: "coast", type: "n.", meaning: "ชายฝั่ง" },
    { word: "code", type: "n.", meaning: "รหัส" },
    { word: "colleague", type: "n.", meaning: "เพื่อนร่วมงาน" },
    { word: "collect", type: "v.", meaning: "สะสม, รวบรวม" },
    { word: "column", type: "n.", meaning: "คอลัมน์, เสา" },
    { word: "comedy", type: "n.", meaning: "ตลก, สุขนาฏกรรม" },
    { word: "comfortable", type: "adj.", meaning: "สบาย" },
    { word: "comment", type: "n.", meaning: "ความคิดเห็น" },
    { word: "communicate", type: "v.", meaning: "สื่อสาร" },
    { word: "community", type: "n.", meaning: "ชุมชน" },
    { word: "compete", type: "v.", meaning: "แข่งขัน" },
    { word: "competition", type: "n.", meaning: "การแข่งขัน" },
    { word: "complain", type: "v.", meaning: "บ่น, ร้องเรียน" },
    { word: "completely", type: "adv.", meaning: "อย่างสมบูรณ์" },
    { word: "condition", type: "n.", meaning: "สภาพ, เงื่อนไข" },
    { word: "conference", type: "n.", meaning: "การประชุม" },
    { word: "connect", type: "v.", meaning: "เชื่อมต่อ" },
    { word: "connected", type: "adj.", meaning: "ที่เชื่อมต่อกัน" },
    { word: "consider", type: "v.", meaning: "พิจารณา" },
    { word: "contain", type: "v.", meaning: "บรรจุ, มีอยู่" },
    { word: "context", type: "n.", meaning: "บริบท" },
    { word: "continent", type: "n.", meaning: "ทวีป" },
    { word: "continue", type: "v.", meaning: "ดำเนินต่อไป" },
    { word: "control", type: "n., v.", meaning: "การควบคุม, ควบคุม" },
    { word: "cook", type: "n.", meaning: "คนทำอาหาร" },
    { word: "cooker", type: "n.", meaning: "เตาทำอาหาร" },
    { word: "copy", type: "n., v.", meaning: "สำเนา, คัดลอก" },
    { word: "corner", type: "n.", meaning: "มุม" },
    { word: "correctly", type: "adv.", meaning: "อย่างถูกต้อง" },
    { word: "count", type: "v.", meaning: "นับ" },
    { word: "couple", type: "n.", meaning: "คู่, สองสาม" },
    { word: "cover", type: "v.", meaning: "คลุม, ปกคลุม" },
    { word: "crazy", type: "adj.", meaning: "บ้า, คลั่ง" },
    { word: "creative", type: "adj.", meaning: "สร้างสรรค์" },
    { word: "credit", type: "n.", meaning: "เครดิต, ความน่าเชื่อถือ" },
    { word: "crime", type: "n.", meaning: "อาชญากรรม" },
    { word: "criminal", type: "n.", meaning: "อาชญากร" },
    { word: "cross", type: "v., n.", meaning: "ข้าม, ไม้กางเขน" },
    { word: "crowd", type: "n.", meaning: "ฝูงชน" },
    { word: "crowded", type: "adj.", meaning: "แออัด" },
    { word: "cry", type: "v.", meaning: "ร้องไห้, ตะโกน" },
    { word: "cupboard", type: "n.", meaning: "ตู้" },
    { word: "curly", type: "adj.", meaning: "หยิก, เป็นลอน" },
    { word: "cycle", type: "n., v.", meaning: "วงจร, ปั่นจักรยาน" },
    { word: "daily", type: "adj.", meaning: "ประจำวัน" },
    { word: "danger", type: "n.", meaning: "อันตราย" },
    { word: "dark", type: "n.", meaning: "ความมืด" },
    { word: "data", type: "n.", meaning: "ข้อมูล" },
    { word: "dead", type: "adj.", meaning: "ตายแล้ว" },
    { word: "deal", type: "v.", meaning: "จัดการ, ตกลง" },
    { word: "dear", type: "exclam.", meaning: "โอ้โห! (ใช้แสดงความประหลาดใจหรือเสียใจ)" },
    { word: "death", type: "n.", meaning: "ความตาย" },
    { word: "decision", type: "n.", meaning: "การตัดสินใจ" },
    { word: "deep", type: "adj.", meaning: "ลึก" },
    { word: "definitely", type: "adv.", meaning: "อย่างแน่นอน" },
    { word: "degree", type: "n.", meaning: "ปริญญา, ระดับองศา" },
    { word: "dentist", type: "n.", meaning: "ทันตแพทย์" },
    { word: "department", type: "n.", meaning: "แผนก, แผนกวิชา" },
    { word: "depend", type: "v.", meaning: "ขึ้นอยู่กับ" },
    { word: "desert", type: "n.", meaning: "ทะเลทราย" },
    { word: "designer", type: "n.", meaning: "นักออกแบบ" },
    { word: "destroy", type: "v.", meaning: "ทำลาย" },
    { word: "detective", type: "n.", meaning: "นักสืบ" },
    { word: "develop", type: "v.", meaning: "พัฒนา" },
    { word: "device", type: "n.", meaning: "อุปกรณ์" },
    { word: "diary", type: "n.", meaning: "สมุดบันทึกประจำวัน" },
    { word: "differently", type: "adv.", meaning: "แตกต่างกัน" },
    { word: "digital", type: "adj.", meaning: "ดิจิทัล" },
    { word: "direct", type: "adj.", meaning: "โดยตรง" },
    { word: "direction", type: "n.", meaning: "ทิศทาง" },
    { word: "director", type: "n.", meaning: "ผู้กำกับ, ผู้อำนวยการ" },
    { word: "disagree", type: "v.", meaning: "ไม่เห็นด้วย" },
    { word: "disappear", type: "v.", meaning: "หายไป" },
    { word: "disaster", type: "n.", meaning: "ภัยพิบัติ" },
    { word: "discover", type: "v.", meaning: "ค้นพบ" },
    { word: "discovery", type: "n.", meaning: "การค้นพบ" },
    { word: "discussion", type: "n.", meaning: "การสนทนา, การอภิปราย" },
    { word: "disease", type: "n.", meaning: "โรค" },
    { word: "distance", type: "n.", meaning: "ระยะทาง" },
    { word: "divorced", type: "adj.", meaning: "หย่าร้าง" },
    { word: "document", type: "n.", meaning: "เอกสาร" },
    { word: "double", type: "adj., det., pron., v.", meaning: "สองเท่า, คูณสอง" },
    { word: "download", type: "v., n.", meaning: "ดาวน์โหลด" },
    { word: "downstairs", type: "adj.", meaning: "ที่อยู่ชั้นล่าง" },
    { word: "drama", type: "n.", meaning: "ละคร, เรื่องราวชีวิต" },
    { word: "drawing", type: "n.", meaning: "ภาพวาด, การวาด" },
    { word: "dream", type: "n., v.", meaning: "ความฝัน, ฝัน" },
    { word: "drive", type: "n.", meaning: "การขับรถ, แรงขับ" },
    { word: "driving", type: "n.", meaning: "การขับรถ" },
    { word: "drop", type: "v.", meaning: "ทำตก, หยด" },
    { word: "drug", type: "n.", meaning: "ยา, ยาเสพติด" },
    { word: "dry", type: "adj., v.", meaning: "แห้ง, ทำให้แห้ง" },
    { word: "earn", type: "v.", meaning: "หารายได้" },
    { word: "earth", type: "n.", meaning: "โลก, พื้นดิน" },
    { word: "easily", type: "adv.", meaning: "อย่างง่ายดาย" },
    { word: "education", type: "n.", meaning: "การศึกษา" },
    { word: "effect", type: "n.", meaning: "ผลกระทบ" },
    { word: "either", type: "det./pron., adv.", meaning: "อย่างใดอย่างหนึ่ง (จากสอง)" },
    { word: "electric", type: "adj.", meaning: "ไฟฟ้า" },
    { word: "electrical", type: "adj.", meaning: "เกี่ยวกับไฟฟ้า" },
    { word: "electricity", type: "n.", meaning: "ไฟฟ้า" },
    { word: "electronic", type: "adj.", meaning: "อิเล็กทรอนิกส์" },
    { word: "employ", type: "v.", meaning: "จ้าง" },
    { word: "employee", type: "n.", meaning: "ลูกจ้าง" },
    { word: "employer", type: "n.", meaning: "นายจ้าง" },
    { word: "empty", type: "adj.", meaning: "ว่างเปล่า" },
    { word: "ending", type: "n.", meaning: "ตอนจบ" },
    { word: "energy", type: "n.", meaning: "พลังงาน" },
    { word: "engine", type: "n.", meaning: "เครื่องยนต์" },
    { word: "engineer", type: "n.", meaning: "วิศวกร" },
    { word: "enormous", type: "adj.", meaning: "ใหญ่โตมโหฬาร" },
    { word: "enter", type: "v.", meaning: "เข้าสู่" },
    { word: "environment", type: "n.", meaning: "สิ่งแวดล้อม" },
    { word: "equipment", type: "n.", meaning: "อุปกรณ์" },
    { word: "error", type: "n.", meaning: "ข้อผิดพลาด" },
    { word: "especially", type: "adv.", meaning: "โดยเฉพาะอย่างยิ่ง" },
    { word: "essay", type: "n.", meaning: "เรียงความ" },
    { word: "everyday", type: "adj.", meaning: "ประจำวัน" },
    { word: "everywhere", type: "adv.", meaning: "ทุกหนทุกแห่ง" },
    { word: "evidence", type: "n.", meaning: "หลักฐาน" },
    { word: "exact", type: "adj.", meaning: "ถูกต้องแม่นยำ" },
    { word: "exactly", type: "adv.", meaning: "อย่างแน่นอน, อย่างแม่นยำ" },
    { word: "excellent", type: "adj.", meaning: "ยอดเยี่ยม" },
    { word: "except", type: "prep.", meaning: "ยกเว้น" },
    { word: "exist", type: "v.", meaning: "มีอยู่" },
    { word: "expect", type: "v.", meaning: "คาดหวัง" },
    { word: "experience", type: "n.", meaning: "ประสบการณ์" },
    { word: "experiment", type: "n.", meaning: "การทดลอง" },
    { word: "expert", type: "n.,adj.", meaning: "ผู้เชี่ยวชาญ" },
    { word: "explanation", type: "n.", meaning: "คำอธิบาย" },
    { word: "express", type: "v.", meaning: "แสดงออก" },
    { word: "expression", type: "n.", meaning: "การแสดงออก, สำนวน" },
    { word: "extreme", type: "adj.", meaning: "สุดขีด, สุดโต่ง" },
    { word: "extremely", type: "adv.", meaning: "อย่างยิ่ง" },
    { word: "factor", type: "n.", meaning: "ปัจจัย" },
    { word: "factory", type: "n.", meaning: "โรงงาน" },
    { word: "fail", type: "v.", meaning: "ล้มเหลว" },
    { word: "fair", type: "adj.", meaning: "ยุติธรรม, เป็นธรรม" },
    { word: "fall", type: "n.", meaning: "การตก, ฤดูใบไม้ร่วง (US)" },
    { word: "fan", type: "n.", meaning: "พัดลม, แฟนคลับ" },
    { word: "farm", type: "v.", meaning: "ทำไร่ไถนา" },
    { word: "farming", type: "n.", meaning: "การทำฟาร์ม" },
    { word: "fashion", type: "n.", meaning: "แฟชั่น" },
    { word: "fat", type: "n.", meaning: "ไขมัน" },
    { word: "fear", type: "n.", meaning: "ความกลัว" },
    { word: "feature", type: "n.", meaning: "คุณสมบัติ, ลักษณะเด่น" },
    { word: "feed", type: "v.", meaning: "ให้อาหาร" },
    { word: "female", type: "adj., n.", meaning: "เพศหญิง, ผู้หญิง" },
    { word: "fiction", type: "n.", meaning: "นวนิยาย, เรื่องแต่ง" },
    { word: "field", type: "n.", meaning: "ทุ่งนา, สนาม, สาขา" },
    { word: "fight", type: "v., n.", meaning: "ต่อสู้, การต่อสู้" },
    { word: "figure", type: "n.", meaning: "ตัวเลข, รูปร่าง" },
    { word: "film", type: "v.", meaning: "ถ่ายทำภาพยนตร์" },
    { word: "final", type: "n.", meaning: "รอบชิงชนะเลิศ" },
    { word: "finally", type: "adv.", meaning: "ในที่สุด" },
    { word: "finger", type: "n.", meaning: "นิ้วมือ" },
    { word: "finish", type: "n.", meaning: "การสิ้นสุด" },
    { word: "first", type: "n.", meaning: "สิ่งแรก, คนแรก" },
    { word: "firstly", type: "adv.", meaning: "ประการแรก" },
    { word: "fish", type: "v.", meaning: "ตกปลา" },
    { word: "fishing", type: "n.", meaning: "การตกปลา" },
    { word: "fit", type: "v., adj.", meaning: "เหมาะสม, พอดี, แข็งแรง" },
    { word: "fix", type: "v.", meaning: "แก้ไข, ซ่อมแซม" },
    { word: "flat", type: "adj.", meaning: "แบน" },
    { word: "flu", type: "n.", meaning: "ไข้หวัดใหญ่" },
    { word: "fly", type: "n.", meaning: "แมลงวัน, การบิน" },
    { word: "flying", type: "n., adj.", meaning: "การบิน, ที่บินได้" },
    { word: "focus", type: "v., n.", meaning: "มุ่งเน้น, จุดโฟกัส" },
    { word: "following", type: "adj.", meaning: "ต่อไปนี้" },
    { word: "foreign", type: "adj.", meaning: "ต่างประเทศ" },
    { word: "forest", type: "n.", meaning: "ป่า" },
    { word: "fork", type: "n.", meaning: "ส้อม" },
    { word: "formal", type: "adj.", meaning: "เป็นทางการ" },
    { word: "fortunately", type: "adv.", meaning: "โชคดีที่" },
    { word: "forward", type: "adv.", meaning: "ไปข้างหน้า" },
    { word: "free", type: "adv.", meaning: "อย่างอิสระ" },
    { word: "fresh", type: "adj.", meaning: "สด, ใหม่" },
    { word: "fridge", type: "n.", meaning: "ตู้เย็น" },
    { word: "frog", type: "n.", meaning: "กบ" },
    { word: "fun", type: "adj.", meaning: "สนุก" },
    { word: "furniture", type: "n.", meaning: "เฟอร์นิเจอร์" },
    { word: "further", type: "adj.", meaning: "ไกลออกไป, เพิ่มเติม" },
    { word: "future", type: "adj.", meaning: "ในอนาคต" },
    { word: "gallery", type: "n.", meaning: "หอศิลป์" },
    { word: "gap", type: "n.", meaning: "ช่องว่าง" },
    { word: "gas", type: "n.", meaning: "แก๊ส, น้ำมัน (US)" },
    { word: "gate", type: "n.", meaning: "ประตูรั้ว, ประตู (สนามบิน)" },
    { word: "general", type: "adj.", meaning: "ทั่วไป" },
    { word: "gift", type: "n.", meaning: "ของขวัญ" },
    { word: "goal", type: "n.", meaning: "เป้าหมาย, ประตู (กีฬา)" },
    { word: "god", type: "n.", meaning: "พระเจ้า" },
    { word: "gold", type: "n., adj.", meaning: "ทองคำ, สีทอง" },
    { word: "golf", type: "n.", meaning: "กอล์ฟ" },
    { word: "good", type: "n.", meaning: "ความดี, สิ่งที่ดี" },
    { word: "government", type: "n.", meaning: "รัฐบาล" },
    { word: "grass", type: "n.", meaning: "หญ้า" },
    { word: "greet", type: "v.", meaning: "ทักทาย" },
    { word: "ground", type: "n.", meaning: "พื้นดิน" },
    { word: "guest", type: "n.", meaning: "แขก" },
    { word: "guide", type: "n., v.", meaning: "มัคคุเทศก์, นำทาง" },
    { word: "gun", type: "n.", meaning: "ปืน" },
    { word: "guy", type: "n.", meaning: "ผู้ชาย (ไม่เป็นทางการ)" },
    { word: "habit", type: "n.", meaning: "นิสัย" },
    { word: "half", type: "adv.", meaning: "ครึ่งหนึ่ง" },
    { word: "hall", type: "n.", meaning: "ห้องโถง" },
    { word: "happily", type: "adv.", meaning: "อย่างมีความสุข" },
    { word: "have", type: "auxiliary v.", meaning: "มี, ได้ (กริยาช่วย)" },
    { word: "headache", type: "n.", meaning: "อาการปวดหัว" },
    { word: "heart", type: "n.", meaning: "หัวใจ" },
    { word: "heat", type: "n., v.", meaning: "ความร้อน, ทำให้ร้อน" },
    { word: "heavy", type: "adj.", meaning: "หนัก" },
    { word: "height", type: "n.", meaning: "ความสูง" },
    { word: "helpful", type: "adj.", meaning: "เป็นประโยชน์" },
    { word: "hero", type: "n.", meaning: "วีรบุรุษ" },
    { word: "hers", type: "pron.", meaning: "ของเธอ (ผู้หญิง)" },
    { word: "herself", type: "pron.", meaning: "ตัวเธอเอง (ผู้หญิง)" },
    { word: "hide", type: "v.", meaning: "ซ่อน" },
    { word: "high", type: "adv.", meaning: "สูง" },
    { word: "hill", type: "n.", meaning: "เนินเขา" },
    { word: "himself", type: "pron.", meaning: "ตัวเขาเอง (ผู้ชาย)" },
    { word: "his", type: "pron.", meaning: "ของเขา (ผู้ชาย)" },
    { word: "hit", type: "v., n.", meaning: "ตี, การตี" },
    { word: "hockey", type: "n.", meaning: "ฮอกกี้" },
    { word: "hold", type: "v.", meaning: "ถือ, จัด" },
    { word: "hole", type: "n.", meaning: "รู" },
    { word: "home", type: "adj.", meaning: "ที่บ้าน" },
    { word: "hope", type: "n.", meaning: "ความหวัง" },
    { word: "huge", type: "adj.", meaning: "ใหญ่มาก, มหึมา" },
    { word: "human", type: "adj., n.", meaning: "มนุษย์, ที่เป็นมนุษย์" },
    { word: "hurt", type: "v., adj.", meaning: "เจ็บ, ทำร้าย, ที่เจ็บปวด" },
    { word: "ideal", type: "adj.", meaning: "ในอุดมคติ" },
    { word: "identify", type: "v.", meaning: "ระบุ" },
    { word: "ill", type: "adj.", meaning: "ป่วย" },
    { word: "illness", type: "n.", meaning: "ความเจ็บป่วย, โรค" },
    { word: "image", type: "n.", meaning: "ภาพ, รูป" },
    { word: "immediately", type: "adv.", meaning: "ทันที" },
    { word: "impossible", type: "adj.", meaning: "เป็นไปไม่ได้" },
    { word: "included", type: "adj.", meaning: "ที่รวมอยู่" },
    { word: "including", type: "prep.", meaning: "รวมถึง" },
    { word: "increase", type: "v., n.", meaning: "เพิ่มขึ้น, การเพิ่มขึ้น" },
    { word: "incredible", type: "adj.", meaning: "ไม่น่าเชื่อ" },
    { word: "independent", type: "adj.", meaning: "อิสระ" },
    { word: "individual", type: "n., adj.", meaning: "บุคคล, รายบุคคล" },
    { word: "industry", type: "n.", meaning: "อุตสาหกรรม" },
    { word: "informal", type: "adj.", meaning: "ไม่เป็นทางการ" },
    { word: "injury", type: "n.", meaning: "อาการบาดเจ็บ" },
    { word: "insect", type: "n.", meaning: "แมลง" },
    { word: "inside", type: "prep., adv., n., adj.", meaning: "ข้างใน" },
    { word: "instead", type: "adv.", meaning: "แทนที่" },
    { word: "instruction", type: "n.", meaning: "คำแนะนำ" },
    { word: "instructor", type: "n.", meaning: "ผู้สอน, ครูฝึก" },
    { word: "instrument", type: "n.", meaning: "เครื่องดนตรี, เครื่องมือ" },
    { word: "intelligent", type: "adj.", meaning: "ฉลาด" },
    { word: "international", type: "adj.", meaning: "ระหว่างประเทศ" },
    { word: "introduction", type: "n.", meaning: "การแนะนำ, บทนำ" },
    { word: "invent", type: "v.", meaning: "ประดิษฐ์" },
    { word: "invention", type: "n.", meaning: "สิ่งประดิษฐ์" },
    { word: "invitation", type: "n.", meaning: "บัตรเชิญ" },
    { word: "invite", type: "v.", meaning: "เชิญ" },
    { word: "involve", type: "v.", meaning: "เกี่ยวข้อง" },
    { word: "item", type: "n.", meaning: "รายการ, สิ่งของ" },
    { word: "itself", type: "pron.", meaning: "ตัวมันเอง" },
    { word: "jam", type: "n.", meaning: "แยม, รถติด" },
    { word: "jazz", type: "n.", meaning: "เพลงแจ๊ส" },
    { word: "jewellery", type: "n.", meaning: "เครื่องประดับ" },
    { word: "joke", type: "n., v.", meaning: "เรื่องตลก, ล้อเล่น" },
    { word: "journalist", type: "n.", meaning: "นักข่าว" },
    { word: "jump", type: "v., n.", meaning: "กระโดด, การกระโดด" },
    { word: "kid", type: "n.", meaning: "เด็ก (ไม่เป็นทางการ)" },
    { word: "kill", type: "v.", meaning: "ฆ่า" },
    { word: "king", type: "n.", meaning: "กษัตริย์" },
    { word: "knee", type: "n.", meaning: "หัวเข่า" },
    { word: "knife", type: "n.", meaning: "มีด" },
    { word: "knock", type: "v.", meaning: "เคาะ" },
    { word: "knowledge", type: "n.", meaning: "ความรู้" },
    { word: "lab", type: "n.", meaning: "ห้องทดลอง" },
    { word: "lady", type: "n.", meaning: "สุภาพสตรี" },
    { word: "lake", type: "n.", meaning: "ทะเลสาบ" },
    { word: "lamp", type: "n.", meaning: "โคมไฟ" },
    { word: "land", type: "v.", meaning: "ลงจอด" },
    { word: "laptop", type: "n.", meaning: "แล็ปท็อป" },
    { word: "last", type: "v., adv., n.", meaning: "คงอยู่, ใช้เวลา, สุดท้าย, สิ่งสุดท้าย" },
    { word: "later", type: "adj.", meaning: "ที่มาทีหลัง, ภายหลัง" },
    { word: "laughter", type: "n.", meaning: "เสียงหัวเราะ" },
    { word: "law", type: "n.", meaning: "กฎหมาย" },
    { word: "lawyer", type: "n.", meaning: "ทนายความ" },
    { word: "lazy", type: "adj.", meaning: "ขี้เกียจ" },
    { word: "lead", type: "v.", meaning: "นำ, นำไปสู่" },
    { word: "leader", type: "n.", meaning: "ผู้นำ" },
    { word: "learning", type: "n.", meaning: "การเรียนรู้" },
    { word: "least", type: "det./pron., adv.", meaning: "น้อยที่สุด" },
    { word: "lecture", type: "n., v.", meaning: "การบรรยาย, บรรยาย" },
    { word: "lemon", type: "n.", meaning: "มะนาว (สีเหลือง)" },
    { word: "lend", type: "v.", meaning: "ให้ยืม" },
    { word: "less", type: "det./pron., adv.", meaning: "น้อยกว่า" },
    { word: "level", type: "n.", meaning: "ระดับ" },
    { word: "lifestyle", type: "n.", meaning: "ไลฟ์สไตล์, วิถีชีวิต" },
    { word: "lift", type: "v., n.", meaning: "ยก, ลิฟต์" },
    { word: "light", type: "v., adj.", meaning: "ให้แสงสว่าง, เบา" },
    { word: "likely", type: "adj.", meaning: "เป็นไปได้" },
    { word: "link", type: "n., v.", meaning: "ลิงก์, เชื่อมโยง" },
    { word: "listener", type: "n.", meaning: "ผู้ฟัง" },
    { word: "little", type: "adv.", meaning: "เล็กน้อย" },
    { word: "lock", type: "v., n.", meaning: "ล็อค, กุญแจ" },
    { word: "look", type: "n.", meaning: "รูปลักษณ์, การมอง" },
    { word: "lorry", type: "n.", meaning: "รถบรรทุก (UK)" },
    { word: "lost", type: "adj.", meaning: "หายไป, หลงทาง" },
    { word: "loud", type: "adj., adv.", meaning: "เสียงดัง, อย่างดัง" },
    { word: "loudly", type: "adv.", meaning: "อย่างเสียงดัง" },
    { word: "lovely", type: "adj.", meaning: "น่ารัก, สวยงาม" },
    { word: "low", type: "adj., adv.", meaning: "ต่ำ, อย่างต่ำ" },
    { word: "luck", type: "n.", meaning: "โชค" },
    { word: "lucky", type: "adj.", meaning: "โชคดี" },
    { word: "mail", type: "n., v.", meaning: "จดหมาย, ส่งจดหมาย" },
    { word: "major", type: "adj.", meaning: "สำคัญ, หลัก" },
    { word: "male", type: "adj., n.", meaning: "เพศชาย, ผู้ชาย" },
    { word: "manage", type: "v.", meaning: "จัดการ, บริหาร" },
    { word: "manager", type: "n.", meaning: "ผู้จัดการ" },
    { word: "manner", type: "n.", meaning: "มารยาท, ลักษณะ" },
    { word: "mark", type: "v., n.", meaning: "ทำเครื่องหมาย, เครื่องหมาย" },
    { word: "marry", type: "v.", meaning: "แต่งงาน" },
    { word: "material", type: "n.", meaning: "วัสดุ, สาร" },
    { word: "mathematics", type: "n.", meaning: "คณิตศาสตร์" },
    { word: "maths", type: "n.", meaning: "คณิตศาสตร์ (UK)" },
    { word: "matter", type: "n., v.", meaning: "เรื่อง, สสาร, สำคัญ" },
    { word: "may", type: "modal v.", meaning: "อาจจะ, อนุญาต" },
    { word: "media", type: "n.", meaning: "สื่อ" },
    { word: "medical", type: "adj.", meaning: "ทางการแพทย์" },
    { word: "medicine", type: "n.", meaning: "ยา, แพทย์ศาสตร์" },
    { word: "memory", type: "n.", meaning: "ความจำ, หน่วยความจำ" },
    { word: "mention", type: "v.", meaning: "กล่าวถึง" },
    { word: "metal", type: "n.", meaning: "โลหะ" },
    { word: "method", type: "n.", meaning: "วิธี, ระเบียบ" },
    { word: "middle", type: "n., adj.", meaning: "ตรงกลาง, กลาง" },
    { word: "might", type: "modal v.", meaning: "อาจจะ (รูปอดีตของ may)" },
    { word: "mind", type: "n., v.", meaning: "จิตใจ, รังเกียจ" },
    { word: "mine", type: "pron.", meaning: "ของฉัน" },
    { word: "mirror", type: "n.", meaning: "กระจก" },
    { word: "missing", type: "adj.", meaning: "หายไป" },
    { word: "mobile", type: "adj., n.", meaning: "เคลื่อนที่ได้, โทรศัพท์มือถือ" },
    { word: "monkey", type: "n.", meaning: "ลิง" },
    { word: "moon", type: "n.", meaning: "ดวงจันทร์" },
    { word: "mostly", type: "adv.", meaning: "ส่วนใหญ่" },
    { word: "motorcycle", type: "n.", meaning: "รถจักรยานยนต์" },
    { word: "movement", type: "n.", meaning: "การเคลื่อนไหว" },
    { word: "musical", type: "adj.", meaning: "เกี่ยวกับดนตรี" },
    { word: "musician", type: "n.", meaning: "นักดนตรี" },
    { word: "myself", type: "pron.", meaning: "ตัวฉันเอง" },
    { word: "narrow", type: "adj.", meaning: "แคบ" },
    { word: "national", type: "adj.", meaning: "แห่งชาติ" },
    { word: "nature", type: "n.", meaning: "ธรรมชาติ" },
    { word: "nearly", type: "adv.", meaning: "เกือบจะ" },
    { word: "necessary", type: "adj.", meaning: "จำเป็น" },
    { word: "neck", type: "n.", meaning: "คอ" },
    { word: "need", type: "n.", meaning: "ความต้องการ" },
    { word: "neither", type: "det./pron.", meaning: "ไม่ทั้งสอง" },
    { word: "nervous", type: "adj.", meaning: "ประหม่า, กังวล" },
    { word: "network", type: "n.", meaning: "เครือข่าย" },
    { word: "noise", type: "n.", meaning: "เสียงรบกวน" },
    { word: "noisy", type: "adj.", meaning: "เสียงดัง" },
    { word: "none", type: "pron.", meaning: "ไม่มีเลย" },
    { word: "normal", type: "adj.", meaning: "ปกติ" },
    { word: "normally", type: "adv.", meaning: "โดยปกติ" },
    { word: "notice", type: "v., n.", meaning: "สังเกต, ประกาศ" },
    { word: "novel", type: "n.", meaning: "นวนิยาย" },
    { word: "nowhere", type: "adv.", meaning: "ที่ไหนเลย (ไม่มีที่ไหนเลย)" },
    { word: "number", type: "v.", meaning: "ใส่หมายเลข" },
    { word: "nut", type: "n.", meaning: "ถั่ว" },
    { word: "ocean", type: "n.", meaning: "มหาสมุทร" },
    { word: "offer", type: "v., n.", meaning: "เสนอ, ข้อเสนอ" },
    { word: "officer", type: "n.", meaning: "เจ้าหน้าที่" },
    { word: "oil", type: "n.", meaning: "น้ำมัน" },
    { word: "onto", type: "prep.", meaning: "ไปบน" },
    { word: "opportunity", type: "n.", meaning: "โอกาส" },
    { word: "option", type: "n.", meaning: "ตัวเลือก" },
    { word: "ordinary", type: "adj.", meaning: "ธรรมดา" },
    { word: "organization", type: "n.", meaning: "องค์กร" },
    { word: "organize", type: "v.", meaning: "จัดระเบียบ" },
    { word: "original", type: "adj.", meaning: "ดั้งเดิม, ต้นฉบับ" },
    { word: "ourselves", type: "pron.", meaning: "ตัวพวกเราเอง" },
    { word: "outside", type: "prep., n., adj.", meaning: "ข้างนอก, ด้านนอก" },
    { word: "oven", type: "n.", meaning: "เตาอบ" },
    { word: "own", type: "v.", meaning: "เป็นเจ้าของ" },
    { word: "owner", type: "n.", meaning: "เจ้าของ" },
    { word: "pack", type: "v.", meaning: "บรรจุ, ห่อ" },
    { word: "pain", type: "n.", meaning: "ความเจ็บปวด" },
    { word: "painter", type: "n.", meaning: "จิตรกร, ช่างทาสี" },
    { word: "palace", type: "n.", meaning: "พระราชวัง" },
    { word: "pants", type: "n.", meaning: "กางเกงขายาว (US), กางเกงใน (UK)" },
    { word: "parking", type: "n.", meaning: "ที่จอดรถ, การจอดรถ" },
    { word: "particular", type: "adj.", meaning: "เฉพาะเจาะจง" },
    { word: "pass", type: "v.", meaning: "ผ่าน, ส่ง" },
    { word: "passenger", type: "n.", meaning: "ผู้โดยสาร" },
    { word: "past", type: "adv.", meaning: "ผ่านไปแล้ว" },
    { word: "patient", type: "n.", meaning: "ผู้ป่วย" },
    { word: "pattern", type: "n.", meaning: "รูปแบบ" },
    { word: "pay", type: "n.", meaning: "ค่าจ้าง, การจ่ายเงิน" },
    { word: "peace", type: "n.", meaning: "ความสงบ" },
    { word: "penny", type: "n.", meaning: "เพนนี (เหรียญสตางค์)" },
    { word: "per", type: "prep.", meaning: "ต่อ (เช่น ต่อชั่วโมง)" },
    { word: "percent", type: "n., adj./adv.", meaning: "เปอร์เซ็นต์" },
    { word: "perform", type: "v.", meaning: "แสดง, ปฏิบัติ" },
    { word: "perhaps", type: "adv.", meaning: "บางที, อาจจะ" },
    { word: "permission", type: "n.", meaning: "การอนุญาต" },
    { word: "personality", type: "n.", meaning: "บุคลิกภาพ" },
    { word: "pet", type: "n.", meaning: "สัตว์เลี้ยง" },
    { word: "petrol", type: "n.", meaning: "น้ำมันเชื้อเพลิง (UK)" },
    { word: "photograph", type: "v.", meaning: "ถ่ายรูป" },
    { word: "physical", type: "adj.", meaning: "กายภาพ, ทางกาย" },
    { word: "physics", type: "n.", meaning: "ฟิสิกส์" },
    { word: "pick", type: "v.", meaning: "เลือก, หยิบ" },
    { word: "pilot", type: "n.", meaning: "นักบิน" },
    { word: "planet", type: "n.", meaning: "ดาวเคราะห์" },
    { word: "plant", type: "v.", meaning: "ปลูก" },
    { word: "plastic", type: "n., adj.", meaning: "พลาสติก" },
    { word: "plate", type: "n.", meaning: "จาน" },
    { word: "platform", type: "n.", meaning: "ชานชาลา, แพลตฟอร์ม" },
    { word: "please", type: "v.", meaning: "ทำให้พอใจ" },
    { word: "pleased", type: "adj.", meaning: "พอใจ" },
    { word: "pocket", type: "n.", meaning: "กระเป๋าเสื้อ/กางเกง" },
    { word: "polite", type: "adj.", meaning: "สุภาพ" },
    { word: "pollution", type: "n.", meaning: "มลพิษ" },
    { word: "pop", type: "n., adj.", meaning: "เพลงป๊อป, เสียงป๊อป" },
    { word: "population", type: "n.", meaning: "ประชากร" },
    { word: "position", type: "n.", meaning: "ตำแหน่ง" },
    { word: "possession", type: "n.", meaning: "การครอบครอง, ทรัพย์สิน" },
    { word: "possibility", type: "n.", meaning: "ความเป็นไปได้" },
    { word: "poster", type: "n.", meaning: "โปสเตอร์" },
    { word: "power", type: "n.", meaning: "พลังงาน, อำนาจ" },
    { word: "predict", type: "v.", meaning: "ทำนาย" },
    { word: "present", type: "v.", meaning: "นำเสนอ, มอบให้" },
    { word: "president", type: "n.", meaning: "ประธานาธิบดี, ประธาน" },
    { word: "prevent", type: "v.", meaning: "ป้องกัน" },
    { word: "print", type: "v.", meaning: "พิมพ์" },
    { word: "printer", type: "n.", meaning: "เครื่องพิมพ์" },
    { word: "prison", type: "n.", meaning: "เรือนจำ, คุก" },
    { word: "prize", type: "n.", meaning: "รางวัล" },
    { word: "process", type: "n.", meaning: "กระบวนการ" },
    { word: "produce", type: "v.", meaning: "ผลิต" },
    { word: "professional", type: "adj.", meaning: "มืออาชีพ" },
    { word: "professor", type: "n.", meaning: "ศาสตราจารย์" },
    { word: "profile", type: "n.", meaning: "ประวัติส่วนตัว, รูปภาพส่วนตัว" },
    { word: "program", type: "n.", meaning: "โปรแกรม (US)" },
    { word: "progress", type: "n.", meaning: "ความก้าวหน้า" },
    { word: "promise", type: "v., n.", meaning: "สัญญา, คำสัญญา" },
    { word: "pronounce", type: "v.", meaning: "ออกเสียง" },
    { word: "protect", type: "v.", meaning: "ปกป้อง" },
    { word: "provide", type: "v.", meaning: "จัดหา, ให้" },
    { word: "pub", type: "n.", meaning: "ผับ" },
    { word: "public", type: "adj., n.", meaning: "สาธารณะ, ประชาชน" },
    { word: "publish", type: "v.", meaning: "ตีพิมพ์, เผยแพร่" },
    { word: "pull", type: "v.", meaning: "ดึง" },
    { word: "purpose", type: "n.", meaning: "วัตถุประสงค์" },
    { word: "push", type: "v.", meaning: "ผลัก" },
    { word: "quality", type: "n.", meaning: "คุณภาพ" },
    { word: "quantity", type: "n.", meaning: "ปริมาณ" },
    { word: "queen", type: "n.", meaning: "พระราชินี" },
    { word: "question", type: "v.", meaning: "ถาม" },
    { word: "quietly", type: "adv.", meaning: "อย่างเงียบๆ" },
    { word: "race", type: "n., v.", meaning: "การแข่งขัน, แข่งขัน" },
    { word: "railway", type: "n.", meaning: "ทางรถไฟ" },
    { word: "raise", type: "v.", meaning: "ยกขึ้น, เพิ่มขึ้น, เลี้ยงดู" },
    { word: "rate", type: "n.", meaning: "อัตรา" },
    { word: "rather", type: "adv.", meaning: "ค่อนข้าง" },
    { word: "reach", type: "v.", meaning: "เอื้อมถึง, ไปถึง" },
    { word: "react", type: "v.", meaning: "ตอบสนอง" },
    { word: "realize", type: "v.", meaning: "ตระหนักรู้" },
    { word: "receive", type: "v.", meaning: "ได้รับ" },
    { word: "recent", type: "adj.", meaning: "เมื่อเร็วๆ นี้" },
    { word: "recently", type: "adv.", meaning: "เมื่อเร็วๆ นี้" },
    { word: "reception", type: "n.", meaning: "แผนกต้อนรับ, การต้อนรับ" },
    { word: "recipe", type: "n.", meaning: "สูตรอาหาร" },
    { word: "recognize", type: "v.", meaning: "จดจำ" },
    { word: "recommend", type: "v.", meaning: "แนะนำ" },
    { word: "record", type: "n., v.", meaning: "บันทึก, สถิติ, บันทึกเสียง" },
    { word: "recording", type: "n.", meaning: "การบันทึกเสียง" },
    { word: "recycle", type: "v.", meaning: "รีไซเคิล" },
    { word: "reduce", type: "v.", meaning: "ลดลง" },
    { word: "refer", type: "v.", meaning: "อ้างถึง, อ้างอิง" },
    { word: "refuse", type: "v.", meaning: "ปฏิเสธ" },
    { word: "region", type: "n.", meaning: "ภูมิภาค" },
    { word: "regular", type: "adj.", meaning: "ปกติ, สม่ำเสมอ" },
    { word: "relationship", type: "n.", meaning: "ความสัมพันธ์" },
    { word: "remove", type: "v.", meaning: "เอาออก" },
    { word: "repair", type: "v.", meaning: "ซ่อมแซม" },
    { word: "replace", type: "v.", meaning: "แทนที่" },
    { word: "reply", type: "v., n.", meaning: "ตอบกลับ, การตอบกลับ" },
    { word: "report", type: "v.", meaning: "รายงาน" },
    { word: "reporter", type: "n.", meaning: "ผู้สื่อข่าว" },
    { word: "request", type: "n.", meaning: "คำขอ" },
    { word: "research", type: "n., v.", meaning: "การวิจัย, วิจัย" },
    { word: "researcher", type: "n.", meaning: "นักวิจัย" },
    { word: "respond", type: "v.", meaning: "ตอบสนอง" },
    { word: "response", type: "n.", meaning: "การตอบสนอง" },
    { word: "rest", type: "n., v.", meaning: "พักผ่อน, การพักผ่อน, ส่วนที่เหลือ" },
    { word: "review", type: "n., v.", meaning: "การทบทวน, วิจารณ์" },
    { word: "ride", type: "n.", meaning: "การขี่" },
    { word: "ring", type: "n.", meaning: "แหวน" },
    { word: "ring", type: "v.", meaning: "โทรศัพท์, สั่น" },
    { word: "rise", type: "v.", meaning: "ขึ้น, เพิ่มขึ้น" },
    { word: "rock", type: "n.", meaning: "หิน, เพลงร็อก" },
    { word: "role", type: "n.", meaning: "บทบาท" },
    { word: "roof", type: "n.", meaning: "หลังคา" },
    { word: "round", type: "adj., adv., prep.", meaning: "กลม, รอบๆ" },
    { word: "route", type: "n.", meaning: "เส้นทาง" },
    { word: "rubbish", type: "n.", meaning: "ขยะ" },
    { word: "rude", type: "adj.", meaning: "หยาบคาย" },
    { word: "run", type: "n.", meaning: "การวิ่ง, การจัดการ" },
    { word: "runner", type: "n.", meaning: "นักวิ่ง" },
    { word: "running", type: "n.", meaning: "การวิ่ง" },
    { word: "sadly", type: "adv.", meaning: "อย่างเศร้า" },
    { word: "safe", type: "adj.", meaning: "ปลอดภัย" },
    { word: "sail", type: "v.", meaning: "แล่นเรือ" },
    { word: "sailing", type: "n.", meaning: "การแล่นเรือ" },
    { word: "salary", type: "n.", meaning: "เงินเดือน" },
    { word: "sale", type: "n.", meaning: "การขาย" },
    { word: "sauce", type: "n.", meaning: "ซอส" },
    { word: "save", type: "v.", meaning: "บันทึก, ประหยัด, ช่วยชีวิต" },
    { word: "scared", type: "adj.", meaning: "ตกใจ, กลัว" },
    { word: "scary", type: "adj.", meaning: "น่ากลัว" },
    { word: "scene", type: "n.", meaning: "ฉาก, ทิวทัศน์" },
    { word: "schedule", type: "n.", meaning: "ตารางเวลา" },
    { word: "score", type: "v., n.", meaning: "ทำคะแนน, คะแนน" },
    { word: "screen", type: "n.", meaning: "หน้าจอ" },
    { word: "search", type: "n., v.", meaning: "การค้นหา, ค้นหา" },
    { word: "season", type: "n.", meaning: "ฤดู, ฤดูกาล" },
    { word: "seat", type: "n.", meaning: "ที่นั่ง" },
    { word: "second", type: "adv.", meaning: "อันดับสอง" },
    { word: "secondly", type: "adv.", meaning: "ประการที่สอง" },
    { word: "secret", type: "adj., n.", meaning: "ความลับ, ลับ" },
    { word: "secretary", type: "n.", meaning: "เลขานุการ" },
    { word: "seem", type: "v.", meaning: "ดูเหมือนว่า" },
    { word: "sense", type: "n.", meaning: "ความรู้สึก, ประสาทสัมผัส" },
    { word: "separate", type: "adj.", meaning: "แยกต่างหาก" },
    { word: "series", type: "n.", meaning: "ชุด, ซีรีส์" },
    { word: "serious", type: "adj.", meaning: "จริงจัง" },
    { word: "serve", type: "v.", meaning: "ให้บริการ, เสิร์ฟ" },
    { word: "service", type: "n.", meaning: "บริการ" },
    { word: "several", type: "det./pron.", meaning: "หลาย" },
    { word: "shake", type: "v.", meaning: "เขย่า, สั่น" },
    { word: "shall", type: "modal v.", meaning: "จะ (ใช้กับ I/we แสดงความตั้งใจ/คำถาม)" },
    { word: "shape", type: "n.", meaning: "รูปร่าง" },
    { word: "sheet", type: "n.", meaning: "แผ่น (กระดาษ), ผ้าปูที่นอน" },
    { word: "ship", type: "n.", meaning: "เรือ" },
    { word: "shoulder", type: "n.", meaning: "ไหล่" },
    { word: "shout", type: "v., n.", meaning: "ตะโกน, การตะโกน" },
    { word: "shut", type: "v., adj.", meaning: "ปิด, ที่ปิดอยู่" },
    { word: "side", type: "n.", meaning: "ด้าน, ข้าง" },
    { word: "sign", type: "n., v.", meaning: "ป้าย, สัญญาณ, ลงชื่อ" },
    { word: "silver", type: "n., adj.", meaning: "เงิน, สีเงิน" },
    { word: "simple", type: "adj.", meaning: "ง่าย, เรียบง่าย" },
    { word: "since", type: "prep., conj.", meaning: "ตั้งแต่, เพราะว่า" },
    { word: "singing", type: "n.", meaning: "การร้องเพลง" },
    { word: "single", type: "adj., n.", meaning: "เดี่ยว, โสด, คนโสด" },
    { word: "sir", type: "n.", meaning: "ท่านครับ (คำเรียกผู้ชายอย่างสุภาพ)" },
    { word: "site", type: "n.", meaning: "เว็บไซต์, สถานที่" },
    { word: "size", type: "n.", meaning: "ขนาด" },
    { word: "ski", type: "v., adj., n.", meaning: "เล่นสกี" },
    { word: "skiing", type: "n.", meaning: "การเล่นสกี" },
    { word: "skin", type: "n.", meaning: "ผิวหนัง" },
    { word: "sky", type: "n.", meaning: "ท้องฟ้า" },
    { word: "sleep", type: "n.", meaning: "การนอนหลับ" },
    { word: "slowly", type: "adv.", meaning: "อย่างช้าๆ" },
    { word: "smartphone", type: "n.", meaning: "สมาร์ทโฟน" },
    { word: "smell", type: "v., n.", meaning: "ดม, มีกลิ่น, กลิ่น" },
    { word: "smile", type: "v., n.", meaning: "ยิ้ม, รอยยิ้ม" },
    { word: "smoke", type: "n., v.", meaning: "ควัน, สูบบุหรี่" },
    { word: "smoking", type: "n.", meaning: "การสูบบุหรี่" },
    { word: "soap", type: "n.", meaning: "สบู่" },
    { word: "soccer", type: "n.", meaning: "ฟุตบอล (US)" },
    { word: "social", type: "adj.", meaning: "สังคม" },
    { word: "society", type: "n.", meaning: "สังคม" },
    { word: "sock", type: "n.", meaning: "ถุงเท้า" },
    { word: "soft", type: "adj.", meaning: "นุ่ม" },
    { word: "soldier", type: "n.", meaning: "ทหาร" },
    { word: "solution", type: "n.", meaning: "วิธีแก้ปัญหา, สารละลาย" },
    { word: "solve", type: "v.", meaning: "แก้ไขปัญหา" },
    { word: "somewhere", type: "adv., pron.", meaning: "ที่ไหนสักแห่ง" },
    { word: "sort", type: "n.", meaning: "ชนิด, ประเภท" },
    { word: "source", type: "n.", meaning: "แหล่งที่มา" },
    { word: "speaker", type: "n.", meaning: "ลำโพง, ผู้พูด" },
    { word: "specific", type: "adj.", meaning: "เฉพาะเจาะจง" },
    { word: "speech", type: "n.", meaning: "คำพูด, สุนทรพจน์" },
    { word: "speed", type: "n.", meaning: "ความเร็ว" },
    { word: "spider", type: "n.", meaning: "แมงมุม" },
    { word: "spoon", type: "n.", meaning: "ช้อน" },
    { word: "square", type: "adj., n.", meaning: "สี่เหลี่ยมจัตุรัส, จัตุรัส" },
    { word: "stage", type: "n.", meaning: "เวที, ขั้นตอน" },
    { word: "stair", type: "n.", meaning: "บันได" },
    { word: "stamp", type: "n.", meaning: "แสตมป์" },
    { word: "star", type: "v.", meaning: "แสดงเป็นตัวเอก" },
    { word: "start", type: "n.", meaning: "การเริ่มต้น" },
    { word: "state", type: "n.", meaning: "รัฐ, สภาพ" },
    { word: "stay", type: "n.", meaning: "การพัก, การอยู่" },
    { word: "steal", type: "v.", meaning: "ขโมย" },
    { word: "step", type: "n.", meaning: "ก้าว, ขั้นบันได" },
    { word: "stomach", type: "n.", meaning: "ท้อง, กระเพาะอาหาร" },
    { word: "stone", type: "n.", meaning: "หิน" },
    { word: "store", type: "n.", meaning: "ร้านค้า (US)" },
    { word: "storm", type: "n.", meaning: "พายุ" },
    { word: "straight", type: "adv., adj.", meaning: "ตรง, ตรงไป" },
    { word: "strange", type: "adj.", meaning: "แปลก" },
    { word: "strategy", type: "n.", meaning: "กลยุทธ์" },
    { word: "stress", type: "n., v.", meaning: "ความเครียด, เน้น" },
    { word: "structure", type: "n.", meaning: "โครงสร้าง" },
    { word: "stupid", type: "adj.", meaning: "โง่" },
    { word: "succeed", type: "v.", meaning: "ประสบความสำเร็จ" },
    { word: "successful", type: "adj.", meaning: "ประสบความสำเร็จ" },
    { word: "such", type: "det./pron.", meaning: "เช่นนี้, อย่างนั้น" },
    { word: "suddenly", type: "adv.", meaning: "ทันใดนั้น" },
    { word: "suggest", type: "v.", meaning: "แนะนำ" },
    { word: "suggestion", type: "n.", meaning: "ข้อเสนอแนะ" },
    { word: "suit", type: "n.", meaning: "ชุดสูท" },
    { word: "support", type: "v., n.", meaning: "สนับสนุน, การสนับสนุน" },
    { word: "suppose", type: "v.", meaning: "สมมติว่า, คิดว่า" },
    { word: "sure", type: "adv.", meaning: "แน่นอน" },
    { word: "surprise", type: "n., v.", meaning: "ความประหลาดใจ, ทำให้ประหลาดใจ" },
    { word: "surprised", type: "adj.", meaning: "ประหลาดใจ" },
    { word: "surprising", type: "adj.", meaning: "น่าประหลาดใจ" },
    { word: "survey", type: "n.", meaning: "แบบสำรวจ, การสำรวจ" },
    { word: "sweet", type: "adj., n.", meaning: "หวาน, ขนมหวาน" },
    { word: "symbol", type: "n.", meaning: "สัญลักษณ์" },
    { word: "system", type: "n.", meaning: "ระบบ" },
    { word: "tablet", type: "n.", meaning: "แท็บเล็ต, ยาเม็ด" },
    { word: "talk", type: "n.", meaning: "การพูดคุย" },
    { word: "target", type: "n.", meaning: "เป้าหมาย" },
    { word: "task", type: "n.", meaning: "งาน, ภารกิจ" },
    { word: "taste", type: "n., v.", meaning: "รสชาติ, ชิม" },
    { word: "teaching", type: "n.", meaning: "การสอน" },
    { word: "technology", type: "n.", meaning: "เทคโนโลยี" },
    { word: "teenage", type: "adj.", meaning: "วัยรุ่น" },
    { word: "temperature", type: "n.", meaning: "อุณหภูมิ" },
    { word: "term", type: "n.", meaning: "ระยะเวลา, เทอม, คำศัพท์" },
    { word: "text", type: "v.", meaning: "ส่งข้อความ" },
    { word: "themselves", type: "pron.", meaning: "ตัวพวกเขาเอง" },
    { word: "thick", type: "adj.", meaning: "หนา" },
    { word: "thief", type: "n.", meaning: "ขโมย" },
    { word: "thin", type: "adj.", meaning: "ผอม, บาง" },
    { word: "thinking", type: "n.", meaning: "การคิด" },
    { word: "third", type: "n.", meaning: "หนึ่งในสาม" },
    { word: "thought", type: "n.", meaning: "ความคิด" },
    { word: "throw", type: "v.", meaning: "โยน" },
    { word: "tidy", type: "adj., v.", meaning: "เป็นระเบียบ, จัดให้เป็นระเบียบ" },
    { word: "tie", type: "v., n.", meaning: "ผูก, เนคไท" },
    { word: "tip", type: "n.", meaning: "เคล็ดลับ, เงินทิป, ปลาย" },
    { word: "tool", type: "n.", meaning: "เครื่องมือ" },
    { word: "top", type: "n., adj.", meaning: "ยอด, ด้านบน, สูงสุด" },
    { word: "touch", type: "v.", meaning: "สัมผัส" },
    { word: "tour", type: "n.", meaning: "การท่องเที่ยว" },
    { word: "tourism", type: "n.", meaning: "การท่องเที่ยว" },
    { word: "towards", type: "prep.", meaning: "ไปทาง" },
    { word: "towel", type: "n.", meaning: "ผ้าเช็ดตัว" },
    { word: "tower", type: "n.", meaning: "หอคอย" },
    { word: "toy", type: "n., adj.", meaning: "ของเล่น" },
    { word: "track", type: "n.", meaning: "รอยทาง, ลู่ (วิ่ง)" },
    { word: "tradition", type: "n.", meaning: "ประเพณี" },
    { word: "traditional", type: "adj.", meaning: "ดั้งเดิม, ตามประเพณี" },
    { word: "train", type: "v.", meaning: "ฝึกฝน" },
    { word: "trainer", type: "n.", meaning: "ผู้ฝึกสอน, รองเท้าผ้าใบ" },
    { word: "training", type: "n.", meaning: "การฝึกอบรม" },
    { word: "transport", type: "n.", meaning: "การขนส่ง" },
    { word: "traveller", type: "n.", meaning: "นักเดินทาง" },
    { word: "trouble", type: "n.", meaning: "ปัญหา" },
    { word: "truck", type: "n.", meaning: "รถบรรทุก (US)" },
    { word: "twin", type: "n., adj.", meaning: "ฝาแฝด" },
    { word: "typical", type: "adj.", meaning: "โดยทั่วไป, เป็นแบบฉบับ" },
    { word: "underground", type: "adj., adv.", meaning: "ใต้ดิน" },
    { word: "understanding", type: "n.", meaning: "ความเข้าใจ" },
    { word: "unfortunately", type: "adv.", meaning: "น่าเสียดายที่" },
    { word: "unhappy", type: "adj.", meaning: "ไม่มีความสุข" },
    { word: "uniform", type: "n.", meaning: "เครื่องแบบ" },
    { word: "unit", type: "n.", meaning: "หน่วย" },
    { word: "united", type: "adj.", meaning: "รวมกัน, สามัคคี" },
    { word: "unusual", type: "adj.", meaning: "ผิดปกติ" },
    { word: "upstairs", type: "adj.", meaning: "ที่อยู่ชั้นบน" },
    { word: "use", type: "n.", meaning: "การใช้, ประโยชน์" },
    { word: "used to", type: "modal v.", meaning: "เคยทำ (ในอดีต)" },
    { word: "user", type: "n.", meaning: "ผู้ใช้" },
    { word: "usual", type: "adj.", meaning: "ปกติ" },
    { word: "valley", type: "n.", meaning: "หุบเขา" },
    { word: "van", type: "n.", meaning: "รถตู้" },
    { word: "variety", type: "n.", meaning: "ความหลากหลาย" },
    { word: "vehicle", type: "n.", meaning: "ยานพาหนะ" },
    { word: "view", type: "n.", meaning: "ทิวทัศน์, มุมมอง" },
    { word: "virus", type: "n.", meaning: "ไวรัส" },
    { word: "voice", type: "n.", meaning: "เสียง (คน)" },
    { word: "wait", type: "n.", meaning: "การรอ" },
    { word: "war", type: "n.", meaning: "สงคราม" },
    { word: "wash", type: "n.", meaning: "การล้าง" },
    { word: "washing", type: "n.", meaning: "การซักผ้า, การล้าง" },
    { word: "wave", type: "n.", meaning: "คลื่น, การโบกมือ" },
    { word: "weak", type: "adj.", meaning: "อ่อนแอ" },
    { word: "web", type: "n.", meaning: "ใยแมงมุม, เว็บ" },
    { word: "wedding", type: "n.", meaning: "งานแต่งงาน" },
    { word: "weight", type: "n.", meaning: "น้ำหนัก" },
    { word: "welcome", type: "n.", meaning: "การต้อนรับ" },
    { word: "wet", type: "adj.", meaning: "เปียก" },
    { word: "wheel", type: "n.", meaning: "ล้อ" },
    { word: "while", type: "conj.", meaning: "ในขณะที่" },
    { word: "whole", type: "adj.", meaning: "ทั้งหมด" },
    { word: "whose", type: "det./pron.", meaning: "ของใคร" },
    { word: "wide", type: "adj.", meaning: "กว้าง" },
    { word: "wild", type: "adj.", meaning: "ป่า, ดุร้าย" },
    { word: "wind", type: "n.", meaning: "ลม" },
    { word: "winner", type: "n.", meaning: "ผู้ชนะ" },
    { word: "wish", type: "v., n.", meaning: "หวัง, ความปรารถนา" },
    { word: "wood", type: "n.", meaning: "ไม้, ป่า" },
    { word: "wooden", type: "adj.", meaning: "ทำจากไม้" },
    { word: "working", type: "adj.", meaning: "ที่ทำงานอยู่" },
    { word: "worried", type: "adj.", meaning: "กังวล" },
    { word: "worry", type: "v.", meaning: "กังวล" },
    { word: "worse", type: "adj.", meaning: "แย่กว่า" },
    { word: "worst", type: "adj.", meaning: "แย่ที่สุด" },
    { word: "yet", type: "adv.", meaning: "ยัง, แต่" },
    { word: "yours", type: "pron.", meaning: "ของคุณ" },
    { word: "zero", type: "number", meaning: "ศูนย์" },
];
