import { Word } from './types';

export const b1Words: Word[] = [
    { word: "absolutely", type: "adv.", meaning: "อย่างแน่นอน, อย่างแท้จริง" },
    { word: "academic", type: "adj.", meaning: "เชิงวิชาการ" },
    { word: "access", type: "n., v.", meaning: "การเข้าถึง, เข้าถึง" },
    { word: "accommodation", type: "n.", meaning: "ที่พัก" },
    { word: "account", type: "n.", meaning: "บัญชี, รายงาน" },
    { word: "achievement", type: "n.", meaning: "ความสำเร็จ" },
    { word: "act", type: "n.", meaning: "การกระทำ, พฤติกรรม" },
    { word: "ad", type: "n.", meaning: "โฆษณา (คำย่อของ advertisement)" },
    { word: "addition", type: "n.", meaning: "การเพิ่ม, ส่วนที่เพิ่ม" },
    { word: "admire", type: "v.", meaning: "ชื่นชม" },
    { word: "admit", type: "v.", meaning: "ยอมรับ, อนุญาตให้เข้า" },
    { word: "advanced", type: "adj.", meaning: "ขั้นสูง" },
    { word: "advise", type: "v.", meaning: "แนะนำ, ให้คำปรึกษา" },
    { word: "afford", type: "v.", meaning: "สามารถซื้อ/จ่ายได้" },
    { word: "age", type: "v.", meaning: "แก่ขึ้น, มีอายุ" },
    { word: "aged", type: "adj.", meaning: "ที่มีอายุ" },
    { word: "agent", type: "n.", meaning: "ตัวแทน" },
    { word: "agreement", type: "n.", meaning: "ข้อตกลง, ความตกลง" },
    { word: "ahead", type: "adv.", meaning: "ข้างหน้า, ก่อน" },
    { word: "aim", type: "v., n.", meaning: "ตั้งเป้าหมาย, เป้าหมาย" },
    { word: "alarm", type: "n.", meaning: "นาฬิกาปลุก, สัญญาณเตือน" },
    { word: "album", type: "n.", meaning: "อัลบั้ม" },
    { word: "alcohol", type: "n.", meaning: "แอลกอฮอล์" },
    { word: "alcoholic", type: "adj.", meaning: "ที่มีแอลกอฮอล์, ติดเหล้า" },
    { word: "alternative", type: "adj.", meaning: "ทางเลือก" },
    { word: "amazed", type: "adj.", meaning: "ประหลาดใจมาก" },
    { word: "ambition", type: "n.", meaning: "ความทะเยอทะยาน" },
    { word: "ambitious", type: "adj.", meaning: "ทะเยอทะยาน" },
    { word: "analyse", type: "v.", meaning: "วิเคราะห์" },
    { word: "analysis", type: "n.", meaning: "การวิเคราะห์" },
    { word: "announce", type: "v.", meaning: "ประกาศ" },
    { word: "announcement", type: "n.", meaning: "ประกาศ, การประกาศ" },
    { word: "annoy", type: "v.", meaning: "รบกวน, ทำให้รำคาญ" },
    { word: "annoyed", type: "adj.", meaning: "รู้สึกรำคาญ" },
    { word: "annoying", type: "adj.", meaning: "น่ารำคาญ" },
    { word: "apart", type: "adv.", meaning: "แยกจากกัน" },
    { word: "apologize", type: "v.", meaning: "ขอโทษ" },
    { word: "application", type: "n.", meaning: "การสมัคร, แอปพลิเคชัน" },
    { word: "appointment", type: "n.", meaning: "การนัดหมาย" },
    { word: "appreciate", type: "v.", meaning: "ซาบซึ้ง, ชื่นชม" },
    { word: "approximately", type: "adv.", meaning: "ประมาณ" },
    { word: "arrest", type: "v., n.", meaning: "จับกุม, การจับกุม" },
    { word: "arrival", type: "n.", meaning: "การมาถึง" },
    { word: "assignment", type: "n.", meaning: "งานที่มอบหมาย" },
    { word: "assist", type: "v.", meaning: "ช่วยเหลือ" },
    { word: "atmosphere", type: "n.", meaning: "บรรยากาศ" },
    { word: "attach", type: "v.", meaning: "แนบ, ติด" },
    { word: "attitude", type: "n.", meaning: "ทัศนคติ" },
    { word: "attract", type: "v.", meaning: "ดึงดูด" },
    { word: "attraction", type: "n.", meaning: "สิ่งดึงดูด, สถานที่ท่องเที่ยว" },
    { word: "authority", type: "n.", meaning: "อำนาจ, เจ้าหน้าที่" },
    { word: "average", type: "v.", meaning: "คิดค่าเฉลี่ย" },
    { word: "award", type: "v.", meaning: "มอบรางวัล" },
    { word: "aware", type: "adj.", meaning: "ตระหนัก, รับรู้" },
    { word: "backwards", type: "adv.", meaning: "ถอยหลัง" },
    { word: "bake", type: "v.", meaning: "อบ" },
    { word: "balance", type: "n., v.", meaning: "สมดุล, ทำให้สมดุล" },
    { word: "ban", type: "v., n.", meaning: "สั่งห้าม, การสั่งห้าม" },
    { word: "bank", type: "n.", meaning: "ริมฝั่งแม่น้ำ" },
    { word: "base", type: "n., v.", meaning: "ฐาน, พื้นฐาน, ตั้งฐาน" },
    { word: "basic", type: "adj.", meaning: "พื้นฐาน" },
    { word: "basis", type: "n.", meaning: "พื้นฐาน, หลักเกณฑ์" },
    { word: "battery", type: "n.", meaning: "แบตเตอรี่" },
    { word: "battle", type: "n.", meaning: "การต่อสู้, ศึก" },
    { word: "beauty", type: "n.", meaning: "ความงาม" },
    { word: "bee", type: "n.", meaning: "ผึ้ง" },
    { word: "belief", type: "n.", meaning: "ความเชื่อ" },
    { word: "bell", type: "n.", meaning: "ระฆัง, กระดิ่ง" },
    { word: "bend", type: "v., n.", meaning: "งอ, โค้ง, ส่วนโค้ง" },
    { word: "benefit", type: "v.", meaning: "เป็นประโยชน์ต่อ" },
    { word: "better", type: "n.", meaning: "สิ่งที่ดีกว่า" },
    { word: "bite", type: "v., n.", meaning: "กัด, รอยกัด" },
    { word: "block", type: "n., v.", meaning: "บล็อก, ตึก, กีดขวาง" },
    { word: "board", type: "v.", meaning: "ขึ้น (เครื่องบิน/เรือ)" },
    { word: "bomb", type: "n., v.", meaning: "ระเบิด, ทิ้งระเบิด" },
    { word: "border", type: "n.", meaning: "ชายแดน, ขอบ" },
    { word: "bother", type: "v.", meaning: "รบกวน, ทำให้กังวล" },
    { word: "branch", type: "n.", meaning: "กิ่งไม้, สาขา" },
    { word: "brand", type: "n., v.", meaning: "ตราสินค้า, ตีตรา" },
    { word: "brave", type: "adj.", meaning: "กล้าหาญ" },
    { word: "breath", type: "n.", meaning: "ลมหายใจ" },
    { word: "breathe", type: "v.", meaning: "หายใจ" },
    { word: "breathing", type: "n.", meaning: "การหายใจ" },
    { word: "bride", type: "n.", meaning: "เจ้าสาว" },
    { word: "bubble", type: "n.", meaning: "ฟอง" },
    { word: "bury", type: "v.", meaning: "ฝัง" },
    { word: "by", type: "adv.", meaning: "อยู่ใกล้ๆ, ผ่านไป" },
    { word: "calm", type: "adj., v., n.", meaning: "สงบ, ทำให้สงบ, ความสงบ" },
    { word: "campaign", type: "n., v.", meaning: "การรณรงค์, รณรงค์" },
    { word: "campus", type: "n.", meaning: "วิทยาเขต" },
    { word: "candidate", type: "n.", meaning: "ผู้สมัคร" },
    { word: "cap", type: "n.", meaning: "หมวกแก๊ป, ฝา" },
    { word: "captain", type: "n.", meaning: "กัปตัน" },
    { word: "careless", type: "adj.", meaning: "ประมาท, ไม่ระมัดระวัง" },
    { word: "category", type: "n.", meaning: "หมวดหมู่" },
    { word: "ceiling", type: "n.", meaning: "เพดาน" },
    { word: "celebration", type: "n.", meaning: "การเฉลิมฉลอง" },
    { word: "central", type: "adj.", meaning: "ส่วนกลาง, ใจกลาง" },
    { word: "centre", type: "v.", meaning: "อยู่ตรงกลาง" },
    { word: "ceremony", type: "n.", meaning: "พิธี" },
    { word: "chain", type: "n.", meaning: "โซ่, ห่วงโซ่" },
    { word: "challenge", type: "n.", meaning: "ความท้าทาย" },
    { word: "champion", type: "n.", meaning: "แชมป์เปี้ยน" },
    { word: "channel", type: "n.", meaning: "ช่อง (ทีวี), ช่องทาง" },
    { word: "chapter", type: "n.", meaning: "บท (ของหนังสือ)" },
    { word: "charge", type: "n., v.", meaning: "ค่าใช้จ่าย, ข้อกล่าวหา, ชาร์จ" },
    { word: "cheap", type: "adv.", meaning: "ราคาถูก" },
    { word: "cheat", type: "v., n.", meaning: "โกง, คนโกง" },
    { word: "cheerful", type: "adj.", meaning: "ร่าเริง" },
    { word: "chemical", type: "adj., n.", meaning: "เคมี, สารเคมี" },
    { word: "chest", type: "n.", meaning: "หน้าอก, หีบ" },
    { word: "childhood", type: "n.", meaning: "วัยเด็ก" },
    { word: "claim", type: "v., n.", meaning: "อ้าง, ข้อเรียกร้อง" },
    { word: "clause", type: "n.", meaning: "อนุประโยค, ข้อกำหนด" },
    { word: "clear", type: "v.", meaning: "ทำให้ชัดเจน, เคลียร์" },
    { word: "click", type: "v., n.", meaning: "คลิก, เสียงคลิก" },
    { word: "client", type: "n.", meaning: "ลูกค้า" },
    { word: "climb", type: "n.", meaning: "การปีน" },
    { word: "close", type: "adv.", meaning: "ใกล้" },
    { word: "cloth", type: "n.", meaning: "ผ้า" },
    { word: "clue", type: "n.", meaning: "เงื่อนงำ, เบาะแส" },
    { word: "coach", type: "v.", meaning: "ฝึกสอน" },
    { word: "coal", type: "n.", meaning: "ถ่านหิน" },
    { word: "coin", type: "n.", meaning: "เหรียญ" },
    { word: "collection", type: "n.", meaning: "คอลเลกชัน, การสะสม" },
    { word: "coloured", type: "adj.", meaning: "มีสี" },
    { word: "combine", type: "v.", meaning: "รวมกัน" },
    { word: "comment", type: "v.", meaning: "แสดงความคิดเห็น" },
    { word: "commercial", type: "adj., n.", meaning: "เชิงพาณิชย์, โฆษณา" },
    { word: "commit", type: "v.", meaning: "กระทำ (ผิด), ให้คำมั่น" },
    { word: "communication", type: "n.", meaning: "การสื่อสาร" },
    { word: "comparison", type: "n.", meaning: "การเปรียบเทียบ" },
    { word: "competitor", type: "n.", meaning: "คู่แข่ง" },
    { word: "competitive", type: "adj.", meaning: "แข่งขัน, ที่เกี่ยวกับการแข่งขัน" },
    { word: "complaint", type: "n.", meaning: "คำบ่น, การร้องเรียน" },
    { word: "complex", type: "adj.", meaning: "ซับซ้อน" },
    { word: "concentrate", type: "v.", meaning: "มีสมาธิ" },
    { word: "conclude", type: "v.", meaning: "สรุป" },
    { word: "conclusion", type: "n.", meaning: "ข้อสรุป" },
    { word: "confident", type: "adj.", meaning: "มั่นใจ" },
    { word: "confirm", type: "v.", meaning: "ยืนยัน" },
    { word: "confuse", type: "v.", meaning: "ทำให้สับสน" },
    { word: "confused", type: "adj.", meaning: "สับสน" },
    { word: "connection", type: "n.", meaning: "การเชื่อมต่อ, ความสัมพันธ์" },
    { word: "consequence", type: "n.", meaning: "ผลที่ตามมา" },
    { word: "consist", type: "v.", meaning: "ประกอบด้วย" },
    { word: "consume", type: "v.", meaning: "บริโภค" },
    { word: "consumer", type: "n.", meaning: "ผู้บริโภค" },
    { word: "contact", type: "n., v.", meaning: "การติดต่อ, ติดต่อ" },
    { word: "container", type: "n.", meaning: "ภาชนะ" },
    { word: "content", type: "n.", meaning: "เนื้อหา" },
    { word: "continuous", type: "adj.", meaning: "ต่อเนื่อง" },
    { word: "contrast", type: "n., v.", meaning: "ความแตกต่าง, เปรียบเทียบ" },
    { word: "convenient", type: "adj.", meaning: "สะดวก" },
    { word: "convince", type: "v.", meaning: "โน้มน้าว" },
    { word: "cool", type: "v.", meaning: "ทำให้เย็นลง" },
    { word: "costume", type: "n.", meaning: "เครื่องแต่งกาย, ชุดแฟนซี" },
    { word: "cottage", type: "n.", meaning: "กระท่อม" },
    { word: "cotton", type: "n.", meaning: "ฝ้าย" },
    { word: "count", type: "n.", meaning: "การนับ" },
    { word: "countryside", type: "n.", meaning: "ชนบท" },
    { word: "court", type: "n.", meaning: "ศาล, สนาม (กีฬา)" },
    { word: "cover", type: "n.", meaning: "ปก, ฝาครอบ" },
    { word: "covered", type: "adj.", meaning: "ที่ถูกปกคลุม" },
    { word: "cream", type: "adj.", meaning: "สีครีม" },
    { word: "criminal", type: "adj.", meaning: "ทางอาญา" },
    { word: "cruel", type: "adj.", meaning: "โหดร้าย" },
    { word: "cultural", type: "adj.", meaning: "ทางวัฒนธรรม" },
    { word: "currency", type: "n.", meaning: "สกุลเงิน" },
    { word: "current", type: "adj.", meaning: "ปัจจุบัน" },
    { word: "currently", type: "adv.", meaning: "ในปัจจุบัน" },
    { word: "curtain", type: "n.", meaning: "ผ้าม่าน" },
    { word: "custom", type: "n.", meaning: "ขนบธรรมเนียม" },
    { word: "cut", type: "n.", meaning: "การตัด, แผลตัด" },
    { word: "daily", type: "adv.", meaning: "ทุกวัน" },
    { word: "damage", type: "n., v.", meaning: "ความเสียหาย, ทำให้เสียหาย" },
    { word: "deal", type: "n.", meaning: "ข้อตกลง, การจัดการ" },
    { word: "decade", type: "n.", meaning: "ทศวรรษ" },
    { word: "decorate", type: "v.", meaning: "ตกแต่ง" },
    { word: "deep", type: "adv.", meaning: "ลึก" },
    { word: "define", type: "v.", meaning: "นิยาม, กำหนด" },
    { word: "definite", type: "adj.", meaning: "แน่นอน, ชัดเจน" },
    { word: "definition", type: "n.", meaning: "คำนิยาม" },
    { word: "deliver", type: "v.", meaning: "ส่งมอบ" },
    { word: "departure", type: "n.", meaning: "การออกเดินทาง" },
    { word: "despite", type: "prep.", meaning: "แม้ว่า" },
    { word: "destination", type: "n.", meaning: "จุดหมายปลายทาง" },
    { word: "determine", type: "v.", meaning: "ตัดสินใจ, กำหนด" },
    { word: "determined", type: "adj.", meaning: "มุ่งมั่น, ตั้งใจแน่วแน่" },
    { word: "development", type: "n.", meaning: "การพัฒนา" },
    { word: "diagram", type: "n.", meaning: "แผนภาพ" },
    { word: "diamond", type: "n.", meaning: "เพชร" },
    { word: "difficulty", type: "n.", meaning: "ความยากลำบาก" },
    { word: "direct", type: "v., adv.", meaning: "กำกับ, โดยตรง" },
    { word: "directly", type: "adv.", meaning: "โดยตรง" },
    { word: "dirt", type: "n.", meaning: "สิ่งสกปรก, ดิน" },
    { word: "disadvantage", type: "n.", meaning: "ข้อเสียเปรียบ" },
    { word: "disappointed", type: "adj.", meaning: "ผิดหวัง" },
    { word: "disappointing", type: "adj.", meaning: "น่าผิดหวัง" },
    { word: "discount", type: "n.", meaning: "ส่วนลด" },
    { word: "dislike", type: "v., n.", meaning: "ไม่ชอบ, ความไม่ชอบ" },
    { word: "divide", type: "v.", meaning: "แบ่ง" },
    { word: "documentary", type: "n.", meaning: "สารคดี" },
    { word: "donate", type: "v.", meaning: "บริจาค" },
    { word: "double", type: "adv.", meaning: "เป็นสองเท่า" },
    { word: "doubt", type: "n., v.", meaning: "ความสงสัย, สงสัย" },
    { word: "dressed", type: "adj.", meaning: "ที่สวมใส่เสื้อผ้า" },
    { word: "drop", type: "n.", meaning: "หยด, การตก" },
    { word: "drum", type: "n.", meaning: "กลอง" },
    { word: "drunk", type: "adj.", meaning: "เมา" },
    { word: "due", type: "adj.", meaning: "ครบกำหนด, เนื่องจาก" },
    { word: "dust", type: "n.", meaning: "ฝุ่น" },
    { word: "duty", type: "n.", meaning: "หน้าที่" },
    { word: "earthquake", type: "n.", meaning: "แผ่นดินไหว" },
    { word: "eastern", type: "adj.", meaning: "ทางทิศตะวันออก" },
    { word: "economic", type: "adj.", meaning: "ทางเศรษฐกิจ" },
    { word: "economy", type: "n.", meaning: "เศรษฐกิจ" },
    { word: "edge", type: "n.", meaning: "ขอบ" },
    { word: "editor", type: "n.", meaning: "บรรณาธิการ" },
    { word: "educate", type: "v.", meaning: "ให้การศึกษา" },
    { word: "educated", type: "adj.", meaning: "มีการศึกษา" },
    { word: "educational", type: "adj.", meaning: "ทางการศึกษา" },
    { word: "effective", type: "adj.", meaning: "มีประสิทธิภาพ" },
    { word: "effectively", type: "adv.", meaning: "อย่างมีประสิทธิภาพ" },
    { word: "effort", type: "n.", meaning: "ความพยายาม" },
    { word: "election", type: "n.", meaning: "การเลือกตั้ง" },
    { word: "element", type: "n.", meaning: "องค์ประกอบ" },
    { word: "embarrassed", type: "adj.", meaning: "อับอาย" },
    { word: "embarrassing", type: "adj.", meaning: "น่าอับอาย" },
    { word: "emergency", type: "n.", meaning: "ภาวะฉุกเฉิน" },
    { word: "emotion", type: "n.", meaning: "อารมณ์" },
    { word: "employment", type: "n.", meaning: "การจ้างงาน" },
    { word: "empty", type: "v.", meaning: "ทำให้ว่างเปล่า" },
    { word: "encourage", type: "v.", meaning: "ให้กำลังใจ, ส่งเสริม" },
    { word: "enemy", type: "n.", meaning: "ศัตรู" },
    { word: "engaged", type: "adj.", meaning: "หมั้นแล้ว, ไม่ว่าง (โทรศัพท์)" },
    { word: "engineering", type: "n.", meaning: "วิศวกรรม" },
    { word: "entertain", type: "v.", meaning: "ให้ความบันเทิง" },
    { word: "entertainment", type: "n.", meaning: "ความบันเทิง" },
    { word: "entrance", type: "n.", meaning: "ทางเข้า" },
    { word: "entry", type: "n.", meaning: "การเข้า, รายการ" },
    { word: "environmental", type: "adj.", meaning: "เกี่ยวกับสิ่งแวดล้อม" },
    { word: "episode", type: "n.", meaning: "ตอน (ของซีรีส์)" },
    { word: "equal", type: "adj., v.", meaning: "เท่ากัน, เท่ากับ" },
    { word: "equally", type: "adv.", meaning: "อย่างเท่าเทียมกัน" },
    { word: "escape", type: "v., n.", meaning: "หลบหนี, การหลบหนี" },
    { word: "essential", type: "adj.", meaning: "จำเป็น, สำคัญ" },
    { word: "eventually", type: "adv.", meaning: "ในที่สุด" },
    { word: "examine", type: "v.", meaning: "ตรวจสอบ, ตรวจสอบ (ร่างกาย)" },
    { word: "except", type: "conj.", meaning: "ยกเว้นแต่ว่า" },
    { word: "exchange", type: "n., v.", meaning: "การแลกเปลี่ยน, แลกเปลี่ยน" },
    { word: "excitement", type: "n.", meaning: "ความตื่นเต้น" },
    { word: "exhibition", type: "n.", meaning: "นิทรรศการ" },
    { word: "expand", type: "v.", meaning: "ขยาย" },
    { word: "expected", type: "adj.", meaning: "ที่คาดไว้" },
    { word: "expedition", type: "n.", meaning: "การเดินทางสำรวจ" },
    { word: "experience", type: "v.", meaning: "ประสบ, ได้รับประสบการณ์" },
    { word: "experienced", type: "adj.", meaning: "มีประสบการณ์" },
    { word: "experiment", type: "v.", meaning: "ทำการทดลอง" },
    { word: "explode", type: "v.", meaning: "ระเบิด" },
    { word: "explore", type: "v.", meaning: "สำรวจ" },
    { word: "explosion", type: "n.", meaning: "การระเบิด" },
    { word: "export", type: "n., v.", meaning: "สินค้าส่งออก, ส่งออก" },
    { word: "extra", type: "n., adv.", meaning: "สิ่งพิเศษ, เพิ่มเติม" },
    { word: "face", type: "v.", meaning: "เผชิญหน้า" },
    { word: "fairly", type: "adv.", meaning: "ค่อนข้าง, อย่างยุติธรรม" },
    { word: "familiar", type: "adj.", meaning: "คุ้นเคย" },
    { word: "fancy", type: "v., adj.", meaning: "อยากได้, ชอบ, หรูหรา" },
    { word: "far", type: "adj.", meaning: "ไกล" },
    { word: "fascinating", type: "adj.", meaning: "น่าหลงใหล" },
    { word: "fashionable", type: "adj.", meaning: "ทันสมัย" },
    { word: "fasten", type: "v.", meaning: "ผูก, ยึด" },
    { word: "favour", type: "n.", meaning: "ความโปรดปราน, การช่วยเหลือ" },
    { word: "fear", type: "v.", meaning: "กลัว" },
    { word: "feature", type: "v.", meaning: "มีลักษณะเด่น, นำเสนอ" },
    { word: "fence", type: "n.", meaning: "รั้ว" },
    { word: "fighting", type: "n.", meaning: "การต่อสู้" },
    { word: "file", type: "n.", meaning: "ไฟล์, แฟ้ม" },
    { word: "financial", type: "adj.", meaning: "ทางการเงิน" },
    { word: "fire", type: "v.", meaning: "ไล่ออก, ยิง" },
    { word: "fitness", type: "n.", meaning: "ความฟิต, สุขภาพแข็งแรง" },
    { word: "fixed", type: "adj.", meaning: "คงที่, ซ่อมแซมแล้ว" },
    { word: "flag", type: "n.", meaning: "ธง" },
    { word: "flood", type: "n., v.", meaning: "น้ำท่วม, ท่วม" },
    { word: "flour", type: "n.", meaning: "แป้ง (ทำอาหาร)" },
    { word: "flow", type: "v., n.", meaning: "ไหล, การไหล" },
    { word: "fold", type: "v.", meaning: "พับ" },
    { word: "folk", type: "n., adj.", meaning: "ผู้คน, พื้นบ้าน" },
    { word: "following", type: "n.", meaning: "ผู้ติดตาม, สิ่งที่ตามมา" },
    { word: "force", type: "n., v.", meaning: "แรง, บังคับ" },
    { word: "forever", type: "adv.", meaning: "ตลอดไป" },
    { word: "frame", type: "n., v.", meaning: "กรอบ, ใส่กรอบ" },
    { word: "freeze", type: "v.", meaning: "แช่แข็ง, แข็งตัว" },
    { word: "frequently", type: "adv.", meaning: "บ่อยๆ" },
    { word: "friendship", type: "n.", meaning: "มิตรภาพ" },
    { word: "frighten", type: "v.", meaning: "ทำให้ตกใจกลัว" },
    { word: "frightened", type: "adj.", meaning: "รู้สึกตกใจกลัว" },
    { word: "frightening", type: "adj.", meaning: "น่าตกใจกลัว" },
    { word: "frozen", type: "adj.", meaning: "แช่แข็ง" },
    { word: "fry", type: "v.", meaning: "ทอด" },
    { word: "fuel", type: "n.", meaning: "เชื้อเพลิง" },
    { word: "function", type: "n.", meaning: "หน้าที่, การทำงาน" },
    { word: "fur", type: "n.", meaning: "ขนสัตว์" },
    { word: "further", type: "adv.", meaning: "ต่อไป, เพิ่มเติม" },
    { word: "garage", type: "n.", meaning: "โรงรถ" },
    { word: "gather", type: "v.", meaning: "รวมตัว, รวบรวม" },
    { word: "generally", type: "adv.", meaning: "โดยทั่วไป" },
    { word: "generation", type: "n.", meaning: "รุ่น, เจเนอเรชัน" },
    { word: "generous", type: "adj.", meaning: "ใจกว้าง" },
    { word: "gentle", type: "adj.", meaning: "อ่อนโยน" },
    { word: "gentleman", type: "n.", meaning: "สุภาพบุรุษ" },
    { word: "ghost", type: "n.", meaning: "ผี" },
    { word: "giant", type: "adj., n.", meaning: "ใหญ่ยักษ์, ยักษ์" },
    { word: "glad", type: "adj.", meaning: "ยินดี, ดีใจ" },
    { word: "global", type: "adj.", meaning: "ทั่วโลก" },
    { word: "glove", type: "n.", meaning: "ถุงมือ" },
    { word: "go", type: "n.", meaning: "การไป (เช่น Have a go)" },
    { word: "goods", type: "n.", meaning: "สินค้า" },
    { word: "grade", type: "n.", meaning: "เกรด, ระดับชั้น" },
    { word: "graduate", type: "n., v.", meaning: "ผู้สำเร็จการศึกษา, สำเร็จการศึกษา" },
    { word: "grain", type: "n.", meaning: "เมล็ดข้าว, เมล็ดธัญพืช" },
    { word: "grateful", type: "adj.", meaning: "รู้สึกขอบคุณ" },
    { word: "growth", type: "n.", meaning: "การเติบโต" },
    { word: "guard", type: "n., v.", meaning: "ยาม, เฝ้าระวัง" },
    { word: "guilty", type: "adj.", meaning: "รู้สึกผิด, มีความผิด" },
    { word: "hand", type: "v.", meaning: "ส่งให้, ยื่นให้" },
    { word: "hang", type: "v.", meaning: "แขวน" },
    { word: "happiness", type: "n.", meaning: "ความสุข" },
    { word: "hardly", type: "adv.", meaning: "แทบจะไม่" },
    { word: "hate", type: "n.", meaning: "ความเกลียดชัง" },
    { word: "head", type: "v.", meaning: "มุ่งหน้าไป, เป็นหัวหน้า" },
    { word: "headline", type: "n.", meaning: "พาดหัวข่าว" },
    { word: "heating", type: "n.", meaning: "ระบบทำความร้อน" },
    { word: "heavily", type: "adv.", meaning: "อย่างหนัก" },
    { word: "helicopter", type: "n.", meaning: "เฮลิคอปเตอร์" },
    { word: "highlight", type: "v., n.", meaning: "เน้น, จุดเด่น" },
    { word: "highly", type: "adv.", meaning: "อย่างสูง" },
    { word: "hire", type: "v.", meaning: "จ้าง, เช่า" },
    { word: "historic", type: "adj.", meaning: "มีคุณค่าทางประวัติศาสตร์" },
    { word: "historical", type: "adj.", meaning: "เกี่ยวกับประวัติศาสตร์" },
    { word: "honest", type: "adj.", meaning: "ซื่อสัตย์" },
    { word: "horrible", type: "adj.", meaning: "น่ากลัว, แย่มาก" },
    { word: "horror", type: "n.", meaning: "ความหวาดกลัว, สยองขวัญ" },
    { word: "host", type: "n.", meaning: "เจ้าภาพ, พิธีกร" },
    { word: "hunt", type: "v.", meaning: "ล่าสัตว์" },
    { word: "hurricane", type: "n.", meaning: "พายุเฮอร์ริเคน" },
    { word: "hurry", type: "n., v.", meaning: "ความเร่งรีบ, รีบ" },
    { word: "identity", type: "n.", meaning: "เอกลักษณ์, ตัวตน" },
    { word: "ignore", type: "v.", meaning: "ละเลย, ไม่สนใจ" },
    { word: "illegal", type: "adj.", meaning: "ผิดกฎหมาย" },
    { word: "imaginary", type: "adj.", meaning: "ในจินตนาการ" },
    { word: "immediate", type: "adj.", meaning: "ทันทีทันใด" },
    { word: "immigrant", type: "n.", meaning: "ผู้ย้ายถิ่นฐาน" },
    { word: "impact", type: "n., v.", meaning: "ผลกระทบ, ส่งผลกระทบ" },
    { word: "import", type: "n., v.", meaning: "สินค้านำเข้า, นำเข้า" },
    { word: "importance", type: "n.", meaning: "ความสำคัญ" },
    { word: "impression", type: "n.", meaning: "ความประทับใจ" },
    { word: "impressive", type: "adj.", meaning: "น่าประทับใจ" },
    { word: "improvement", type: "n.", meaning: "การปรับปรุง" },
    { word: "incredibly", type: "adv.", meaning: "อย่างไม่น่าเชื่อ" },
    { word: "indeed", type: "adv.", meaning: "จริงๆ แล้ว" },
    { word: "indicate", type: "v.", meaning: "บ่งชี้, แสดงให้เห็น" },
    { word: "indirect", type: "adj.", meaning: "โดยอ้อม" },
    { word: "indoor", type: "adj.", meaning: "ในร่ม" },
    { word: "indoors", type: "adv.", meaning: "ในอาคาร, ในร่ม" },
    { word: "influence", type: "n., v.", meaning: "อิทธิพล, มีอิทธิพลต่อ" },
    { word: "ingredient", type: "n.", meaning: "ส่วนผสม" },
    { word: "injure", type: "v.", meaning: "ทำให้บาดเจ็บ" },
    { word: "injured", type: "adj.", meaning: "ที่ได้รับบาดเจ็บ" },
    { word: "innocent", type: "adj.", meaning: "ไร้เดียงสา, บริสุทธิ์" },
    { word: "intelligence", type: "n.", meaning: "สติปัญญา" },
    { word: "intend", type: "v.", meaning: "ตั้งใจ" },
    { word: "intention", type: "n.", meaning: "ความตั้งใจ" },
    { word: "invest", type: "v.", meaning: "ลงทุน" },
    { word: "investigate", type: "v.", meaning: "สืบสวน" },
    { word: "involved", type: "adj.", meaning: "ที่เกี่ยวข้อง" },
    { word: "iron", type: "n., v.", meaning: "เหล็ก, เตารีด, รีดผ้า" },
    { word: "issue", type: "n.", meaning: "ประเด็น, ปัญหา" },
    { word: "IT", type: "n.", meaning: "เทคโนโลยีสารสนเทศ (Information Technology)" },
    { word: "journal", type: "n.", meaning: "วารสาร, บันทึกประจำวัน" },
    { word: "judge", type: "n., v.", meaning: "ผู้พิพากษา, ตัดสิน" },
    { word: "keen", type: "adj.", meaning: "กระตือรือร้น, คม" },
    { word: "key", type: "v.", meaning: "ป้อนข้อมูล (ด้วยแป้นพิมพ์)" },
    { word: "keyboard", type: "n.", meaning: "แป้นพิมพ์, คีย์บอร์ด" },
    { word: "kick", type: "v., n.", meaning: "เตะ, การเตะ" },
    { word: "killing", type: "n.", meaning: "การฆ่า" },
    { word: "kind", type: "adj.", meaning: "ใจดี" },
    { word: "kiss", type: "v., n.", meaning: "จูบ, การจูบ" },
    { word: "knock", type: "n.", meaning: "การเคาะ, เสียงเคาะ" },
    { word: "label", type: "n., v.", meaning: "ฉลาก, ติดฉลาก" },
    { word: "laboratory", type: "n.", meaning: "ห้องปฏิบัติการ" },
    { word: "lack", type: "n., v.", meaning: "การขาดแคลน, ขาด" },
    { word: "latest", type: "adj.", meaning: "ล่าสุด" },
    { word: "lay", type: "v.", meaning: "วาง, ออกไข่" },
    { word: "layer", type: "n.", meaning: "ชั้น" },
    { word: "lead", type: "n.", meaning: "ผู้นำ, ตะกั่ว" },
    { word: "leading", type: "adj.", meaning: "ชั้นนำ, เป็นผู้นำ" },
    { word: "leaf", type: "n.", meaning: "ใบไม้" },
    { word: "leather", type: "n.", meaning: "หนัง" },
    { word: "legal", type: "adj.", meaning: "ถูกกฎหมาย" },
    { word: "leisure", type: "n.", meaning: "เวลาว่าง" },
    { word: "length", type: "n.", meaning: "ความยาว" },
    { word: "level", type: "adj.", meaning: "ระดับเดียวกัน, แบนราบ" },
    { word: "lie", type: "v., n.", meaning: "โกหก, คำโกหก" },
    { word: "like", type: "n.", meaning: "สิ่งที่ชอบ, คนที่ชอบ" },
    { word: "limit", type: "n., v.", meaning: "ขีดจำกัด, จำกัด" },
    { word: "lip", type: "n.", meaning: "ริมฝีปาก" },
    { word: "liquid", type: "n., adj.", meaning: "ของเหลว" },
    { word: "literature", type: "n.", meaning: "วรรณคดี" },
    { word: "live", type: "adj., adv.", meaning: "สด, มีชีวิต" },
    { word: "living", type: "adj., n.", meaning: "มีชีวิตอยู่, การดำรงชีวิต" },
    { word: "local", type: "n.", meaning: "คนท้องถิ่น" },
    { word: "locate", type: "v.", meaning: "ตั้งอยู่, ค้นหาตำแหน่ง" },
    { word: "located", type: "adj.", meaning: "ที่ตั้งอยู่" },
    { word: "location", type: "n.", meaning: "ที่ตั้ง, ทำเล" },
    { word: "lonely", type: "adj.", meaning: "เหงา" },
    { word: "loss", type: "n.", meaning: "การสูญเสีย" },
    { word: "luxury", type: "n.", meaning: "ความหรูหรา" },
    { word: "mad", type: "adj.", meaning: "บ้า, โกรธจัด" },
    { word: "magic", type: "n., adj.", meaning: "เวทมนตร์, มายากล" },
    { word: "mainly", type: "adv.", meaning: "ส่วนใหญ่" },
    { word: "mall", type: "n.", meaning: "ศูนย์การค้า" },
    { word: "management", type: "n.", meaning: "การจัดการ" },
    { word: "market", type: "v.", meaning: "ทำการตลาด" },
    { word: "marketing", type: "n.", meaning: "การตลาด" },
    { word: "marriage", type: "n.", meaning: "การแต่งงาน" },
    { word: "meanwhile", type: "adv.", meaning: "ในขณะเดียวกัน" },
    { word: "measure", type: "v., n.", meaning: "วัด, มาตรการ" },
    { word: "medium", type: "adj.", meaning: "ปานกลาง" },
    { word: "mental", type: "adj.", meaning: "ทางจิตใจ" },
    { word: "mention", type: "n.", meaning: "การกล่าวถึง" },
    { word: "mess", type: "n.", meaning: "ความยุ่งเหยิง" },
    { word: "mild", type: "adj.", meaning: "อ่อนโยน, ไม่รุนแรง" },
    { word: "mine", type: "n.", meaning: "เหมือง" },
    { word: "mix", type: "v., n.", meaning: "ผสม, ส่วนผสม" },
    { word: "mixture", type: "n.", meaning: "ส่วนผสม" },
    { word: "mood", type: "n.", meaning: "อารมณ์" },
    { word: "move", type: "n.", meaning: "การเคลื่อนไหว, การย้าย" },
    { word: "mud", type: "n.", meaning: "โคลน" },
    { word: "murder", type: "n., v.", meaning: "การฆาตกรรม, ฆาตกรรม" },
    { word: "muscle", type: "n.", meaning: "กล้ามเนื้อ" },
    { word: "musical", type: "n.", meaning: "ละครเพลง, ดนตรี" },
    { word: "mystery", type: "n.", meaning: "ความลึกลับ" },
    { word: "nail", type: "n.", meaning: "เล็บ, ตะปู" },
    { word: "narrative", type: "n., adj.", meaning: "เรื่องเล่า, เกี่ยวกับการเล่าเรื่อง" },
    { word: "nation", type: "n.", meaning: "ประเทศชาติ" },
    { word: "native", type: "adj., n.", meaning: "พื้นเมือง, คนพื้นเมือง" },
    { word: "naturally", type: "adv.", meaning: "โดยธรรมชาติ" },
    { word: "necessarily", type: "adv.", meaning: "อย่างจำเป็น" },
    { word: "need", type: "modal v.", meaning: "จำเป็นต้อง" },
    { word: "needle", type: "n.", meaning: "เข็ม" },
    { word: "neighbourhood", type: "n.", meaning: "ละแวกบ้าน, ย่าน" },
    { word: "neither", type: "adv.", meaning: "ไม่เช่นกัน" },
    { word: "net", type: "n.", meaning: "ตาข่าย" },
    { word: "next", type: "n.", meaning: "สิ่งถัดไป, คนถัดไป" },
    { word: "nor", type: "conj./adv.", meaning: "และไม่...เช่นกัน" },
    { word: "normal", type: "n.", meaning: "ภาวะปกติ" },
    { word: "northern", type: "adj.", meaning: "ทางเหนือ" },
    { word: "note", type: "v.", meaning: "จดบันทึก, สังเกต" },
    { word: "now", type: "conj.", meaning: "เนื่องจาก, ขณะนี้" },
    { word: "nuclear", type: "adj.", meaning: "นิวเคลียร์" },
    { word: "obvious", type: "adj.", meaning: "ชัดเจน" },
    { word: "obviously", type: "adv.", meaning: "อย่างเห็นได้ชัด" },
    { word: "occasion", type: "n.", meaning: "โอกาส, โอกาสพิเศษ" },
    { word: "occur", type: "v.", meaning: "เกิดขึ้น" },
    { word: "odd", type: "adj.", meaning: "แปลก, เป็นเลขคี่" },
    { word: "official", type: "adj.", meaning: "เป็นทางการ" },
    { word: "old-fashioned", type: "adj.", meaning: "ล้าสมัย" },
    { word: "once", type: "conj.", meaning: "เมื่อ (Once you finish...)" },
    { word: "operation", type: "n.", meaning: "การผ่าตัด, การปฏิบัติงาน" },
    { word: "organized", type: "adj.", meaning: "ที่มีการจัดระเบียบ" },
    { word: "organizer", type: "n.", meaning: "ผู้จัดงาน" },
    { word: "original", type: "n.", meaning: "ต้นฉบับ" },
    { word: "originally", type: "adv.", meaning: "แต่เดิม" },
    { word: "ought", type: "modal v.", meaning: "ควรจะ" },
    { word: "ours", type: "pron.", meaning: "ของพวกเรา" },
    { word: "outdoor", type: "adj.", meaning: "กลางแจ้ง" },
    { word: "outdoors", type: "adv.", meaning: "นอกอาคาร, กลางแจ้ง" },
    { word: "pack", type: "n.", meaning: "ห่อ, ชุด" },
    { word: "package", type: "n.", meaning: "พัสดุ, หีบห่อ" },
    { word: "painful", type: "adj.", meaning: "เจ็บปวด" },
    { word: "pale", type: "adj.", meaning: "ซีด" },
    { word: "pan", type: "n.", meaning: "กระทะ" },
    { word: "participate", type: "v.", meaning: "เข้าร่วม" },
    { word: "particularly", type: "adv.", meaning: "โดยเฉพาะอย่างยิ่ง" },
    { word: "pass", type: "n.", meaning: "บัตรผ่าน, การส่งผ่าน" },
    { word: "passion", type: "n.", meaning: "ความหลงใหล" },
    { word: "path", type: "n.", meaning: "เส้นทาง" },
    { word: "payment", type: "n.", meaning: "การชำระเงิน" },
    { word: "peaceful", type: "adj.", meaning: "สงบสุข" },
    { word: "percentage", type: "n.", meaning: "ร้อยละ, เปอร์เซ็นต์" },
    { word: "perfectly", type: "adv.", meaning: "อย่างสมบูรณ์แบบ" },
    { word: "performance", type: "n.", meaning: "การแสดง, ประสิทธิภาพ" },
    { word: "personally", type: "adv.", meaning: "โดยส่วนตัว" },
    { word: "persuade", type: "v.", meaning: "ชักชวน, โน้มน้าว" },
    { word: "photographer", type: "n.", meaning: "ช่างภาพ" },
    { word: "photography", type: "n.", meaning: "การถ่ายภาพ" },
    { word: "pin", type: "n., v.", meaning: "เข็มหมุด, กลัด" },
    { word: "pipe", type: "n.", meaning: "ท่อ" },
    { word: "place", type: "v.", meaning: "วาง" },
    { word: "planning", type: "n.", meaning: "การวางแผน" },
    { word: "pleasant", type: "adj.", meaning: "น่าพอใจ" },
    { word: "pleasure", type: "n.", meaning: "ความสุข, ความพึงพอใจ" },
    { word: "plenty", type: "pron.", meaning: "มากมาย" },
    { word: "plot", type: "n.", meaning: "โครงเรื่อง, แผนการ" },
    { word: "plus", type: "prep.", meaning: "บวก" },
    { word: "poem", type: "n.", meaning: "บทกวี" },
    { word: "poet", type: "n.", meaning: "กวี" },
    { word: "poetry", type: "n.", meaning: "บทกวี, กวีนิพนธ์" },
    { word: "point", type: "v.", meaning: "ชี้" },
    { word: "poison", type: "n., v.", meaning: "ยาพิษ, วางยาพิษ" },
    { word: "poisonous", type: "adj.", meaning: "เป็นพิษ" },
    { word: "policy", type: "n.", meaning: "นโยบาย" },
    { word: "political", type: "adj.", meaning: "ทางการเมือง" },
    { word: "politician", type: "n.", meaning: "นักการเมือง" },
    { word: "politics", type: "n.", meaning: "การเมือง" },
    { word: "port", type: "n.", meaning: "ท่าเรือ" },
    { word: "portrait", type: "n.", meaning: "ภาพเหมือน" },
    { word: "possibly", type: "adv.", meaning: "อาจจะ" },
    { word: "pot", type: "n.", meaning: "หม้อ" },
    { word: "pour", type: "v.", meaning: "เท" },
    { word: "poverty", type: "n.", meaning: "ความยากจน" },
    { word: "powder", type: "n.", meaning: "ผง" },
    { word: "powerful", type: "adj.", meaning: "ทรงพลัง" },
    { word: "practical", type: "adj.", meaning: "ใช้ได้จริง, ปฏิบัติได้" },
    { word: "pray", type: "v.", meaning: "สวดมนต์" },
    { word: "prayer", type: "n.", meaning: "คำอธิษฐาน" },
    { word: "prediction", type: "n.", meaning: "การทำนาย" },
    { word: "prepared", type: "adj.", meaning: "ที่เตรียมพร้อม" },
    { word: "presentation", type: "n.", meaning: "การนำเสนอ" },
    { word: "press", type: "n., v.", meaning: "การกด, ข่าว, กด" },
    { word: "pressure", type: "n.", meaning: "ความกดดัน" },
    { word: "pretend", type: "v.", meaning: "แกล้งทำ" },
    { word: "previous", type: "adj.", meaning: "ก่อนหน้านี้" },
    { word: "previously", type: "adv.", meaning: "ก่อนหน้านี้" },
    { word: "priest", type: "n.", meaning: "นักบวช" },
    { word: "primary", type: "adj.", meaning: "หลัก, ขั้นต้น" },
    { word: "prince", type: "n.", meaning: "เจ้าชาย" },
    { word: "princess", type: "n.", meaning: "เจ้าหญิง" },
    { word: "printing", type: "n.", meaning: "การพิมพ์" },
    { word: "prisoner", type: "n.", meaning: "นักโทษ" },
    { word: "private", type: "adj.", meaning: "ส่วนตัว" },
    { word: "producer", type: "n.", meaning: "ผู้ผลิต, ผู้อำนวยการสร้าง" },
    { word: "production", type: "n.", meaning: "การผลิต" },
    { word: "profession", type: "n.", meaning: "อาชีพ" },
    { word: "profit", type: "n.", meaning: "กำไร" },
    { word: "program", type: "v.", meaning: "ตั้งโปรแกรม (US)" },
    { word: "promote", type: "v.", meaning: "ส่งเสริม, เลื่อนตำแหน่ง" },
    { word: "proper", type: "adj.", meaning: "เหมาะสม, ถูกต้อง" },
    { word: "properly", type: "adv.", meaning: "อย่างเหมาะสม" },
    { word: "property", type: "n.", meaning: "ทรัพย์สิน, อสังหาริมทรัพย์" },
    { word: "protest", type: "n., v.", meaning: "การประท้วง, ประท้วง" },
    { word: "proud", type: "adj.", meaning: "ภูมิใจ" },
    { word: "prove", type: "v.", meaning: "พิสูจน์" },
    { word: "pull", type: "n.", meaning: "การดึง" },
    { word: "punish", type: "v.", meaning: "ลงโทษ" },
    { word: "punishment", type: "n.", meaning: "การลงโทษ" },
    { word: "push", type: "n.", meaning: "การผลัก" },
    { word: "qualification", type: "n.", meaning: "คุณสมบัติ" },
    { word: "qualified", type: "adj.", meaning: "มีคุณสมบัติ" },
    { word: "qualify", type: "v.", meaning: "มีคุณสมบัติ, ทำให้มีคุณสมบัติ" },
    { word: "queue", type: "n., v.", meaning: "คิว, เข้าคิว" },
    { word: "quit", type: "v.", meaning: "เลิก, ลาออก" },
    { word: "quotation", type: "n.", meaning: "คำอ้างอิง, การเสนอราคา" },
    { word: "quote", type: "v., n.", meaning: "อ้างอิง, คำอ้างอิง" },
    { word: "race", type: "n.", meaning: "เผ่าพันธุ์" },
    { word: "racing", type: "n.", meaning: "การแข่งรถ/กีฬา" },
    { word: "range", type: "n.", meaning: "ช่วง, แนว" },
    { word: "rare", type: "adj.", meaning: "หายาก" },
    { word: "rarely", type: "adv.", meaning: "ไม่ค่อยจะ" },
    { word: "reaction", type: "n.", meaning: "ปฏิกิริยา" },
    { word: "reality", type: "n.", meaning: "ความเป็นจริง" },
    { word: "receipt", type: "n.", meaning: "ใบเสร็จ" },
    { word: "recommendation", type: "n.", meaning: "คำแนะนำ" },
    { word: "reference", type: "n.", meaning: "การอ้างอิง, แหล่งอ้างอิง" },
    { word: "reflect", type: "v.", meaning: "สะท้อน" },
    { word: "regularly", type: "adv.", meaning: "เป็นประจำ" },
    { word: "reject", type: "v.", meaning: "ปฏิเสธ" },
    { word: "relate", type: "v.", meaning: "เกี่ยวข้อง" },
    { word: "related", type: "adj.", meaning: "ที่เกี่ยวข้อง" },
    { word: "relation", type: "n.", meaning: "ความสัมพันธ์" },
    { word: "relative", type: "adj., n.", meaning: "สัมพัทธ์, ญาติ" },
    { word: "relaxed", type: "adj.", meaning: "ผ่อนคลาย" },
    { word: "relaxing", type: "adj.", meaning: "ผ่อนคลาย (ทำให้รู้สึกผ่อนคลาย)" },
    { word: "release", type: "v., n.", meaning: "ปล่อย, การปล่อย" },
    { word: "reliable", type: "adj.", meaning: "เชื่อถือได้" },
    { word: "religion", type: "n.", meaning: "ศาสนา" },
    { word: "religious", type: "adj.", meaning: "เกี่ยวกับศาสนา" },
    { word: "remain", type: "v.", meaning: "ยังคงอยู่" },
    { word: "remind", type: "v.", meaning: "เตือนความจำ" },
    { word: "remote", type: "adj.", meaning: "ห่างไกล" },
    { word: "rent", type: "n., v.", meaning: "ค่าเช่า, เช่า" },
    { word: "repair", type: "n.", meaning: "การซ่อมแซม" },
    { word: "repeat", type: "n.", meaning: "การทำซ้ำ" },
    { word: "repeated", type: "adj.", meaning: "ที่ทำซ้ำแล้วซ้ำอีก" },
    { word: "represent", type: "v.", meaning: "เป็นตัวแทน, แสดง" },
    { word: "request", type: "v.", meaning: "ร้องขอ" },
    { word: "require", type: "v.", meaning: "ต้องการ, กำหนดให้มี" },
    { word: "reservation", type: "n.", meaning: "การจอง" },
    { word: "resource", type: "n.", meaning: "ทรัพยากร" },
    { word: "respect", type: "n., v.", meaning: "ความเคารพ, เคารพ" },
    { word: "responsibility", type: "n.", meaning: "ความรับผิดชอบ" },
    { word: "responsible", type: "adj.", meaning: "รับผิดชอบ" },
    { word: "result", type: "v.", meaning: "ส่งผลให้เกิด" },
    { word: "retire", type: "v.", meaning: "เกษียณ" },
    { word: "retired", type: "adj.", meaning: "ที่เกษียณแล้ว" },
    { word: "revise", type: "v.", meaning: "ทบทวน, แก้ไข" },
    { word: "ring", type: "n.", meaning: "เสียงกริ่ง, โทรศัพท์" },
    { word: "rise", type: "n.", meaning: "การเพิ่มขึ้น, การขึ้น" },
    { word: "risk", type: "n., v.", meaning: "ความเสี่ยง, เสี่ยง" },
    { word: "robot", type: "n.", meaning: "หุ่นยนต์" },
    { word: "roll", type: "v., n.", meaning: "กลิ้ง, ม้วน, การกลิ้ง" },
    { word: "romantic", type: "adj.", meaning: "โรแมนติก" },
    { word: "rope", type: "n.", meaning: "เชือก" },
    { word: "rough", type: "adj.", meaning: "หยาบ, ขรุขระ" },
    { word: "row", type: "n.", meaning: "แถว" },
    { word: "royal", type: "adj.", meaning: "ของราชวงศ์" },
    { word: "rugby", type: "n.", meaning: "รักบี้" },
    { word: "rule", type: "v.", meaning: "ปกครอง, กำหนดกฎ" },
    { word: "safety", type: "n.", meaning: "ความปลอดภัย" },
    { word: "sail", type: "n.", meaning: "ใบเรือ, การแล่นเรือ" },
    { word: "sailor", type: "n.", meaning: "กะลาสี" },
    { word: "sample", type: "n.", meaning: "ตัวอย่าง" },
    { word: "sand", type: "n.", meaning: "ทราย" },
    { word: "scan", type: "v.", meaning: "สแกน" },
    { word: "scientific", type: "adj.", meaning: "ทางวิทยาศาสตร์" },
    { word: "script", type: "n.", meaning: "บทภาพยนตร์/ละคร, สคริปต์" },
    { word: "sculpture", type: "n.", meaning: "ประติมากรรม" },
    { word: "secondary", type: "adj.", meaning: "รอง, ระดับมัธยมศึกษา" },
    { word: "security", type: "n.", meaning: "ความปลอดภัย, หลักทรัพย์" },
    { word: "seed", type: "n.", meaning: "เมล็ด" },
    { word: "sensible", type: "adj.", meaning: "มีเหตุผล, มีสติ" },
    { word: "separate", type: "v.", meaning: "แยก" },
    { word: "seriously", type: "adv.", meaning: "อย่างจริงจัง" },
    { word: "servant", type: "n.", meaning: "คนรับใช้" },
    { word: "set", type: "v., n.", meaning: "วาง, ตั้งค่า, ชุด, กลุ่ม" },
    { word: "setting", type: "n.", meaning: "ฉาก, การตั้งค่า" },
    { word: "sex", type: "n.", meaning: "เพศ" },
    { word: "sexual", type: "adj.", meaning: "ทางเพศ" },
    { word: "shake", type: "n.", meaning: "การสั่น" },
    { word: "share", type: "n.", meaning: "ส่วนแบ่ง" },
    { word: "sharp", type: "adj.", meaning: "คม, แหลม" },
    { word: "shelf", type: "n.", meaning: "ชั้นวางของ" },
    { word: "shell", type: "n.", meaning: "เปลือก" },
    { word: "shift", type: "n.", meaning: "กะ, การเปลี่ยนแปลง" },
    { word: "shine", type: "v.", meaning: "ส่องแสง, เปล่งประกาย" },
    { word: "shiny", type: "adj.", meaning: "เป็นประกาย" },
    { word: "shoot", type: "v.", meaning: "ยิง, ถ่ายภาพยนตร์" },
    { word: "shy", type: "adj.", meaning: "ขี้อาย" },
    { word: "sight", type: "n.", meaning: "สายตา, การมองเห็น" },
    { word: "signal", type: "n., v.", meaning: "สัญญาณ, ให้สัญญาณ" },
    { word: "silent", type: "adj.", meaning: "เงียบ" },
    { word: "silly", type: "adj.", meaning: "โง่, เหลวไหล" },
    { word: "similarity", type: "n.", meaning: "ความคล้ายคลึง" },
    { word: "similarly", type: "adv.", meaning: "ในทำนองเดียวกัน" },
    { word: "simply", type: "adv.", meaning: "อย่างเรียบง่าย, เพียงแค่" },
    { word: "since", type: "adv.", meaning: "ตั้งแต่นั้นมา" },
    { word: "sink", type: "v.", meaning: "จม" },
    { word: "slice", type: "n., v.", meaning: "ชิ้นบางๆ, หั่นเป็นชิ้น" },
    { word: "slightly", type: "adv.", meaning: "เล็กน้อย" },
    { word: "slow", type: "v.", meaning: "ทำให้ช้าลง" },
    { word: "smart", type: "adj.", meaning: "ฉลาด, ดูดี" },
    { word: "smooth", type: "adj.", meaning: "เรียบเนียน" },
    { word: "software", type: "n.", meaning: "ซอฟต์แวร์" },
    { word: "soil", type: "n.", meaning: "ดิน" },
    { word: "solid", type: "adj., n.", meaning: "ของแข็ง, แข็ง" },
    { word: "sort", type: "v.", meaning: "จัดเรียง" },
    { word: "southern", type: "adj.", meaning: "ทางใต้" },
    { word: "specifically", type: "adv.", meaning: "โดยเฉพาะเจาะจง" },
    { word: "spending", type: "n.", meaning: "การใช้จ่าย" },
    { word: "spicy", type: "adj.", meaning: "เผ็ด" },
    { word: "spirit", type: "n.", meaning: "จิตวิญญาณ, วิญญาณ" },
    { word: "spoken", type: "adj.", meaning: "ที่พูด" },
    { word: "spot", type: "n.", meaning: "จุด, สถานที่" },
    { word: "spread", type: "v.", meaning: "แพร่กระจาย, แผ่ออก" },
    { word: "spring", type: "v.", meaning: "กระโดด, ดีดตัว" },
    { word: "stadium", type: "n.", meaning: "สนามกีฬา" },
    { word: "staff", type: "n.", meaning: "พนักงาน" },
    { word: "standard", type: "n., adj.", meaning: "มาตรฐาน" },
    { word: "state", type: "adj., v.", meaning: "ของรัฐ, ระบุ" },
    { word: "statistic", type: "n.", meaning: "สถิติ" },
    { word: "statue", type: "n.", meaning: "รูปปั้น" },
    { word: "stick", type: "v., n.", meaning: "ติด, ปัก, ไม้เรียว, กิ่งไม้" },
    { word: "still", type: "adj.", meaning: "นิ่ง, สงบ" },
    { word: "store", type: "v.", meaning: "เก็บ, สะสม" },
    { word: "stranger", type: "n.", meaning: "คนแปลกหน้า" },
    { word: "strength", type: "n.", meaning: "ความแข็งแรง" },
    { word: "string", type: "n.", meaning: "เชือก, สาย" },
    { word: "strongly", type: "adv.", meaning: "อย่างแข็งขัน, อย่างแรง" },
    { word: "studio", type: "n.", meaning: "สตูดิโอ" },
    { word: "stuff", type: "n.", meaning: "สิ่งของ (ไม่เป็นทางการ)" },
    { word: "substance", type: "n.", meaning: "สาร" },
    { word: "successfully", type: "adv.", meaning: "อย่างประสบความสำเร็จ" },
    { word: "sudden", type: "adj.", meaning: "กะทันหัน" },
    { word: "suffer", type: "v.", meaning: "ทนทุกข์, ประสบ" },
    { word: "suit", type: "v.", meaning: "เหมาะสมกับ" },
    { word: "suitable", type: "adj.", meaning: "เหมาะสม" },
    { word: "summarize", type: "v.", meaning: "สรุป" },
    { word: "summary", type: "n.", meaning: "บทสรุป" },
    { word: "supply", type: "n., v.", meaning: "อุปทาน, จัดหา" },
    { word: "supporter", type: "n.", meaning: "ผู้สนับสนุน" },
    { word: "surely", type: "adv.", meaning: "อย่างแน่นอน, น่าจะ" },
    { word: "surface", type: "n.", meaning: "พื้นผิว" },
    { word: "survive", type: "v.", meaning: "รอดชีวิต" },
    { word: "swim", type: "n.", meaning: "การว่ายน้ำ" },
    { word: "switch", type: "v.", meaning: "สลับ, เปลี่ยน" },
    { word: "symptom", type: "n.", meaning: "อาการ" },
    { word: "tail", type: "n.", meaning: "หาง" },
    { word: "talent", type: "n.", meaning: "พรสวรรค์" },
    { word: "talented", type: "adj.", meaning: "มีความสามารถ" },
    { word: "tape", type: "n.", meaning: "เทป" },
    { word: "tax", type: "n., v.", meaning: "ภาษี, เก็บภาษี" },
    { word: "technical", type: "adj.", meaning: "ทางเทคนิค" },
    { word: "technique", type: "n.", meaning: "เทคนิค" },
    { word: "tend", type: "v.", meaning: "มีแนวโน้มที่จะ" },
    { word: "tent", type: "n.", meaning: "เต็นท์" },
    { word: "that", type: "adv.", meaning: "มากขนาดนั้น (เช่น not that good)" },
    { word: "theirs", type: "pron.", meaning: "ของพวกเขา" },
    { word: "theme", type: "n.", meaning: "หัวข้อ, ธีม" },
    { word: "theory", type: "n.", meaning: "ทฤษฎี" },
    { word: "therefore", type: "adv.", meaning: "ดังนั้น" },
    { word: "this", type: "adv.", meaning: "ขนาดนี้ (เช่น this big)" },
    { word: "though", type: "conj., adv.", meaning: "แม้ว่า, อย่างไรก็ตาม" },
    { word: "throat", type: "n.", meaning: "ลำคอ" },
    { word: "throughout", type: "prep./adv.", meaning: "ตลอดทั่ว" },
    { word: "tight", type: "adj.", meaning: "แน่น, คับ" },
    { word: "till", type: "conj./prep.", meaning: "จนกระทั่ง" },
    { word: "tin", type: "n.", meaning: "กระป๋อง, ดีบุก" },
    { word: "tiny", type: "adj.", meaning: "เล็กจิ๋ว" },
    { word: "tip", type: "v.", meaning: "ให้เงินทิป, ทำให้เอียง" },
    { word: "toe", type: "n.", meaning: "นิ้วเท้า" },
    { word: "tongue", type: "n.", meaning: "ลิ้น" },
    { word: "total", type: "adj., n.", meaning: "ทั้งหมด, ผลรวม" },
    { word: "totally", type: "adv.", meaning: "โดยสิ้นเชิง" },
    { word: "touch", type: "n.", meaning: "การสัมผัส" },
    { word: "tour", type: "v.", meaning: "ท่องเที่ยว" },
    { word: "tourism", type: "n.", meaning: "การท่องเที่ยว" },
    { word: "towards", type: "prep.", meaning: "ไปทาง" },
    { word: "towel", type: "n.", meaning: "ผ้าเช็ดตัว" },
    { word: "tower", type: "n.", meaning: "หอคอย" },
    { word: "toy", type: "n., adj.", meaning: "ของเล่น" },
    { word: "track", type: "n.", meaning: "ร่องรอย, ลู่ (วิ่ง), เพลง" },
    { word: "tradition", type: "n.", meaning: "ประเพณี" },
    { word: "traditional", type: "adj.", meaning: "ดั้งเดิม, ตามประเพณี" },
    { word: "train", type: "v.", meaning: "ฝึกฝน" },
    { word: "trainer", type: "n.", meaning: "ผู้ฝึกสอน, รองเท้าผ้าใบ" },
    { word: "training", type: "n.", meaning: "การฝึกอบรม" },
    { word: "transport", type: "n.", meaning: "การขนส่ง" },
    { word: "traveller", type: "n.", meaning: "นักเดินทาง" },
    { word: "trouble", type: "n.", meaning: "ปัญหา" },
    { word: "truck", type: "n.", meaning: "รถบรรทุก (US)" },
    { word: "twin", type: "n., adj.", meaning: "ฝาแฝด" },
    { word: "typical", type: "adj.", meaning: "โดยทั่วไป, เป็นแบบฉบับ" },
    { word: "underground", type: "adj., adv.", meaning: "ใต้ดิน" },
    { word: "understanding", type: "n.", meaning: "ความเข้าใจ" },
    { word: "unfortunately", type: "adv.", meaning: "น่าเสียดายที่" },
    { word: "unhappy", type: "adj.", meaning: "ไม่มีความสุข" },
    { word: "uniform", type: "n.", meaning: "เครื่องแบบ" },
    { word: "unit", type: "n.", meaning: "หน่วย" },
    { word: "united", type: "adj.", meaning: "รวมกัน, สามัคคี" },
    { word: "unusual", type: "adj.", meaning: "ผิดปกติ" },
    { word: "upstairs", type: "adj.", meaning: "ที่อยู่ชั้นบน" },
    { word: "use", type: "n.", meaning: "การใช้, ประโยชน์" },
    { word: "used", type: "adj.", meaning: "ที่ใช้แล้ว, ที่คุ้นเคย" },
    { word: "valuable", type: "adj.", meaning: "มีค่า" },
    { word: "value", type: "n.", meaning: "คุณค่า, มูลค่า" },
    { word: "various", type: "adj.", meaning: "หลากหลาย" },
    { word: "version", type: "n.", meaning: "ฉบับ, เวอร์ชั่น" },
    { word: "victim", type: "n.", meaning: "เหยื่อ" },
    { word: "view", type: "v.", meaning: "มอง, เห็น" },
    { word: "viewer", type: "n.", meaning: "ผู้ชม" },
    { word: "violent", type: "adj.", meaning: "รุนแรง" },
    { word: "volunteer", type: "n., v.", meaning: "อาสาสมัคร, อาสา" },
    { word: "vote", type: "n., v.", meaning: "การลงคะแนน, ลงคะแนน" },
    { word: "warm", type: "v.", meaning: "ทำให้ร้อน, ทำให้อบอุ่น" },
    { word: "warn", type: "v.", meaning: "เตือน" },
    { word: "warning", type: "n.", meaning: "คำเตือน" },
    { word: "waste", type: "n., v., adj.", meaning: "ขยะ, เสียเปล่า, เปล่าประโยชน์" },
    { word: "water", type: "v.", meaning: "รดน้ำ" },
    { word: "wave", type: "v.", meaning: "โบกมือ" },
    { word: "weapon", type: "n.", meaning: "อาวุธ" },
    { word: "weigh", type: "v.", meaning: "ชั่งน้ำหนัก" },
    { word: "western", type: "adj.", meaning: "ทางตะวันตก" },
    { word: "whatever", type: "det./pron.", meaning: "อะไรก็ตาม" },
    { word: "whenever", type: "conj.", meaning: "เมื่อไรก็ตาม" },
    { word: "whether", type: "conj.", meaning: "ไม่ว่า...หรือไม่" },
    { word: "while", type: "n.", meaning: "ช่วงเวลาสั้นๆ" },
    { word: "whole", type: "n.", meaning: "ทั้งหมด" },
    { word: "will", type: "n.", meaning: "เจตจำนง, พินัยกรรม" },
    { word: "win", type: "n.", meaning: "ชัยชนะ" },
    { word: "wing", type: "n.", meaning: "ปีก" },
    { word: "within", type: "prep.", meaning: "ภายใน" },
    { word: "wonder", type: "v., n.", meaning: "สงสัย, ความสงสัย" },
    { word: "wool", type: "n.", meaning: "ขนสัตว์, ผ้าขนสัตว์" },
    { word: "worldwide", type: "adj., adv.", meaning: "ทั่วโลก" },
    { word: "worry", type: "n.", meaning: "ความกังวล" },
    { word: "worse", type: "adv.", meaning: "แย่ลง" },
    { word: "worst", type: "adv.", meaning: "แย่ที่สุด" },
    { word: "worth", type: "adj.", meaning: "คุ้มค่า" },
    { word: "written", type: "adj.", meaning: "ที่เขียน" },
    { word: "wrong", type: "adv.", meaning: "ผิดพลาด" },
    { word: "yard", type: "n.", meaning: "หลา (หน่วยวัด), ลาน" },
    { word: "young", type: "n.", meaning: "คนหนุ่มสาว" },
    { word: "youth", type: "n.", meaning: "วัยหนุ่มสาว, เยาวชน" },
];
