import { Word } from './types';

export const b2Words: Word[] = [
    { word: "abandon", type: "v.", meaning: "ละทิ้ง, ทอดทิ้ง" },
    { word: "absolute", type: "adj.", meaning: "สมบูรณ์, แน่นอน" },
    { word: "academic", type: "n.", meaning: "นักวิชาการ" },
    { word: "acceptable", type: "adj.", meaning: "เป็นที่ยอมรับได้" },
    { word: "accompany", type: "v.", meaning: "ติดตาม, ไปเป็นเพื่อน" },
    { word: "account", type: "v.", meaning: "พิจารณาว่า, ถือว่า" },
    { word: "accurate", type: "adj.", meaning: "ถูกต้องแม่นยำ" },
    { word: "accuse", type: "v.", meaning: "กล่าวหา" },
    { word: "acknowledge", type: "v.", meaning: "ยอมรับ, รับทราบ" },
    { word: "acquire", type: "v.", meaning: "ได้รับ, ได้มา" },
    { word: "actual", type: "adj.", meaning: "แท้จริง, ที่เกิดขึ้นจริง" },
    { word: "adapt", type: "v.", meaning: "ปรับตัว, ดัดแปลง" },
    { word: "additional", type: "adj.", meaning: "เพิ่มเติม" },
    { word: "address", type: "v.", meaning: "กล่าวปราศรัย, จัดการ" },
    { word: "administration", type: "n.", meaning: "การบริหาร" },
    { word: "adopt", type: "v.", meaning: "รับเอามาใช้, รับเลี้ยง (บุตร)" },
    { word: "advance", type: "n., v., adj.", meaning: "ความก้าวหน้า, ก้าวหน้า, ล่วงหน้า" },
    { word: "affair", type: "n.", meaning: "เรื่องราว, กิจธุระ" },
    { word: "afterwards", type: "adv.", meaning: "ภายหลัง, หลังจากนั้น" },
    { word: "agency", type: "n.", meaning: "หน่วยงาน, ตัวแทน" },
    { word: "agenda", type: "n.", meaning: "วาระการประชุม" },
    { word: "aggressive", type: "adj.", meaning: "ก้าวร้าว" },
    { word: "aid", type: "n., v.", meaning: "ความช่วยเหลือ, ช่วยเหลือ" },
    { word: "aircraft", type: "n.", meaning: "เครื่องบิน" },
    { word: "alarm", type: "v.", meaning: "ทำให้ตกใจ, เตือน" },
    { word: "alter", type: "v.", meaning: "เปลี่ยนแปลง" },
    { word: "amount", type: "v.", meaning: "รวมเป็นจำนวน" },
    { word: "anger", type: "n.", meaning: "ความโกรธ" },
    { word: "angle", type: "n.", meaning: "มุม" },
    { word: "anniversary", type: "n.", meaning: "วันครบรอบ" },
    { word: "annual", type: "adj.", meaning: "ประจำปี" },
    { word: "anxious", type: "adj.", meaning: "วิตกกังวล" },
    { word: "apparent", type: "adj.", meaning: "ชัดเจน, ปรากฏชัด" },
    { word: "apparently", type: "adv.", meaning: "ดูเหมือนว่า, อย่างชัดเจน" },
    { word: "appeal", type: "n., v.", meaning: "อุทธรณ์, ดึงดูดความสนใจ" },
    { word: "approach", type: "n., v.", meaning: "การเข้าถึง, เข้าใกล้" },
    { word: "appropriate", type: "adj.", meaning: "เหมาะสม" },
    { word: "approval", type: "n.", meaning: "การอนุมัติ, ความเห็นชอบ" },
    { word: "approve", type: "v.", meaning: "อนุมัติ, เห็นด้วย" },
    { word: "arise", type: "v.", meaning: "เกิดขึ้น, ลุกขึ้น" },
    { word: "armed", type: "adj.", meaning: "ติดอาวุธ" },
    { word: "arms", type: "n.", meaning: "อาวุธ" },
    { word: "artificial", type: "adj.", meaning: "เทียม, ประดิษฐ์" },
    { word: "artistic", type: "adj.", meaning: "มีศิลปะ" },
    { word: "ashamed", type: "adj.", meaning: "ละอายใจ" },
    { word: "aspect", type: "n.", meaning: "แง่มุม, ลักษณะ" },
    { word: "assess", type: "v.", meaning: "ประเมิน" },
    { word: "assessment", type: "n.", meaning: "การประเมิน" },
    { word: "associate", type: "v.", meaning: "เกี่ยวข้อง, เชื่อมโยง" },
    { word: "associated", type: "adj.", meaning: "ที่เกี่ยวข้อง" },
    { word: "association", type: "n.", meaning: "สมาคม, การเชื่อมโยง" },
    { word: "assume", type: "v.", meaning: "สมมติ, สันนิษฐาน" },
    { word: "attempt", type: "n., v.", meaning: "ความพยายาม, พยายาม" },
    { word: "back", type: "v.", meaning: "สนับสนุน, ถอยหลัง" },
    { word: "bacteria", type: "n.", meaning: "แบคทีเรีย" },
    { word: "bar", type: "v.", meaning: "ห้าม, กีดขวาง" },
    { word: "barrier", type: "n.", meaning: "อุปสรรค, สิ่งกีดขวาง" },
    { word: "basically", type: "adv.", meaning: "โดยพื้นฐานแล้ว" },
    { word: "battle", type: "v.", meaning: "ต่อสู้" },
    { word: "bear", type: "v.", meaning: "ทน, รับมือ" },
    { word: "beat", type: "n.", meaning: "จังหวะ, การตี" },
    { word: "beg", type: "v.", meaning: "ขอทาน, วิงวอน" },
    { word: "being", type: "n.", meaning: "สิ่งมีชีวิต, การเป็นอยู่" },
    { word: "bent", type: "adj.", meaning: "โค้งงอ" },
    { word: "bet", type: "v., n.", meaning: "พนัน, การพนัน" },
    { word: "beyond", type: "prep., adv.", meaning: "พ้นจาก, เกินกว่า" },
    { word: "bill", type: "v.", meaning: "เรียกเก็บเงิน" },
    { word: "bitter", type: "adj.", meaning: "ขม, ขมขื่น" },
    { word: "blame", type: "v., n.", meaning: "ตำหนิ, การตำหนิ" },
    { word: "blind", type: "adj.", meaning: "ตาบอด" },
    { word: "bond", type: "n.", meaning: "พันธะ, ข้อผูกมัด" },
    { word: "border", type: "v.", meaning: "มีพรมแดนติดกับ" },
    { word: "breast", type: "n.", meaning: "หน้าอก (ผู้หญิง), เต้านม" },
    { word: "brief", type: "adj.", meaning: "สั้น, กระชับ" },
    { word: "broad", type: "adj.", meaning: "กว้าง" },
    { word: "broadcast", type: "v., n.", meaning: "ออกอากาศ, การออกอากาศ" },
    { word: "budget", type: "n.", meaning: "งบประมาณ" },
    { word: "bullet", type: "n.", meaning: "กระสุน" },
    { word: "bunch", type: "n.", meaning: "พวง, กลุ่ม" },
    { word: "burn", type: "n.", meaning: "แผลไหม้, การเผาไหม้" },
    { word: "bush", type: "n.", meaning: "พุ่มไม้" },
    { word: "but", type: "prep.", meaning: "ยกเว้น" },
    { word: "cable", type: "n.", meaning: "สายเคเบิล" },
    { word: "calculate", type: "v.", meaning: "คำนวณ" },
    { word: "cancel", type: "v.", meaning: "ยกเลิก" },
    { word: "cancer", type: "n.", meaning: "มะเร็ง" },
    { word: "capable", type: "adj.", meaning: "สามารถ (ที่จะทำ)" },
    { word: "capacity", type: "n.", meaning: "ความจุ, กำลังการผลิต" },
    { word: "capture", type: "v., n.", meaning: "จับกุม, การจับกุม" },
    { word: "cast", type: "n., v.", meaning: "นักแสดง, หล่อ, โยน" },
    { word: "catch", type: "n.", meaning: "การจับ, สิ่งที่จับได้" },
    { word: "cell", type: "n.", meaning: "เซลล์, ห้องขัง" },
    { word: "chain", type: "v.", meaning: "ล่ามโซ่" },
    { word: "chair", type: "v.", meaning: "เป็นประธาน" },
    { word: "chairman", type: "n.", meaning: "ประธาน (ผู้ชาย)" },
    { word: "challenge", type: "v.", meaning: "ท้าทาย" },
    { word: "characteristic", type: "n., adj.", meaning: "ลักษณะเฉพาะ, เป็นลักษณะเฉพาะ" },
    { word: "chart", type: "v.", meaning: "ทำแผนภูมิ" },
    { word: "chief", type: "adj., n.", meaning: "หัวหน้า, หลัก" },
    { word: "circumstance", type: "n.", meaning: "สถานการณ์, สภาวการณ์" },
    { word: "cite", type: "v.", meaning: "อ้างอิง" },
    { word: "citizen", type: "n.", meaning: "พลเมือง" },
    { word: "civil", type: "adj.", meaning: "พลเรือน, ที่เกี่ยวกับพลเมือง" },
    { word: "classic", type: "adj., n.", meaning: "คลาสสิก, ผลงานคลาสสิก" },
    { word: "close", type: "n.", meaning: "การปิด" },
    { word: "closely", type: "adv.", meaning: "อย่างใกล้ชิด" },
    { word: "collapse", type: "v., n.", meaning: "พังทลาย, การพังทลาย" },
    { word: "combination", type: "n.", meaning: "การรวมกัน, ส่วนผสม" },
    { word: "comfort", type: "n., v.", meaning: "ความสบาย, ปลอบโยน" },
    { word: "command", type: "n., v.", meaning: "คำสั่ง, สั่ง" },
    { word: "commission", type: "n., v.", meaning: "คณะกรรมการ, ค่านายหน้า, มอบหมาย" },
    { word: "commitment", type: "n.", meaning: "พันธะสัญญา, ความผูกมัด" },
    { word: "committee", type: "n.", meaning: "คณะกรรมการ" },
    { word: "commonly", type: "adv.", meaning: "โดยทั่วไป" },
    { word: "complex", type: "n.", meaning: "ความซับซ้อน, กลุ่มอาคาร" },
    { word: "complicated", type: "adj.", meaning: "ซับซ้อน" },
    { word: "component", type: "n.", meaning: "ส่วนประกอบ" },
    { word: "concentration", type: "n.", meaning: "สมาธิ, ความเข้มข้น" },
    { word: "concept", type: "n.", meaning: "แนวคิด" },
    { word: "concern", type: "n., v.", meaning: "ความกังวล, ทำให้กังวล" },
    { word: "concerned", type: "adj.", meaning: "ที่เกี่ยวข้อง, กังวล" },
    { word: "conduct", type: "v., n.", meaning: "ดำเนินการ, ความประพฤติ" },
    { word: "confidence", type: "n.", meaning: "ความมั่นใจ" },
    { word: "conflict", type: "n., v.", meaning: "ความขัดแย้ง, ขัดแย้ง" },
    { word: "confusing", type: "adj.", meaning: "น่าสับสน" },
    { word: "conscious", type: "adj.", meaning: "มีสติ, ที่รู้สึกตัว" },
    { word: "conservative", type: "adj., n.", meaning: "อนุรักษ์นิยม" },
    { word: "consideration", type: "n.", meaning: "การพิจารณา, ข้อควรพิจารณา" },
    { word: "consistent", type: "adj.", meaning: "สอดคล้องกัน, คงเส้นคงวา" },
    { word: "constant", type: "adj.", meaning: "คงที่, สม่ำเสมอ" },
    { word: "constantly", type: "adv.", meaning: "อย่างสม่ำเสมอ" },
    { word: "construct", type: "v.", meaning: "สร้าง" },
    { word: "construction", type: "n.", meaning: "การก่อสร้าง" },
    { word: "contemporary", type: "adj.", meaning: "ร่วมสมัย" },
    { word: "contest", type: "n., v.", meaning: "การประกวด, แข่งขัน" },
    { word: "contract", type: "n., v.", meaning: "สัญญา, ทำสัญญา" },
    { word: "contribute", type: "v.", meaning: "มีส่วนร่วม, บริจาค" },
    { word: "contribution", type: "n.", meaning: "การมีส่วนร่วม, สิ่งที่บริจาค" },
    { word: "convert", type: "v.", meaning: "แปลง, เปลี่ยน" },
    { word: "convinced", type: "adj.", meaning: "ที่เชื่อมั่น" },
    { word: "core", type: "n., adj.", meaning: "แกนหลัก, สำคัญ" },
    { word: "corporate", type: "adj.", meaning: "องค์กร, บริษัท" },
    { word: "council", type: "n.", meaning: "สภา" },
    { word: "county", type: "n.", meaning: "มณฑล, เทศมณฑล" },
    { word: "courage", type: "n.", meaning: "ความกล้าหาญ" },
    { word: "crash", type: "n., v.", meaning: "การชน, พัง, ชน" },
    { word: "creation", type: "n.", meaning: "การสร้าง, สิ่งที่สร้างขึ้น" },
    { word: "creature", type: "n.", meaning: "สิ่งมีชีวิต" },
    { word: "credit", type: "v.", meaning: "เชื่อถือ, ให้เครดิต" },
    { word: "crew", type: "n.", meaning: "ลูกเรือ, ลูกทีม" },
    { word: "crisis", type: "n.", meaning: "วิกฤต" },
    { word: "criterion", type: "n.", meaning: "เกณฑ์" },
    { word: "critic", type: "n.", meaning: "นักวิจารณ์" },
    { word: "critical", type: "adj.", meaning: "วิกฤต, สำคัญยิ่ง, เกี่ยวกับการวิจารณ์" },
    { word: "criticism", type: "n.", meaning: "คำวิจารณ์" },
    { word: "criticize", type: "v.", meaning: "วิจารณ์" },
    { word: "crop", type: "n.", meaning: "พืชผล" },
    { word: "crucial", type: "adj.", meaning: "สำคัญมาก, เด็ดขาด" },
    { word: "cry", type: "n.", meaning: "เสียงร้อง, การร้องไห้" },
    { word: "cure", type: "v., n.", meaning: "รักษา, การรักษา" },
    { word: "current", type: "n.", meaning: "กระแส, กระแสน้ำ" },
    { word: "curve", type: "n., v.", meaning: "เส้นโค้ง, โค้ง" },
    { word: "curved", type: "adj.", meaning: "โค้ง" },
    { word: "date", type: "v.", meaning: "ระบุวันที่, คบหา" },
    { word: "debate", type: "n., v.", meaning: "การถกเถียง, ถกเถียง" },
    { word: "debt", type: "n.", meaning: "หนี้สิน" },
    { word: "decent", type: "adj.", meaning: "เหมาะสม, ดีงาม" },
    { word: "declare", type: "v.", meaning: "ประกาศ" },
    { word: "decline", type: "v., n.", meaning: "ลดลง, การลดลง" },
    { word: "decoration", type: "n.", meaning: "การตกแต่ง, ของประดับ" },
    { word: "decrease", type: "v., n.", meaning: "ลดลง, การลดลง" },
    { word: "deeply", type: "adv.", meaning: "อย่างลึกซึ้ง" },
    { word: "defeat", type: "v., n.", meaning: "เอาชนะ, ความพ่ายแพ้" },
    { word: "defence", type: "n.", meaning: "การป้องกัน" },
    { word: "defend", type: "v.", meaning: "ป้องกัน" },
    { word: "delay", type: "v., n.", meaning: "ล่าช้า, ความล่าช้า" },
    { word: "deliberate", type: "adj.", meaning: "เจตนา, รอบคอบ" },
    { word: "deliberately", type: "adv.", meaning: "โดยเจตนา" },
    { word: "delight", type: "v., n.", meaning: "ทำให้พอใจ, ความยินดี" },
    { word: "delighted", type: "adj.", meaning: "ยินดีอย่างยิ่ง" },
    { word: "delivery", type: "n.", meaning: "การส่งมอบ" },
    { word: "demand", type: "n., v.", meaning: "ความต้องการ, เรียกร้อง" },
    { word: "demonstrate", type: "v.", meaning: "สาธิต, แสดงให้เห็น" },
    { word: "deny", type: "v.", meaning: "ปฏิเสธ" },
    { word: "depressed", type: "adj.", meaning: "หดหู่, ซึมเศร้า" },
    { word: "depressing", type: "adj.", meaning: "น่าหดหู่" },
    { word: "depth", type: "n.", meaning: "ความลึก" },
    { word: "desert", type: "v.", meaning: "ทอดทิ้ง" },
    { word: "deserve", type: "v.", meaning: "สมควรได้รับ" },
    { word: "desire", type: "n., v.", meaning: "ความปรารถนา, ปรารถนา" },
    { word: "desperate", type: "adj.", meaning: "หมดหวัง, สิ้นหวัง" },
    { word: "detail", type: "v.", meaning: "ให้รายละเอียด" },
    { word: "detailed", type: "adj.", meaning: "ที่มีรายละเอียด" },
    { word: "detect", type: "v.", meaning: "ตรวจจับ, ค้นพบ" },
    { word: "dig", type: "v.", meaning: "ขุด" },
    { word: "disc", type: "n.", meaning: "แผ่นดิสก์" },
    { word: "discipline", type: "n.", meaning: "ระเบียบวินัย, สาขาวิชา" },
    { word: "discount", type: "v.", meaning: "ลดราคา" },
    { word: "dishonest", type: "adj.", meaning: "ไม่ซื่อสัตย์" },
    { word: "dismiss", type: "v.", meaning: "ไล่ออก, ปัดทิ้ง" },
    { word: "display", type: "v., n.", meaning: "แสดง, การแสดง" },
    { word: "distribute", type: "v.", meaning: "แจกจ่าย, แบ่งปัน" },
    { word: "distribution", type: "n.", meaning: "การแจกจ่าย" },
    { word: "district", type: "n.", meaning: "เขต, อำเภอ" },
    { word: "divide", type: "n.", meaning: "การแบ่ง" },
    { word: "division", type: "n.", meaning: "การแบ่ง, แผนก" },
    { word: "document", type: "v.", meaning: "จัดทำเป็นเอกสาร" },
    { word: "domestic", type: "adj.", meaning: "ภายในประเทศ, เกี่ยวกับบ้าน" },
    { word: "dominate", type: "v.", meaning: "ครอบงำ" },
    { word: "downwards", type: "adv.", meaning: "ลงด้านล่าง" },
    { word: "dozen", type: "n., det.", meaning: "โหล" },
    { word: "draft", type: "n., v.", meaning: "ฉบับร่าง, ร่าง" },
    { word: "drag", type: "v.", meaning: "ลาก" },
    { word: "dramatic", type: "adj.", meaning: "น่าทึ่ง, น่าตื่นเต้น" },
    { word: "edit", type: "v.", meaning: "แก้ไข, ตัดต่อ" },
    { word: "edition", type: "n.", meaning: "ฉบับ, ครั้งที่พิมพ์" },
    { word: "efficient", type: "adj.", meaning: "มีประสิทธิภาพ" },
    { word: "elderly", type: "adj.", meaning: "สูงอายุ" },
    { word: "elect", type: "v.", meaning: "เลือกตั้ง" },
    { word: "elsewhere", type: "adv.", meaning: "ที่อื่น" },
    { word: "emerge", type: "v.", meaning: "ปรากฏออกมา, โผล่ออกมา" },
    { word: "emotional", type: "adj.", meaning: "เกี่ยวกับอารมณ์" },
    { word: "emphasis", type: "n.", meaning: "การเน้น, จุดเน้น" },
    { word: "emphasize", type: "v.", meaning: "เน้นย้ำ" },
    { word: "enable", type: "v.", meaning: "ทำให้สามารถ" },
    { word: "encounter", type: "v., n.", meaning: "เผชิญหน้า, การเผชิญหน้า" },
    { word: "engage", type: "v.", meaning: "มีส่วนร่วม, หมั้นหมาย" },
    { word: "enhance", type: "v.", meaning: "เพิ่มพูน, ทำให้ดีขึ้น" },
    { word: "enquiry", type: "n.", meaning: "การสอบถาม" },
    { word: "ensure", type: "v.", meaning: "ทำให้มั่นใจ" },
    { word: "enthusiasm", type: "n.", meaning: "ความกระตือรือร้น" },
    { word: "enthusiastic", type: "adj.", meaning: "กระตือรือร้น" },
    { word: "entire", type: "adj.", meaning: "ทั้งหมด" },
    { word: "entirely", type: "adv.", meaning: "ทั้งหมด, โดยสิ้นเชิง" },
    { word: "equal", type: "n.", meaning: "สิ่ง/คนที่เท่ากัน" },
    { word: "establish", type: "v.", meaning: "ก่อตั้ง, สร้าง" },
    { word: "estate", type: "n.", meaning: "อสังหาริมทรัพย์, ที่ดิน" },
    { word: "estimate", type: "v., n.", meaning: "ประมาณการ, การประมาณการ" },
    { word: "ethical", type: "adj.", meaning: "เชิงจริยธรรม" },
    { word: "evaluate", type: "v.", meaning: "ประเมินผล" },
    { word: "even", type: "adj.", meaning: "เท่ากัน, คู่, ราบเรียบ" },
    { word: "evil", type: "adj., n.", meaning: "ชั่วร้าย, ความชั่วร้าย" },
    { word: "examination", type: "n.", meaning: "การตรวจสอบ, การสอบ" },
    { word: "excuse", type: "n., v.", meaning: "ข้อแก้ตัว, ให้อภัย" },
    { word: "executive", type: "n., adj.", meaning: "ผู้บริหาร, เกี่ยวกับการบริหาร" },
    { word: "existence", type: "n.", meaning: "การดำรงอยู่" },
    { word: "expectation", type: "n.", meaning: "ความคาดหวัง" },
    { word: "expense", type: "n.", meaning: "ค่าใช้จ่าย" },
    { word: "exploration", type: "n.", meaning: "การสำรวจ" },
    { word: "expose", type: "v.", meaning: "เปิดเผย, เปิดโปง" },
    { word: "extend", type: "v.", meaning: "ขยาย, ยื่นออกไป" },
    { word: "extent", type: "n.", meaning: "ขอบเขต, ระดับ" },
    { word: "external", type: "adj.", meaning: "ภายนอก" },
    { word: "extraordinary", type: "adj.", meaning: "ไม่ธรรมดา, พิเศษ" },
    { word: "extreme", type: "n.", meaning: "ขั้นสุดขีด" },
    { word: "facility", type: "n.", meaning: "สิ่งอำนวยความสะดวก" },
    { word: "failure", type: "n.", meaning: "ความล้มเหลว" },
    { word: "faith", type: "n.", meaning: "ความศรัทธา" },
    { word: "fault", type: "n.", meaning: "ข้อผิดพลาด, ความผิด" },
    { word: "favour", type: "v.", meaning: "สนับสนุน, โปรดปราน" },
    { word: "feather", type: "n.", meaning: "ขนนก" },
    { word: "fee", type: "n.", meaning: "ค่าธรรมเนียม" },
    { word: "feed", type: "n.", meaning: "อาหารสัตว์" },
    { word: "feedback", type: "n.", meaning: "ผลตอบรับ" },
    { word: "feel", type: "n.", meaning: "ความรู้สึก" },
    { word: "fellow", type: "adj.", meaning: "เพื่อนร่วม, สหาย" },
    { word: "figure", type: "v.", meaning: "คิดคำนวณ, คาดการณ์" },
    { word: "file", type: "v.", meaning: "ยื่น (เอกสาร), จัดเก็บ" },
    { word: "finance", type: "n., v.", meaning: "การเงิน, จัดหาเงินทุน" },
    { word: "finding", type: "n.", meaning: "ผลการวิจัย, การค้นพบ" },
    { word: "firm", type: "n.", meaning: "บริษัท" },
    { word: "fix", type: "n.", meaning: "การแก้ไข (ปัญหา)" },
    { word: "flame", type: "n.", meaning: "เปลวไฟ" },
    { word: "flash", type: "n., v.", meaning: "แสงวาบ, วาบ" },
    { word: "flexible", type: "adj.", meaning: "ยืดหยุ่น" },
    { word: "float", type: "v.", meaning: "ลอย" },
    { word: "fold", type: "n.", meaning: "รอยพับ" },
    { word: "folding", type: "adj.", meaning: "ที่พับได้" },
    { word: "following", type: "prep.", meaning: "หลังจาก" },
    { word: "forgive", type: "v.", meaning: "ให้อภัย" },
    { word: "former", type: "adj.", meaning: "อดีต, ก่อนหน้านี้" },
    { word: "fortune", type: "n.", meaning: "โชคลาภ, ทรัพย์สมบัติ" },
    { word: "forward", type: "adj.", meaning: "ข้างหน้า" },
    { word: "found", type: "v.", meaning: "ก่อตั้ง (รูปอดีตของ find)" },
    { word: "free", type: "v.", meaning: "ทำให้เป็นอิสระ, ปล่อย" },
    { word: "freedom", type: "n.", meaning: "อิสรภาพ" },
    { word: "frequency", type: "n.", meaning: "ความถี่" },
    { word: "fuel", type: "v.", meaning: "เติมเชื้อเพลิง" },
    { word: "fully", type: "adv.", meaning: "อย่างเต็มที่" },
    { word: "function", type: "v.", meaning: "ทำหน้าที่" },
    { word: "fund", type: "n., v.", meaning: "เงินทุน, ให้เงินทุน" },
    { word: "fundamental", type: "adj.", meaning: "พื้นฐาน, มูลฐาน" },
    { word: "funding", type: "n.", meaning: "เงินทุน, การจัดหาเงินทุน" },
    { word: "furthermore", type: "adv.", meaning: "ยิ่งไปกว่านั้น" },
    { word: "gain", type: "v., n.", meaning: "ได้รับ, กำไร" },
    { word: "gang", type: "n.", meaning: "แก๊ง, กลุ่ม" },
    { word: "generate", type: "v.", meaning: "สร้าง, ก่อให้เกิด" },
    { word: "genre", type: "n.", meaning: "ประเภท (งานศิลปะ, ดนตรี)" },
    { word: "govern", type: "v.", meaning: "ปกครอง" },
    { word: "grab", type: "v.", meaning: "คว้า, ฉวย" },
    { word: "grade", type: "v.", meaning: "ให้คะแนน, จัดระดับ" },
    { word: "gradually", type: "adv.", meaning: "ทีละน้อย, ค่อยๆ" },
    { word: "grand", type: "adj.", meaning: "ยิ่งใหญ่, สง่างาม" },
    { word: "grant", type: "v., n.", meaning: "ให้, เงินช่วยเหลือ" },
    { word: "guarantee", type: "v., n.", meaning: "รับประกัน, การรับประกัน" },
    { word: "handle", type: "v., n.", meaning: "จัดการ, มือจับ" },
    { word: "harm", type: "n., v.", meaning: "อันตราย, ทำอันตราย" },
    { word: "harmful", type: "adj.", meaning: "เป็นอันตราย" },
    { word: "hearing", type: "n.", meaning: "การได้ยิน, การพิจารณาคดี" },
    { word: "heaven", type: "n.", meaning: "สวรรค์" },
    { word: "heel", type: "n.", meaning: "ส้นเท้า" },
    { word: "hell", type: "n.", meaning: "นรก" },
    { word: "hesitate", type: "v.", meaning: "ลังเล, รีรอ" },
    { word: "high", type: "n.", meaning: "จุดสูงสุด, ที่สูง" },
    { word: "hire", type: "n.", meaning: "การจ้าง, ค่าจ้าง" },
    { word: "hold", type: "n.", meaning: "การถือ, การควบคุม" },
    { word: "hollow", type: "adj.", meaning: "กลวง" },
    { word: "holy", type: "adj.", meaning: "ศักดิ์สิทธิ์" },
    { word: "honour", type: "n., v.", meaning: "เกียรติ, ให้เกียรติ" },
    { word: "host", type: "v.", meaning: "เป็นเจ้าภาพ" },
    { word: "house", type: "v.", meaning: "จัดเก็บ, ให้ที่พัก" },
    { word: "household", type: "n.", meaning: "ครัวเรือน" },
    { word: "housing", type: "n.", meaning: "ที่อยู่อาศัย" },
    { word: "humorous", type: "adj.", meaning: "ตลก, มีอารมณ์ขัน" },
    { word: "humour", type: "n.", meaning: "อารมณ์ขัน" },
    { word: "hunt", type: "n.", meaning: "การล่าสัตว์" },
    { word: "hunting", type: "n.", meaning: "การล่าสัตว์" },
    { word: "hurt", type: "n.", meaning: "ความเจ็บปวด, การบาดเจ็บ" },
    { word: "ideal", type: "n.", meaning: "อุดมคติ" },
    { word: "illustrate", type: "v.", meaning: "แสดงให้เห็น, อธิบายด้วยภาพ" },
    { word: "illustration", type: "n.", meaning: "ภาพประกอบ, การแสดงให้เห็น" },
    { word: "imagination", type: "n.", meaning: "จินตนาการ" },
    { word: "impatient", type: "adj.", meaning: "ไม่อดทน" },
    { word: "imply", type: "v.", meaning: "บอกเป็นนัย" },
    { word: "impose", type: "v.", meaning: "บังคับใช้, กำหนด" },
    { word: "impress", type: "v.", meaning: "สร้างความประทับใจ" },
    { word: "impressed", type: "adj.", meaning: "รู้สึกประทับใจ" },
    { word: "inch", type: "n.", meaning: "นิ้ว (หน่วยวัด)" },
    { word: "incident", type: "n.", meaning: "เหตุการณ์" },
    { word: "income", type: "n.", meaning: "รายได้" },
    { word: "increasingly", type: "adv.", meaning: "เพิ่มขึ้นเรื่อยๆ" },
    { word: "industrial", type: "adj.", meaning: "ทางอุตสาหกรรม" },
    { word: "infection", type: "n.", meaning: "การติดเชื้อ" },
    { word: "inform", type: "v.", meaning: "แจ้งให้ทราบ" },
    { word: "initial", type: "adj.", meaning: "เริ่มต้น, เบื้องต้น" },
    { word: "initially", type: "adv.", meaning: "ในตอนแรก" },
    { word: "initiative", type: "n.", meaning: "ความคิดริเริ่ม" },
    { word: "inner", type: "adj.", meaning: "ภายใน" },
    { word: "insight", type: "n.", meaning: "ข้อมูลเชิงลึก, ความเข้าใจ" },
    { word: "insist", type: "v.", meaning: "ยืนยัน, ยืนกราน" },
    { word: "inspire", type: "v.", meaning: "สร้างแรงบันดาลใจ" },
    { word: "install", type: "v.", meaning: "ติดตั้ง" },
    { word: "instance", type: "n.", meaning: "ตัวอย่าง" },
    { word: "institute", type: "n.", meaning: "สถาบัน" },
    { word: "institution", type: "n.", meaning: "สถาบัน" },
    { word: "insurance", type: "n.", meaning: "ประกันภัย" },
    { word: "intended", type: "adj.", meaning: "ที่ตั้งใจไว้" },
    { word: "intense", type: "adj.", meaning: "เข้มข้น, รุนแรง" },
    { word: "internal", type: "adj.", meaning: "ภายใน" },
    { word: "interpret", type: "v.", meaning: "ตีความ, แปลความ" },
    { word: "interrupt", type: "v.", meaning: "ขัดจังหวะ" },
    { word: "investigation", type: "n.", meaning: "การสืบสวน" },
    { word: "investment", type: "n.", meaning: "การลงทุน" },
    { word: "issue", type: "v.", meaning: "ออก, เผยแพร่" },
    { word: "joy", type: "n.", meaning: "ความสุข, ความปิติ" },
    { word: "judgement", type: "n.", meaning: "การตัดสิน, คำตัดสิน" },
    { word: "junior", type: "adj.", meaning: "ผู้น้อย, อาวุโสน้อยกว่า" },
    { word: "justice", type: "n.", meaning: "ความยุติธรรม" },
    { word: "justify", type: "v.", meaning: "ให้เหตุผล, พิสูจน์ว่าถูกต้อง" },
    { word: "labour", type: "n.", meaning: "แรงงาน" },
    { word: "landscape", type: "n.", meaning: "ภูมิประเทศ" },
    { word: "largely", type: "adv.", meaning: "ส่วนใหญ่" },
    { word: "latest", type: "n.", meaning: "สิ่งล่าสุด" },
    { word: "launch", type: "v., n.", meaning: "เปิดตัว, การเปิดตัว" },
    { word: "leadership", type: "n.", meaning: "ความเป็นผู้นำ" },
    { word: "league", type: "n.", meaning: "ลีก, สันนิบาต" },
    { word: "lean", type: "v.", meaning: "พิง, เอียง" },
    { word: "leave", type: "n.", meaning: "การลา, การจากไป" },
    { word: "level", type: "v.", meaning: "ทำให้เท่ากัน" },
    { word: "licence", type: "n.", meaning: "ใบอนุญาต" },
    { word: "limited", type: "adj.", meaning: "จำกัด" },
    { word: "line", type: "v.", meaning: "เรียงแถว, ขีดเส้น" },
    { word: "lively", type: "adj.", meaning: "มีชีวิตชีวา" },
    { word: "load", type: "n., v.", meaning: "ภาระ, บรรทุก" },
    { word: "loan", type: "n.", meaning: "เงินกู้" },
    { word: "logical", type: "adj.", meaning: "มีเหตุผล, ตรรกะ" },
    { word: "long-term", type: "adj., adv.", meaning: "ระยะยาว" },
    { word: "loose", type: "adj.", meaning: "หลวม" },
    { word: "lord", type: "n.", meaning: "ท่านลอร์ด, พระเจ้า" },
    { word: "low", type: "n.", meaning: "จุดต่ำสุด" },
    { word: "lower", type: "v.", meaning: "ลดต่ำลง" },
    { word: "lung", type: "n.", meaning: "ปอด" },
    { word: "maintain", type: "v.", meaning: "บำรุงรักษา, รักษาไว้" },
    { word: "majority", type: "n.", meaning: "ส่วนใหญ่, เสียงข้างมาก" },
    { word: "make", type: "n.", meaning: "ยี่ห้อ, การสร้าง" },
    { word: "map", type: "v.", meaning: "ทำแผนที่" },
    { word: "mass", type: "n., adj.", meaning: "มวล, จำนวนมาก" },
    { word: "massive", type: "adj.", meaning: "ใหญ่โต, มหาศาล" },
    { word: "master", type: "n., v.", meaning: "นาย, ปรมาจารย์, เชี่ยวชาญ" },
    { word: "matching", type: "adj.", meaning: "เข้ากัน, ตรงกัน" },
    { word: "material", type: "adj.", meaning: "ทางวัตถุ" },
    { word: "maximum", type: "adj., n.", meaning: "สูงสุด" },
    { word: "means", type: "n.", meaning: "วิธีการ, รายได้" },
    { word: "measurement", type: "n.", meaning: "การวัด, หน่วยวัด" },
    { word: "medium", type: "n.", meaning: "สื่อ, ขนาดกลาง" },
    { word: "melt", type: "v.", meaning: "ละลาย" },
    { word: "military", type: "adj., n.", meaning: "ทางทหาร, กองทัพ" },
    { word: "mineral", type: "n.", meaning: "แร่ธาตุ" },
    { word: "minimum", type: "adj., n.", meaning: "ต่ำสุด" },
    { word: "minister", type: "n.", meaning: "รัฐมนตรี" },
    { word: "minor", type: "adj.", meaning: "เล็กน้อย, ไม่สำคัญ" },
    { word: "minority", type: "n.", meaning: "ชนกลุ่มน้อย" },
    { word: "mission", type: "n.", meaning: "ภารกิจ" },
    { word: "mistake", type: "v.", meaning: "ทำผิด, เข้าใจผิด" },
    { word: "mixed", type: "adj.", meaning: "ผสม" },
    { word: "model", type: "v.", meaning: "เป็นแบบอย่าง, สร้างแบบจำลอง" },
    { word: "modify", type: "v.", meaning: "แก้ไข, ปรับเปลี่ยน" },
    { word: "monitor", type: "n., v.", meaning: "จอภาพ, ตรวจสอบ" },
    { word: "moral", type: "adj., n.", meaning: "ศีลธรรม, คุณธรรม" },
    { word: "motor", type: "n., adj.", meaning: "มอเตอร์, เกี่ยวกับเครื่องยนต์" },
    { word: "mount", type: "v.", meaning: "ขึ้นไป, เพิ่มขึ้น" },
    { word: "multiple", type: "adj.", meaning: "หลากหลาย, หลายส่วน" },
    { word: "multiply", type: "v.", meaning: "คูณ, เพิ่มจำนวน" },
    { word: "mysterious", type: "adj.", meaning: "ลึกลับ" },
    { word: "narrow", type: "v.", meaning: "ทำให้แคบลง" },
    { word: "national", type: "n.", meaning: "พลเมือง" },
    { word: "neat", type: "adj.", meaning: "เรียบร้อย, สะอาด" },
    { word: "negative", type: "n.", meaning: "เชิงลบ, ผลลบ" },
    { word: "nerve", type: "n.", meaning: "เส้นประสาท, ความกล้า" },
    { word: "nevertheless", type: "adv.", meaning: "อย่างไรก็ตาม" },
    { word: "nightmare", type: "n.", meaning: "ฝันร้าย" },
    { word: "notion", type: "n.", meaning: "แนวคิด, ความคิด" },
    { word: "numerous", type: "adj.", meaning: "มากมาย" },
    { word: "obey", type: "v.", meaning: "เชื่อฟัง" },
    { word: "object", type: "v.", meaning: "คัดค้าน" },
    { word: "objective", type: "n., adj.", meaning: "วัตถุประสงค์, เป็นกลาง" },
    { word: "obligation", type: "n.", meaning: "พันธะ, หน้าที่" },
    { word: "observation", type: "n.", meaning: "การสังเกต" },
    { word: "observe", type: "v.", meaning: "สังเกต, ปฏิบัติตาม" },
    { word: "obtain", type: "v.", meaning: "ได้รับ" },
    { word: "occasionally", type: "adv.", meaning: "บางครั้งบางคราว" },
    { word: "offence", type: "n.", meaning: "การกระทำผิด, การรุกราน" },
    { word: "offend", type: "v.", meaning: "ทำให้ขุ่นเคือง, กระทำผิด" },
    { word: "offensive", type: "adj.", meaning: "ก้าวร้าว, น่ารังเกียจ" },
    { word: "official", type: "n.", meaning: "เจ้าหน้าที่" },
    { word: "opening", type: "n.", meaning: "การเปิด, ช่องเปิด, พิธีเปิด" },
    { word: "operate", type: "v.", meaning: "ดำเนินการ, ผ่าตัด" },
    { word: "opponent", type: "n.", meaning: "คู่ต่อสู้" },
    { word: "oppose", type: "v.", meaning: "คัดค้าน" },
    { word: "opposed", type: "adj.", meaning: "ที่คัดค้าน" },
    { word: "opposition", type: "n.", meaning: "ฝ่ายค้าน, การคัดค้าน" },
    { word: "organ", type: "n.", meaning: "อวัยวะ, ออร์แกน" },
    { word: "origin", type: "n.", meaning: "ต้นกำเนิด" },
    { word: "otherwise", type: "adv.", meaning: "มิฉะนั้น, อย่างอื่น" },
    { word: "outcome", type: "n.", meaning: "ผลลัพธ์" },
    { word: "outer", type: "adj.", meaning: "ภายนอก" },
    { word: "outline", type: "n., v.", meaning: "เค้าโครง, ร่างเค้าโครง" },
    { word: "overall", type: "adj., adv.", meaning: "โดยรวม" },
    { word: "owe", type: "v.", meaning: "เป็นหนี้, เป็นหนี้บุญคุณ" },
    { word: "pace", type: "n., v.", meaning: "ก้าว, จังหวะ, เดินไปมา" },
    { word: "package", type: "v.", meaning: "บรรจุหีบห่อ" },
    { word: "panel", type: "n.", meaning: "คณะกรรมการ, แผงควบคุม" },
    { word: "parliament", type: "n.", meaning: "รัฐสภา" },
    { word: "participant", type: "n.", meaning: "ผู้เข้าร่วม" },
    { word: "partly", type: "adv.", meaning: "บางส่วน" },
    { word: "passage", type: "n.", meaning: "ทางเดิน, ข้อความ" },
    { word: "patient", type: "adj.", meaning: "อดทน" },
    { word: "pension", type: "n.", meaning: "บำนาญ" },
    { word: "permanent", type: "adj.", meaning: "ถาวร" },
    { word: "permit", type: "v., n.", meaning: "อนุญาต, ใบอนุญาต" },
    { word: "perspective", type: "n.", meaning: "มุมมอง, ทัศนคติ" },
    { word: "phase", type: "n.", meaning: "ระยะ, ขั้นตอน" },
    { word: "phenomenon", type: "n.", meaning: "ปรากฏการณ์" },
    { word: "philosophy", type: "n.", meaning: "ปรัชญา" },
    { word: "pick", type: "n.", meaning: "การเลือก, การหยิบ" },
    { word: "picture", type: "v.", meaning: "วาดภาพ, จินตนาการ" },
    { word: "pile", type: "n., v.", meaning: "กอง, กองทับ" },
    { word: "pitch", type: "n.", meaning: "สนาม (กีฬา), ระดับเสียง" },
    { word: "plain", type: "adj.", meaning: "ธรรมดา, เรียบง่าย" },
    { word: "plot", type: "v.", meaning: "วางแผน, พล็อตเรื่อง" },
    { word: "plus", type: "adj., n., conj.", meaning: "บวก, เพิ่ม" },
    { word: "pointed", type: "adj.", meaning: "แหลมคม, ชี้ไปที่" },
    { word: "popularity", type: "n.", meaning: "ความนิยม" },
    { word: "pose", type: "v.", meaning: "วางท่า, ก่อให้เกิด" },
    { word: "position", type: "v.", meaning: "วางตำแหน่ง" },
    { word: "positive", type: "n.", meaning: "ผลบวก, สิ่งที่เป็นบวก" },
    { word: "possess", type: "v.", meaning: "ครอบครอง" },
    { word: "potential", type: "adj., n.", meaning: "ศักยภาพ, ที่เป็นไปได้" },
    { word: "power", type: "v.", meaning: "ให้พลังงาน, ควบคุม" },
    { word: "praise", type: "n., v.", meaning: "คำชม, ชมเชย" },
    { word: "pregnant", type: "adj.", meaning: "ตั้งครรภ์" },
    { word: "preparation", type: "n.", meaning: "การเตรียมตัว" },
    { word: "presence", type: "n.", meaning: "การมีอยู่, การปรากฏ" },
    { word: "preserve", type: "v.", meaning: "รักษาไว้, ถนอม" },
    { word: "price", type: "v.", meaning: "ตั้งราคา" },
    { word: "prime", type: "adj.", meaning: "สำคัญที่สุด, ชั้นเยี่ยม" },
    { word: "principle", type: "n.", meaning: "หลักการ" },
    { word: "print", type: "n.", meaning: "สิ่งพิมพ์, รอยพิมพ์" },
    { word: "priority", type: "n.", meaning: "ลำดับความสำคัญ" },
    { word: "privacy", type: "n.", meaning: "ความเป็นส่วนตัว" },
    { word: "procedure", type: "n.", meaning: "ขั้นตอนการปฏิบัติ" },
    { word: "process", type: "v.", meaning: "ดำเนินการ, แปรรูป" },
    { word: "produce", type: "n.", meaning: "ผลิตผล" },
    { word: "professional", type: "n.", meaning: "ผู้ประกอบวิชาชีพ" },
    { word: "progress", type: "v.", meaning: "ก้าวหน้า" },
    { word: "project", type: "v.", meaning: "ฉายภาพ, คาดการณ์" },
    { word: "proof", type: "n.", meaning: "หลักฐาน" },
    { word: "proposal", type: "n.", meaning: "ข้อเสนอ" },
    { word: "propose", type: "v.", meaning: "เสนอ, ขอแต่งงาน" },
    { word: "prospect", type: "n.", meaning: "โอกาส, ความหวัง" },
    { word: "protection", type: "n.", meaning: "การป้องกัน" },
    { word: "psychologist", type: "n.", meaning: "นักจิตวิทยา" },
    { word: "psychology", type: "n.", meaning: "จิตวิทยา" },
    { word: "publication", type: "n.", meaning: "สิ่งพิมพ์, การตีพิมพ์" },
    { word: "pupil", type: "n.", meaning: "นักเรียน (โดยเฉพาะโรงเรียนประถม)" },
    { word: "purchase", type: "n., v.", meaning: "การซื้อ, ซื้อ" },
    { word: "pure", type: "adj.", meaning: "บริสุทธิ์" },
    { word: "pursue", type: "v.", meaning: "ติดตาม, ไล่ตาม" },
    { word: "range", type: "v.", meaning: "ครอบคลุม, มีช่วง" },
    { word: "rank", type: "n., v.", meaning: "อันดับ, จัดอันดับ" },
    { word: "rapid", type: "adj.", meaning: "รวดเร็ว" },
    { word: "rapidly", type: "adv.", meaning: "อย่างรวดเร็ว" },
    { word: "rate", type: "v.", meaning: "ให้คะแนน, ประเมิน" },
    { word: "raw", type: "adj.", meaning: "ดิบ, ยังไม่ผ่านการแปรรูป" },
    { word: "reach", type: "n.", meaning: "การเอื้อมถึง, ระยะที่เอื้อมถึง" },
    { word: "realistic", type: "adj.", meaning: "สมจริง" },
    { word: "reasonable", type: "adj.", meaning: "มีเหตุผล, พอสมควร" },
    { word: "recall", type: "v.", meaning: "ระลึกได้, เรียกคืน" },
    { word: "recover", type: "v.", meaning: "ฟื้นตัว, กู้คืน" },
    { word: "reduction", type: "n.", meaning: "การลดลง" },
    { word: "regard", type: "v., n.", meaning: "พิจารณา, ความเคารพ" },
    { word: "regional", type: "adj.", meaning: "ระดับภูมิภาค" },
    { word: "register", type: "v., n.", meaning: "ลงทะเบียน, ทะเบียน" },
    { word: "regret", type: "v., n.", meaning: "เสียใจ, ความเสียใจ" },
    { word: "regulation", type: "n.", meaning: "ข้อบังคับ, กฎระเบียบ" },
    { word: "relatively", type: "adv.", meaning: "ค่อนข้าง" },
    { word: "relevant", type: "adj.", meaning: "ที่เกี่ยวข้อง" },
    { word: "relief", type: "n.", meaning: "ความโล่งใจ, การบรรเทา" },
    { word: "rely", type: "v.", meaning: "พึ่งพา" },
    { word: "remark", type: "n., v.", meaning: "ข้อสังเกต, สังเกต" },
    { word: "representative", type: "n., adj.", meaning: "ตัวแทน" },
    { word: "reputation", type: "n.", meaning: "ชื่อเสียง" },
    { word: "requirement", type: "n.", meaning: "ข้อกำหนด" },
    { word: "rescue", type: "v., n.", meaning: "ช่วยเหลือ, การช่วยเหลือ" },
    { word: "reserve", type: "n., v.", meaning: "เงินสำรอง, สำรอง, จอง" },
    { word: "resident", type: "n., adj.", meaning: "ผู้อยู่อาศัย, ที่อาศัยอยู่" },
    { word: "resist", type: "v.", meaning: "ต่อต้าน" },
    { word: "resolve", type: "v.", meaning: "แก้ไขปัญหา, ตัดสินใจ" },
    { word: "resort", type: "n.", meaning: "รีสอร์ท, การพึ่งพา" },
    { word: "retain", type: "v.", meaning: "เก็บรักษาไว้" },
    { word: "reveal", type: "v.", meaning: "เปิดเผย" },
    { word: "revolution", type: "n.", meaning: "การปฏิวัติ" },
    { word: "reward", type: "n., v.", meaning: "รางวัล, ให้รางวัล" },
    { word: "rhythm", type: "n.", meaning: "จังหวะ" },
    { word: "rid", type: "v.", meaning: "กำจัด" },
    { word: "root", type: "n.", meaning: "ราก, ต้นกำเนิด" },
    { word: "round", type: "n.", meaning: "รอบ (ในการแข่งขัน)" },
    { word: "routine", type: "adj.", meaning: "เป็นกิจวัตร" },
    { word: "rub", type: "v.", meaning: "ถู, ขัด" },
    { word: "rubber", type: "n., adj.", meaning: "ยาง, ยางลบ" },
    { word: "rural", type: "adj.", meaning: "ชนบท" },
    { word: "rush", type: "v., n.", meaning: "รีบเร่ง, การเร่งรีบ" },
    { word: "sample", type: "v.", meaning: "สุ่มตัวอย่าง, ลองชิม" },
    { word: "satellite", type: "n.", meaning: "ดาวเทียม" },
    { word: "satisfied", type: "adj.", meaning: "พึงพอใจ" },
    { word: "satisfy", type: "v.", meaning: "ทำให้พอใจ" },
    { word: "saving", type: "n.", meaning: "เงินออม" },
    { word: "scale", type: "n.", meaning: "ขนาด, มาตราส่วน" },
    { word: "schedule", type: "v.", meaning: "กำหนดตารางเวลา" },
    { word: "scheme", type: "n.", meaning: "แผนการ, โครงการ" },
    { word: "scream", type: "v., n.", meaning: "กรีดร้อง, เสียงกรีดร้อง" },
    { word: "screen", type: "v.", meaning: "คัดกรอง" },
    { word: "seat", type: "v.", meaning: "ให้นั่ง" },
    { word: "sector", type: "n.", meaning: "ภาคส่วน" },
    { word: "secure", type: "v., adj.", meaning: "ทำให้ปลอดภัย, ปลอดภัย" },
    { word: "seek", type: "v.", meaning: "แสวงหา, ค้นหา" },
    { word: "select", type: "v.", meaning: "เลือก" },
    { word: "selection", type: "n.", meaning: "การเลือก, ตัวเลือก" },
    { word: "self", type: "n.", meaning: "ตัวตน" },
    { word: "senior", type: "adj.", meaning: "อาวุโส" },
    { word: "sense", type: "v.", meaning: "รับรู้, เข้าใจ" },
    { word: "sensitive", type: "adj.", meaning: "ละเอียดอ่อน" },
    { word: "sentence", type: "v.", meaning: "ตัดสินลงโทษ" },
    { word: "sequence", type: "n.", meaning: "ลำดับ" },
    { word: "session", type: "n.", meaning: "ช่วงเวลา, การประชุม" },
    { word: "settle", type: "v.", meaning: "ตัดสินใจ, ชำระ, ตั้งถิ่นฐาน" },
    { word: "severe", type: "adj.", meaning: "รุนแรง" },
    { word: "shade", type: "n.", meaning: "ร่มเงา, สีอ่อน" },
    { word: "shadow", type: "n.", meaning: "เงา" },
    { word: "shallow", type: "adj.", meaning: "ตื้น" },
    { word: "shame", type: "n.", meaning: "ความละอาย" },
    { word: "shape", type: "v.", meaning: "สร้างรูปร่าง, กำหนด" },
    { word: "shelter", type: "n., v.", meaning: "ที่พักพิง, ให้ที่พักพิง" },
    { word: "shift", type: "v.", meaning: "เปลี่ยน, เลื่อน" },
    { word: "ship", type: "v.", meaning: "ส่งทางเรือ" },
    { word: "shock", type: "n., v.", meaning: "อาการตกใจ, ทำให้ตกใจ" },
    { word: "shocked", type: "adj.", meaning: "ตกใจ" },
    { word: "shooting", type: "n.", meaning: "การยิง, การถ่ายทำ" },
    { word: "shot", type: "n.", meaning: "การยิง, ลูกกระสุน, ภาพถ่าย" },
    { word: "significant", type: "adj.", meaning: "สำคัญ, มีนัยสำคัญ" },
    { word: "significantly", type: "adv.", meaning: "อย่างมีนัยสำคัญ" },
    { word: "silence", type: "n.", meaning: "ความเงียบ" },
    { word: "silk", type: "n.", meaning: "ผ้าไหม" },
    { word: "sincere", type: "adj.", meaning: "จริงใจ" },
    { word: "slave", type: "n.", meaning: "ทาส" },
    { word: "slide", type: "v., n.", meaning: "เลื่อน, สไลด์" },
    { word: "slight", type: "adj.", meaning: "เล็กน้อย" },
    { word: "slip", type: "v.", meaning: "ลื่น, เลื่อน" },
    { word: "slope", type: "n., v.", meaning: "ความลาดชัน, ลาดเอียง" },
    { word: "solar", type: "adj.", meaning: "เกี่ยวกับพลังงานแสงอาทิตย์" },
    { word: "somewhat", type: "adv.", meaning: "ค่อนข้าง, บางส่วน" },
    { word: "soul", type: "n.", meaning: "จิตวิญญาณ" },
    { word: "specialist", type: "n., adj.", meaning: "ผู้เชี่ยวชาญ" },
    { word: "species", type: "n.", meaning: "สายพันธุ์" },
    { word: "speed", type: "v.", meaning: "เร่งความเร็ว" },
    { word: "spiritual", type: "adj.", meaning: "ทางจิตวิญญาณ" },
    { word: "split", type: "v., n.", meaning: "แยก, การแยก" },
    { word: "sponsor", type: "v., n.", meaning: "สนับสนุน, ผู้สนับสนุน" },
    { word: "spot", type: "v.", meaning: "พบเห็น, ตรวจจับ" },
    { word: "spread", type: "n.", meaning: "การแพร่กระจาย" },
    { word: "stable", type: "adj.", meaning: "มั่นคง, เสถียร" },
    { word: "stage", type: "v.", meaning: "จัดฉาก, จัดแสดง" },
    { word: "stand", type: "n.", meaning: "จุดยืน, แท่นวาง" },
    { word: "stare", type: "v.", meaning: "จ้องมอง" },
    { word: "status", type: "n.", meaning: "สถานะ" },
    { word: "steady", type: "adj.", meaning: "มั่นคง, สม่ำเสมอ" },
    { word: "steel", type: "n.", meaning: "เหล็กกล้า" },
    { word: "steep", type: "adj.", meaning: "ชัน" },
    { word: "step", type: "v.", meaning: "ก้าวเดิน" },
    { word: "sticky", type: "adj.", meaning: "เหนียว" },
    { word: "stiff", type: "adj.", meaning: "แข็งทื่อ, แข็ง" },
    { word: "stock", type: "n.", meaning: "สต็อก, หุ้น" },
    { word: "stream", type: "n.", meaning: "ลำธาร, กระแส" },
    { word: "stretch", type: "v., n.", meaning: "ยืด, การยืด" },
    { word: "strict", type: "adj.", meaning: "เข้มงวด" },
    { word: "strike", type: "v., n.", meaning: "ตี, การนัดหยุดงาน" },
    { word: "structure", type: "v.", meaning: "จัดโครงสร้าง" },
    { word: "struggle", type: "v., n.", meaning: "ดิ้นรน, การดิ้นรน" },
    { word: "stuff", type: "v.", meaning: "ยัด, บรรจุ" },
    { word: "subject", type: "n.", meaning: "ประธาน (ไวยากรณ์)" },
    { word: "submit", type: "v.", meaning: "ส่ง, ยื่น" },
    { word: "sum", type: "n., v.", meaning: "ผลรวม, รวมยอด" },
    { word: "surgery", type: "n.", meaning: "การผ่าตัด" },
    { word: "surround", type: "v.", meaning: "ล้อมรอบ" },
    { word: "surrounding", type: "adj.", meaning: "ที่อยู่รอบๆ" },
    { word: "survey", type: "v.", meaning: "สำรวจ" },
    { word: "suspect", type: "v., n.", meaning: "สงสัย, ผู้ต้องสงสัย" },
    { word: "swear", type: "v.", meaning: "สาบาน, สบถ" },
    { word: "sweep", type: "v.", meaning: "กวาด" },
    { word: "switch", type: "n.", meaning: "สวิตช์, การเปลี่ยนแปลง" },
    { word: "sympathy", type: "n.", meaning: "ความเห็นอกเห็นใจ" },
    { word: "tale", type: "n.", meaning: "นิทาน, เรื่องเล่า" },
    { word: "tank", type: "n.", meaning: "ถัง, รถถัง" },
    { word: "target", type: "v.", meaning: "ตั้งเป้าหมาย" },
    { word: "tear", type: "v., n.", meaning: "ฉีก, รอยฉีก, น้ำตา" },
    { word: "temporary", type: "adj.", meaning: "ชั่วคราว" },
    { word: "term", type: "v.", meaning: "เรียก, กำหนดคำศัพท์" },
    { word: "therapy", type: "n.", meaning: "การบำบัด" },
    { word: "threat", type: "n.", meaning: "ภัยคุกคาม" },
    { word: "threaten", type: "v.", meaning: "คุกคาม, ขู่" },
    { word: "thus", type: "adv.", meaning: "ดังนั้น, เพราะฉะนั้น" },
    { word: "time", type: "v.", meaning: "จับเวลา, กำหนดเวลา" },
    { word: "title", type: "v.", meaning: "ตั้งชื่อเรื่อง" },
    { word: "tone", type: "n.", meaning: "น้ำเสียง, โทนสี" },
    { word: "tough", type: "adj.", meaning: "ยาก, แข็งแรง, อดทน" },
    { word: "track", type: "v.", meaning: "ติดตาม" },
    { word: "transfer", type: "v., n.", meaning: "โอน, การโอน" },
    { word: "transform", type: "v.", meaning: "เปลี่ยนแปลง, แปลงร่าง" },
    { word: "transition", type: "n.", meaning: "การเปลี่ยนแปลง, การเปลี่ยนผ่าน" },
    { word: "trial", type: "n.", meaning: "การทดลอง, การพิจารณาคดี" },
    { word: "trip", type: "v.", meaning: "สะดุด, ทำให้สะดุด" },
    { word: "tropical", type: "adj.", meaning: "เขตร้อน" },
    { word: "trouble", type: "v.", meaning: "รบกวน, ทำให้เป็นปัญหา" },
    { word: "truly", type: "adv.", meaning: "อย่างแท้จริง" },
    { word: "trust", type: "n., v.", meaning: "ความไว้วางใจ, ไว้วางใจ" },
    { word: "try", type: "n.", meaning: "การลอง, ความพยายาม" },
    { word: "tune", type: "n.", meaning: "ทำนอง, เพลง" },
    { word: "tunnel", type: "n.", meaning: "อุโมงค์" },
    { word: "ultimately", type: "adv.", meaning: "ในที่สุด, ท้ายที่สุด" },
    { word: "unconscious", type: "adj.", meaning: "หมดสติ" },
    { word: "unexpected", type: "adj.", meaning: "ไม่คาดคิด" },
    { word: "unique", type: "adj.", meaning: "เป็นเอกลักษณ์" },
    { word: "universe", type: "n.", meaning: "จักรวาล" },
    { word: "unknown", type: "adj.", meaning: "ไม่เป็นที่รู้จัก" },
    { word: "upper", type: "adj.", meaning: "ส่วนบน" },
    { word: "upwards", type: "adv.", meaning: "ขึ้นไปข้างบน" },
    { word: "urban", type: "adj.", meaning: "ในเมือง" },
    { word: "urge", type: "v.", meaning: "กระตุ้น, เร่งรัด" },
    { word: "value", type: "v.", meaning: "ให้คุณค่า" },
    { word: "vary", type: "v.", meaning: "แตกต่างกันไป" },
    { word: "vast", type: "adj.", meaning: "กว้างใหญ่ไพศาล" },
    { word: "venue", type: "n.", meaning: "สถานที่จัดงาน" },
    { word: "very", type: "adj.", meaning: "มาก (ใช้เน้นคำนาม)" },
    { word: "via", type: "prep.", meaning: "โดยทาง" },
    { word: "victory", type: "n.", meaning: "ชัยชนะ" },
    { word: "violence", type: "n.", meaning: "ความรุนแรง" },
    { word: "virtual", type: "adj.", meaning: "เสมือนจริง" },
    { word: "vision", type: "n.", meaning: "วิสัยทัศน์, การมองเห็น" },
    { word: "visual", type: "adj.", meaning: "เกี่ยวกับการมองเห็น" },
    { word: "vital", type: "adj.", meaning: "สำคัญยิ่ง, จำเป็น" },
    { word: "vitamin", type: "n.", meaning: "วิตามิน" },
    { word: "volume", type: "n.", meaning: "ปริมาณ, ระดับเสียง" },
    { word: "wage", type: "n.", meaning: "ค่าจ้าง" },
    { word: "way", type: "adv.", meaning: "มาก (ใช้เน้น)" },
    { word: "weakness", type: "n.", meaning: "จุดอ่อน, ความอ่อนแอ" },
    { word: "wealth", type: "n.", meaning: "ความมั่งคั่ง" },
    { word: "wealthy", type: "adj.", meaning: "ร่ำรวย" },
    { word: "whereas", type: "conj.", meaning: "ในขณะที่" },
    { word: "wherever", type: "conj.", meaning: "ที่ไหนก็ตาม" },
    { word: "whisper", type: "v., n.", meaning: "กระซิบ, เสียงกระซิบ" },
    { word: "whom", type: "pron.", meaning: "ผู้ซึ่ง (กรรม)" },
    { word: "widely", type: "adv.", meaning: "อย่างกว้างขวาง" },
    { word: "wildlife", type: "n.", meaning: "สัตว์ป่า" },
    { word: "willing", type: "adj.", meaning: "เต็มใจ" },
    { word: "wind", type: "v.", meaning: "ม้วน, พัน" },
    { word: "wire", type: "n.", meaning: "ลวด, สายไฟ" },
    { word: "wise", type: "adj.", meaning: "ฉลาด" },
    { word: "witness", type: "n., v.", meaning: "พยาน, เป็นพยาน" },
    { word: "worse", type: "n.", meaning: "สิ่งที่แย่กว่า" },
    { word: "worst", type: "n.", meaning: "สิ่งที่แย่ที่สุด" },
    { word: "worth", type: "n.", meaning: "มูลค่า, ความคุ้มค่า" },
    { word: "wound", type: "n., v.", meaning: "บาดแผล, ทำให้บาดเจ็บ" },
    { word: "wrap", type: "v.", meaning: "ห่อ" },
    { word: "wrong", type: "n.", meaning: "ความผิด" },
    { word: "yet", type: "conj.", meaning: "แต่" },
    { word: "zone", type: "n.", meaning: "เขต, โซน" },
    { word: "absorb", type: "v.", meaning: "ดูดซับ" },
    { word: "abstract", type: "adj.", meaning: "ที่เป็นนามธรรม" },
    { word: "accent", type: "n.", meaning: "สำเนียง" },
    { word: "accidentally", type: "adv.", meaning: "โดยบังเอิญ" },
    { word: "accommodate", type: "v.", meaning: "รองรับ, จัดหาที่พักให้" },
    { word: "accomplish", type: "v.", meaning: "ทำให้สำเร็จ" },
    { word: "accountant", type: "n.", meaning: "นักบัญชี" },
    { word: "accuracy", type: "n.", meaning: "ความถูกต้องแม่นยำ" },
    { word: "accurately", type: "adv.", meaning: "อย่างถูกต้องแม่นยำ" },
    { word: "acid", type: "n.", meaning: "กรด" },
    { word: "activate", type: "v.", meaning: "กระตุ้น, เปิดใช้งาน" },
    { word: "addiction", type: "n.", meaning: "การเสพติด" },
    { word: "additionally", type: "adv.", meaning: "นอกจากนี้" },
    { word: "adequate", type: "adj.", meaning: "เพียงพอ" },
    { word: "adequately", type: "adv.", meaning: "อย่างเพียงพอ" },
    { word: "adjust", type: "v.", meaning: "ปรับเปลี่ยน" },
    { word: "affordable", type: "adj.", meaning: "ที่สามารถจ่ายได้" },
    { word: "agriculture", type: "n.", meaning: "เกษตรกรรม" },
    { word: "AIDS", type: "n.", meaning: "เอดส์" },
    { word: "alien", type: "n.", meaning: "มนุษย์ต่างดาว, คนต่างด้าว" },
    { word: "alongside", type: "prep.", meaning: "เคียงข้าง, ข้างๆ" },
    { word: "altogether", type: "adv.", meaning: "ทั้งหมด, โดยสิ้นเชิง" },
    { word: "ambulance", type: "n.", meaning: "รถพยาบาล" },
    { word: "amusing", type: "adj.", meaning: "น่าขบขัน" },
    { word: "analyst", type: "n.", meaning: "นักวิเคราะห์" },
    { word: "ancestor", type: "n.", meaning: "บรรพบุรุษ" },
    { word: "animation", type: "n.", meaning: "ภาพเคลื่อนไหว, แอนิเมชัน" },
    { word: "annually", type: "adv.", meaning: "ทุกปี" },
    { word: "anticipate", type: "v.", meaning: "คาดการณ์, คาดหวัง" },
    { word: "anxiety", type: "n.", meaning: "ความวิตกกังวล" },
    { word: "apology", type: "n.", meaning: "คำขอโทษ" },
    { word: "applicant", type: "n.", meaning: "ผู้สมัคร" },
    { word: "appropriately", type: "adv.", meaning: "อย่างเหมาะสม" },
    { word: "arrow", type: "n.", meaning: "ลูกศร" },
    { word: "artwork", type: "n.", meaning: "งานศิลปะ" },
    { word: "aside", type: "adv.", meaning: "ข้างๆ, แยกต่างหาก" },
    { word: "asset", type: "n.", meaning: "สินทรัพย์" },
    { word: "assign", type: "v.", meaning: "มอบหมาย" },
    { word: "assistance", type: "n.", meaning: "ความช่วยเหลือ" },
    { word: "assumption", type: "n.", meaning: "ข้อสมมติฐาน" },
    { word: "assure", type: "v.", meaning: "รับรอง, ทำให้มั่นใจ" },
    { word: "astonishing", type: "adj.", meaning: "น่าประหลาดใจอย่างยิ่ง" },
    { word: "attachment", type: "n.", meaning: "สิ่งที่แนบมา, ความผูกพัน" },
    { word: "auction", type: "n.", meaning: "การประมูล" },
    { word: "audio", type: "adj.", meaning: "เกี่ยวกับเสียง" },
    { word: "automatic", type: "adj.", meaning: "อัตโนมัติ" },
    { word: "automatically", type: "adv.", meaning: "โดยอัตโนมัติ" },
    { word: "awareness", type: "n.", meaning: "การตระหนักรู้" },
    { word: "awkward", type: "adj.", meaning: "น่าอึดอัด, งุ่มง่าม" },
    { word: "badge", type: "n.", meaning: "เข็มกลัด, ป้าย" },
    { word: "balanced", type: "adj.", meaning: "สมดุล" },
    { word: "ballet", type: "n.", meaning: "บัลเลต์" },
    { word: "balloon", type: "n.", meaning: "ลูกโป่ง" },
    { word: "barely", type: "adv.", meaning: "แทบจะไม่" },
    { word: "bargain", type: "n.", meaning: "สินค้าลดราคา, การต่อรอง" },
    { word: "basement", type: "n.", meaning: "ห้องใต้ดิน" },
    { word: "basket", type: "n.", meaning: "ตะกร้า" },
    { word: "bat", type: "n.", meaning: "ค้างคาว, ไม้ตี (เบสบอล)" },
    { word: "beneficial", type: "adj.", meaning: "เป็นประโยชน์" },
    { word: "beside", type: "prep.", meaning: "ข้างๆ" },
    { word: "besides", type: "prep., adv.", meaning: "นอกจากนี้" },
    { word: "bias", type: "n.", meaning: "อคติ" },
    { word: "bid", type: "n., v.", meaning: "การเสนอราคา, เสนอราคา" },
    { word: "biological", type: "adj.", meaning: "ทางชีวภาพ" },
    { word: "blanket", type: "n.", meaning: "ผ้าห่ม" },
    { word: "blow", type: "n.", meaning: "การเป่า, การพัด" },
    { word: "bold", type: "adj.", meaning: "กล้าหาญ, ตัวหนา" },
    { word: "bombing", type: "n.", meaning: "การทิ้งระเบิด" },
    { word: "booking", type: "n.", meaning: "การจอง" },
    { word: "boost", type: "v., n.", meaning: "ส่งเสริม, เพิ่ม, การส่งเสริม" },
    { word: "bound", type: "adj.", meaning: "ผูกมัด, มุ่งหน้าไป" },
    { word: "brick", type: "n.", meaning: "อิฐ" },
    { word: "briefly", type: "adv.", meaning: "สั้นๆ, โดยย่อ" },
    { word: "broadcaster", type: "n.", meaning: "ผู้ประกาศ" },
    { word: "broadly", type: "adv.", meaning: "อย่างกว้างขวาง" },
    { word: "bug", type: "n.", meaning: "แมลง, ข้อผิดพลาด (ในคอมพิวเตอร์)" },
    { word: "cabin", type: "n.", meaning: "กระท่อมไม้ซุง, ห้องโดยสาร" },
    { word: "canal", type: "n.", meaning: "คลอง" },
    { word: "candle", type: "n.", meaning: "เทียน" },
    { word: "carbon", type: "n.", meaning: "คาร์บอน" },
    { word: "casual", type: "adj.", meaning: "ไม่เป็นทางการ, สบายๆ" },
    { word: "cave", type: "n.", meaning: "ถ้ำ" },
    { word: "certainty", type: "n.", meaning: "ความแน่นอน" },
    { word: "certificate", type: "n.", meaning: "ใบรับรอง" },
    { word: "challenging", type: "adj.", meaning: "ท้าทาย" },
    { word: "championship", type: "n.", meaning: "การแข่งขันชิงแชมป์" },
    { word: "charming", type: "adj.", meaning: "มีเสน่ห์" },
    { word: "chase", type: "v., n.", meaning: "ไล่ตาม, การไล่ตาม" },
    { word: "cheek", type: "n.", meaning: "แก้ม" },
    { word: "cheer", type: "v., n.", meaning: "ให้กำลังใจ, เสียงเชียร์" },
    { word: "choir", type: "n.", meaning: "คณะนักร้องประสานเสียง" },
    { word: "chop", type: "v.", meaning: "สับ, ฟัน" },
    { word: "circuit", type: "n.", meaning: "วงจร" },
    { word: "civilization", type: "n.", meaning: "อารยธรรม" },
    { word: "clarify", type: "v.", meaning: "ชี้แจง, ทำให้ชัดเจน" },
    { word: "classify", type: "v.", meaning: "จัดประเภท" },
    { word: "clerk", type: "n.", meaning: "พนักงาน, เสมียน" },
    { word: "cliff", type: "n.", meaning: "หน้าผา" },
    { word: "clinic", type: "n.", meaning: "คลินิก" },
    { word: "clip", type: "n.", meaning: "คลิป, หนีบ" },
    { word: "coincidence", type: "n.", meaning: "เรื่องบังเอิญ" },
    { word: "collector", type: "n.", meaning: "นักสะสม" },
    { word: "colony", type: "n.", meaning: "อาณานิคม" },
    { word: "colourful", type: "adj.", meaning: "มีสีสัน" },
    { word: "comic", type: "adj., n.", meaning: "ตลก, การ์ตูนช่อง" },
    { word: "commander", type: "n.", meaning: "ผู้บังคับบัญชา" },
    { word: "comparative", type: "adj.", meaning: "ที่เปรียบเทียบ" },
    { word: "completion", type: "n.", meaning: "การสำเร็จ, การเสร็จสมบูรณ์" },
    { word: "compose", type: "v.", meaning: "แต่งเพลง, ประกอบด้วย" },
    { word: "composer", type: "n.", meaning: "นักแต่งเพลง" },
    { word: "compound", type: "n.", meaning: "สารประกอบ, บริเวณที่มีรั้วรอบ" },
    { word: "comprehensive", type: "adj.", meaning: "ครอบคลุม, ครบวงจร" },
    { word: "comprise", type: "v.", meaning: "ประกอบด้วย" },
    { word: "compulsory", type: "adj.", meaning: "บังคับ" },
    { word: "concrete", type: "adj., n.", meaning: "ที่เป็นรูปธรรม, คอนกรีต" },
    { word: "confess", type: "v.", meaning: "สารภาพ" },
    { word: "confusion", type: "n.", meaning: "ความสับสน" },
    { word: "consequently", type: "adv.", meaning: "ดังนั้น, ผลที่ตามมาคือ" },
    { word: "conservation", type: "n.", meaning: "การอนุรักษ์" },
    { word: "considerable", type: "adj.", meaning: "สำคัญ, มากมาย" },
    { word: "considerably", type: "adv.", meaning: "อย่างมาก" },
    { word: "consistently", type: "adv.", meaning: "อย่างสม่ำเสมอ" },
    { word: "conspiracy", type: "n.", meaning: "การสมรู้ร่วมคิด" },
    { word: "consult", type: "v.", meaning: "ปรึกษา" },
    { word: "consultant", type: "n.", meaning: "ที่ปรึกษา" },
    { word: "consumption", type: "n.", meaning: "การบริโภค" },
    { word: "controversial", type: "adj.", meaning: "เป็นที่ถกเถียง" },
    { word: "controversy", type: "n.", meaning: "ข้อถกเถียง" },
    { word: "convenience", type: "n.", meaning: "ความสะดวกสบาย" },
    { word: "convention", type: "n.", meaning: "การประชุมใหญ่, ธรรมเนียม" },
    { word: "conventional", type: "adj.", meaning: "ตามแบบแผน, ดั้งเดิม" },
    { word: "convey", type: "v.", meaning: "สื่อความหมาย, ถ่ายทอด" },
    { word: "convincing", type: "adj.", meaning: "น่าเชื่อถือ" },
    { word: "cope", type: "v.", meaning: "รับมือ, จัดการ" },
    { word: "corporation", type: "n.", meaning: "บริษัทขนาดใหญ่" },
    { word: "corridor", type: "n.", meaning: "ทางเดิน" },
    { word: "counter", type: "n.", meaning: "เคาน์เตอร์, โต๊ะยาว" },
    { word: "coverage", type: "n.", meaning: "การรายงานข่าว, ความครอบคลุม" },
    { word: "crack", type: "v., n.", meaning: "แตก, ร้าว, รอยแตก" },
    { word: "craft", type: "n.", meaning: "งานฝีมือ, ยาน" },
    { word: "creativity", type: "n.", meaning: "ความคิดสร้างสรรค์" },
    { word: "critically", type: "adv.", meaning: "อย่างวิกฤต, อย่างสำคัญ" },
    { word: "cruise", type: "n., v.", meaning: "การล่องเรือ, ล่องเรือ" },
    { word: "cue", type: "n.", meaning: "คิว (ไม้คิว), สัญญาณบอก" },
    { word: "curious", type: "adj.", meaning: "อยากรู้อยากเห็น" },
    { word: "curriculum", type: "n.", meaning: "หลักสูตร" },
    { word: "cute", type: "adj.", meaning: "น่ารัก" },
    { word: "dairy", type: "n., adj.", meaning: "ผลิตภัณฑ์นม, เกี่ยวกับนม" },
    { word: "dare", type: "v.", meaning: "กล้า" },
    { word: "darkness", type: "n.", meaning: "ความมืด" },
    { word: "database", type: "n.", meaning: "ฐานข้อมูล" },
    { word: "deadline", type: "n.", meaning: "กำหนดส่งงาน" },
    { word: "deadly", type: "adj.", meaning: "ร้ายแรงถึงตาย" },
    { word: "dealer", type: "n.", meaning: "ตัวแทนจำหน่าย" },
    { word: "deck", type: "n.", meaning: "ดาดฟ้าเรือ, ระเบียง" },
    { word: "defender", type: "n.", meaning: "ผู้พิทักษ์, กองหลัง" },
    { word: "delete", type: "v.", meaning: "ลบ" },
    { word: "democracy", type: "n.", meaning: "ประชาธิปไตย" },
    { word: "democratic", type: "adj.", meaning: "ในระบอบประชาธิปไตย" },
    { word: "demonstration", type: "n.", meaning: "การสาธิต, การเดินขบวน" },
    { word: "depart", type: "v.", meaning: "ออกเดินทาง" },
    { word: "dependent", type: "adj.", meaning: "ขึ้นอยู่กับ" },
    { word: "deposit", type: "n.", meaning: "เงินมัดจำ, เงินฝาก" },
    { word: "depression", type: "n.", meaning: "ภาวะซึมเศร้า, เศรษฐกิจตกต่ำ" },
    { word: "derive", type: "v.", meaning: "ได้มาจาก" },
    { word: "desperately", type: "adv.", meaning: "อย่างสิ้นหวัง" },
    { word: "destruction", type: "n.", meaning: "การทำลาย" },
    { word: "determination", type: "n.", meaning: "ความมุ่งมั่น" },
    { word: "devote", type: "v.", meaning: "อุทิศ" },
    { word: "differ", type: "v.", meaning: "แตกต่าง" },
    { word: "disability", type: "n.", meaning: "ความพิการ" },
    { word: "disabled", type: "adj.", meaning: "พิการ" },
    { word: "disagreement", type: "n.", meaning: "ความไม่เห็นด้วย" },
    { word: "disappoint", type: "v.", meaning: "ทำให้ผิดหวัง" },
    { word: "disappointment", type: "n.", meaning: "ความผิดหวัง" },
    { word: "discourage", type: "v.", meaning: "ทำให้ท้อแท้" },
    { word: "disorder", type: "n.", meaning: "ความผิดปกติ, ความยุ่งเหยิง" },
    { word: "distant", type: "adj.", meaning: "ห่างไกล" },
    { word: "distinct", type: "adj.", meaning: "แตกต่างอย่างชัดเจน" },
    { word: "distinguish", type: "v.", meaning: "แยกแยะ, ทำให้แตกต่าง" },
    { word: "distract", type: "v.", meaning: "ทำให้ไขว้เขว, ทำให้เสียสมาธิ" },
    { word: "disturb", type: "v.", meaning: "รบกวน" },
    { word: "dive", type: "v., n.", meaning: "ดำน้ำ, การดำน้ำ" },
    { word: "diverse", type: "adj.", meaning: "หลากหลาย" },
    { word: "diversity", type: "n.", meaning: "ความหลากหลาย" },
    { word: "divorce", type: "n., v.", meaning: "การหย่าร้าง, หย่าร้าง" },
    { word: "dominant", type: "adj.", meaning: "ที่โดดเด่น, มีอิทธิพล" },
    { word: "donation", type: "n.", meaning: "การบริจาค" },
    { word: "dot", type: "n.", meaning: "จุด" },
    { word: "downtown", type: "n., adj., adv.", meaning: "ใจกลางเมือง (US)" },
    { word: "dramatically", type: "adv.", meaning: "อย่างมาก, อย่างน่าทึ่ง" },
    { word: "drought", type: "n.", meaning: "ความแห้งแล้ง" },
    { word: "dull", type: "adj.", meaning: "น่าเบื่อ, ทื่อ" },
    { word: "dump", type: "v.", meaning: "ทิ้ง, ทิ้งขยะ" },
    { word: "duration", type: "n.", meaning: "ระยะเวลา" },
    { word: "dynamic", type: "adj.", meaning: "มีพลวัต, กระตือรือร้น" },
    { word: "economics", type: "n.", meaning: "เศรษฐศาสตร์" },
    { word: "economist", type: "n.", meaning: "นักเศรษฐศาสตร์" },
    { word: "editorial", type: "adj.", meaning: "กองบรรณาธิการ" },
    { word: "efficiently", type: "adv.", meaning: "อย่างมีประสิทธิภาพ" },
    { word: "elbow", type: "n.", meaning: "ข้อศอก" },
    { word: "electronics", type: "n.", meaning: "อุปกรณ์อิเล็กทรอนิกส์" },
    { word: "elegant", type: "adj.", meaning: "สง่างาม" },
    { word: "elementary", type: "adj.", meaning: "ขั้นพื้นฐาน, ประถม" },
    { word: "eliminate", type: "v.", meaning: "กำจัด" },
    { word: "embrace", type: "v.", meaning: "โอบกอด, ยอมรับ" },
    { word: "emission", type: "n.", meaning: "การปล่อย (ก๊าซ, แสง)" },
    { word: "emotionally", type: "adv.", meaning: "ทางอารมณ์" },
    { word: "empire", type: "n.", meaning: "อาณาจักร" },
    { word: "enjoyable", type: "adj.", meaning: "เพลิดเพลิน" },
    { word: "entertaining", type: "adj.", meaning: "ให้ความบันเทิง" },
    { word: "entrepreneur", type: "n.", meaning: "ผู้ประกอบการ" },
    { word: "envelope", type: "n.", meaning: "ซองจดหมาย" },
    { word: "equip", type: "v.", meaning: "ติดตั้งอุปกรณ์" },
    { word: "equivalent", type: "n., adj.", meaning: "สิ่งที่เท่ากัน, ที่เท่ากัน" },
    { word: "era", type: "n.", meaning: "ยุค" },
    { word: "erupt", type: "v.", meaning: "ระเบิด (ภูเขาไฟ), ปะทุ" },
    { word: "essentially", type: "adv.", meaning: "โดยพื้นฐานแล้ว, โดยเนื้อแท้" },
    { word: "ethic", type: "n.", meaning: "จริยธรรม" },
    { word: "ethnic", type: "adj.", meaning: "ทางชาติพันธุ์" },
    { word: "evaluation", type: "n.", meaning: "การประเมินผล" },
    { word: "evident", type: "adj.", meaning: "ชัดเจน" },
    { word: "evolution", type: "n.", meaning: "วิวัฒนาการ" },
    { word: "evolve", type: "v.", meaning: "วิวัฒนาการ" },
    { word: "exceed", type: "v.", meaning: "เกินกว่า" },
    { word: "exception", type: "n.", meaning: "ข้อยกเว้น" },
    { word: "excessive", type: "adj.", meaning: "มากเกินไป" },
    { word: "exclude", type: "v.", meaning: "ยกเว้น, ไม่รวม" },
    { word: "exhibit", type: "v., n.", meaning: "จัดแสดง, สิ่งที่จัดแสดง" },
    { word: "exit", type: "n.", meaning: "ทางออก" },
    { word: "exotic", type: "adj.", meaning: "แปลกใหม่, มาจากต่างถิ่น" },
    { word: "expansion", type: "n.", meaning: "การขยาย" },
    { word: "expertise", type: "n.", meaning: "ความเชี่ยวชาญ" },
    { word: "exploit", type: "v.", meaning: "ใช้ประโยชน์ (ในทางไม่ดี), หาประโยชน์" },
    { word: "exposure", type: "n.", meaning: "การเปิดเผย, การสัมผัส" },
    { word: "extension", type: "n.", meaning: "ส่วนขยาย, การขยายเวลา" },
    { word: "extensive", type: "adj.", meaning: "กว้างขวาง" },
    { word: "extensively", type: "adv.", meaning: "อย่างกว้างขวาง" },
    { word: "extract", type: "n.", meaning: "สารสกัด, ข้อความที่คัดลอกมา" },
    { word: "fabric", type: "n.", meaning: "ผ้า" },
    { word: "fabulous", type: "adj.", meaning: "เยี่ยมยอด, เหลือเชื่อ" },
    { word: "failed", type: "adj.", meaning: "ที่ล้มเหลว" },
    { word: "fake", type: "adj.", meaning: "ปลอม" },
    { word: "fame", type: "n.", meaning: "ชื่อเสียง" },
    { word: "fantasy", type: "n.", meaning: "จินตนาการ, เรื่องเพ้อฝัน" },
    { word: "fare", type: "n.", meaning: "ค่าโดยสาร" },
    { word: "federal", type: "adj.", meaning: "สหพันธรัฐ" },
    { word: "fever", type: "n.", meaning: "ไข้" },
    { word: "firefighter", type: "n.", meaning: "นักดับเพลิง" },
    { word: "firework", type: "n.", meaning: "ดอกไม้ไฟ" },
    { word: "firm", type: "adj.", meaning: "มั่นคง, แน่นอน" },
    { word: "firmly", type: "adv.", meaning: "อย่างมั่นคง" },
    { word: "flavour", type: "n.", meaning: "รสชาติ" },
    { word: "fond", type: "adj.", meaning: "ชอบ (มาก), หลงรัก" },
    { word: "fool", type: "n.", meaning: "คนโง่" },
    { word: "forbid", type: "v.", meaning: "ห้าม" },
    { word: "forecast", type: "n., v.", meaning: "การพยากรณ์, พยากรณ์" },
    { word: "format", type: "n.", meaning: "รูปแบบ" },
    { word: "formation", type: "n.", meaning: "การก่อตัว, รูปแบบ" },
    { word: "formerly", type: "adv.", meaning: "ในอดีต" },
    { word: "fortunate", type: "adj.", meaning: "โชคดี" },
    { word: "forum", type: "n.", meaning: "เวทีสาธารณะ, ฟอรัม" },
    { word: "fossil", type: "n.", meaning: "ซากดึกดำบรรพ์" },
    { word: "foundation", type: "n.", meaning: "รากฐาน, มูลนิธิ" },
    { word: "founder", type: "n.", meaning: "ผู้ก่อตั้ง" },
    { word: "fraction", type: "n.", meaning: "เศษส่วน" },
    { word: "fragment", type: "n.", meaning: "ชิ้นส่วน" },
    { word: "framework", type: "n.", meaning: "โครงสร้าง, กรอบการทำงาน" },
    { word: "fraud", type: "n.", meaning: "การฉ้อโกง" },
    { word: "freely", type: "adv.", meaning: "อย่างอิสระ" },
    { word: "frequent", type: "adj.", meaning: "บ่อยครั้ง" },
    { word: "fulfil", type: "v.", meaning: "เติมเต็ม, ทำให้สำเร็จ" },
    { word: "full-time", type: "adj./adv.", meaning: "เต็มเวลา" },
    { word: "fundamentally", type: "adv.", meaning: "โดยพื้นฐานแล้ว" },
    { word: "furious", type: "adj.", meaning: "โกรธจัด" },
    { word: "gaming", type: "n.", meaning: "การเล่นเกม" },
    { word: "gay", type: "adj.", meaning: "เกย์, ร่าเริง" },
    { word: "gender", type: "n.", meaning: "เพศ" },
    { word: "gene", type: "n.", meaning: "ยีน" },
    { word: "genetic", type: "adj.", meaning: "ทางพันธุกรรม" },
    { word: "genius", type: "n.", meaning: "อัจฉริยะ" },
    { word: "genuine", type: "adj.", meaning: "แท้จริง, จริงใจ" },
    { word: "genuinely", type: "adv.", meaning: "อย่างแท้จริง" },
    { word: "gesture", type: "n.", meaning: "ท่าทาง" },
    { word: "gig", type: "n.", meaning: "งานแสดงดนตรี, งานชั่วคราว" },
    { word: "globalization", type: "n.", meaning: "โลกาภิวัตน์" },
    { word: "globe", type: "n.", meaning: "ลูกโลก" },
    { word: "golden", type: "adj.", meaning: "สีทอง, ยอดเยี่ยม" },
    { word: "goodness", type: "n.", meaning: "ความดีงาม" },
    { word: "gorgeous", type: "adj.", meaning: "สวยงามมาก" },
    { word: "governor", type: "n.", meaning: "ผู้ว่าการ" },
    { word: "graphic", type: "adj.", meaning: "เกี่ยวกับภาพ" },
    { word: "graphics", type: "n.", meaning: "ภาพกราฟิก" },
    { word: "greatly", type: "adv.", meaning: "อย่างมาก" },
    { word: "greenhouse", type: "n.", meaning: "เรือนกระจก" },
    { word: "grocery", type: "n.", meaning: "ร้านขายของชำ" },
    { word: "guideline", type: "n.", meaning: "แนวทาง" },
    { word: "habitat", type: "n.", meaning: "ที่อยู่อาศัย (ของสัตว์)" },
    { word: "harbour", type: "n.", meaning: "ท่าเรือ" },
    { word: "headquarters", type: "n.", meaning: "สำนักงานใหญ่" },
    { word: "heal", type: "v.", meaning: "รักษาให้หาย" },
    { word: "healthcare", type: "n.", meaning: "การดูแลสุขภาพ" },
    { word: "helmet", type: "n.", meaning: "หมวกกันน็อค" },
    { word: "hence", type: "adv.", meaning: "ดังนั้น, ด้วยเหตุนี้" },
    { word: "herb", type: "n.", meaning: "สมุนไพร" },
    { word: "hidden", type: "adj.", meaning: "ที่ซ่อนอยู่" },
    { word: "highway", type: "n.", meaning: "ทางหลวง" },
    { word: "hilarious", type: "adj.", meaning: "ตลกมาก" },
    { word: "hip", type: "n.", meaning: "สะโพก" },
    { word: "historian", type: "n.", meaning: "นักประวัติศาสตร์" },
    { word: "homeless", type: "adj.", meaning: "ไร้บ้าน" },
    { word: "honesty", type: "n.", meaning: "ความซื่อสัตย์" },
    { word: "hook", type: "n.", meaning: "ตะขอ" },
    { word: "hopefully", type: "adv.", meaning: "หวังว่า" },
    { word: "hunger", type: "n.", meaning: "ความหิวโหย" },
    { word: "hypothesis", type: "n.", meaning: "สมมติฐาน" },
    { word: "icon", type: "n.", meaning: "ไอคอน, สัญลักษณ์" },
    { word: "ID", type: "n.", meaning: "บัตรประจำตัว" },
    { word: "identical", type: "adj.", meaning: "เหมือนกันทุกประการ" },
    { word: "illusion", type: "n.", meaning: "ภาพลวงตา" },
    { word: "immigration", type: "n.", meaning: "การอพยพเข้า" },
    { word: "immune", type: "adj.", meaning: "มีภูมิคุ้มกัน" },
    { word: "implement", type: "v.", meaning: "นำไปปฏิบัติ, ทำให้เกิดผล" },
    { word: "implication", type: "n.", meaning: "ผลกระทบ, นัยยะ" },
    { word: "incentive", type: "n.", meaning: "สิ่งจูงใจ" },
    { word: "incorporate", type: "v.", meaning: "รวมเข้าด้วยกัน" },
    { word: "incorrect", type: "adj.", meaning: "ไม่ถูกต้อง" },
    { word: "independence", type: "n.", meaning: "อิสรภาพ, ความเป็นอิสระ" },
    { word: "index", type: "n.", meaning: "ดัชนี" },
    { word: "indication", type: "n.", meaning: "การบ่งชี้, สัญญาณ" },
    { word: "inevitable", type: "adj.", meaning: "หลีกเลี่ยงไม่ได้" },
    { word: "inevitably", type: "adv.", meaning: "อย่างหลีกเลี่ยงไม่ได้" },
    { word: "infer", type: "v.", meaning: "อนุมาน" },
    { word: "inflation", type: "n.", meaning: "ภาวะเงินเฟ้อ" },
    { word: "info", type: "n.", meaning: "ข้อมูล (ไม่เป็นทางการ)" },
    { word: "infrastructure", type: "n.", meaning: "โครงสร้างพื้นฐาน" },
    { word: "inhabitant", type: "n.", meaning: "ผู้อยู่อาศัย" },
    { word: "inherit", type: "v.", meaning: "สืบทอด, รับมรดก" },
    { word: "ink", type: "n.", meaning: "หมึก" },
    { word: "innovation", type: "n.", meaning: "นวัตกรรม" },
    { word: "innovative", type: "adj.", meaning: "นวัตกรรม, สร้างสรรค์" },
    { word: "input", type: "n.", meaning: "ข้อมูลเข้า, การป้อนข้อมูล" },
    { word: "insert", type: "v.", meaning: "ใส่, สอด" },
    { word: "inspector", type: "n.", meaning: "ผู้ตรวจสอบ" },
    { word: "installation", type: "n.", meaning: "การติดตั้ง" },
    { word: "instant", type: "adj.", meaning: "ทันทีทันใด" },
    { word: "instantly", type: "adv.", meaning: "ในทันที" },
    { word: "integrate", type: "v.", meaning: "รวมเข้าด้วยกัน" },
    { word: "intellectual", type: "adj.", meaning: "ทางปัญญา" },
    { word: "interact", type: "v.", meaning: "มีปฏิสัมพันธ์" },
    { word: "interaction", type: "n.", meaning: "ปฏิสัมพันธ์" },
    { word: "interpretation", type: "n.", meaning: "การตีความ" },
    { word: "interval", type: "n.", meaning: "ช่วงเวลา, ช่วงพัก" },
    { word: "invade", type: "v.", meaning: "บุกรุก" },
    { word: "invasion", type: "n.", meaning: "การบุกรุก" },
    { word: "investor", type: "n.", meaning: "นักลงทุน" },
    { word: "isolate", type: "v.", meaning: "แยกตัวออกไป" },
    { word: "isolated", type: "adj.", meaning: "โดดเดี่ยว" },
    { word: "jail", type: "n., v.", meaning: "คุก, คุมขัง" },
    { word: "jet", type: "n.", meaning: "เครื่องบินเจ็ต" },
    { word: "joint", type: "adj., n.", meaning: "ร่วมกัน, ข้อต่อ" },
    { word: "journalism", type: "n.", meaning: "วารสารศาสตร์" },
    { word: "jury", type: "n.", meaning: "คณะลูกขุน" },
    { word: "kit", type: "n.", meaning: "ชุดอุปกรณ์" },
    { word: "ladder", type: "n.", meaning: "บันได (แบบพกพา)" },
    { word: "landing", type: "n.", meaning: "การลงจอด" },
    { word: "lane", type: "n.", meaning: "เลน (ถนน), ช่องทาง" },
    { word: "lately", type: "adv.", meaning: "เมื่อไม่นานมานี้" },
    { word: "leaflet", type: "n.", meaning: "ใบปลิว" },
    { word: "legend", type: "n.", meaning: "ตำนาน" },
    { word: "lens", type: "n.", meaning: "เลนส์" },
    { word: "lifetime", type: "n.", meaning: "ช่วงชีวิต" },
    { word: "lighting", type: "n.", meaning: "แสงสว่าง" },
    { word: "likewise", type: "adv.", meaning: "เช่นเดียวกัน" },
    { word: "limitation", type: "n.", meaning: "ข้อจำกัด" },
    { word: "literally", type: "adv.", meaning: "ตามตัวอักษร, อย่างแท้จริง" },
    { word: "literary", type: "adj.", meaning: "ทางวรรณกรรม" },
    { word: "litre", type: "n.", meaning: "ลิตร" },
    { word: "litter", type: "n.", meaning: "ขยะมูลฝอย" },
    { word: "logo", type: "n.", meaning: "โลโก้" },
    { word: "lottery", type: "n.", meaning: "ลอตเตอรี่" },
    { word: "loyal", type: "adj.", meaning: "ซื่อสัตย์" },
    { word: "lyric", type: "n.", meaning: "เนื้อเพลง" },
    { word: "magnificent", type: "adj.", meaning: "งดงาม, สง่างาม" },
    { word: "make-up", type: "n.", meaning: "เครื่องสำอาง, การแต่งหน้า" },
    { word: "making", type: "n.", meaning: "การสร้าง, การผลิต" },
    { word: "manufacture", type: "v.", meaning: "ผลิต" },
    { word: "manufacturing", type: "n.", meaning: "การผลิต" },
    { word: "marathon", type: "n.", meaning: "มาราธอน" },
    { word: "margin", type: "n.", meaning: "ขอบ, ส่วนต่าง" },
    { word: "marker", type: "n.", meaning: "ปากกาเมจิก, เครื่องหมาย" },
    { word: "martial", type: "adj.", meaning: "ทางทหาร, การต่อสู้" },
    { word: "mate", type: "n., v.", meaning: "เพื่อน, คู่, จับคู่" },
    { word: "mayor", type: "n.", meaning: "นายกเทศมนตรี" },
    { word: "mechanic", type: "n.", meaning: "ช่างเครื่อง" },
    { word: "mechanical", type: "adj.", meaning: "เกี่ยวกับเครื่องจักรกล" },
    { word: "mechanism", type: "n.", meaning: "กลไก" },
    { word: "medal", type: "n.", meaning: "เหรียญรางวัล" },
    { word: "medication", type: "n.", meaning: "ยา" },
    { word: "membership", type: "n.", meaning: "ความเป็นสมาชิก" },
    { word: "memorable", type: "adj.", meaning: "น่าจดจำ" },
    { word: "metaphor", type: "n.", meaning: "อุปลักษณ์" },
    { word: "miner", type: "n.", meaning: "คนงานเหมือง" },
    { word: "miserable", type: "adj.", meaning: "น่าสงสาร, ทุกข์ใจ" },
    { word: "mode", type: "n.", meaning: "โหมด, วิธี" },
    { word: "modest", type: "adj.", meaning: "ถ่อมตัว, ไม่มาก" },
    { word: "monster", type: "n.", meaning: "สัตว์ประหลาด" },
    { word: "monthly", type: "adj.", meaning: "รายเดือน" },
    { word: "monument", type: "n.", meaning: "อนุสาวรีย์" },
    { word: "moreover", type: "adv.", meaning: "ยิ่งไปกว่านั้น" },
    { word: "mortgage", type: "n.", meaning: "การจำนอง" },
    { word: "mosque", type: "n.", meaning: "มัสยิด" },
    { word: "motion", type: "n.", meaning: "การเคลื่อนไหว" },
    { word: "motivate", type: "v.", meaning: "กระตุ้น" },
    { word: "motivation", type: "n.", meaning: "แรงจูงใจ" },
    { word: "moving", type: "adj.", meaning: "น่าประทับใจ, เคลื่อนไหว" },
    { word: "myth", type: "n.", meaning: "ตำนาน, ความเชื่อผิดๆ" },
    { word: "naked", type: "adj.", meaning: "เปลือย" },
    { word: "nasty", type: "adj.", meaning: "น่ารังเกียจ, น่าขยะแขยง" },
    { word: "navigation", type: "n.", meaning: "การนำทาง" },
    { word: "nearby", type: "adj., adv.", meaning: "ใกล้เคียง" },
    { word: "necessity", type: "n.", meaning: "ความจำเป็น" },
    { word: "negotiate", type: "v.", meaning: "เจรจา" },
    { word: "negotiation", type: "n.", meaning: "การเจรจา" },
    { word: "neutral", type: "adj.", meaning: "เป็นกลาง" },
    { word: "newly", type: "adv.", meaning: "เพิ่งจะ, ใหม่ๆ" },
    { word: "norm", type: "n.", meaning: "บรรทัดฐาน" },
    { word: "notebook", type: "n.", meaning: "สมุดบันทึก" },
    { word: "novelist", type: "n.", meaning: "นักเขียนนวนิยาย" },
    { word: "nowadays", type: "adv.", meaning: "ทุกวันนี้" },
    { word: "nursing", type: "adj.", meaning: "เกี่ยวกับการพยาบาล" },
    { word: "nutrition", type: "n.", meaning: "โภชนาการ" },
    { word: "obesity", type: "n.", meaning: "โรคอ้วน" },
    { word: "observer", type: "n.", meaning: "ผู้สังเกตการณ์" },
    { word: "obstacle", type: "n.", meaning: "อุปสรรค" },
    { word: "occupation", type: "n.", meaning: "อาชีพ" },
    { word: "occupy", type: "v.", meaning: "ครอบครอง, ยึดครอง" },
    { word: "offender", type: "n.", meaning: "ผู้กระทำผิด" },
    { word: "ongoing", type: "adj.", meaning: "ที่กำลังดำเนินอยู่" },
    { word: "openly", type: "adv.", meaning: "อย่างเปิดเผย" },
    { word: "opera", type: "n.", meaning: "โอเปร่า" },
    { word: "operator", type: "n.", meaning: "ผู้ปฏิบัติงาน, พนักงานโทรศัพท์" },
    { word: "optimistic", type: "adj.", meaning: "มองโลกในแง่ดี" },
    { word: "orchestra", type: "n.", meaning: "วงออร์เคสตรา" },
    { word: "organic", type: "adj.", meaning: "ออร์แกนิก, อินทรีย์" },
    { word: "outfit", type: "n.", meaning: "ชุดเสื้อผ้า" },
    { word: "output", type: "n.", meaning: "ผลผลิต, เอาต์พุต" },
    { word: "outstanding", type: "adj.", meaning: "โดดเด่น, ยอดเยี่ยม" },
    { word: "overcome", type: "v.", meaning: "เอาชนะ" },
    { word: "overnight", type: "adv.", meaning: "ค้างคืน" },
    { word: "overseas", type: "adv., adj.", meaning: "ในต่างประเทศ" },
    { word: "ownership", type: "n.", meaning: "ความเป็นเจ้าของ" },
    { word: "oxygen", type: "n.", meaning: "ออกซิเจน" },
    { word: "packet", type: "n.", meaning: "ห่อเล็กๆ, ซอง" },
    { word: "palm", type: "n.", meaning: "ฝ่ามือ, ต้นปาล์ม" },
    { word: "panic", type: "n.", meaning: "ความตื่นตระหนก" },
    { word: "parade", type: "n.", meaning: "ขบวนพาเหรด" },
    { word: "parallel", type: "adj., n.", meaning: "ขนาน, สิ่งที่ขนานกัน" },
    { word: "participation", type: "n.", meaning: "การมีส่วนร่วม" },
    { word: "partnership", type: "n.", meaning: "การเป็นหุ้นส่วน" },
    { word: "part-time", type: "adj./adv.", meaning: "ไม่เต็มเวลา" },
    { word: "passionate", type: "adj.", meaning: "กระตือรือร้น, หลงใหล" },
    { word: "password", type: "n.", meaning: "รหัสผ่าน" },
    { word: "patience", type: "n.", meaning: "ความอดทน" },
    { word: "pause", type: "v., n.", meaning: "หยุดชั่วคราว, การหยุดชั่วคราว" },
    { word: "peer", type: "n.", meaning: "เพื่อนร่วมรุ่น, ผู้ที่เท่าเทียมกัน" },
    { word: "penalty", type: "n.", meaning: "บทลงโทษ" },
    { word: "perceive", type: "v.", meaning: "รับรู้" },
    { word: "perception", type: "n.", meaning: "การรับรู้" },
    { word: "permanently", type: "adv.", meaning: "อย่างถาวร" },
    { word: "pill", type: "n.", meaning: "ยาเม็ด" },
    { word: "pity", type: "n.", meaning: "ความสงสาร" },
    { word: "placement", type: "n.", meaning: "การจัดวาง, ตำแหน่งงาน" },
    { word: "portion", type: "n.", meaning: "ส่วนแบ่ง, ส่วนหนึ่ง" },
    { word: "potentially", type: "adv.", meaning: "อาจเป็นไปได้" },
    { word: "precede", type: "v.", meaning: "มาก่อน" },
    { word: "precious", type: "adj.", meaning: "ล้ำค่า" },
    { word: "precise", type: "adj.", meaning: "แม่นยำ" },
    { word: "precisely", type: "adv.", meaning: "อย่างแม่นยำ" },
    { word: "predictable", type: "adj.", meaning: "ที่คาดการณ์ได้" },
    { word: "preference", type: "n.", meaning: "ความพึงพอใจ, สิ่งที่ชอบมากกว่า" },
    { word: "pride", type: "n.", meaning: "ความภาคภูมิใจ" },
    { word: "primarily", type: "adv.", meaning: "ส่วนใหญ่, เป็นหลัก" },
    { word: "principal", type: "adj.", meaning: "สำคัญที่สุด, หลัก" },
    { word: "prior", type: "adj.", meaning: "มาก่อน, สำคัญกว่า" },
    { word: "probability", type: "n.", meaning: "ความน่าจะเป็น" },
    { word: "probable", type: "adj.", meaning: "น่าจะเป็นไปได้" },
    { word: "proceed", type: "v.", meaning: "ดำเนินต่อไป" },
    { word: "programming", type: "n.", meaning: "การเขียนโปรแกรม" },
    { word: "progressive", type: "adj.", meaning: "ก้าวหน้า" },
    { word: "prohibit", type: "v.", meaning: "ห้าม" },
    { word: "promising", type: "adj.", meaning: "มีแววดี, มีแนวโน้มที่ดี" },
    { word: "promotion", type: "n.", meaning: "การส่งเสริม, การเลื่อนตำแหน่ง" },
    { word: "prompt", type: "v.", meaning: "กระตุ้น, เตือน" },
    { word: "proportion", type: "n.", meaning: "สัดส่วน" },
    { word: "protein", type: "n.", meaning: "โปรตีน" },
    { word: "protester", type: "n.", meaning: "ผู้ประท้วง" },
    { word: "psychological", type: "adj.", meaning: "ทางจิตวิทยา" },
    { word: "publicity", type: "n.", meaning: "การประชาสัมพันธ์" },
    { word: "publishing", type: "n.", meaning: "การตีพิมพ์" },
    { word: "punk", type: "n.", meaning: "พังก์ (แนวเพลง/แฟชั่น)" },
    { word: "purely", type: "adv.", meaning: "อย่างบริสุทธิ์ใจ, อย่างแท้จริง" },
    { word: "pursuit", type: "n.", meaning: "การไล่ตาม, การแสวงหา" },
    { word: "puzzle", type: "n.", meaning: "ปริศนา" },
    { word: "questionnaire", type: "n.", meaning: "แบบสอบถาม" },
    { word: "racial", type: "adj.", meaning: "เกี่ยวกับเชื้อชาติ" },
    { word: "racism", type: "n.", meaning: "การเหยียดเชื้อชาติ" },
    { word: "racist", type: "adj., n.", meaning: "ที่เหยียดเชื้อชาติ, ผู้เหยียดเชื้อชาติ" },
    { word: "radiation", type: "n.", meaning: "รังสี" },
    { word: "rail", type: "n.", meaning: "ราว, รางรถไฟ" },
    { word: "random", type: "adj.", meaning: "สุ่ม" },
    { word: "rat", type: "n.", meaning: "หนู (ตัวใหญ่)" },
    { word: "rating", type: "n.", meaning: "การจัดอันดับ, คะแนน" },
    { word: "reasonably", type: "adv.", meaning: "อย่างมีเหตุผล, อย่างพอสมควร" },
    { word: "rebuild", type: "v.", meaning: "สร้างใหม่" },
    { word: "receiver", type: "n.", meaning: "ผู้รับ, เครื่องรับ" },
    { word: "recession", type: "n.", meaning: "ภาวะเศรษฐกิจถดถอย" },
    { word: "reckon", type: "v.", meaning: "คิดว่า, ประมาณการ" },
    { word: "recognition", type: "n.", meaning: "การจดจำ, การยอมรับ" },
    { word: "recovery", type: "n.", meaning: "การฟื้นตัว" },
    { word: "recruit", type: "v., n.", meaning: "รับสมัคร, ผู้รับสมัคร" },
    { word: "recruitment", type: "n.", meaning: "การรับสมัคร" },
    { word: "referee", type: "n.", meaning: "ผู้ตัดสิน (กีฬา)" },
    { word: "refugee", type: "n.", meaning: "ผู้ลี้ภัย" },
    { word: "registration", type: "n.", meaning: "การลงทะเบียน" },
    { word: "regulate", type: "v.", meaning: "ควบคุม, กำกับ" },
    { word: "reinforce", type: "v.", meaning: "เสริมกำลัง, ตอกย้ำ" },
    { word: "relieve", type: "v.", meaning: "บรรเทา, ทำให้โล่งใจ" },
    { word: "relieved", type: "adj.", meaning: "โล่งใจ" },
    { word: "remarkable", type: "adj.", meaning: "น่าทึ่ง, น่าสังเกต" },
    { word: "remarkably", type: "adv.", meaning: "อย่างน่าทึ่ง" },
    { word: "reporting", type: "n.", meaning: "การรายงานข่าว" },
    { word: "resign", type: "v.", meaning: "ลาออก" },
    { word: "resolution", type: "n.", meaning: "มติ, การแก้ปัญหา" },
    { word: "restore", type: "v.", meaning: "ฟื้นฟู, ซ่อมแซม" },
    { word: "restrict", type: "v.", meaning: "จำกัด" },
    { word: "restriction", type: "n.", meaning: "ข้อจำกัด" },
    { word: "retail", type: "n.", meaning: "การค้าปลีก" },
    { word: "retirement", type: "n.", meaning: "การเกษียณอายุ" },
    { word: "revenue", type: "n.", meaning: "รายได้" },
    { word: "revision", type: "n.", meaning: "การทบทวน, การแก้ไข" },
    { word: "ridiculous", type: "adj.", meaning: "ไร้สาระ, น่าขัน" },
    { word: "risky", type: "adj.", meaning: "เสี่ยง" },
    { word: "rival", type: "n., adj.", meaning: "คู่แข่ง" },
    { word: "rob", type: "v.", meaning: "ปล้น" },
    { word: "robbery", type: "n.", meaning: "การปล้น" },
    { word: "rocket", type: "n.", meaning: "จรวด" },
    { word: "romance", type: "n.", meaning: "ความรัก, เรื่องโรแมนติก" },
    { word: "rose", type: "n.", meaning: "ดอกกุหลาบ" },
    { word: "roughly", type: "adv.", meaning: "อย่างคร่าวๆ, โดยประมาณ" },
    { word: "ruin", type: "v., n.", meaning: "ทำลาย, ซากปรักหักพัง" },
    { word: "satisfaction", type: "n.", meaning: "ความพึงพอใจ" },
    { word: "scandal", type: "n.", meaning: "เรื่องอื้อฉาว" },
    { word: "scare", type: "v., n.", meaning: "ทำให้กลัว, ความกลัว" },
    { word: "scenario", type: "n.", meaning: "สถานการณ์, สถานการณ์จำลอง" },
    { word: "scholar", type: "n.", meaning: "นักวิชาการ" },
    { word: "scholarship", type: "n.", meaning: "ทุนการศึกษา" },
    { word: "scratch", type: "v., n.", meaning: "เกา, ขีดข่วน, รอยขีดข่วน" },
    { word: "screening", type: "n.", meaning: "การฉาย, การคัดกรอง" },
    { word: "seeker", type: "n.", meaning: "ผู้ค้นหา" },
    { word: "seminar", type: "n.", meaning: "สัมมนา" },
    { word: "settler", type: "n.", meaning: "ผู้ตั้งถิ่นฐาน" },
    { word: "severely", type: "adv.", meaning: "อย่างรุนแรง" },
    { word: "sexy", type: "adj.", meaning: "เซ็กซี่" },
    { word: "shaped", type: "adj.", meaning: "ที่มีรูปร่าง" },
    { word: "shocking", type: "adj.", meaning: "น่าตกใจ" },
    { word: "shore", type: "n.", meaning: "ชายฝั่ง" },
    { word: "shortage", type: "n.", meaning: "การขาดแคลน" },
    { word: "shortly", type: "adv.", meaning: "ในไม่ช้า" },
    { word: "short-term", type: "adj.", meaning: "ระยะสั้น" },
    { word: "sibling", type: "n.", meaning: "พี่น้อง" },
    { word: "signature", type: "n.", meaning: "ลายเซ็น" },
    { word: "significance", type: "n.", meaning: "ความสำคัญ" },
    { word: "skilled", type: "adj.", meaning: "มีทักษะ" },
    { word: "skull", type: "n.", meaning: "กะโหลกศีรษะ" },
    { word: "slogan", type: "n.", meaning: "คำขวัญ" },
    { word: "so-called", type: "adj.", meaning: "ที่เรียกกันว่า" },
    { word: "somehow", type: "adv.", meaning: "ด้วยวิธีใดวิธีหนึ่ง" },
    { word: "sometime", type: "adv.", meaning: "บางครั้ง, สักวันหนึ่ง" },
    { word: "sophisticated", type: "adj.", meaning: "ซับซ้อน, มีความรู้" },
    { word: "spare", type: "adj.", meaning: "สำรอง, ว่าง" },
    { word: "specialize", type: "v.", meaning: "เชี่ยวชาญ" },
    { word: "specify", type: "v.", meaning: "ระบุ" },
    { word: "spectacular", type: "adj.", meaning: "น่าตื่นตาตื่นใจ" },
    { word: "spectator", type: "n.", meaning: "ผู้ชม (กีฬา)" },
    { word: "speculate", type: "v.", meaning: "คาดการณ์, เก็งกำไร" },
    { word: "speculation", type: "n.", meaning: "การคาดการณ์" },
    { word: "spice", type: "n.", meaning: "เครื่องเทศ" },
    { word: "spill", type: "v.", meaning: "หก, ทำหก" },
    { word: "spite", type: "n.", meaning: "ความมุ่งร้าย" },
    { word: "spoil", type: "v.", meaning: "ทำให้เสีย, ตามใจ" },
    { word: "spokesman", type: "n.", meaning: "โฆษก (ชาย)" },
    { word: "spokesperson", type: "n.", meaning: "โฆษก" },
    { word: "spokeswoman", type: "n.", meaning: "โฆษก (หญิง)" },
    { word: "sponsorship", type: "n.", meaning: "การเป็นสปอนเซอร์" },
    { word: "sporting", type: "adj.", meaning: "เกี่ยวกับการกีฬา" },
    { word: "stall", type: "n.", meaning: "แผงลอย, คอก" },
    { word: "stance", type: "n.", meaning: "จุดยืน" },
    { word: "starve", type: "v.", meaning: "อดอยาก" },
    { word: "steadily", type: "adv.", meaning: "อย่างสม่ำเสมอ" },
    { word: "steam", type: "n.", meaning: "ไอน้ำ" },
    { word: "stimulate", type: "v.", meaning: "กระตุ้น" },
    { word: "strengthen", type: "v.", meaning: "ทำให้แข็งแกร่งขึ้น" },
    { word: "strictly", type: "adv.", meaning: "อย่างเคร่งครัด" },
    { word: "stroke", type: "n.", meaning: "การลูบ, โรคหลอดเลือดสมอง" },
    { word: "stunning", type: "adj.", meaning: "สวยงามน่าทึ่ง" },
    { word: "subsequent", type: "adj.", meaning: "ที่ตามมาภายหลัง" },
    { word: "subsequently", type: "adv.", meaning: "ภายหลัง" },
    { word: "suburb", type: "n.", meaning: "ชานเมือง" },
    { word: "suffering", type: "n.", meaning: "ความทุกข์ทรมาน" },
    { word: "sufficient", type: "adj.", meaning: "เพียงพอ" },
    { word: "sufficiently", type: "adv.", meaning: "อย่างเพียงพอ" },
    { word: "super", type: "adj.", meaning: "ยอดเยี่ยม (ไม่เป็นทางการ)" },
    { word: "surgeon", type: "n.", meaning: "ศัลยแพทย์" },
    { word: "survival", type: "n.", meaning: "การรอดชีวิต" },
    { word: "survivor", type: "n.", meaning: "ผู้รอดชีวิต" },
    { word: "suspend", type: "v.", meaning: "ระงับ, แขวน" },
    { word: "sustainable", type: "adj.", meaning: "ยั่งยืน" },
    { word: "swallow", type: "v.", meaning: "กลืน" },
    { word: "sympathetic", type: "adj.", meaning: "เห็นอกเห็นใจ" },
    { word: "tackle", type: "v.", meaning: "รับมือ, จัดการ" },
    { word: "tag", type: "n., v.", meaning: "ป้าย, แท็ก, ติดแท็ก" },
    { word: "tap", type: "v., n.", meaning: "เคาะเบาๆ, ก๊อกน้ำ" },
    { word: "technological", type: "adj.", meaning: "ทางเทคโนโลยี" },
    { word: "teens", type: "n.", meaning: "วัยรุ่น (ช่วงอายุ 13-19)" },
    { word: "temple", type: "n.", meaning: "วัด, ขมับ" },
    { word: "temporarily", type: "adv.", meaning: "ชั่วคราว" },
    { word: "tendency", type: "n.", meaning: "แนวโน้ม" },
    { word: "tension", type: "n.", meaning: "ความตึงเครียด" },
    { word: "terminal", type: "n.", meaning: "อาคารผู้โดยสาร, จุดสุดท้าย" },
    { word: "terms", type: "n.", meaning: "เงื่อนไข, ข้อกำหนด" },
    { word: "terribly", type: "adv.", meaning: "อย่างมาก, อย่างแย่มาก" },
    { word: "terrify", type: "v.", meaning: "ทำให้หวาดกลัว" },
    { word: "territory", type: "n.", meaning: "อาณาเขต" },
    { word: "terror", type: "n.", meaning: "ความหวาดกลัว" },
    { word: "terrorism", type: "n.", meaning: "การก่อการร้าย" },
    { word: "terrorist", type: "n.", meaning: "ผู้ก่อการร้าย" },
    { word: "testing", type: "n.", meaning: "การทดสอบ" },
    { word: "textbook", type: "n.", meaning: "หนังสือเรียน" },
    { word: "theft", type: "n.", meaning: "การโจรกรรม" },
    { word: "therapist", type: "n.", meaning: "นักบำบัด" },
    { word: "thesis", type: "n.", meaning: "วิทยานิพนธ์" },
    { word: "thorough", type: "adj.", meaning: "ละเอียดถี่ถ้วน" },
    { word: "thoroughly", type: "adv.", meaning: "อย่างละเอียดถี่ถ้วน" },
    { word: "thumb", type: "n.", meaning: "นิ้วหัวแม่มือ" },
    { word: "timing", type: "n.", meaning: "การกำหนดเวลา" },
    { word: "tissue", type: "n.", meaning: "เนื้อเยื่อ, กระดาษทิชชู" },
    { word: "ton", type: "n.", meaning: "ตัน (หน่วยน้ำหนัก)" },
    { word: "tonne", type: "n.", meaning: "ตัน (หน่วยน้ำหนัก, UK)" },
    { word: "tournament", type: "n.", meaning: "การแข่งขัน" },
    { word: "trace", type: "v.", meaning: "ติดตาม, ค้นหาร่องรอย" },
    { word: "trading", type: "n.", meaning: "การค้า" },
    { word: "tragedy", type: "n.", meaning: "โศกนาฏกรรม" },
    { word: "tragic", type: "adj.", meaning: "เศร้าสลด" },
    { word: "trait", type: "n.", meaning: "ลักษณะเฉพาะ" },
    { word: "transmit", type: "v.", meaning: "ส่งผ่าน, ถ่ายทอด" },
    { word: "transportation", type: "n.", meaning: "การขนส่ง" },
    { word: "trap", type: "v., n.", meaning: "กับดัก, ดักจับ" },
    { word: "treasure", type: "n.", meaning: "สมบัติ" },
    { word: "tribe", type: "n.", meaning: "ชนเผ่า" },
    { word: "trigger", type: "v.", meaning: "กระตุ้น, จุดชนวน" },
    { word: "trillion", type: "number", meaning: "ล้านล้าน" },
    { word: "troop", type: "n.", meaning: "กองกำลัง" },
    { word: "tsunami", type: "n.", meaning: "สึนามิ" },
    { word: "ultimate", type: "adj.", meaning: "ที่สุด, สุดท้าย" },
    { word: "unacceptable", type: "adj.", meaning: "ไม่เป็นที่ยอมรับ" },
    { word: "uncertainty", type: "n.", meaning: "ความไม่แน่นอน" },
    { word: "undergo", type: "v.", meaning: "ผ่านประสบการณ์, เข้ารับ" },
    { word: "undertake", type: "v.", meaning: "ดำเนินการ, รับผิดชอบ" },
    { word: "unfold", type: "v.", meaning: "คลี่ออก, เปิดเผย" },
    { word: "unfortunate", type: "adj.", meaning: "โชคร้าย" },
    { word: "unite", type: "v.", meaning: "รวมกัน" },
    { word: "unity", type: "n.", meaning: "ความเป็นเอกภาพ" },
    { word: "universal", type: "adj.", meaning: "สากล, ทั่วไป" },
    { word: "urgent", type: "adj.", meaning: "เร่งด่วน" },
    { word: "usage", type: "n.", meaning: "การใช้" },
    { word: "useless", type: "adj.", meaning: "ไร้ประโยชน์" },
    { word: "valid", type: "adj.", meaning: "ถูกต้องตามกฎหมาย/เหตุผล" },
    { word: "variation", type: "n.", meaning: "ความแตกต่าง, การเปลี่ยนแปลง" },
    { word: "vertical", type: "adj.", meaning: "แนวตั้ง" },
    { word: "viewpoint", type: "n.", meaning: "มุมมอง" },
    { word: "visa", type: "n.", meaning: "วีซ่า" },
    { word: "visible", type: "adj.", meaning: "มองเห็นได้" },
    { word: "voluntary", type: "adj.", meaning: "ด้วยความสมัครใจ" },
    { word: "voting", type: "n.", meaning: "การลงคะแนน" },
    { word: "wander", type: "v.", meaning: "เดินเร่ร่อน, เตร็ดเตร่" },
    { word: "warming", type: "n.", meaning: "ภาวะโลกร้อน, การอุ่น" },
    { word: "weekly", type: "adj.", meaning: "รายสัปดาห์" },
    { word: "weird", type: "adj.", meaning: "แปลกประหลาด" },
    { word: "welfare", type: "n.", meaning: "สวัสดิการ" },
    { word: "wheat", type: "n.", meaning: "ข้าวสาลี" },
    { word: "whoever", type: "pron.", meaning: "ใครก็ตาม" },
    { word: "widespread", type: "adj.", meaning: "แพร่หลาย" },
    { word: "wisdom", type: "n.", meaning: "ปัญญา" },
    { word: "withdraw", type: "v.", meaning: "ถอน, ถอนตัว" },
    { word: "workforce", type: "n.", meaning: "กำลังคน, แรงงาน" },
    { word: "workplace", type: "n.", meaning: "สถานที่ทำงาน" },
    { word: "workshop", type: "n.", meaning: "เวิร์คช็อป, โรงซ่อม" },
    { word: "worm", type: "n.", meaning: "หนอน" },
    { word: "wrist", type: "n.", meaning: "ข้อมือ" }
];
