import { Word } from './types';

export const c1Words: Word[] = [
    { word: "abolish", type: "v.", meaning: "ยกเลิก" },
    { word: "abortion", type: "n.", meaning: "การทำแท้ง" },
    { word: "absence", type: "n.", meaning: "การขาด, การไม่อยู่" },
    { word: "absent", type: "adj.", meaning: "ขาด, ไม่อยู่" },
    { word: "absurd", type: "adj.", meaning: "ไร้สาระ" },
    { word: "abundance", type: "n.", meaning: "ความอุดมสมบูรณ์" },
    { word: "abuse", type: "n., v.", meaning: "การทารุณกรรม, ทารุณกรรม" },
    { word: "academy", type: "n.", meaning: "สถาบันการศึกษา" },
    { word: "accelerate", type: "v.", meaning: "เร่งความเร็ว" },
    { word: "acceptance", type: "n.", meaning: "การยอมรับ" },
    { word: "accessible", type: "adj.", meaning: "เข้าถึงได้" },
    { word: "accomplishment", type: "n.", meaning: "ความสำเร็จ, ผลงาน" },
    { word: "accordance", type: "n.", meaning: "การสอดคล้อง" },
    { word: "accordingly", type: "adv.", meaning: "ตามนั้น, ดังนั้น" },
    { word: "accountability", type: "n.", meaning: "ความรับผิดชอบ" },
    { word: "accountable", type: "adj.", meaning: "ต้องรับผิดชอบ" },
    { word: "accumulate", type: "v.", meaning: "สะสม" },
    { word: "accumulation", type: "n.", meaning: "การสะสม" },
    { word: "accusation", type: "n.", meaning: "ข้อกล่าวหา" },
    { word: "accused", type: "n.", meaning: "ผู้ถูกกล่าวหา" },
    { word: "acid", type: "adj.", meaning: "เปรี้ยว, เป็นกรด" },
    { word: "acquisition", type: "n.", meaning: "การได้มา, การเข้าซื้อกิจการ" },
    { word: "acre", type: "n.", meaning: "เอเคอร์ (หน่วยวัดพื้นที่)" },
    { word: "activation", type: "n.", meaning: "การเปิดใช้งาน" },
    { word: "activist", type: "n.", meaning: "นักกิจกรรม" },
    { word: "acute", type: "adj.", meaning: "เฉียบพลัน, แหลมคม" },
    { word: "adaptation", type: "n.", meaning: "การปรับตัว, การดัดแปลง" },
    { word: "adhere", type: "v.", meaning: "ยึดติด, ปฏิบัติตาม" },
    { word: "adjacent", type: "adj.", meaning: "ข้างเคียง, ใกล้กัน" },
    { word: "adjustment", type: "n.", meaning: "การปรับเปลี่ยน" },
    { word: "administer", type: "v.", meaning: "บริหาร, จัดการ" },
    { word: "administrative", type: "adj.", meaning: "เกี่ยวกับการบริหาร" },
    { word: "administrator", type: "n.", meaning: "ผู้บริหาร" },
    { word: "admission", type: "n.", meaning: "การรับเข้า, ค่าเข้าชม" },
    { word: "adolescent", type: "n.", meaning: "วัยรุ่น" },
    { word: "adoption", type: "n.", meaning: "การรับเลี้ยงบุตรบุญธรรม, การนำมาใช้" },
    { word: "adverse", type: "adj.", meaning: "เป็นผลร้าย, ตรงกันข้าม" },
    { word: "advocate", type: "n., v.", meaning: "ผู้สนับสนุน, สนับสนุน" },
    { word: "aesthetic", type: "adj.", meaning: "สุนทรียภาพ" },
    { word: "affection", type: "n.", meaning: "ความรักใคร่, ความเสน่หา" },
    { word: "aftermath", type: "n.", meaning: "ผลที่ตามมา (โดยเฉพาะผลร้าย)" },
    { word: "aggression", type: "n.", meaning: "การรุกราน, ความก้าวร้าว" },
    { word: "agricultural", type: "adj.", meaning: "เกี่ยวกับการเกษตร" },
    { word: "aide", type: "n.", meaning: "ผู้ช่วย" },
    { word: "albeit", type: "conj.", meaning: "ถึงแม้ว่า" },
    { word: "alert", type: "v., n., adj.", meaning: "เตือน, การเตือน, ตื่นตัว" },
    { word: "alien", type: "adj.", meaning: "ต่างด้าว, แตกต่าง" },
    { word: "align", type: "v.", meaning: "จัดแนว, จัดให้อยู่ในแนวเดียวกัน" },
    { word: "alignment", type: "n.", meaning: "การจัดแนว" },
    { word: "alike", type: "adv., adj.", meaning: "เหมือนกัน" },
    { word: "allegation", type: "n.", meaning: "ข้อกล่าวหา" },
    { word: "allege", type: "v.", meaning: "กล่าวหา, อ้างว่า" },
    { word: "allegedly", type: "adv.", meaning: "ตามที่กล่าวหา" },
    { word: "alliance", type: "n.", meaning: "พันธมิตร" },
    { word: "allocate", type: "v.", meaning: "จัดสรร" },
    { word: "allocation", type: "n.", meaning: "การจัดสรร" },
    { word: "allowance", type: "n.", meaning: "เบี้ยเลี้ยง, การอนุญาต" },
    { word: "ally", type: "n.", meaning: "พันธมิตร" },
    { word: "aluminium", type: "n.", meaning: "อลูมิเนียม" },
    { word: "amateur", type: "adj., n.", meaning: "สมัครเล่น" },
    { word: "ambassador", type: "n.", meaning: "เอกอัครราชทูต" },
    { word: "amend", type: "v.", meaning: "แก้ไข, ปรับปรุง" },
    { word: "amendment", type: "n.", meaning: "การแก้ไข" },
    { word: "amid", type: "prep.", meaning: "ท่ามกลาง" },
    { word: "analogy", type: "n.", meaning: "การเปรียบเทียบเทียบเคียง" },
    { word: "anchor", type: "n.", meaning: "สมอเรือ, ผู้ประกาศข่าว" },
    { word: "angel", type: "n.", meaning: "นางฟ้า, เทวดา" },
    { word: "anonymous", type: "adj.", meaning: "นิรนาม" },
    { word: "apparatus", type: "n.", meaning: "อุปกรณ์, เครื่องมือ" },
    { word: "appealing", type: "adj.", meaning: "น่าสนใจ, ดึงดูดใจ" },
    { word: "appetite", type: "n.", meaning: "ความอยากอาหาร" },
    { word: "applaud", type: "v.", meaning: "ปรบมือ" },
    { word: "applicable", type: "adj.", meaning: "ใช้ได้, ที่เกี่ยวข้อง" },
    { word: "appoint", type: "v.", meaning: "แต่งตั้ง" },
    { word: "appreciation", type: "n.", meaning: "ความซาบซึ้ง, การชื่นชม" },
    { word: "arbitrary", type: "adj.", meaning: "ตามอำเภอใจ, โดยพลการ" },
    { word: "architectural", type: "adj.", meaning: "เกี่ยวกับสถาปัตยกรรม" },
    { word: "archive", type: "n.", meaning: "เอกสารสำคัญทางประวัติศาสตร์, หอจดหมายเหตุ" },
    { word: "arena", type: "n.", meaning: "สนามแข่งขัน, เวที" },
    { word: "arguably", type: "adv.", meaning: "ที่โต้แย้งได้, ที่น่าจะจริงที่สุด" },
    { word: "arm", type: "v.", meaning: "ติดอาวุธ" },
    { word: "array", type: "n.", meaning: "ชุด, แถว" },
    { word: "articulate", type: "v.", meaning: "พูดให้ชัดเจน" },
    { word: "ash", type: "n.", meaning: "ขี้เถ้า" },
    { word: "aspiration", type: "n.", meaning: "ความมุ่งมาดปรารถนา" },
    { word: "aspire", type: "v.", meaning: "มุ่งมั่น, ปรารถนา" },
    { word: "assassination", type: "n.", meaning: "การลอบสังหาร" },
    { word: "assault", type: "n., v.", meaning: "การจู่โจม, จู่โจม" },
    { word: "assemble", type: "v.", meaning: "ประกอบ, รวมตัว" },
    { word: "assembly", type: "n.", meaning: "การประกอบ, ที่ประชุม" },
    { word: "assert", type: "v.", meaning: "ยืนยัน, อ้าง" },
    { word: "assertion", type: "n.", meaning: "การยืนยัน, ข้อกล่าวอ้าง" },
    { word: "assurance", type: "n.", meaning: "การรับรอง, ความมั่นใจ" },
    { word: "asylum", type: "n.", meaning: "ที่ลี้ภัย, โรงพยาบาลบ้า (คำเก่า)" },
    { word: "atrocity", type: "n.", meaning: "ความโหดร้าย, การกระทำที่โหดร้าย" },
    { word: "attain", type: "v.", meaning: "บรรลุ, ได้มา" },
    { word: "attendance", type: "n.", meaning: "การเข้าร่วม, ผู้เข้าร่วม" },
    { word: "attorney", type: "n.", meaning: "ทนายความ (US)" },
    { word: "attribute", type: "v., n.", meaning: "ถือว่าเป็นของ, คุณสมบัติ" },
    { word: "audit", type: "n.", meaning: "การตรวจสอบบัญชี" },
    { word: "authentic", type: "adj.", meaning: "ของแท้, น่าเชื่อถือ" },
    { word: "authorize", type: "v.", meaning: "ให้อำนาจ, อนุญาต" },
    { word: "auto", type: "n.", meaning: "รถยนต์ (คำย่อของ automobile)" },
    { word: "autonomy", type: "n.", meaning: "อิสระในการปกครองตนเอง" },
    { word: "availability", type: "n.", meaning: "ความพร้อมใช้งาน" },
    { word: "await", type: "v.", meaning: "รอคอย" },
    { word: "backdrop", type: "n.", meaning: "ฉากหลัง" },
    { word: "backing", type: "n.", meaning: "การสนับสนุน" },
    { word: "backup", type: "n.", meaning: "การสำรอง, สิ่งสำรอง" },
    { word: "bail", type: "n.", meaning: "การประกันตัว" },
    { word: "ballot", type: "n.", meaning: "บัตรลงคะแนน" },
    { word: "banner", type: "n.", meaning: "ป้ายโฆษณา, ธง" },
    { word: "bare", type: "adj.", meaning: "เปลือยเปล่า, เปล่า" },
    { word: "barrel", type: "n.", meaning: "ถัง, ลำกล้องปืน" },
    { word: "bass", type: "n.", meaning: "เสียงเบส, ปลาเบส" },
    { word: "bat", type: "v.", meaning: "ตี (ด้วยไม้ตี)" },
    { word: "battlefield", type: "n.", meaning: "สนามรบ" },
    { word: "bay", type: "n.", meaning: "อ่าว" },
    { word: "beam", type: "n.", meaning: "ลำแสง, คาน" },
    { word: "beast", type: "n.", meaning: "สัตว์ร้าย" },
    { word: "behalf", type: "n.", meaning: "ในนามของ" },
    { word: "beloved", type: "adj.", meaning: "ที่เป็นที่รัก" },
    { word: "bench", type: "n.", meaning: "ม้านั่ง, ที่นั่งในศาล" },
    { word: "benchmark", type: "n.", meaning: "เกณฑ์มาตรฐาน" },
    { word: "beneath", type: "prep.", meaning: "ข้างใต้" },
    { word: "beneficiary", type: "n.", meaning: "ผู้รับผลประโยชน์" },
    { word: "betray", type: "v.", meaning: "ทรยศ" },
    { word: "bind", type: "v.", meaning: "ผูกมัด" },
    { word: "biography", type: "n.", meaning: "ชีวประวัติ" },
    { word: "bishop", type: "n.", meaning: "บาทหลวง" },
    { word: "bizarre", type: "adj.", meaning: "แปลกประหลาดมาก" },
    { word: "blade", type: "n.", meaning: "ใบมีด, ใบพัด" },
    { word: "blast", type: "n., v.", meaning: "การระเบิด, ระเบิด" },
    { word: "bleed", type: "v.", meaning: "เลือดออก" },
    { word: "blend", type: "v., n.", meaning: "ผสม, การผสม" },
    { word: "bless", type: "v.", meaning: "อวยพร" },
    { word: "blessing", type: "n.", meaning: "พร, สิ่งดีๆ" },
    { word: "boast", type: "v.", meaning: "โอ้อวด" },
    { word: "bonus", type: "n.", meaning: "โบนัส" },
    { word: "boom", type: "n.", meaning: "ความเจริญรุ่งเรืองอย่างรวดเร็ว, เสียงดัง" },
    { word: "bounce", type: "v.", meaning: "กระเด้ง" },
    { word: "boundary", type: "n.", meaning: "เขตแดน" },
    { word: "bow", type: "v., n.", meaning: "โค้งคำนับ, คันธนู" },
    { word: "breach", type: "n., v.", meaning: "การละเมิด, ละเมิด" },
    { word: "breakdown", type: "n.", meaning: "การชำรุด, การล้มเหลว" },
    { word: "breakthrough", type: "n.", meaning: "การพัฒนาครั้งสำคัญ" },
    { word: "breed", type: "v., n.", meaning: "เพาะพันธุ์, พันธุ์" },
    { word: "broadband", type: "n.", meaning: "บรอดแบนด์" },
    { word: "browser", type: "n.", meaning: "เว็บเบราว์เซอร์" },
    { word: "brutal", type: "adj.", meaning: "โหดร้าย" },
    { word: "buck", type: "n.", meaning: "ดอลลาร์ (ไม่เป็นทางการ), กวางตัวผู้" },
    { word: "buddy", type: "n.", meaning: "เพื่อนสนิท (ไม่เป็นทางการ)" },
    { word: "buffer", type: "n.", meaning: "กันชน, ตัวกันชน" },
    { word: "bulk", type: "n.", meaning: "ปริมาณมาก" },
    { word: "burden", type: "n.", meaning: "ภาระ" },
    { word: "bureaucracy", type: "n.", meaning: "ระบบราชการ" },
    { word: "burial", type: "n.", meaning: "การฝังศพ" },
    { word: "burst", type: "v.", meaning: "ระเบิด, แตก" },
    { word: "cabinet", type: "n.", meaning: "คณะรัฐมนตรี, ตู้" },
    { word: "calculation", type: "n.", meaning: "การคำนวณ" },
    { word: "canvas", type: "n.", meaning: "ผ้าใบ" },
    { word: "capability", type: "n.", meaning: "ความสามารถ" },
    { word: "capitalism", type: "n.", meaning: "ระบบทุนนิยม" },
    { word: "capitalist", type: "adj.", meaning: "ทุนนิยม" },
    { word: "cargo", type: "n.", meaning: "สินค้า (ที่บรรทุก)" },
    { word: "carriage", type: "n.", meaning: "รถม้า, ตู้รถไฟ" },
    { word: "carve", type: "v.", meaning: "แกะสลัก" },
    { word: "casino", type: "n.", meaning: "บ่อนคาสิโน" },
    { word: "casualty", type: "n.", meaning: "ผู้บาดเจ็บล้มตาย" },
    { word: "catalogue", type: "n.", meaning: "แค็ตตาล็อก" },
    { word: "cater", type: "v.", meaning: "จัดหาอาหาร, ตอบสนองความต้องการ" },
    { word: "cattle", type: "n.", meaning: "วัว, ปศุสัตว์" },
    { word: "caution", type: "n.", meaning: "ความระมัดระวัง, คำเตือน" },
    { word: "cautious", type: "adj.", meaning: "ระมัดระวัง" },
    { word: "cease", type: "v.", meaning: "หยุด" },
    { word: "cemetery", type: "n.", meaning: "สุสาน, ป่าช้า" },
    { word: "chamber", type: "n.", meaning: "ห้อง (โดยเฉพาะห้องใหญ่/ทางการ)" },
    { word: "chaos", type: "n.", meaning: "ความวุ่นวาย" },
    { word: "characterize", type: "v.", meaning: "เป็นลักษณะเฉพาะของ" },
    { word: "charm", type: "n.", meaning: "เสน่ห์" },
    { word: "charter", type: "n.", meaning: "กฎบัตร, สัญญาเช่า" },
    { word: "chronic", type: "adj.", meaning: "เรื้อรัง" },
    { word: "chunk", type: "n.", meaning: "ก้อนใหญ่, ชิ้นใหญ่" },
    { word: "circulate", type: "v.", meaning: "หมุนเวียน, เผยแพร่" },
    { word: "circulation", type: "n.", meaning: "การหมุนเวียน, การไหลเวียน" },
    { word: "citizenship", type: "n.", meaning: "ความเป็นพลเมือง" },
    { word: "civic", type: "adj.", meaning: "เกี่ยวกับพลเมือง/เทศบาล" },
    { word: "civilian", type: "n., adj.", meaning: "พลเรือน" },
    { word: "clarity", type: "n.", meaning: "ความชัดเจน" },
    { word: "clash", type: "n.", meaning: "การปะทะ, ความขัดแย้ง" },
    { word: "classification", type: "n.", meaning: "การจัดประเภท" },
    { word: "cling", type: "v.", meaning: "ยึดติด, เกาะติด" },
    { word: "clinical", type: "adj.", meaning: "ทางคลินิก" },
    { word: "closure", type: "n.", meaning: "การปิด" },
    { word: "cluster", type: "n.", meaning: "กลุ่ม, กระจุก" },
    { word: "coalition", type: "n.", meaning: "แนวร่วม, พันธมิตร" },
    { word: "coastal", type: "adj.", meaning: "ชายฝั่ง" },
    { word: "cocktail", type: "n.", meaning: "ค็อกเทล" },
    { word: "cognitive", type: "adj.", meaning: "เกี่ยวกับการรับรู้" },
    { word: "coincide", type: "v.", meaning: "เกิดขึ้นพร้อมกัน" },
    { word: "collaborate", type: "v.", meaning: "ร่วมมือ" },
    { word: "collaboration", type: "n.", meaning: "ความร่วมมือ" },
    { word: "collective", type: "adj.", meaning: "รวมหมู่, โดยรวม" },
    { word: "collision", type: "n.", meaning: "การชนกัน" },
    { word: "colonial", type: "adj.", meaning: "เกี่ยวกับอาณานิคม" },
    { word: "columnist", type: "n.", meaning: "นักเขียนคอลัมน์" },
    { word: "combat", type: "n., v.", meaning: "การต่อสู้, ต่อสู้" },
    { word: "commence", type: "v.", meaning: "เริ่มต้น" },
    { word: "commentary", type: "n.", meaning: "คำบรรยาย, บทวิจารณ์" },
    { word: "commentator", type: "n.", meaning: "ผู้บรรยาย, ผู้วิจารณ์" },
    { word: "commerce", type: "n.", meaning: "การค้า" },
    { word: "commissioner", type: "n.", meaning: "ผู้ตรวจการ, กรรมาธิการ" },
    { word: "commodity", type: "n.", meaning: "สินค้าโภคภัณฑ์" },
    { word: "communist", type: "adj.", meaning: "คอมมิวนิสต์" },
    { word: "companion", type: "n.", meaning: "เพื่อนร่วมทาง" },
    { word: "comparable", type: "adj.", meaning: "เปรียบเทียบกันได้" },
    { word: "compassion", type: "n.", meaning: "ความเมตตา, ความสงสาร" },
    { word: "compel", type: "v.", meaning: "บังคับ" },
    { word: "compelling", type: "adj.", meaning: "น่าสนใจ, น่าดึงดูด" },
    { word: "compensate", type: "v.", meaning: "ชดเชย" },
    { word: "compensation", type: "n.", meaning: "ค่าชดเชย" },
    { word: "competence", type: "n.", meaning: "ความสามารถ" },
    { word: "competent", type: "adj.", meaning: "มีความสามารถ" },
    { word: "compile", type: "v.", meaning: "รวบรวม, เรียบเรียง" },
    { word: "complement", type: "v.", meaning: "ส่งเสริม, เสริมเต็ม" },
    { word: "complexity", type: "n.", meaning: "ความซับซ้อน" },
    { word: "compliance", type: "n.", meaning: "การปฏิบัติตาม" },
    { word: "complication", type: "n.", meaning: "ภาวะแทรกซ้อน, ความยุ่งยาก" },
    { word: "comply", type: "v.", meaning: "ปฏิบัติตาม" },
    { word: "composition", type: "n.", meaning: "องค์ประกอบ, การประพันธ์" },
    { word: "compromise", type: "n., v.", meaning: "การประนีประนอม, ประนีประนอม" },
    { word: "compute", type: "v.", meaning: "คำนวณ" },
    { word: "conceal", type: "v.", meaning: "ปกปิด" },
    { word: "concede", type: "v.", meaning: "ยอมรับ, ยอมจำนน" },
    { word: "conceive", type: "v.", meaning: "ตั้งครรภ์, คิดขึ้น" },
    { word: "conception", type: "n.", meaning: "แนวคิด, การตั้งครรภ์" },
    { word: "concession", type: "n.", meaning: "การยินยอม, สัมปทาน" },
    { word: "condemn", type: "v.", meaning: "ประณาม" },
    { word: "confer", type: "v.", meaning: "ปรึกษาหารือ, มอบให้" },
    { word: "confession", type: "n.", meaning: "การสารภาพ" },
    { word: "configuration", type: "n.", meaning: "การจัดโครงแบบ" },
    { word: "confine", type: "v.", meaning: "จำกัด, กักขัง" },
    { word: "confirmation", type: "n.", meaning: "การยืนยัน" },
    { word: "confront", type: "v.", meaning: "เผชิญหน้า" },
    { word: "confrontation", type: "n.", meaning: "การเผชิญหน้า" },
    { word: "congratulate", type: "v.", meaning: "แสดงความยินดี" },
    { word: "congregation", type: "n.", meaning: "ที่ประชุม (ทางศาสนา)" },
    { word: "congressional", type: "adj.", meaning: "เกี่ยวกับรัฐสภา" },
    { word: "conquer", type: "v.", meaning: "พิชิต" },
    { word: "conscience", type: "n.", meaning: "มโนธรรม, จิตสำนึก" },
    { word: "consciousness", type: "n.", meaning: "สติ, จิตสำนึก" },
    { word: "consecutive", type: "adj.", meaning: "ติดต่อกัน" },
    { word: "consensus", type: "n.", meaning: "ฉันทามติ" },
    { word: "consent", type: "n., v.", meaning: "ความยินยอม, ยินยอม" },
    { word: "conserve", type: "v.", meaning: "อนุรักษ์" },
    { word: "consistency", type: "n.", meaning: "ความสอดคล้องกัน, ความคงเส้นคงวา" },
    { word: "consolidate", type: "v.", meaning: "รวมเข้าด้วยกัน, ทำให้แข็งแกร่งขึ้น" },
    { word: "constituency", type: "n.", meaning: "เขตเลือกตั้ง" },
    { word: "constitute", type: "v.", meaning: "ประกอบด้วย, ก่อให้เกิด" },
    { word: "constitution", type: "n.", meaning: "รัฐธรรมนูญ" },
    { word: "constitutional", type: "adj.", meaning: "ตามรัฐธรรมนูญ" },
    { word: "constraint", type: "n.", meaning: "ข้อจำกัด" },
    { word: "consultation", type: "n.", meaning: "การปรึกษาหารือ" },
    { word: "contemplate", type: "v.", meaning: "ครุ่นคิด, พิจารณา" },
    { word: "contempt", type: "n.", meaning: "การดูถูก, การหมิ่นประมาท" },
    { word: "contend", type: "v.", meaning: "โต้แย้ง, แข่งขัน" },
    { word: "contender", type: "n.", meaning: "ผู้แข่งขัน" },
    { word: "content", type: "adj.", meaning: "พอใจ" },
    { word: "contention", type: "n.", meaning: "ข้อโต้แย้ง, การโต้แย้ง" },
    { word: "continually", type: "adv.", meaning: "อย่างต่อเนื่อง" },
    { word: "contractor", type: "n.", meaning: "ผู้รับเหมา" },
    { word: "contradiction", type: "n.", meaning: "ความขัดแย้ง" },
    { word: "contrary", type: "adj., n.", meaning: "ตรงกันข้าม, สิ่งที่ตรงกันข้าม" },
    { word: "contributor", type: "n.", meaning: "ผู้สนับสนุน, ผู้มีส่วนร่วม" },
    { word: "conversion", type: "n.", meaning: "การแปลง, การเปลี่ยน" },
    { word: "convict", type: "v.", meaning: "ตัดสินว่ามีความผิด" },
    { word: "conviction", type: "n.", meaning: "การตัดสินว่ามีความผิด, ความเชื่อมั่น" },
    { word: "cooperate", type: "v.", meaning: "ร่วมมือ" },
    { word: "cooperative", type: "adj.", meaning: "ร่วมมือกัน" },
    { word: "coordinate", type: "v.", meaning: "ประสานงาน" },
    { word: "coordination", type: "n.", meaning: "การประสานงาน" },
    { word: "coordinator", type: "n.", meaning: "ผู้ประสานงาน" },
    { word: "cop", type: "n.", meaning: "ตำรวจ (ไม่เป็นทางการ)" },
    { word: "copper", type: "n.", meaning: "ทองแดง" },
    { word: "copyright", type: "n.", meaning: "ลิขสิทธิ์" },
    { word: "correction", type: "n.", meaning: "การแก้ไข, สิ่งที่ถูกต้อง" },
    { word: "correlate", type: "v.", meaning: "มีความสัมพันธ์กัน" },
    { word: "correlation", type: "n.", meaning: "ความสัมพันธ์" },
    { word: "correspond", type: "v.", meaning: "สอดคล้อง, ติดต่อทางจดหมาย" },
    { word: "correspondence", type: "n.", meaning: "จดหมายโต้ตอบ, ความสอดคล้อง" },
    { word: "correspondent", type: "n.", meaning: "ผู้สื่อข่าว" },
    { word: "corresponding", type: "adj.", meaning: "ที่สอดคล้องกัน" },
    { word: "corrupt", type: "adj.", meaning: "ทุจริต, เสื่อมทราม" },
    { word: "corruption", type: "n.", meaning: "การทุจริต, การคอร์รัปชัน" },
    { word: "costly", type: "adj.", meaning: "แพง, มีราคาแพง" },
    { word: "councillor", type: "n.", meaning: "สมาชิกสภา" },
    { word: "counselling", type: "n.", meaning: "การให้คำปรึกษา" },
    { word: "counsellor", type: "n.", meaning: "ที่ปรึกษา" },
    { word: "counter", type: "v.", meaning: "โต้แย้ง, ตอบโต้" },
    { word: "counterpart", type: "n.", meaning: "คู่ฉบับ, สิ่งที่เทียบเท่า" },
    { word: "countless", type: "adj.", meaning: "นับไม่ถ้วน" },
    { word: "coup", type: "n.", meaning: "การรัฐประหาร" },
    { word: "courtesy", type: "n.", meaning: "ความสุภาพ, มารยาท" },
    { word: "craft", type: "v.", meaning: "ประดิษฐ์, สร้าง" },
    { word: "crawl", type: "v.", meaning: "คลาน" },
    { word: "creator", type: "n.", meaning: "ผู้สร้าง" },
    { word: "credibility", type: "n.", meaning: "ความน่าเชื่อถือ" },
    { word: "credible", type: "adj.", meaning: "น่าเชื่อถือ" },
    { word: "creep", type: "v.", meaning: "คืบคลาน, เลื้อย" },
    { word: "critique", type: "n.", meaning: "บทวิจารณ์, การวิจารณ์" },
    { word: "crown", type: "n.", meaning: "มงกุฎ" },
    { word: "crude", type: "adj.", meaning: "ดิบ, หยาบคาย" },
    { word: "crush", type: "v.", meaning: "บดขยี้, ทำให้แหลก" },
    { word: "crystal", type: "n.", meaning: "คริสตัล" },
    { word: "cult", type: "n., adj.", meaning: "ลัทธิ, เกี่ยวกับลัทธิ" },
    { word: "cultivate", type: "v.", meaning: "เพาะปลูก, บ่มเพาะ" },
    { word: "curiosity", type: "n.", meaning: "ความอยากรู้อยากเห็น" },
    { word: "custody", type: "n.", meaning: "การควบคุมตัว, การดูแล" },
    { word: "cutting", type: "n.", meaning: "การตัด, ชิ้นส่วนที่ถูกตัด" },
    { word: "cynical", type: "adj.", meaning: "เหยียดหยาม, เยาะเย้ย" },
    { word: "dam", type: "n.", meaning: "เขื่อน" },
    { word: "damaging", type: "adj.", meaning: "ที่ก่อให้เกิดความเสียหาย" },
    { word: "dawn", type: "n.", meaning: "รุ่งอรุณ" },
    { word: "debris", type: "n.", meaning: "ซากปรักหักพัง, เศษซาก" },
    { word: "debut", type: "n.", meaning: "การเปิดตัว" },
    { word: "decision-making", type: "n.", meaning: "การตัดสินใจ" },
    { word: "decisive", type: "adj.", meaning: "เด็ดขาด, มีการตัดสินใจ" },
    { word: "declaration", type: "n.", meaning: "การประกาศ" },
    { word: "dedicated", type: "adj.", meaning: "ทุ่มเท, อุทิศ" },
    { word: "dedication", type: "n.", meaning: "ความทุ่มเท, การอุทิศ" },
    { word: "deed", type: "n.", meaning: "การกระทำ, โฉนด" },
    { word: "deem", type: "v.", meaning: "ถือว่า, พิจารณาว่า" },
    { word: "default", type: "n.", meaning: "ค่าเริ่มต้น, การผิดนัดชำระ" },
    { word: "defect", type: "n.", meaning: "ข้อบกพร่อง" },
    { word: "defensive", type: "adj.", meaning: "ในการป้องกัน" },
    { word: "deficiency", type: "n.", meaning: "ความบกพร่อง, การขาดแคลน" },
    { word: "deficit", type: "n.", meaning: "การขาดดุล" },
    { word: "defy", type: "v.", meaning: "ท้าทาย, ขัดขืน" },
    { word: "delegate", type: "n.", meaning: "ผู้แทน" },
    { word: "delegation", type: "n.", meaning: "คณะผู้แทน" },
    { word: "delicate", type: "adj.", meaning: "บอบบาง, ละเอียดอ่อน" },
    { word: "demon", type: "n.", meaning: "ปีศาจ" },
    { word: "denial", type: "n.", meaning: "การปฏิเสธ" },
    { word: "denounce", type: "v.", meaning: "ประณาม" },
    { word: "dense", type: "adj.", meaning: "หนาแน่น" },
    { word: "density", type: "n.", meaning: "ความหนาแน่น" },
    { word: "dependence", type: "n.", meaning: "การพึ่งพา" },
    { word: "depict", type: "v.", meaning: "พรรณนา, แสดงภาพ" },
    { word: "deploy", type: "v.", meaning: "ประจำการ, จัดกำลัง" },
    { word: "deployment", type: "n.", meaning: "การประจำการ, การจัดกำลัง" },
    { word: "deposit", type: "v.", meaning: "ฝาก (เงิน), วาง" },
    { word: "deprive", type: "v.", meaning: "พรากไป, ทำให้ขาดแคลน" },
    { word: "deputy", type: "n.", meaning: "รอง, ผู้ช่วย" },
    { word: "descend", type: "v.", meaning: "ลงมา" },
    { word: "descent", type: "n.", meaning: "การลงมา, เชื้อสาย" },
    { word: "designate", type: "v.", meaning: "กำหนด, แต่งตั้ง" },
    { word: "desirable", type: "adj.", meaning: "เป็นที่พึงปรารถนา" },
    { word: "desktop", type: "n.", meaning: "คอมพิวเตอร์ตั้งโต๊ะ, หน้าจอคอมพิวเตอร์" },
    { word: "destructive", type: "adj.", meaning: "ที่ก่อให้เกิดการทำลาย" },
    { word: "detain", type: "v.", meaning: "กักตัว" },
    { word: "detection", type: "n.", meaning: "การตรวจจับ" },
    { word: "detention", type: "n.", meaning: "การกักกัน" },
    { word: "deteriorate", type: "v.", meaning: "เสื่อมโทรมลง" },
    { word: "devastate", type: "v.", meaning: "ทำลายล้าง" },
    { word: "devil", type: "n.", meaning: "ปีศาจ" },
    { word: "devise", type: "v.", meaning: "ประดิษฐ์, คิดค้น" },
    { word: "diagnose", type: "v.", meaning: "วินิจฉัย" },
    { word: "diagnosis", type: "n.", meaning: "การวินิจฉัย" },
    { word: "dictate", type: "v.", meaning: "บงการ, กำหนด" },
    { word: "dictator", type: "n.", meaning: "เผด็จการ" },
    { word: "differentiate", type: "v.", meaning: "แยกแยะความแตกต่าง" },
    { word: "dignity", type: "n.", meaning: "ศักดิ์ศรี" },
    { word: "dilemma", type: "n.", meaning: "ภาวะที่กลืนไม่เข้าคายไม่ออก" },
    { word: "dimension", type: "n.", meaning: "มิติ" },
    { word: "diminish", type: "v.", meaning: "ลดลง" },
    { word: "dip", type: "v.", meaning: "จุ่ม, แช่" },
    { word: "diplomat", type: "n.", meaning: "นักการทูต" },
    { word: "diplomatic", type: "n.", meaning: "ทางการทูต" },
    { word: "directory", type: "n.", meaning: "สมุดรายนาม, สารบบ" },
    { word: "disastrous", type: "adj.", meaning: "หายนะ, เป็นภัยพิบัติ" },
    { word: "discard", type: "v.", meaning: "ทิ้ง" },
    { word: "discharge", type: "v.", meaning: "ปลดประจำการ, ปล่อย" },
    { word: "disclose", type: "v.", meaning: "เปิดเผย" },
    { word: "disclosure", type: "n.", meaning: "การเปิดเผย" },
    { word: "discourse", type: "n.", meaning: "วาทกรรม, การสนทนา" },
    { word: "discretion", type: "n.", meaning: "ดุลยพินิจ" },
    { word: "discrimination", type: "n.", meaning: "การเลือกปฏิบัติ, การแบ่งแยก" },
    { word: "dismissal", type: "n.", meaning: "การไล่ออก, การปัดทิ้ง" },
    { word: "displace", type: "v.", meaning: "แทนที่, ทำให้ต้องย้ายที่อยู่" },
    { word: "disposal", type: "n.", meaning: "การกำจัด" },
    { word: "dispose", type: "v.", meaning: "กำจัด" },
    { word: "dispute", type: "n., v.", meaning: "ข้อพิพาท, โต้แย้ง" },
    { word: "disrupt", type: "v.", meaning: "ขัดขวาง, ก่อกวน" },
    { word: "disruption", type: "n.", meaning: "การหยุดชะงัก, การก่อกวน" },
    { word: "dissolve", type: "v.", meaning: "ละลาย, ยุบ" },
    { word: "distinction", type: "n.", meaning: "ความแตกต่าง, ความโดดเด่น" },
    { word: "distinctive", type: "adj.", meaning: "โดดเด่น, มีเอกลักษณ์" },
    { word: "distort", type: "v.", meaning: "บิดเบือน" },
    { word: "distress", type: "n., v.", meaning: "ความทุกข์, ทำให้ทุกข์" },
    { word: "disturbing", type: "adj.", meaning: "น่ารบกวน, น่ากังวล" },
    { word: "divert", type: "v.", meaning: "เบี่ยงเบนความสนใจ, เปลี่ยนเส้นทาง" },
    { word: "divine", type: "adj.", meaning: "ศักดิ์สิทธิ์, เกี่ยวกับพระเจ้า" },
    { word: "doctrine", type: "n.", meaning: "หลักคำสอน, ลัทธิ" },
    { word: "documentation", type: "n.", meaning: "เอกสารประกอบ" },
    { word: "domain", type: "n.", meaning: "ขอบเขต, อาณาเขต" },
    { word: "dominance", type: "n.", meaning: "การครอบงำ" },
    { word: "donor", type: "n.", meaning: "ผู้บริจาค" },
    { word: "dose", type: "n.", meaning: "ปริมาณ (ยา)" },
    { word: "drain", type: "v.", meaning: "ระบายน้ำ, ทำให้แห้ง" },
    { word: "drift", type: "v.", meaning: "ลอยไป, ล่องลอย" },
    { word: "driving", type: "adj.", meaning: "ที่เป็นแรงผลักดัน" },
    { word: "drown", type: "v.", meaning: "จมน้ำ" },
    { word: "dual", type: "adj.", meaning: "สองส่วน, คู่" },
    { word: "dub", type: "v.", meaning: "พากย์เสียง, ขนานนาม" },
    { word: "dumb", type: "adj.", meaning: "ใบ้, โง่ (ไม่สุภาพ)" },
    { word: "duo", type: "n.", meaning: "คู่, สองคน" },
    { word: "dynamic", type: "n.", meaning: "พลวัต, พลัง" },
    { word: "eager", type: "adj.", meaning: "กระตือรือร้น" },
    { word: "earnings", type: "n.", meaning: "รายได้" },
    { word: "ease", type: "n., v.", meaning: "ความง่าย, ทำให้ง่ายขึ้น" },
    { word: "echo", type: "v., n.", meaning: "สะท้อน, เสียงสะท้อน" },
    { word: "ecological", type: "adj.", meaning: "เกี่ยวกับนิเวศวิทยา" },
    { word: "educator", type: "n.", meaning: "นักการศึกษา" },
    { word: "effectiveness", type: "n.", meaning: "ประสิทธิผล" },
    { word: "efficiency", type: "n.", meaning: "ประสิทธิภาพ" },
    { word: "ego", type: "n.", meaning: "อัตตา" },
    { word: "elaborate", type: "adj.", meaning: "ซับซ้อน, ละเอียด" },
    { word: "electoral", type: "adj.", meaning: "เกี่ยวกับการเลือกตั้ง" },
    { word: "elevate", type: "v.", meaning: "ยกระดับ" },
    { word: "eligible", type: "adj.", meaning: "มีสิทธิ์" },
    { word: "elite", type: "n.", meaning: "ชนชั้นนำ" },
    { word: "embark", type: "v.", meaning: "ขึ้นเรือ/เครื่องบิน, เริ่มต้น" },
    { word: "embarrassment", type: "n.", meaning: "ความอับอาย" },
    { word: "embassy", type: "n.", meaning: "สถานทูต" },
    { word: "embed", type: "v.", meaning: "ฝัง, ตรึง" },
    { word: "embody", type: "v.", meaning: "รวมเป็นหนึ่ง, เป็นตัวแทนของ" },
    { word: "emergence", type: "n.", meaning: "การเกิดขึ้น, การโผล่ออกมา" },
    { word: "empirical", type: "adj.", meaning: "เชิงประจักษ์" },
    { word: "empower", type: "v.", meaning: "ให้อำนาจ, ทำให้มีพลัง" },
    { word: "enact", type: "v.", meaning: "ตรากฎหมาย, บัญญัติ" },
    { word: "encompass", type: "v.", meaning: "ครอบคลุม" },
    { word: "encouragement", type: "n.", meaning: "กำลังใจ, การส่งเสริม" },
    { word: "encouraging", type: "adj.", meaning: "ให้กำลังใจ" },
    { word: "endeavour", type: "n.", meaning: "ความพยายาม" },
    { word: "endless", type: "adj.", meaning: "ไม่มีที่สิ้นสุด" },
    { word: "endorse", type: "v.", meaning: "รับรอง, สนับสนุน" },
    { word: "endorsement", type: "n.", meaning: "การรับรอง, การสนับสนุน" },
    { word: "endure", type: "v.", meaning: "อดทน, คงอยู่" },
    { word: "enforce", type: "v.", meaning: "บังคับใช้" },
    { word: "enforcement", type: "n.", meaning: "การบังคับใช้" },
    { word: "engagement", type: "n.", meaning: "การมีส่วนร่วม, การหมั้น" },
    { word: "engaging", type: "adj.", meaning: "น่าดึงดูดใจ" },
    { word: "enquire", type: "v.", meaning: "สอบถาม" },
    { word: "enrich", type: "v.", meaning: "ทำให้สมบูรณ์ขึ้น, เสริมคุณค่า" },
    { word: "enrol", type: "v.", meaning: "ลงทะเบียน, สมัครเรียน" },
    { word: "ensue", type: "v.", meaning: "เกิดขึ้นตามมา" },
    { word: "enterprise", type: "n.", meaning: "องค์กร, กิจการ" },
    { word: "enthusiast", type: "n.", meaning: "ผู้กระตือรือร้น, ผู้คลั่งไคล้" },
    { word: "entitle", type: "v.", meaning: "ให้สิทธิ์" },
    { word: "entity", type: "n.", meaning: "หน่วยงาน, สิ่งที่มีอยู่จริง" },
    { word: "epidemic", type: "n.", meaning: "โรคระบาด" },
    { word: "equality", type: "n.", meaning: "ความเท่าเทียม" },
    { word: "equation", type: "n.", meaning: "สมการ" },
    { word: "erect", type: "v.", meaning: "สร้าง, ตั้งตรง" },
    { word: "escalate", type: "v.", meaning: "ทวีความรุนแรงขึ้น" },
    { word: "essence", type: "n.", meaning: "แก่นแท้" },
    { word: "establishment", type: "n.", meaning: "การก่อตั้ง, สถานประกอบการ" },
    { word: "eternal", type: "adj.", meaning: "นิรันดร์" },
    { word: "evacuate", type: "v.", meaning: "อพยพ" },
    { word: "evoke", type: "v.", meaning: "กระตุ้น (ความรู้สึก), ทำให้ระลึกถึง" },
    { word: "evolutionary", type: "adj.", meaning: "เกี่ยวกับวิวัฒนาการ" },
    { word: "exaggerate", type: "v.", meaning: "กล่าวเกินจริง" },
    { word: "excellence", type: "n.", meaning: "ความเป็นเลิศ" },
    { word: "exceptional", type: "adj.", meaning: "ยอดเยี่ยม, เป็นพิเศษ" },
    { word: "excess", type: "n., adj.", meaning: "ส่วนเกิน, มากเกินไป" },
    { word: "exclusion", type: "n.", meaning: "การกีดกัน, การยกเว้น" },
    { word: "exclusive", type: "adj.", meaning: "พิเศษ, เฉพาะ" },
    { word: "exclusively", type: "adv.", meaning: "โดยเฉพาะ" },
    { word: "execute", type: "v.", meaning: "ประหารชีวิต, ดำเนินการ" },
    { word: "execution", type: "n.", meaning: "การประหารชีวิต, การดำเนินการ" },
    { word: "exert", type: "v.", meaning: "ออกแรง, ใช้อำนาจ" },
    { word: "exile", type: "n.", meaning: "การเนรเทศ, ผู้ถูกเนรเทศ" },
    { word: "exit", type: "v.", meaning: "ออกไป" },
    { word: "expenditure", type: "n.", meaning: "รายจ่าย" },
    { word: "experimental", type: "adj.", meaning: "เชิงทดลอง" },
    { word: "expire", type: "v.", meaning: "หมดอายุ" },
    { word: "explicit", type: "adj.", meaning: "ชัดเจน, ตรงไปตรงมา" },
    { word: "explicitly", type: "adv.", meaning: "อย่างชัดเจน" },
    { word: "exploitation", type: "n.", meaning: "การแสวงหาผลประโยชน์" },
    { word: "explosive", type: "adj., n.", meaning: "ระเบิดได้, วัตถุระเบิด" },
    { word: "extract", type: "v.", meaning: "สกัด, ถอน" },
    { word: "extremist", type: "n.", meaning: "พวกหัวรุนแรง" },
    { word: "facilitate", type: "v.", meaning: "อำนวยความสะดวก" },
    { word: "faction", type: "n.", meaning: "ฝ่าย, กลุ่ม (ในการเมือง)" },
    { word: "faculty", type: "n.", meaning: "คณะ (ในมหาวิทยาลัย), คณาจารย์" },
    { word: "fade", type: "v.", meaning: "จางหายไป" },
    { word: "fairness", type: "n.", meaning: "ความเป็นธรรม" },
    { word: "fatal", type: "adj.", meaning: "ถึงตาย" },
    { word: "fate", type: "n.", meaning: "โชคชะตา" },
    { word: "favourable", type: "adj.", meaning: "เป็นที่ชื่นชอบ, เอื้ออำนวย" },
    { word: "feat", type: "n.", meaning: "ความสำเร็จที่ยิ่งใหญ่" },
    { word: "feminist", type: "adj., n.", meaning: "สตรีนิยม" },
    { word: "fibre", type: "n.", meaning: "เส้นใย" },
    { word: "fierce", type: "adj.", meaning: "ดุร้าย, รุนแรง" },
    { word: "film-maker", type: "n.", meaning: "ผู้สร้างภาพยนตร์" },
    { word: "filter", type: "n., v.", meaning: "ตัวกรอง, กรอง" },
    { word: "fine", type: "n., v.", meaning: "ค่าปรับ, ปรับ" },
    { word: "firearm", type: "n.", meaning: "อาวุธปืน" },
    { word: "fit", type: "n.", meaning: "การพอดี, การโจมตี (โรค)" },
    { word: "fixture", type: "n.", meaning: "เครื่องตกแต่ง, การแข่งขันที่กำหนดไว้" },
    { word: "flaw", type: "n.", meaning: "ข้อบกพร่อง" },
    { word: "flawed", type: "adj.", meaning: "มีข้อบกพร่อง" },
    { word: "flee", type: "v.", meaning: "หลบหนี" },
    { word: "fleet", type: "n.", meaning: "กองเรือ, ฝูงบิน" },
    { word: "flesh", type: "n.", meaning: "เนื้อ (ของคน/สัตว์)" },
    { word: "flexibility", type: "n.", meaning: "ความยืดหยุ่น" },
    { word: "flourish", type: "v.", meaning: "เจริญรุ่งเรือง" },
    { word: "fluid", type: "n.", meaning: "ของไหล, ของเหลว" },
    { word: "footage", type: "n.", meaning: "ภาพวิดีโอ, ฟุตเทจ" },
    { word: "foreigner", type: "n.", meaning: "ชาวต่างชาติ" },
    { word: "forge", type: "v.", meaning: "ปลอมแปลง, หลอม" },
    { word: "formula", type: "n.", meaning: "สูตร" },
    { word: "formulate", type: "v.", meaning: "กำหนดสูตร, คิดค้น" },
    { word: "forth", type: "adv.", meaning: "ไปข้างหน้า" },
    { word: "forthcoming", type: "adj.", meaning: "ที่จะมาถึง, ที่กำลังจะเกิดขึ้น" },
    { word: "foster", type: "v.", meaning: "ส่งเสริม, อุปถัมภ์" },
    { word: "fragile", type: "adj.", meaning: "เปราะบาง" },
    { word: "franchise", type: "n.", meaning: "แฟรนไชส์" },
    { word: "frankly", type: "adv.", meaning: "อย่างตรงไปตรงมา" },
    { word: "frustrated", type: "adj.", meaning: "หงุดหงิด, ท้อแท้" },
    { word: "frustrating", type: "adj.", meaning: "น่าหงุดหงิด" },
    { word: "frustration", type: "n.", meaning: "ความหงุดหงิด, ความท้อแท้" },
    { word: "functional", type: "adj.", meaning: "ใช้งานได้" },
    { word: "fundraising", type: "n.", meaning: "การระดมทุน" },
    { word: "funeral", type: "n.", meaning: "งานศพ" },
    { word: "gallon", type: "n.", meaning: "แกลลอน (หน่วยวัดปริมาตร)" },
    { word: "gambling", type: "n.", meaning: "การพนัน" },
    { word: "gathering", type: "n.", meaning: "การรวมตัว, การชุมนุม" },
    { word: "gaze", type: "n., v.", meaning: "การจ้องมอง, จ้องมอง" },
    { word: "gear", type: "n.", meaning: "เกียร์, อุปกรณ์" },
    { word: "generic", type: "adj.", meaning: "ทั่วไป, ไม่มียี่ห้อ" },
    { word: "genocide", type: "n.", meaning: "การฆ่าล้างเผ่าพันธุ์" },
    { word: "glance", type: "n., v.", meaning: "การชำเลืองมอง, ชำเลืองมอง" },
    { word: "glimpse", type: "n.", meaning: "การเหลือบมอง, การเห็นแวบหนึ่ง" },
    { word: "glorious", type: "adj.", meaning: "รุ่งโรจน์, มีเกียรติ" },
    { word: "glory", type: "n.", meaning: "ความรุ่งโรจน์, เกียรติยศ" },
    { word: "governance", type: "n.", meaning: "ธรรมาภิบาล, การปกครอง" },
    { word: "grace", type: "n.", meaning: "ความสง่างาม, ความเมตตา" },
    { word: "grasp", type: "v., n.", meaning: "จับ, เข้าใจ, การจับ" },
    { word: "grave", type: "n., adj.", meaning: "หลุมศพ, ร้ายแรง, สำคัญ" },
    { word: "gravity", type: "n.", meaning: "แรงโน้มถ่วง, ความจริงจัง" },
    { word: "grid", type: "n.", meaning: "ตาราง, โครงข่าย" },
    { word: "grief", type: "n.", meaning: "ความโศกเศร้า" },
    { word: "grin", type: "v., n.", meaning: "ยิ้มกว้าง, รอยยิ้มกว้าง" },
    { word: "grind", type: "v.", meaning: "บด, โม่" },
    { word: "grip", type: "n., v.", meaning: "การยึดจับ, ยึดจับ" },
    { word: "gross", type: "adj.", meaning: "รวมทั้งหมด (ก่อนหักค่าใช้จ่าย), หยาบคาย" },
    { word: "guerrilla", type: "n.", meaning: "กองโจร" },
    { word: "guidance", type: "n.", meaning: "คำแนะนำ" },
    { word: "guilt", type: "n.", meaning: "ความรู้สึกผิด" },
    { word: "gut", type: "n.", meaning: "ลำไส้ (ไม่เป็นทางการ), สัญชาตญาณ" },
    { word: "hail", type: "v.", meaning: "ลูกเห็บตก, ทักทาย, เรียก" },
    { word: "halfway", type: "adv.", meaning: "ครึ่งทาง" },
    { word: "halt", type: "v., n.", meaning: "หยุด, การหยุด" },
    { word: "handful", type: "n.", meaning: "กำมือหนึ่ง, จำนวนน้อย" },
    { word: "handling", type: "n.", meaning: "การจัดการ" },
    { word: "handy", type: "adj.", meaning: "มีประโยชน์, สะดวก" },
    { word: "harassment", type: "n.", meaning: "การล่วงละเมิด" },
    { word: "hardware", type: "n.", meaning: "ฮาร์ดแวร์" },
    { word: "harmony", type: "n.", meaning: "ความสามัคคี, ความกลมกลืน" },
    { word: "harsh", type: "adj.", meaning: "รุนแรง, หยาบกระด้าง" },
    { word: "harvest", type: "n., v.", meaning: "การเก็บเกี่ยว, เก็บเกี่ยว" },
    { word: "hatred", type: "n.", meaning: "ความเกลียดชัง" },
    { word: "haunt", type: "v.", meaning: "หลอกหลอน" },
    { word: "hazard", type: "n.", meaning: "อันตราย" },
    { word: "heighten", type: "v.", meaning: "ทำให้สูงขึ้น, เพิ่มมากขึ้น" },
    { word: "heritage", type: "n.", meaning: "มรดก" },
    { word: "hierarchy", type: "n.", meaning: "ลำดับชั้น" },
    { word: "high-profile", type: "adj.", meaning: "เป็นที่รู้จักอย่างกว้างขวาง" },
    { word: "hint", type: "n., v.", meaning: "คำใบ้, บอกใบ้" },
    { word: "homeland", type: "n.", meaning: "บ้านเกิด" },
    { word: "hook", type: "v.", meaning: "เกี่ยว, ตกเบ็ด" },
    { word: "hopeful", type: "adj.", meaning: "มีความหวัง" },
    { word: "horizon", type: "n.", meaning: "ขอบฟ้า" },
    { word: "horn", type: "n.", meaning: "เขา (สัตว์), แตร" },
    { word: "hostage", type: "n.", meaning: "ตัวประกัน" },
    { word: "hostile", type: "adj.", meaning: "เป็นศัตรู, ไม่เป็นมิตร" },
    { word: "hostility", type: "n.", meaning: "ความเป็นศัตรู" },
    { word: "humanitarian", type: "adj.", meaning: "เกี่ยวกับมนุษยธรรม" },
    { word: "humanity", type: "n.", meaning: "มนุษยชาติ, มนุษยธรรม" },
    { word: "humble", type: "adj.", meaning: "ถ่อมตัว" },
    { word: "hydrogen", type: "n.", meaning: "ไฮโดรเจน" },
    { word: "identification", type: "n.", meaning: "การระบุตัวตน, บัตรประจำตัว" },
    { word: "ideological", type: "adj.", meaning: "เกี่ยวกับอุดมการณ์" },
    { word: "ideology", type: "n.", meaning: "อุดมการณ์" },
    { word: "idiot", type: "n.", meaning: "คนโง่" },
    { word: "ignorance", type: "n.", meaning: "ความไม่รู้" },
    { word: "imagery", type: "n.", meaning: "ภาพพจน์, รูปภาพ" },
    { word: "immense", type: "adj.", meaning: "ใหญ่โตมโหฬาร" },
    { word: "imminent", type: "adj.", meaning: "ใกล้จะเกิดขึ้น" },
    { word: "implementation", type: "n.", meaning: "การนำไปปฏิบัติ" },
    { word: "imprison", type: "v.", meaning: "จำคุก" },
    { word: "imprisonment", type: "n.", meaning: "การจำคุก" },
    { word: "inability", type: "n.", meaning: "การไร้ความสามารถ" },
    { word: "inadequate", type: "adj.", meaning: "ไม่เพียงพอ" },
    { word: "inappropriate", type: "adj.", meaning: "ไม่เหมาะสม" },
    { word: "incidence", type: "n.", meaning: "อุบัติการณ์, การเกิด" },
    { word: "inclined", type: "adj.", meaning: "มีแนวโน้มที่จะ" },
    { word: "inclusion", type: "n.", meaning: "การรวมเข้าด้วยกัน" },
    { word: "incur", type: "v.", meaning: "ประสบ (หนี้สิน/ความเสียหาย)" },
    { word: "indicator", type: "n.", meaning: "ตัวบ่งชี้" },
    { word: "indictment", type: "n.", meaning: "การฟ้องร้อง" },
    { word: "indigenous", type: "adj.", meaning: "พื้นเมือง" },
    { word: "induce", type: "v.", meaning: "ชักจูง, ก่อให้เกิด" },
    { word: "indulge", type: "v.", meaning: "ตามใจ, ดื่มด่ำ" },
    { word: "inequality", type: "n.", meaning: "ความไม่เท่าเทียมกัน" },
    { word: "infamous", type: "adj.", meaning: "ฉาวโฉ่, เสื่อมเสีย" },
    { word: "infant", type: "n.", meaning: "ทารก" },
    { word: "infect", type: "v.", meaning: "ติดเชื้อ" },
    { word: "inflict", type: "v.", meaning: "ก่อให้เกิด (ความเสียหาย, ความเจ็บปวด)" },
    { word: "influential", type: "adj.", meaning: "มีอิทธิพล" },
    { word: "inherent", type: "adj.", meaning: "โดยธรรมชาติ, โดยเนื้อแท้" },
    { word: "inhibit", type: "v.", meaning: "ยับยั้ง" },
    { word: "initiate", type: "v.", meaning: "เริ่มต้น, ริเริ่ม" },
    { word: "inject", type: "v.", meaning: "ฉีด" },
    { word: "injection", type: "n.", meaning: "การฉีด" },
    { word: "injustice", type: "n.", meaning: "ความอยุติธรรม" },
    { word: "inmate", type: "n.", meaning: "ผู้ต้องขัง" },
    { word: "insertion", type: "n.", meaning: "การสอดใส่" },
    { word: "insider", type: "n.", meaning: "คนภายใน" },
    { word: "inspect", type: "v.", meaning: "ตรวจสอบ" },
    { word: "inspection", type: "n.", meaning: "การตรวจสอบ" },
    { word: "inspiration", type: "n.", meaning: "แรงบันดาลใจ" },
    { word: "instinct", type: "n.", meaning: "สัญชาตญาณ" },
    { word: "institutional", type: "adj.", meaning: "เกี่ยวกับสถาบัน" },
    { word: "instruct", type: "v.", meaning: "สั่งสอน, แนะนำ" },
    { word: "instrumental", type: "adj.", meaning: "เป็นเครื่องมือ, มีส่วนสำคัญ" },
    { word: "insufficient", type: "adj.", meaning: "ไม่เพียงพอ" },
    { word: "insult", type: "n., v.", meaning: "การดูถูก, ดูถูก" },
    { word: "intact", type: "adj.", meaning: "ไม่บุบสลาย, คงเดิม" },
    { word: "intake", type: "n.", meaning: "การนำเข้า, ปริมาณที่รับเข้า" },
    { word: "integral", type: "adj.", meaning: "สำคัญยิ่ง, เป็นส่วนหนึ่ง" },
    { word: "integrated", type: "adj.", meaning: "บูรณาการ" },
    { word: "integration", type: "n.", meaning: "การบูรณาการ, การรวมเข้าด้วยกัน" },
    { word: "integrity", type: "n.", meaning: "ความซื่อสัตย์, ความสมบูรณ์" },
    { word: "intellectual", type: "n.", meaning: "ปัญญาชน" },
    { word: "intensify", type: "v.", meaning: "ทำให้เข้มข้นขึ้น" },
    { word: "intensity", type: "n.", meaning: "ความเข้มข้น, ความรุนแรง" },
    { word: "intensive", type: "adj.", meaning: "เข้มข้น" },
    { word: "intent", type: "n.", meaning: "ความตั้งใจ, เจตนา" },
    { word: "interactive", type: "adj.", meaning: "โต้ตอบได้" },
    { word: "interface", type: "n.", meaning: "ส่วนต่อประสาน" },
    { word: "interfere", type: "v.", meaning: "แทรกแซง" },
    { word: "interference", type: "n.", meaning: "การแทรกแซง" },
    { word: "interim", type: "adj.", meaning: "ชั่วคราว" },
    { word: "interior", type: "adj., n.", meaning: "ภายใน, ส่วนภายใน" },
    { word: "intermediate", type: "adj.", meaning: "ระดับกลาง" },
    { word: "intervene", type: "v.", meaning: "แทรกแซง" },
    { word: "intervention", type: "n.", meaning: "การแทรกแซง" },
    { word: "intimate", type: "adj.", meaning: "ใกล้ชิด, สนิทสนม" },
    { word: "intriguing", type: "adj.", meaning: "น่าสนใจ, น่าทึ่ง" },
    { word: "investigator", type: "n.", meaning: "ผู้สืบสวน" },
    { word: "invisible", type: "adj.", meaning: "มองไม่เห็น" },
    { word: "invoke", type: "v.", meaning: "อ้างถึง, เรียกใช้" },
    { word: "involvement", type: "n.", meaning: "การมีส่วนร่วม" },
    { word: "ironic", type: "adj.", meaning: "เสียดสี, แดกดัน" },
    { word: "ironically", type: "adv.", meaning: "อย่างเสียดสี, อย่างแดกดัน" },
    { word: "irony", type: "n.", meaning: "การเสียดสี, ความย้อนแย้ง" },
    { word: "irrelevant", type: "adj.", meaning: "ไม่เกี่ยวข้อง" },
    { word: "isolation", type: "n.", meaning: "การแยกตัว, ความโดดเดี่ยว" },
    { word: "judicial", type: "adj.", meaning: "เกี่ยวกับการพิจารณาคดี, ตุลาการ" },
    { word: "junction", type: "n.", meaning: "ทางแยก, จุดเชื่อมต่อ" },
    { word: "jurisdiction", type: "n.", meaning: "อำนาจศาล, เขตอำนาจ" },
    { word: "just", type: "adj.", meaning: "ยุติธรรม" },
    { word: "justification", type: "n.", meaning: "การให้เหตุผล, ความชอบธรรม" },
    { word: "kidnap", type: "v.", meaning: "ลักพาตัว" },
    { word: "kidney", type: "n.", meaning: "ไต" },
    { word: "kingdom", type: "n.", meaning: "อาณาจักร" },
    { word: "lad", type: "n.", meaning: "เด็กหนุ่ม (ไม่เป็นทางการ)" },
    { word: "landlord", type: "n.", meaning: "เจ้าของบ้านเช่า" },
    { word: "landmark", type: "n.", meaning: "จุดสังเกต, สถานที่สำคัญ" },
    { word: "lap", type: "n.", meaning: "ตัก (ที่นั่ง), รอบ (ในการแข่งขัน)" },
    { word: "large-scale", type: "adj.", meaning: "ขนาดใหญ่" },
    { word: "laser", type: "n.", meaning: "เลเซอร์" },
    { word: "latter", type: "adj., n.", meaning: "ส่วนหลัง, อย่างหลัง" },
    { word: "lawn", type: "n.", meaning: "สนามหญ้า" },
    { word: "lawsuit", type: "n.", meaning: "คดีความ" },
    { word: "layout", type: "n.", meaning: "ผัง, การจัดวาง" },
    { word: "leak", type: "v., n.", meaning: "รั่ว, การรั่วไหล" },
    { word: "leap", type: "v., n.", meaning: "กระโดด, การกระโดด" },
    { word: "legacy", type: "n.", meaning: "มรดก" },
    { word: "legendary", type: "adj.", meaning: "ในตำนาน" },
    { word: "legislation", type: "n.", meaning: "การออกกฎหมาย, กฎหมาย" },
    { word: "legislative", type: "adj.", meaning: "เกี่ยวกับการออกกฎหมาย" },
    { word: "legislature", type: "n.", meaning: "สภานิติบัญญัติ" },
    { word: "legitimate", type: "adj.", meaning: "ชอบด้วยกฎหมาย, ถูกต้อง" },
    { word: "lengthy", type: "adj.", meaning: "ยาวนาน" },
    { word: "lesbian", type: "adj.", meaning: "เลสเบี้ยน" },
    { word: "lesser", type: "adj.", meaning: "น้อยกว่า, ด้อยกว่า" },
    { word: "lethal", type: "adj.", meaning: "ถึงตาย" },
    { word: "liable", type: "adj.", meaning: "มีแนวโน้มที่จะ, รับผิดชอบ" },
    { word: "liberal", type: "adj., n.", meaning: "เสรีนิยม" },
    { word: "liberation", type: "n.", meaning: "การปลดปล่อย" },
    { word: "liberty", type: "n.", meaning: "เสรีภาพ" },
    { word: "license", type: "v.", meaning: "ออกใบอนุญาต" },
    { word: "lifelong", type: "adj.", meaning: "ตลอดชีวิต" },
    { word: "likelihood", type: "n.", meaning: "ความเป็นไปได้" },
    { word: "limb", type: "n.", meaning: "แขนขา" },
    { word: "linear", type: "adj.", meaning: "เชิงเส้น" },
    { word: "line-up", type: "n.", meaning: "ผู้เล่นตัวจริง, การจัดแถว" },
    { word: "linger", type: "v.", meaning: "ยังคงอยู่, อ้อยอิ่ง" },
    { word: "listing", type: "n.", meaning: "รายการ, การลงรายการ" },
    { word: "literacy", type: "n.", meaning: "การรู้หนังสือ" },
    { word: "liver", type: "n.", meaning: "ตับ" },
    { word: "lobby", type: "n., v.", meaning: "ห้องโถง, ล็อบบี้, ล็อบบี้ (การเมือง)" },
    { word: "log", type: "n., v.", meaning: "ท่อนไม้, บันทึก, ตัดไม้" },
    { word: "logic", type: "n.", meaning: "ตรรกะ" },
    { word: "long-standing", type: "adj.", meaning: "ยาวนาน (ที่ดำรงอยู่มานาน)" },
    { word: "long-time", type: "adj.", meaning: "เป็นเวลานาน" },
    { word: "loom", type: "v.", meaning: "ปรากฏขึ้นอย่างน่ากลัว" },
    { word: "loop", type: "n.", meaning: "ห่วง, วง" },
    { word: "loyalty", type: "n.", meaning: "ความภักดี" },
    { word: "machinery", type: "n.", meaning: "เครื่องจักร" },
    { word: "magical", type: "adj.", meaning: "มีมนต์ขลัง" },
    { word: "magistrate", type: "n.", meaning: "ผู้พิพากษาศาลแขวง" },
    { word: "magnetic", type: "adj.", meaning: "แม่เหล็ก" },
    { word: "magnitude", type: "n.", meaning: "ขนาด, ความสำคัญ" },
    { word: "mainland", type: "n.", meaning: "แผ่นดินใหญ่" },
    { word: "mainstream", type: "n., adj.", meaning: "กระแสหลัก" },
    { word: "maintenance", type: "n.", meaning: "การบำรุงรักษา" },
    { word: "mandate", type: "n.", meaning: "อาณัติ, คำสั่ง" },
    { word: "mandatory", type: "adj.", meaning: "บังคับ" },
    { word: "manifest", type: "v.", meaning: "แสดงให้เห็นอย่างชัดเจน" },
    { word: "manipulate", type: "v.", meaning: "บงการ, จัดการ" },
    { word: "manipulation", type: "n.", meaning: "การบงการ, การจัดการ" },
    { word: "manuscript", type: "n.", meaning: "ต้นฉบับ" },
    { word: "march", type: "n., v.", meaning: "การเดินขบวน, เดินขบวน" },
    { word: "marginal", type: "adj.", meaning: "เล็กน้อย, Marginal" },
    { word: "marine", type: "adj.", meaning: "เกี่ยวกับทะเล" },
    { word: "marketplace", type: "n.", meaning: "ตลาด" },
    { word: "mask", type: "n.", meaning: "หน้ากาก" },
    { word: "massacre", type: "n.", meaning: "การสังหารหมู่" },
    { word: "mathematical", type: "adj.", meaning: "ทางคณิตศาสตร์" },
    { word: "mature", type: "adj., v.", meaning: "เป็นผู้ใหญ่, โตเต็มที่" },
    { word: "maximize", type: "v.", meaning: "ทำให้มากที่สุด" },
    { word: "meaningful", type: "adj.", meaning: "มีความหมาย" },
    { word: "meantime", type: "n.", meaning: "ในระหว่างนั้น" },
    { word: "medieval", type: "adj.", meaning: "สมัยกลาง" },
    { word: "meditation", type: "n.", meaning: "การทำสมาธิ" },
    { word: "melody", type: "n.", meaning: "ทำนอง" },
    { word: "memo", type: "n.", meaning: "บันทึกช่วยจำ" },
    { word: "memoir", type: "n.", meaning: "บันทึกความทรงจำ" },
    { word: "memorial", type: "n.", meaning: "อนุสรณ์" },
    { word: "mentor", type: "n.", meaning: "ที่ปรึกษา" },
    { word: "merchant", type: "n.", meaning: "พ่อค้า" },
    { word: "mercy", type: "n.", meaning: "ความเมตตา" },
    { word: "mere", type: "adj.", meaning: "เป็นเพียงแค่" },
    { word: "merely", type: "adv.", meaning: "เป็นเพียงแค่" },
    { word: "merge", type: "v.", meaning: "รวมเข้าด้วยกัน" },
    { word: "merger", type: "n.", meaning: "การควบรวมกิจการ" },
    { word: "merit", type: "n.", meaning: "คุณงามความดี, ข้อดี" },
    { word: "methodology", type: "n.", meaning: "ระเบียบวิธีวิจัย" },
    { word: "midst", type: "n.", meaning: "ท่ามกลาง" },
    { word: "migration", type: "n.", meaning: "การอพยพ" },
    { word: "militant", type: "n., adj.", meaning: "ผู้ก่อความไม่สงบ, หัวรุนแรง" },
    { word: "militia", type: "n.", meaning: "กองกำลังอาสาสมัคร" },
    { word: "mill", type: "n.", meaning: "โรงสี, โรงงาน" },
    { word: "minimal", type: "adj.", meaning: "น้อยที่สุด" },
    { word: "minimize", type: "v.", meaning: "ลดให้น้อยที่สุด" },
    { word: "mining", type: "n.", meaning: "การทำเหมืองแร่" },
    { word: "ministry", type: "n.", meaning: "กระทรวง" },
    { word: "minute", type: "adj.", meaning: "เล็กมาก, ละเอียดมาก" },
    { word: "miracle", type: "n.", meaning: "ปาฏิหาริย์" },
    { word: "misery", type: "n.", meaning: "ความทุกข์ยาก" },
    { word: "misleading", type: "adj.", meaning: "ทำให้เข้าใจผิด" },
    { word: "missile", type: "n.", meaning: "ขีปนาวุธ" },
    { word: "mob", type: "n.", meaning: "ฝูงชนที่ก่อความไม่สงบ" },
    { word: "mobility", type: "n.", meaning: "การเคลื่อนที่" },
    { word: "mobilize", type: "v.", meaning: "ระดมพล" },
    { word: "moderate", type: "adj.", meaning: "ปานกลาง, ไม่รุนแรง" },
    { word: "modification", type: "n.", meaning: "การดัดแปลง" },
    { word: "momentum", type: "n.", meaning: "แรงเหวี่ยง, แรงผลักดัน" },
    { word: "monk", type: "n.", meaning: "พระ, ภิกษุ" },
    { word: "monopoly", type: "n.", meaning: "การผูกขาด" },
    { word: "morality", type: "n.", meaning: "คุณธรรม" },
    { word: "motive", type: "n.", meaning: "แรงจูงใจ" },
    { word: "motorist", type: "n.", meaning: "ผู้ขับขี่ยานยนต์" },
    { word: "municipal", type: "adj.", meaning: "เกี่ยวกับเทศบาล" },
    { word: "mutual", type: "adj.", meaning: "ซึ่งกันและกัน" },
    { word: "namely", type: "adv.", meaning: "คือ, กล่าวคือ" },
    { word: "nationwide", type: "adj.", meaning: "ทั่วประเทศ" },
    { word: "naval", type: "adj.", meaning: "เกี่ยวกับกองทัพเรือ" },
    { word: "neglect", type: "v., n.", meaning: "ละเลย, การละเลย" },
    { word: "neighbouring", type: "adj.", meaning: "ใกล้เคียง" },
    { word: "nest", type: "n.", meaning: "รัง" },
    { word: "net", type: "adj.", meaning: "สุทธิ, แท้จริง" },
    { word: "newsletter", type: "n.", meaning: "จดหมายข่าว" },
    { word: "niche", type: "n.", meaning: "ตลาดเฉพาะกลุ่ม, ช่อง" },
    { word: "noble", type: "adj.", meaning: "สูงศักดิ์, มีเกียรติ" },
    { word: "nod", type: "v.", meaning: "พยักหน้า" },
    { word: "nominate", type: "v.", meaning: "เสนอชื่อ, แต่งตั้ง" },
    { word: "nomination", type: "n.", meaning: "การเสนอชื่อ" },
    { word: "nominee", type: "n.", meaning: "ผู้ถูกเสนอชื่อ" },
    { word: "nonetheless", type: "adv.", meaning: "ถึงกระนั้นก็ตาม" },
    { word: "non-profit", type: "adj.", meaning: "ไม่แสวงหาผลกำไร" },
    { word: "nonsense", type: "n.", meaning: "เรื่องไร้สาระ" },
    { word: "noon", type: "n.", meaning: "เที่ยงวัน" },
    { word: "notable", type: "adj.", meaning: "โดดเด่น, น่าสังเกต" },
    { word: "notably", type: "adv.", meaning: "อย่างเห็นได้ชัด, โดยเฉพาะอย่างยิ่ง" },
    { word: "notify", type: "v.", meaning: "แจ้งให้ทราบ" },
    { word: "notorious", type: "adj.", meaning: "ฉาวโฉ่" },
    { word: "novel", type: "adj.", meaning: "ใหม่, แปลกใหม่" },
    { word: "nursery", type: "n.", meaning: "สถานรับเลี้ยงเด็ก, ห้องเพาะชำ" },
    { word: "objection", type: "n.", meaning: "การคัดค้าน" },
    { word: "oblige", type: "v.", meaning: "บังคับ, ผูกมัด" },
    { word: "obsess", type: "v.", meaning: "ครอบงำ (ความคิด), หมกมุ่น" },
    { word: "obsession", type: "n.", meaning: "การหมกมุ่น" },
    { word: "occasional", type: "adj.", meaning: "บางครั้งบางคราว" },
    { word: "occurrence", type: "n.", meaning: "การเกิดขึ้น" },
    { word: "odds", type: "n.", meaning: "โอกาส, ความเป็นไปได้" },
    { word: "offering", type: "n.", meaning: "ข้อเสนอ, สิ่งที่เสนอ" },
    { word: "offspring", type: "n.", meaning: "ลูกหลาน, ผลผลิต" },
    { word: "operational", type: "adj.", meaning: "ที่ใช้งานได้, เกี่ยวกับการปฏิบัติงาน" },
    { word: "opt", type: "v.", meaning: "เลือก" },
    { word: "optical", type: "adj.", meaning: "เกี่ยวกับสายตา/แสง" },
    { word: "optimism", type: "n.", meaning: "การมองโลกในแง่ดี" },
    { word: "oral", type: "adj.", meaning: "ทางปาก, ด้วยวาจา" },
    { word: "organizational", type: "adj.", meaning: "เกี่ยวกับองค์กร" },
    { word: "orientation", type: "n.", meaning: "การปฐมนิเทศ, การปรับตัว" },
    { word: "originate", type: "v.", meaning: "มีกำเนิดมาจาก" },
    { word: "outbreak", type: "n.", meaning: "การระบาด, การปะทุ" },
    { word: "outing", type: "n.", meaning: "การออกไปเที่ยว" },
    { word: "outlet", type: "n.", meaning: "ช่องระบายอากาศ, ร้านค้า" },
    { word: "outlook", type: "n.", meaning: "ทัศนคติ, แนวโน้ม" },
    { word: "outrage", type: "n., v.", meaning: "ความโกรธแค้น, ทำให้โกรธแค้น" },
    { word: "outsider", type: "n.", meaning: "คนนอก" },
    { word: "overlook", type: "v.", meaning: "มองข้าม, ไม่สังเกตเห็น" },
    { word: "overly", type: "adv.", meaning: "มากเกินไป" },
    { word: "oversee", type: "v.", meaning: "ดูแล, ควบคุม" },
    { word: "overturn", type: "v.", meaning: "คว่ำ, ล้มล้าง (คำตัดสิน)" },
    { word: "overwhelm", type: "v.", meaning: "ท่วมท้น, ครอบงำ" },
    { word: "overwhelming", type: "adj.", meaning: "ท่วมท้น, ครอบงำ" },
    { word: "pad", type: "n.", meaning: "แผ่นรอง, เบาะ" },
    { word: "parameter", type: "n.", meaning: "พารามิเตอร์, ตัวแปร" },
    { word: "parental", type: "adj.", meaning: "เกี่ยวกับพ่อแม่" },
    { word: "parish", type: "n.", meaning: "เขตศาสนา, เขตปกครองย่อย" },
    { word: "parliamentary", type: "adj.", meaning: "เกี่ยวกับรัฐสภา" },
    { word: "partial", type: "adj.", meaning: "บางส่วน, ลำเอียง" },
    { word: "partially", type: "adv.", meaning: "บางส่วน" },
    { word: "passing", type: "n.", meaning: "การผ่านไป, การตาย" },
    { word: "passive", type: "adj.", meaning: "เฉื่อยชา, ไม่ตอบสนอง" },
    { word: "pastor", type: "n.", meaning: "ศิษยาภิบาล, บาทหลวง" },
    { word: "patch", type: "n.", meaning: "แผ่นแปะ, ผืนเล็กๆ" },
    { word: "patent", type: "n.", meaning: "สิทธิบัตร" },
    { word: "pathway", type: "n.", meaning: "ทางเดิน, วิถีทาง" },
    { word: "patrol", type: "n., v.", meaning: "การลาดตระเวน, ลาดตระเวน" },
    { word: "patron", type: "n.", meaning: "ผู้อุปถัมภ์" },
    { word: "peak", type: "n.", meaning: "ยอดเขา, จุดสูงสุด" },
    { word: "peasant", type: "n.", meaning: "ชาวนา" },
    { word: "peculiar", type: "adj.", meaning: "แปลกประหลาด, ผิดปกติ" },
    { word: "persist", type: "v.", meaning: "คงอยู่, ยืนกราน" },
    { word: "persistent", type: "adj.", meaning: "คงทน, ดื้อรั้น" },
    { word: "personnel", type: "n.", meaning: "บุคลากร" },
    { word: "petition", type: "n.", meaning: "คำร้อง, ฎีกา" },
    { word: "philosopher", type: "n.", meaning: "นักปรัชญา" },
    { word: "philosophical", type: "adj.", meaning: "ทางปรัชญา" },
    { word: "physician", type: "n.", meaning: "แพทย์" },
    { word: "pioneer", type: "n., v.", meaning: "ผู้บุกเบิก, บุกเบิก" },
    { word: "pipeline", type: "n.", meaning: "ท่อส่ง, ช่องทาง" },
    { word: "pirate", type: "n.", meaning: "โจรสลัด" },
    { word: "pit", type: "n.", meaning: "หลุม, บ่อ" },
    { word: "plea", type: "n.", meaning: "คำร้อง, ข้อแก้ต่าง" },
    { word: "plead", type: "v.", meaning: "วิงวอน, สารภาพ" },
    { word: "pledge", type: "v., n.", meaning: "ให้คำมั่นสัญญา, คำมั่นสัญญา" },
    { word: "plug", type: "v., n.", meaning: "เสียบปลั๊ก, ปลั๊ก" },
    { word: "plunge", type: "v.", meaning: "จุ่มลง, ตกฮวบ" },
    { word: "pole", type: "n.", meaning: "เสา, ขั้วโลก" },
    { word: "poll", type: "n.", meaning: "การสำรวจความคิดเห็น, การลงคะแนน" },
    { word: "pond", type: "n.", meaning: "บ่อน้ำ, สระน้ำ" },
    { word: "pop", type: "v.", meaning: "ปรากฏขึ้นทันที, แตก (เสียง)" },
    { word: "portfolio", type: "n.", meaning: "แฟ้มสะสมผลงาน" },
    { word: "portray", type: "v.", meaning: "พรรณนา, แสดงภาพ" },
    { word: "postpone", type: "v.", meaning: "เลื่อนออกไป" },
    { word: "post-war", type: "adj.", meaning: "หลังสงคราม" },
    { word: "practitioner", type: "n.", meaning: "ผู้ประกอบวิชาชีพ" },
    { word: "preach", type: "v.", meaning: "เทศนา, สั่งสอน" },
    { word: "precedent", type: "n.", meaning: "บรรทัดฐาน, แบบอย่าง" },
    { word: "precision", type: "n.", meaning: "ความแม่นยำ" },
    { word: "predator", type: "n.", meaning: "สัตว์นักล่า" },
    { word: "predecessor", type: "n.", meaning: "ผู้มาก่อน" },
    { word: "predominantly", type: "adv.", meaning: "ส่วนใหญ่, เด่นกว่า" },
    { word: "pregnancy", type: "n.", meaning: "การตั้งครรภ์" },
    { word: "prejudice", type: "n.", meaning: "อคติ" },
    { word: "preliminary", type: "adj.", meaning: "เบื้องต้น" },
    { word: "premier", type: "n.", meaning: "นายกรัฐมนตรี (ในบางประเทศ)" },
    { word: "premise", type: "n.", meaning: "ข้อสมมติ, ที่ตั้ง" },
    { word: "premium", type: "n.", meaning: "เบี้ยประกัน, ค่าพรีเมียม" },
    { word: "prescribe", type: "v.", meaning: "สั่งยา, กำหนด" },
    { word: "prescription", type: "n.", meaning: "ใบสั่งยา" },
    { word: "presently", type: "adv.", meaning: "ในไม่ช้า, ปัจจุบัน" },
    { word: "preservation", type: "n.", meaning: "การถนอม, การอนุรักษ์" },
    { word: "preside", type: "v.", meaning: "เป็นประธาน" },
    { word: "presidency", type: "n.", meaning: "ตำแหน่งประธานาธิบดี" },
    { word: "presidential", type: "adj.", meaning: "เกี่ยวกับประธานาธิบดี" },
    { word: "prestigious", type: "adj.", meaning: "มีชื่อเสียง, ทรงเกียรติ" },
    { word: "presumably", type: "adv.", meaning: "สันนิษฐานว่า" },
    { word: "presume", type: "v.", meaning: "สันนิษฐาน" },
    { word: "prevail", type: "v.", meaning: "มีอยู่ทั่วไป, มีชัย" },
    { word: "prevalence", type: "n.", meaning: "ความชุก, การแพร่หลาย" },
    { word: "prevention", type: "n.", meaning: "การป้องกัน" },
    { word: "prey", type: "n.", meaning: "เหยื่อ" },
    { word: "principal", type: "n.", meaning: "ครูใหญ่, อาจารย์ใหญ่, เงินต้น" },
    { word: "privatization", type: "n.", meaning: "การแปรรูปเป็นเอกชน" },
    { word: "privilege", type: "n.", meaning: "สิทธิพิเศษ" },
    { word: "probe", type: "n., v.", meaning: "การสอบสวน, สอบสวน" },
    { word: "problematic", type: "adj.", meaning: "ที่เป็นปัญหา" },
    { word: "proceedings", type: "n.", meaning: "การดำเนินคดี, การประชุม" },
    { word: "proceeds", type: "n.", meaning: "รายได้, เงินที่ได้มา" },
    { word: "processing", type: "n.", meaning: "การประมวลผล" },
    { word: "processor", type: "n.", meaning: "หน่วยประมวลผล" },
    { word: "proclaim", type: "v.", meaning: "ประกาศ, แถลง" },
    { word: "productive", type: "adj.", meaning: "มีประสิทธิผล" },
    { word: "productivity", type: "n.", meaning: "ประสิทธิภาพการผลิต" },
    { word: "profitable", type: "adj.", meaning: "ได้กำไร" },
    { word: "profound", type: "adj.", meaning: "ลึกซึ้ง" },
    { word: "projection", type: "n.", meaning: "การคาดการณ์, การฉายภาพ" },
    { word: "prominent", type: "adj.", meaning: "โดดเด่น, มีชื่อเสียง" },
    { word: "pronounced", type: "adj.", meaning: "เด่นชัด" },
    { word: "propaganda", type: "n.", meaning: "โฆษณาชวนเชื่อ" },
    { word: "proposition", type: "n.", meaning: "ข้อเสนอ, ข้อเสนอแนะ" },
    { word: "prosecute", type: "v.", meaning: "ดำเนินคดี" },
    { word: "prosecution", type: "n.", meaning: "การดำเนินคดี" },
    { word: "prosecutor", type: "n.", meaning: "อัยการ" },
    { word: "prospective", type: "adj.", meaning: "ที่มีแนวโน้ม, ที่คาดหวัง" },
    { word: "prosperity", type: "n.", meaning: "ความเจริญรุ่งเรือง" },
    { word: "protective", type: "adj.", meaning: "เป็นการป้องกัน" },
    { word: "protocol", type: "n.", meaning: "พิธีสาร, ระเบียบการ" },
    { word: "province", type: "n.", meaning: "จังหวัด" },
    { word: "provincial", type: "adj.", meaning: "เกี่ยวกับจังหวัด" },
    { word: "provision", type: "n.", meaning: "การจัดหา, ข้อกำหนด" },
    { word: "provoke", type: "v.", meaning: "ยั่วยุ, ก่อให้เกิด" },
    { word: "psychiatric", type: "adj.", meaning: "เกี่ยวกับจิตเวช" },
    { word: "pulse", type: "n.", meaning: "ชีพจร" },
    { word: "pump", type: "v., n.", meaning: "สูบ, ปั๊ม" },
    { word: "punch", type: "n., v.", meaning: "การชก, ชก" },
    { word: "query", type: "n.", meaning: "คำถาม, ข้อสงสัย" },
    { word: "quest", type: "n.", meaning: "การแสวงหา" },
    { word: "quota", type: "n.", meaning: "โควตา, ส่วนแบ่ง" },
    { word: "radar", type: "n.", meaning: "เรดาร์" },
    { word: "radical", type: "adj.", meaning: "หัวรุนแรง, ถอนรากถอนโคน" },
    { word: "rage", type: "n.", meaning: "ความโกรธเกรี้ยว" },
    { word: "raid", type: "n., v.", meaning: "การจู่โจม, จู่โจม" },
    { word: "rally", type: "n., v.", meaning: "การชุมนุม, ชุมนุม" },
    { word: "ranking", type: "n.", meaning: "การจัดอันดับ" },
    { word: "rape", type: "n., v.", meaning: "การข่มขืน, ข่มขืน" },
    { word: "ratio", type: "n.", meaning: "อัตราส่วน" },
    { word: "rational", type: "adj.", meaning: "มีเหตุผล" },
    { word: "ray", type: "n.", meaning: "รังสี, แสง" },
    { word: "readily", type: "adv.", meaning: "อย่างง่ายดาย, อย่างเต็มใจ" },
    { word: "realization", type: "n.", meaning: "การตระหนักรู้" },
    { word: "realm", type: "n.", meaning: "อาณาจักร, ขอบเขต" },
    { word: "rear", type: "adj., n.", meaning: "ด้านหลัง, หลัง" },
    { word: "reasoning", type: "n.", meaning: "การใช้เหตุผล" },
    { word: "reassure", type: "v.", meaning: "ทำให้มั่นใจ" },
    { word: "rebel", type: "n.", meaning: "กบฏ" },
    { word: "rebellion", type: "n.", meaning: "การกบฏ" },
    { word: "recipient", type: "n.", meaning: "ผู้รับ" },
    { word: "reconstruction", type: "n.", meaning: "การสร้างใหม่" },
    { word: "recount", type: "v.", meaning: "เล่าเรื่อง, นับใหม่" },
    { word: "referendum", type: "n.", meaning: "การลงประชามติ" },
    { word: "reflection", type: "n.", meaning: "การสะท้อน, ภาพสะท้อน" },
    { word: "reform", type: "n., v.", meaning: "การปฏิรูป, ปฏิรูป" },
    { word: "refuge", type: "n.", meaning: "ที่ลี้ภัย" },
    { word: "refusal", type: "n.", meaning: "การปฏิเสธ" },
    { word: "regain", type: "v.", meaning: "ได้คืนมา" },
    { word: "regardless", type: "adv.", meaning: "โดยไม่คำนึงถึง" },
    { word: "regime", type: "n.", meaning: "ระบอบการปกครอง" },
    { word: "regulator", type: "n.", meaning: "ผู้ควบคุม" },
    { word: "regulatory", type: "adj.", meaning: "เกี่ยวกับการควบคุม" },
    { word: "rehabilitation", type: "n.", meaning: "การฟื้นฟูสภาพ" },
    { word: "reign", type: "n., v.", meaning: "รัชสมัย, ปกครอง" },
    { word: "rejection", type: "n.", meaning: "การปฏิเสธ" },
    { word: "relevance", type: "n.", meaning: "ความเกี่ยวข้อง" },
    { word: "reliability", type: "n.", meaning: "ความน่าเชื่อถือ" },
    { word: "reluctant", type: "adj.", meaning: "ไม่เต็มใจ" },
    { word: "remainder", type: "n.", meaning: "ส่วนที่เหลือ" },
    { word: "remains", type: "n.", meaning: "ซาก, ซากศพ" },
    { word: "remedy", type: "n.", meaning: "การเยียวยา, วิธีแก้" },
    { word: "reminder", type: "n.", meaning: "สิ่งเตือนความจำ" },
    { word: "removal", type: "n.", meaning: "การถอดออก, การกำจัด" },
    { word: "render", type: "v.", meaning: "ทำให้, มอบให้" },
    { word: "renew", type: "v.", meaning: "ต่ออายุ, ทำให้ใหม่" },
    { word: "renowned", type: "adj.", meaning: "มีชื่อเสียง" },
    { word: "rental", type: "n.", meaning: "การเช่า, สิ่งที่เช่า" },
    { word: "replacement", type: "n.", meaning: "การแทนที่, สิ่งที่มาแทน" },
    { word: "reportedly", type: "adv.", meaning: "ตามที่รายงาน" },
    { word: "representation", type: "n.", meaning: "การเป็นตัวแทน, ตัวแทน" },
    { word: "reproduce", type: "v.", meaning: "สืบพันธุ์, ทำซ้ำ" },
    { word: "reproduction", type: "n.", meaning: "การสืบพันธุ์, การทำซ้ำ" },
    { word: "republic", type: "n.", meaning: "สาธารณรัฐ" },
    { word: "resemble", type: "v.", meaning: "คล้ายคลึง" },
    { word: "reside", type: "v.", meaning: "อาศัยอยู่" },
    { word: "residence", type: "n.", meaning: "ที่อยู่อาศัย" },
    { word: "residential", type: "adj.", meaning: "เกี่ยวกับที่อยู่อาศัย" },
    { word: "residue", type: "n.", meaning: "สารตกค้าง" },
    { word: "resignation", type: "n.", meaning: "การลาออก" },
    { word: "resistance", type: "n.", meaning: "การต่อต้าน" },
    { word: "respective", type: "adj.", meaning: "ของตน, ตามลำดับ" },
    { word: "respectively", type: "adv.", meaning: "ตามลำดับ" },
    { word: "restoration", type: "n.", meaning: "การฟื้นฟู" },
    { word: "restraint", type: "n.", meaning: "การยับยั้ง, ข้อจำกัด" },
    { word: "resume", type: "v.", meaning: "กลับมาเริ่มใหม่" },
    { word: "retreat", type: "n., v.", meaning: "การถอย, ถอย" },
    { word: "retrieve", type: "v.", meaning: "ดึงกลับ, กู้คืน" },
    { word: "revelation", type: "n.", meaning: "การเปิดเผย" },
    { word: "revenge", type: "n.", meaning: "การแก้แค้น" },
    { word: "reverse", type: "v. , n., adj.", meaning: "กลับกัน, ย้อนกลับ, ด้านตรงข้าม" },
    { word: "revival", type: "n.", meaning: "การฟื้นคืนชีพ" },
    { word: "revive", type: "v.", meaning: "ฟื้นคืนชีพ" },
    { word: "revolutionary", type: "adj.", meaning: "ปฏิวัติ" },
    { word: "rhetoric", type: "n.", meaning: "วาทศิลป์" },
    { word: "rifle", type: "n.", meaning: "ปืนไรเฟิล" },
    { word: "riot", type: "n.", meaning: "การจลาจล" },
    { word: "rip", type: "v.", meaning: "ฉีก" },
    { word: "ritual", type: "n.", meaning: "พิธีกรรม" },
    { word: "robust", type: "adj.", meaning: "แข็งแรง, ทนทาน" },
    { word: "rock", type: "v.", meaning: "โยก, สั่น" },
    { word: "rod", type: "n.", meaning: "แท่ง, ไม้เรียว" },
    { word: "rotate", type: "v.", meaning: "หมุน" },
    { word: "rotation", type: "n.", meaning: "การหมุน" },
    { word: "ruling", type: "n.", meaning: "คำตัดสิน, การปกครอง" },
    { word: "rumour", type: "n.", meaning: "ข่าวลือ" },
    { word: "sack", type: "v.", meaning: "ไล่ออก (ไม่เป็นทางการ), บรรจุใส่กระสอบ" },
    { word: "sacred", type: "adj.", meaning: "ศักดิ์สิทธิ์" },
    { word: "sacrifice", type: "n., v.", meaning: "การเสียสละ, เสียสละ" },
    { word: "saint", type: "n.", meaning: "นักบุญ" },
    { word: "sake", type: "n.", meaning: "เพื่อประโยชน์ของ" },
    { word: "sanction", type: "n.", meaning: "การลงโทษ, มาตรการคว่ำบาตร" },
    { word: "say", type: "n.", meaning: "สิ่งที่พูด, สิทธิในการพูด" },
    { word: "scattered", type: "adj.", meaning: "กระจัดกระจาย" },
    { word: "sceptical", type: "adj.", meaning: "สงสัย" },
    { word: "scope", type: "n.", meaning: "ขอบเขต" },
    { word: "screw", type: "v., n.", meaning: "ไขสกรู, สกรู" },
    { word: "scrutiny", type: "n.", meaning: "การตรวจสอบอย่างละเอียด" },
    { word: "seal", type: "v., n.", meaning: "ผนึก, ตราประทับ, แมวน้ำ" },
    { word: "secular", type: "adj.", meaning: "ทางโลก, ไม่เกี่ยวกับศาสนา" },
    { word: "seemingly", type: "adv.", meaning: "ดูเหมือนว่า" },
    { word: "segment", type: "n.", meaning: "ส่วน, ท่อน" },
    { word: "seize", type: "v.", meaning: "ยึด, ฉวยโอกาส" },
    { word: "seldom", type: "adv.", meaning: "ไม่ค่อยจะ" },
    { word: "selective", type: "adj.", meaning: "คัดเลือก" },
    { word: "senator", type: "n.", meaning: "สมาชิกวุฒิสภา" },
    { word: "sensation", type: "n.", meaning: "ความรู้สึก, ความฮือฮา" },
    { word: "sensitivity", type: "n.", meaning: "ความไว, ความอ่อนไหว" },
    { word: "sentiment", type: "n.", meaning: "ความรู้สึก, ทัศนคติ" },
    { word: "separation", type: "n.", meaning: "การแยก" },
    { word: "serial", type: "adj.", meaning: "ต่อเนื่อง, อนุกรม" },
    { word: "settlement", type: "n.", meaning: "การตั้งถิ่นฐาน, การยุติข้อพิพาท" },
    { word: "set-up", type: "n.", meaning: "การจัดตั้ง, โครงสร้าง" },
    { word: "sexuality", type: "n.", meaning: "เพศวิถี" },
    { word: "shareholder", type: "n.", meaning: "ผู้ถือหุ้น" },
    { word: "shatter", type: "v.", meaning: "แตกละเอียด, ทำลาย" },
    { word: "shed", type: "v.", meaning: "หลั่ง (น้ำตา), สลัด (ขน), ปล่อย" },
    { word: "sheer", type: "adj.", meaning: "อย่างแท้จริง, บางใส" },
    { word: "shipping", type: "n.", meaning: "การขนส่งทางเรือ" },
    { word: "shoot", type: "n.", meaning: "การยิง, หน่อไม้" },
    { word: "shrink", type: "v.", meaning: "หดตัว, ลดขนาด" },
    { word: "shrug", type: "v.", meaning: "ยักไหล่" },
    { word: "sigh", type: "v., n.", meaning: "ถอนหายใจ, เสียงถอนหายใจ" },
    { word: "simulate", type: "v.", meaning: "จำลอง" },
    { word: "simulation", type: "n.", meaning: "การจำลอง" },
    { word: "simultaneously", type: "adv.", meaning: "ในเวลาเดียวกัน" },
    { word: "sin", type: "n.", meaning: "บาป" },
    { word: "situated", type: "adj.", meaning: "ตั้งอยู่" },
    { word: "sketch", type: "n.", meaning: "ภาพร่าง, การร่างภาพ" },
    { word: "skip", type: "v.", meaning: "ข้าม, กระโดดข้าม" },
    { word: "slam", type: "v.", meaning: "กระแทกปิด" },
    { word: "slap", type: "v.", meaning: "ตบ" },
    { word: "slash", type: "v.", meaning: "ฟัน, ลดอย่างรวดเร็ว" },
    { word: "slavery", type: "n.", meaning: "การเป็นทาส" },
    { word: "slot", type: "n.", meaning: "ช่อง, สล็อต" },
    { word: "smash", type: "v.", meaning: "ชนอย่างแรง, ทุบให้แตก" },
    { word: "snap", type: "v.", meaning: "หักดังเป๊าะ, ถ่ายรูป (ไม่เป็นทางการ)" },
    { word: "soak", type: "v.", meaning: "แช่, ซึมซับ" },
    { word: "soar", type: "v.", meaning: "ทะยานขึ้น, พุ่งสูงขึ้น" },
    { word: "socialist", type: "adj.", meaning: "สังคมนิยม" },
    { word: "sole", type: "adj.", meaning: "แต่เพียงผู้เดียว" },
    { word: "solely", type: "adv.", meaning: "โดยลำพัง, เพียงเท่านั้น" },
    { word: "solicitor", type: "n.", meaning: "ทนายความ (UK)" },
    { word: "solidarity", type: "n.", meaning: "ความเป็นน้ำหนึ่งใจเดียวกัน" },
    { word: "solo", type: "adj., n.", meaning: "เดี่ยว" },
    { word: "sound", type: "adj.", meaning: "สมบูรณ์, มีเหตุผล" },
    { word: "sovereignty", type: "n.", meaning: "อำนาจอธิปไตย" },
    { word: "spam", type: "n.", meaning: "สแปม (อีเมลขยะ)" },
    { word: "span", type: "v., n.", meaning: "ครอบคลุม, ช่วง" },
    { word: "spare", type: "v.", meaning: "ไว้ชีวิต, สละให้" },
    { word: "spark", type: "v.", meaning: "จุดประกาย, ก่อให้เกิด" },
    { word: "specialized", type: "adj.", meaning: "เฉพาะทาง" },
    { word: "specification", type: "n.", meaning: "ข้อกำหนด" },
    { word: "specimen", type: "n.", meaning: "ตัวอย่าง" },
    { word: "spectacle", type: "n.", meaning: "ภาพที่น่าตื่นเต้น, แว่นตา (พหูพจน์)" },
    { word: "spectrum", type: "n.", meaning: "สเปกตรัม, ช่วงกว้าง" },
    { word: "spell", type: "n.", meaning: "ช่วงเวลาสั้นๆ" },
    { word: "sphere", type: "n.", meaning: "ทรงกลม, ขอบเขต" },
    { word: "spin", type: "v., n.", meaning: "หมุน, การหมุน" },
    { word: "spine", type: "n.", meaning: "กระดูกสันหลัง, สันหนังสือ" },
    { word: "spotlight", type: "n.", meaning: "ไฟสปอตไลท์, จุดสนใจ" },
    { word: "spouse", type: "n.", meaning: "คู่สมรส" },
    { word: "spy", type: "n., v.", meaning: "สายลับ, สอดแนม" },
    { word: "squad", type: "n.", meaning: "ทีม, หมู่" },
    { word: "squeeze", type: "v.", meaning: "บีบ" },
    { word: "stab", type: "v.", meaning: "แทง" },
    { word: "stability", type: "n.", meaning: "ความมั่นคง" },
    { word: "stabilize", type: "v.", meaning: "ทำให้มั่นคง" },
    { word: "stake", type: "n.", meaning: "เงินเดิมพัน, ส่วนได้ส่วนเสีย" },
    { word: "standing", type: "adj.", meaning: "ยืนยาว, ตำแหน่ง" },
    { word: "stark", type: "adj.", meaning: "รุนแรง, เปลือยเปล่า" },
    { word: "statistical", type: "adj.", meaning: "เกี่ยวกับสถิติ" },
    { word: "steer", type: "v.", meaning: "บังคับทิศทาง, นำ" },
    { word: "stem", type: "n., v.", meaning: "ลำต้น, ก้าน, มาจาก" },
    { word: "stereotype", type: "n.", meaning: "ทัศนคติแบบเหมารวม" },
    { word: "stimulus", type: "n.", meaning: "สิ่งกระตุ้น" },
    { word: "stir", type: "v.", meaning: "คน, กวน, กระตุ้น" },
    { word: "storage", type: "n.", meaning: "การจัดเก็บ, ที่เก็บ" },
    { word: "straightforward", type: "adj.", meaning: "ตรงไปตรงมา, ง่าย" },
    { word: "strain", type: "n.", meaning: "ความตึงเครียด, สายพันธุ์" },
    { word: "strand", type: "n.", meaning: "เกลียว (เชือก), ชายหาด" },
    { word: "strategic", type: "adj.", meaning: "เชิงกลยุทธ์" },
    { word: "striking", type: "adj.", meaning: "โดดเด่น, น่าประหลาดใจ" },
    { word: "strip", type: "n., v.", meaning: "แถบ, ชิ้นยาวๆ, ถอดเสื้อผ้า, ลอกออก" },
    { word: "strive", type: "v.", meaning: "มุ่งมั่น, พยายามอย่างหนัก" },
    { word: "structural", type: "adj.", meaning: "เกี่ยวกับโครงสร้าง" },
    { word: "stumble", type: "v.", meaning: "สะดุด" },
    { word: "stun", type: "v.", meaning: "ทำให้ตกตะลึง" },
    { word: "submission", type: "n.", meaning: "การส่ง, การยอมจำนน" },
    { word: "subscriber", type: "n.", meaning: "ผู้ติดตาม, สมาชิก" },
    { word: "subscription", type: "n.", meaning: "การสมัครสมาชิก" },
    { word: "subsidy", type: "n.", meaning: "เงินอุดหนุน" },
    { word: "substantial", type: "adj.", meaning: "สำคัญ, มากมาย" },
    { word: "substantially", type: "adv.", meaning: "อย่างมาก" },
    { word: "substitute", type: "n., v.", meaning: "ตัวแทน, แทนที่" },
    { word: "substitution", type: "n.", meaning: "การแทนที่" },
    { word: "subtle", type: "adj.", meaning: "ละเอียดอ่อน, แยบยล" },
    { word: "suburban", type: "adj.", meaning: "ชานเมือง" },
    { word: "succession", type: "n.", meaning: "การสืบทอด" },
    { word: "successive", type: "adj.", meaning: "ต่อเนื่องกัน" },
    { word: "successor", type: "n.", meaning: "ผู้สืบทอด" },
    { word: "suck", type: "v.", meaning: "ดูด" },
    { word: "sue", type: "v.", meaning: "ฟ้องร้อง" },
    { word: "suicide", type: "n.", meaning: "การฆ่าตัวตาย" },
    { word: "suite", type: "n.", meaning: "ชุด (ห้องพัก), สวีท (เพลง)" },
    { word: "summit", type: "n.", meaning: "การประชุมสุดยอด, ยอดเขา" },
    { word: "superb", type: "adj.", meaning: "ยอดเยี่ยม" },
    { word: "superior", type: "adj.", meaning: "เหนือกว่า" },
    { word: "supervise", type: "v.", meaning: "ดูแล, ควบคุม" },
    { word: "supervision", type: "n.", meaning: "การดูแล, การควบคุม" },
    { word: "supervisor", type: "n.", meaning: "ผู้ควบคุม, หัวหน้างาน" },
    { word: "supplement", type: "n., v.", meaning: "อาหารเสริม, ส่วนเสริม, เสริม" },
    { word: "supportive", type: "adj.", meaning: "ที่ให้การสนับสนุน" },
    { word: "supposedly", type: "adv.", meaning: "ตามที่กล่าวอ้าง" },
    { word: "suppress", type: "v.", meaning: "ปราบปราม, ระงับ" },
    { word: "supreme", type: "adj.", meaning: "สูงสุด" },
    { word: "surge", type: "n., v.", meaning: "การเพิ่มขึ้นอย่างรวดเร็ว, เพิ่มขึ้นอย่างรวดเร็ว" },
    { word: "surgical", type: "adj.", meaning: "เกี่ยวกับการผ่าตัด" },
    { word: "surplus", type: "n.", meaning: "ส่วนเกิน" },
    { word: "surrender", type: "v.", meaning: "ยอมจำนน" },
    { word: "surveillance", type: "n.", meaning: "การเฝ้าระวัง" },
    { word: "suspension", type: "n.", meaning: "การระงับ, การพัก" },
    { word: "suspicion", type: "n.", meaning: "ความสงสัย" },
    { word: "suspicious", type: "adj.", meaning: "น่าสงสัย" },
    { word: "sustain", type: "v.", meaning: "รักษาไว้, ค้ำจุน" },
    { word: "swing", type: "v., n.", meaning: "แกว่ง, การแกว่ง" },
    { word: "sword", type: "n.", meaning: "ดาบ" },
    { word: "symbolic", type: "adj.", meaning: "เชิงสัญลักษณ์" },
    { word: "syndrome", type: "n.", meaning: "กลุ่มอาการ" },
    { word: "synthesis", type: "n.", meaning: "การสังเคราะห์" },
    { word: "systematic", type: "adj.", meaning: "เป็นระบบ" },
    { word: "tackle", type: "n.", meaning: "อุปกรณ์ (ตกปลา), การจัดการ" },
    { word: "tactic", type: "n.", meaning: "ยุทธวิธี" },
    { word: "tactical", type: "adj.", meaning: "เชิงยุทธวิธี" },
    { word: "taxpayer", type: "n.", meaning: "ผู้เสียภาษี" },
    { word: "tempt", type: "v.", meaning: "ล่อลวง, ยั่วเย้า" },
    { word: "tenant", type: "n.", meaning: "ผู้เช่า" },
    { word: "tender", type: "adj.", meaning: "อ่อนโยน, นุ่ม" },
    { word: "tenure", type: "n.", meaning: "การดำรงตำแหน่ง" },
    { word: "terminal", type: "adj.", meaning: "ปลายทาง, ขั้นสุดท้าย" },
    { word: "terminate", type: "v.", meaning: "สิ้นสุด, ยุติ" },
    { word: "terrain", type: "n.", meaning: "ภูมิประเทศ" },
    { word: "terrific", type: "adj.", meaning: "ยอดเยี่ยมมาก" },
    { word: "testify", type: "v.", meaning: "เป็นพยาน" },
    { word: "testimony", type: "n.", meaning: "คำให้การ" },
    { word: "texture", type: "n.", meaning: "พื้นผิว, เนื้อสัมผัส" },
    { word: "thankfully", type: "adv.", meaning: "โชคดีที่" },
    { word: "theatrical", type: "adj.", meaning: "เกี่ยวกับการแสดงละคร" },
    { word: "theology", type: "n.", meaning: "เทววิทยา" },
    { word: "theoretical", type: "adj.", meaning: "ทางทฤษฎี" },
    { word: "thereafter", type: "adv.", meaning: "หลังจากนั้น" },
    { word: "thereby", type: "adv.", meaning: "ด้วยเหตุนั้น" },
    { word: "thoughtful", type: "adj.", meaning: "ช่างคิด, รอบคอบ" },
    { word: "thought-provoking", type: "adj.", meaning: "กระตุ้นความคิด" },
    { word: "thread", type: "n.", meaning: "ด้าย, เส้นด้าย" },
    { word: "threshold", type: "n.", meaning: "ธรณีประตู, จุดเริ่มต้น" },
    { word: "thrilled", type: "adj.", meaning: "รู้สึกตื่นเต้นยินดี" },
    { word: "thrive", type: "v.", meaning: "เจริญรุ่งเรือง, เติบโต" },
    { word: "tide", type: "n.", meaning: "กระแสน้ำ" },
    { word: "tighten", type: "v.", meaning: "ทำให้แน่นขึ้น" },
    { word: "timber", type: "n.", meaning: "ไม้ซุง" },
    { word: "timely", type: "adj.", meaning: "ทันเวลา" },
    { word: "tobacco", type: "n.", meaning: "ยาสูบ" },
    { word: "tolerance", type: "n.", meaning: "ความอดทน" },
    { word: "tolerate", type: "v.", meaning: "ทนได้, ยอมรับได้" },
    { word: "toll", type: "n.", meaning: "ค่าผ่านทาง, ความเสียหาย" },
    { word: "top", type: "v.", meaning: "อยู่บนสุด, เอาชนะ" },
    { word: "torture", type: "n., v.", meaning: "การทรมาน, ทรมาน" },
    { word: "toss", type: "v.", meaning: "โยน" },
    { word: "total", type: "v.", meaning: "รวมทั้งหมด" },
    { word: "toxic", type: "adj.", meaning: "เป็นพิษ" },
    { word: "trace", type: "n.", meaning: "ร่องรอย" },
    { word: "trademark", type: "n.", meaning: "เครื่องหมายการค้า" },
    { word: "trail", type: "n., v.", meaning: "ร่องรอย, ทางเดิน, ตามรอย" },
    { word: "trailer", type: "n.", meaning: "รถพ่วง, ตัวอย่างภาพยนตร์" },
    { word: "transaction", type: "n.", meaning: "การทำธุรกรรม" },
    { word: "transcript", type: "n.", meaning: "ใบรับรองผลการเรียน, บทถอดเสียง" },
    { word: "transformation", type: "n.", meaning: "การเปลี่ยนแปลง" },
    { word: "transit", type: "n.", meaning: "การขนส่ง, การผ่าน" },
    { word: "transmission", type: "n.", meaning: "การส่งผ่าน" },
    { word: "transparency", type: "n.", meaning: "ความโปร่งใส" },
    { word: "transparent", type: "adj.", meaning: "โปร่งใส" },
    { word: "trauma", type: "n.", meaning: "ความบอบช้ำทางจิตใจ, บาดเจ็บ" },
    { word: "treaty", type: "n.", meaning: "สนธิสัญญา" },
    { word: "tremendous", type: "adj.", meaning: "ใหญ่มาก, มหาศาล" },
    { word: "tribal", type: "adj.", meaning: "เกี่ยวกับชนเผ่า" },
    { word: "tribunal", type: "n.", meaning: "ศาลพิเศษ, คณะตุลาการ" },
    { word: "tribute", type: "n.", meaning: "เครื่องบรรณาการ, คำยกย่อง" },
    { word: "trigger", type: "n.", meaning: "ไกปืน, สิ่งกระตุ้น" },
    { word: "trio", type: "n.", meaning: "กลุ่มสามคน/สิ่ง" },
    { word: "triumph", type: "n.", meaning: "ชัยชนะ" },
    { word: "trophy", type: "n.", meaning: "ถ้วยรางวัล" },
    { word: "troubled", type: "adj.", meaning: "มีปัญหา, วุ่นวาย" },
    { word: "trustee", type: "n.", meaning: "ผู้ดูแลผลประโยชน์" },
    { word: "tuition", type: "n.", meaning: "ค่าเล่าเรียน" },
    { word: "turnout", type: "n.", meaning: "จำนวนผู้มาประชุม/ลงคะแนน" },
    { word: "turnover", type: "n.", meaning: "ยอดขาย, อัตราการเข้าออกของพนักงาน" },
    { word: "twist", type: "v., n.", meaning: "บิด, หักมุม, การบิด" },
    { word: "undergraduate", type: "n.", meaning: "นักศึกษาระดับปริญญาตรี" },
    { word: "underlying", type: "adj.", meaning: "ที่เป็นรากฐาน, แฝงอยู่" },
    { word: "undermine", type: "v.", meaning: "บ่อนทำลาย" },
    { word: "undoubtedly", type: "adv.", meaning: "อย่างไม่ต้องสงสัย" },
    { word: "unify", type: "v.", meaning: "รวมกัน, ทำให้เป็นเอกภาพ" },
    { word: "unprecedented", type: "adj.", meaning: "ไม่เคยมีมาก่อน" },
    { word: "unveil", type: "v.", meaning: "เปิดเผย, เปิดตัว" },
    { word: "upcoming", type: "adj.", meaning: "ที่จะมาถึง" },
    { word: "upgrade", type: "v., n.", meaning: "อัปเกรด, การอัปเกรด" },
    { word: "uphold", type: "v.", meaning: "ยึดมั่น, สนับสนุน" },
    { word: "utility", type: "n.", meaning: "สาธารณูปโภค, ประโยชน์" },
    { word: "utilize", type: "v.", meaning: "ใช้ประโยชน์" },
    { word: "utterly", type: "adv.", meaning: "อย่างที่สุด" },
    { word: "vacuum", type: "n.", meaning: "สุญญากาศ, เครื่องดูดฝุ่น" },
    { word: "vague", type: "adj.", meaning: "คลุมเครือ" },
    { word: "validity", type: "n.", meaning: "ความถูกต้อง, ความสมเหตุสมผล" },
    { word: "vanish", type: "v.", meaning: "หายไป" },
    { word: "variable", type: "n., adj.", meaning: "ตัวแปร, ที่เปลี่ยนแปลงได้" },
    { word: "varied", type: "adj.", meaning: "หลากหลาย" },
    { word: "vein", type: "n.", meaning: "เส้นเลือดดำ" },
    { word: "venture", type: "n., v.", meaning: "การผจญภัย, ร่วมลงทุน" },
    { word: "verbal", type: "adj.", meaning: "ด้วยวาจา" },
    { word: "verdict", type: "n.", meaning: "คำตัดสิน (ของคณะลูกขุน)" },
    { word: "verify", type: "v.", meaning: "ตรวจสอบ, ยืนยัน" },
    { word: "verse", type: "n.", meaning: "บทกวี, โคลง" },
    { word: "versus", type: "prep.", meaning: "เทียบกับ" },
    { word: "vessel", type: "n.", meaning: "เรือ, หลอดเลือด, ภาชนะ" },
    { word: "veteran", type: "n.", meaning: "ทหารผ่านศึก, ผู้มีประสบการณ์" },
    { word: "viable", type: "adj.", meaning: "เป็นไปได้ (ที่จะสำเร็จ)" },
    { word: "vibrant", type: "adj.", meaning: "มีชีวิตชีวา, สดใส" },
    { word: "vice", type: "n.", meaning: "ความชั่วร้าย, รอง (ตำแหน่ง)" },
    { word: "vicious", type: "adj.", meaning: "โหดร้าย, ร้ายกาจ" },
    { word: "villager", type: "n.", meaning: "ชาวบ้าน" },
    { word: "violate", type: "v.", meaning: "ละเมิด, ฝ่าฝืน" },
    { word: "violation", type: "n.", meaning: "การละเมิด" },
    { word: "virtue", type: "n.", meaning: "คุณธรรม, ความดีงาม" },
    { word: "vocal", type: "adj.", meaning: "เกี่ยวกับเสียง, ที่ใช้เสียง" },
    { word: "vow", type: "v.", meaning: "สาบาน, ปฏิญาณ" },
    { word: "vulnerability", type: "n.", meaning: "ความเปราะบาง" },
    { word: "vulnerable", type: "adj.", meaning: "เปราะบาง, อ่อนแอ" },
    { word: "ward", type: "n.", meaning: "หอผู้ป่วย, เขตเลือกตั้ง" },
    { word: "warehouse", type: "n.", meaning: "โกดัง, คลังสินค้า" },
    { word: "warfare", type: "n.", meaning: "การสงคราม" },
    { word: "warrant", type: "n., v.", meaning: "หมายจับ, รับประกัน" },
    { word: "warrior", type: "n.", meaning: "นักรบ" },
    { word: "weaken", type: "v.", meaning: "ทำให้อ่อนแอลง" },
    { word: "weave", type: "v.", meaning: "ทอ, สาน" },
    { word: "weed", type: "n.", meaning: "วัชพืช" },
    { word: "well", type: "n.", meaning: "บ่อน้ำ" },
    { word: "well-being", type: "n.", meaning: "ความเป็นอยู่ที่ดี" },
    { word: "whatsoever", type: "adv.", meaning: "เลย (ใช้เน้นในประโยคปฏิเสธ)" },
    { word: "whereby", type: "adv.", meaning: "โดยที่" },
    { word: "whilst", type: "conj.", meaning: "ในขณะที่" },
    { word: "whip", type: "v.", meaning: "เฆี่ยน, ตี (ให้ขึ้นฟู)" },
    { word: "wholly", type: "adv.", meaning: "ทั้งหมด, โดยสิ้นเชิง" },
    { word: "widen", type: "v.", meaning: "ขยายให้กว้างขึ้น" },
    { word: "widow", type: "n.", meaning: "แม่ม่าย" },
    { word: "width", type: "n.", meaning: "ความกว้าง" },
    { word: "willingness", type: "n.", meaning: "ความเต็มใจ" },
    { word: "wipe", type: "v.", meaning: "เช็ด" },
    { word: "wit", type: "n.", meaning: "ไหวพริบ, ปัญญา" },
    { word: "withdrawal", type: "n.", meaning: "การถอน, การถอนตัว" },
    { word: "workout", type: "n.", meaning: "การออกกำลังกาย" },
    { word: "worship", type: "n., v.", meaning: "การบูชา, บูชา" },
    { word: "worthwhile", type: "adj.", meaning: "คุ้มค่า" },
    { word: "worthy", type: "adj.", meaning: "มีค่าควร" },
    { word: "yell", type: "v.", meaning: "ตะโกน" },
    { word: "yield", type: "n., v.", meaning: "ผลผลิต, ยอมให้, ให้ผลผลิต" },
    { word: "youngster", type: "n.", meaning: "เด็กหนุ่ม, วัยรุ่น" },
];
