import { Word } from './types';

export const c2Words: Word[] = [
    { word: "abide", type: "v.", meaning: "ทนทาน, ยอมทน, ปฏิบัติตาม" },
    { word: "abound", type: "v.", meaning: "มีอยู่มากมาย" },
    { word: "accede", type: "v.", meaning: "ยอมรับ, เห็นด้วย, เข้าดำรงตำแหน่ง" },
    { word: "accolade", type: "n.", meaning: "เกียรติยศ, คำชมเชย" },
    { word: "accretion", type: "n.", meaning: "การเพิ่มขึ้นจากการสะสม" },
    { word: "acquiesce", type: "v.", meaning: "ยินยอม, เห็นพ้อง" },
    { word: "acrimony", type: "n.", meaning: "ความขุ่นเคือง, ความบาดหมาง" },
    { word: "acumen", type: "n.", meaning: "ความเฉียบแหลม, ความเข้าใจอย่างลึกซึ้ง" },
    { word: "adage", type: "n.", meaning: "สุภาษิต, คติพจน์" },
    { word: "adamant", type: "adj.", meaning: "แน่วแน่, ไม่ยอมอ่อนข้อ" },
    { word: "adjudicate", type: "v.", "meaning": "ตัดสิน, ชี้ขาด" },
    { word: "admonish", type: "v.", meaning: "ตักเตือน, ตำหนิ" },
    { word: "adroit", type: "adj.", meaning: "คล่องแคล่ว, ชำนาญ" },
    { word: "adulation", type: "n.", meaning: "การยกย่องสรรเสริญเกินจริง" },
    { word: "adversarial", type: "adj.", meaning: "เป็นปฏิปักษ์, เป็นคู่แข่ง" },
    { word: "aesthetic", type: "n.", meaning: "สุนทรียศาสตร์" },
    { word: "affinity", type: "n.", meaning: "ความสัมพันธ์ใกล้ชิด, ความชอบ" },
    { word: "aggrandize", type: "v.", meaning: "เพิ่มอำนาจ/เกียรติยศ" },
    { word: "alacrity", type: "n.", meaning: "ความกระตือรือร้น, ความรวดเร็ว" },
    { word: "alleviate", type: "v.", meaning: "บรรเทา, ทำให้ลดน้อยลง" },
    { word: "allude", type: "v.", meaning: "อ้างถึงโดยอ้อม, พาดพิง" },
    { word: "altruism", type: "n.", meaning: "ความไม่เห็นแก่ตัว, การกระทำเพื่อผู้อื่น" },
    { word: "ameliorate", type: "v.", meaning: "ทำให้ดีขึ้น, ปรับปรุง" },
    { word: "amenable", type: "adj.", meaning: "ที่อ่อนน้อม, ที่ยอมรับได้" },
    { word: "anachronism", type: "n.", meaning: "ความผิดพลาดทางกาลเวลา (สิ่งที่ไม่เข้ากับยุคสมัย)" },
    { word: "anathema", type: "n.", meaning: "สิ่งที่ถูกสาปแช่ง, สิ่งที่ถูกเกลียดชัง" },
    { word: "anecdote", type: "n.", meaning: "เรื่องเล่าสั้นๆ, เกร็ดเล็กเกร็ดน้อย" },
    { word: "animus", type: "n.", meaning: "ความเป็นปรปักษ์, ความอาฆาต" },
    { word: "anomaly", type: "n.", meaning: "ความผิดปกติ, สิ่งที่ผิดแปลกไปจากปกติ" },
    { word: "antediluvian", type: "adj.", meaning: "โบราณมาก, ล้าสมัย" },
    { word: "antithesis", type: "n.", meaning: "สิ่งที่ตรงกันข้าม, ขั้วตรงข้าม" },
    { word: "apathy", type: "n.", meaning: "การไม่แยแส, ความเฉยเมย" },
    { word: "aplomb", type: "n.", meaning: "ความมั่นใจในตนเอง, ความสงบเสงี่ยม" },
    { word: "apocryphal", type: "adj.", meaning: "ที่ไม่มีหลักฐานยืนยัน, ที่น่าสงสัย" },
    { word: "apostate", type: "n.", meaning: "ผู้ละทิ้งศาสนา/ความเชื่อ" },
    { word: "apposite", type: "adj.", meaning: "เหมาะสม, ตรงประเด็น" },
    { word: "apprehension", type: "n.", meaning: "ความวิตกกังวล, ความเข้าใจ" },
    { word: "approbation", type: "n.", meaning: "การเห็นด้วย, การอนุมัติ" },
    { word: "arbiter", type: "n.", meaning: "ผู้ชี้ขาด, ผู้ตัดสิน" },
    { word: "arcane", type: "adj.", meaning: "ลึกลับ, ยากที่จะเข้าใจ" },
    { word: "ardent", type: "adj.", meaning: "กระตือรือร้น, เร่าร้อน" },
    { word: "arduous", type: "adj.", meaning: "ยากลำบาก, ตรากตรำ" },
    { word: "arraign", type: "v.", meaning: "ฟ้องร้อง, กล่าวหา" },
    { word: "ascetic", type: "adj., n.", meaning: "สมถะ, ผู้บำเพ็ญตบะ" },
    { word: "ascribe", type: "v.", meaning: "ให้เหตุผล, อ้างว่าเป็นผลมาจาก" },
    { word: "askance", type: "adv.", meaning: "ด้วยความสงสัย/ไม่ไว้วางใจ" },
    { word: "asseverate", type: "v.", meaning: "ยืนยันอย่างหนักแน่น" },
    { word: "assiduous", type: "adj.", meaning: "ขยันหมั่นเพียร" },
    { word: "assuage", type: "v.", meaning: "บรรเทา, ทำให้สงบลง" },
    { word: "atrophy", type: "n., v.", meaning: "การฝ่อ, การเสื่อม" },
    { word: "attenuate", type: "v.", meaning: "ทำให้อ่อนลง, ทำให้บางลง" },
    { word: "audacious", type: "adj.", meaning: "กล้าหาญ, ทะเยอทะยาน" },
    { word: "august", type: "adj.", meaning: "สง่างาม, น่าเคารพ" },
    { word: "auspicious", type: "adj.", meaning: "เป็นมงคล" },
    { word: "austere", type: "adj.", meaning: "เคร่งครัด, เรียบง่าย" },
    { word: "avarice", type: "n.", meaning: "ความโลภ" },
    { word: "aver", type: "v.", meaning: "ยืนยัน, รับรอง" },
    { word: "axiom", type: "n.", meaning: "สัจพจน์, หลักการที่เป็นที่ยอมรับ" },
    { word: "bale", type: "n.", meaning: "ฟ่อน (ฟาง), ห่อใหญ่" },
    { word: "baleful", type: "adj.", meaning: "เป็นอันตราย, มุ่งร้าย" },
    { word: "balk", type: "v.", meaning: "หยุดชะงัก, ไม่ยอมทำตาม" },
    { word: "banal", type: "adj.", meaning: "ซ้ำซาก, น่าเบื่อ" },
    { word: "bane", type: "n.", meaning: "หายนะ, สิ่งที่เป็นพิษ" },
    { word: "barb", type: "n.", meaning: "หนาม, คำพูดเสียดสี" },
    { word: "barrage", type: "n.", meaning: "การระดมยิง, การยิงคุ้มกัน" },
    { word: "bastion", type: "n.", meaning: "ป้อมปราการ, ที่มั่น" },
    { word: "beget", type: "v.", meaning: "ให้กำเนิด, ก่อให้เกิด" },
    { word: "beleaguer", type: "v.", meaning: "รบกวน, ล้อม" },
    { word: "belie", type: "v.", meaning: "ปกปิดความจริง, ขัดแย้งกับ" },
    { word: "bellicose", type: "adj.", meaning: "ชอบการทะเลาะวิวาท" },
    { word: "belligerent", type: "adj.", meaning: "ซึ่งทำสงคราม, เป็นปรปักษ์" },
    { word: "bemuse", type: "v.", meaning: "ทำให้งุนงง, ทำให้สับสน" },
    { word: "benign", type: "adj.", meaning: "ไม่เป็นอันตราย, ใจดี" },
    { word: "bequeath", type: "v.", meaning: "ยกมรดกให้" },
    { word: "bereft", type: "adj.", meaning: "ที่ปราศจาก, ที่สูญเสีย" },
    { word: "bifurcate", type: "v.", meaning: "แยกออกเป็นสองแฉก" },
    { word: "bilk", type: "v.", meaning: "โกงเงิน" },
    { word: "blandishment", type: "n.", meaning: "คำเยินยอ, การประจบประแจง" },
    { word: "blight", type: "n., v.", meaning: "โรคพืช, สิ่งที่ทำลาย, ทำลาย" },
    { word: "blithe", type: "adj.", meaning: "ร่าเริง, ไม่สนใจ" },
    { word: "bombastic", type: "adj.", meaning: "คุยโว, โอ้อวด" },
    { word: "boorish", type: "adj.", meaning: "หยาบคาย, ไร้มารยาท" },
    { word: "bovine", type: "adj.", meaning: "เหมือนวัว, เชื่องช้า" },
    { word: "brazen", type: "adj.", meaning: "ไร้ยางอาย, หน้าด้าน" },
    { word: "brevity", type: "n.", meaning: "ความกระชับ, ความสั้น" },
    { word: "bromide", type: "n.", meaning: "คำพูดซ้ำซาก, คำพูดที่น่าเบื่อ" },
    { word: "bucolic", type: "adj.", meaning: "เกี่ยวกับชีวิตในชนบท" },
    { word: "burgeon", type: "v.", meaning: "เจริญงอกงามอย่างรวดเร็ว" },
    { word: "buttress", type: "n., v.", meaning: "กำแพงค้ำยัน, ค้ำจุน" },
    { word: "cabal", type: "n.", meaning: "คณะสมรู้ร่วมคิด" },
    { word: "cacophony", type: "n.", meaning: "เสียงไม่พึงประสงค์, เสียงอึกทึก" },
    { word: "cadence", type: "n.", meaning: "จังหวะ, ท่วงทำนอง" },
    { word: "cajole", type: "v.", meaning: "หว่านล้อม, โน้มน้าว" },
    { word: "callous", type: "adj.", meaning: "ใจแข็ง, ไร้ความรู้สึก" },
    { word: "calumny", type: "n.", meaning: "การหมิ่นประมาท, การใส่ร้าย" },
    { word: "canard", type: "n.", meaning: "ข่าวลือที่ไม่มีมูลความจริง" },
    { word: "candor", type: "n.", meaning: "ความจริงใจ, ความตรงไปตรงมา" },
    { word: "canvass", type: "v.", meaning: "สำรวจความคิดเห็น, หาเสียง" },
    { word: "capricious", type: "adj.", meaning: "เอาแต่ใจ, เปลี่ยนแปลงง่าย" },
    { word: "captious", type: "adj.", meaning: "ชอบจับผิด" },
    { word: "carouse", type: "v.", meaning: "ดื่มฉลองอย่างสนุกสนาน" },
    { word: "carte blanche", type: "n.", meaning: "อำนาจเต็มที่" },
    { word: "castigate", type: "v.", meaning: "ลงโทษอย่างรุนแรง, ตำหนิ" },
    { word: "catalyst", type: "n.", meaning: "ตัวเร่งปฏิกิริยา, สิ่งกระตุ้น" },
    { word: "catharsis", type: "n.", meaning: "การระบายอารมณ์" },
    { word: "caucus", type: "n.", meaning: "การประชุมพรรคการเมือง" },
    { word: "caustic", type: "adj.", meaning: "กัดกร่อน, เสียดสี" },
    { word: "cavalier", type: "adj.", meaning: "ไม่สนใจผู้อื่น, หยิ่งยโส" },
    { word: "cavil", type: "v.", meaning: "จู้จี้จุกจิก, หาเรื่องจับผิด" },
    { word: "celerity", type: "n.", meaning: "ความรวดเร็ว" },
    { word: "censorious", type: "adj.", meaning: "ชอบวิจารณ์, ชอบจับผิด" },
    { word: "chagrin", type: "n.", meaning: "ความรู้สึกอับอาย/ผิดหวัง" },
    { word: "charlatan", type: "n.", meaning: "คนหลอกลวง, หมอเถื่อน" },
    { word: "chicanery", type: "n.", meaning: "การใช้เล่ห์เหลี่ยม, การโกง" },
    { word: "chimerical", type: "adj.", meaning: "เพ้อฝัน, ไม่เป็นจริง" },
    { word: "choleric", type: "adj.", meaning: "เจ้าอารมณ์, โกรธง่าย" },
    { word: "churlish", type: "adj.", meaning: "หยาบคาย, ไร้มารยาท" },
    { word: "circuitous", type: "adj.", meaning: "อ้อม, ไม่ตรง" },
    { word: "circumlocution", type: "n.", meaning: "การพูดอ้อมค้อม" },
    { word: "circumscribe", type: "v.", meaning: "จำกัด, ล้อมรอบ" },
    { word: "circumvent", type: "v.", meaning: "หลีกเลี่ยง (ปัญหา/กฎ)" },
    { word: "clandestine", type: "adj.", meaning: "ลับๆ, แอบซ่อน" },
    { word: "cloying", type: "adj.", meaning: "ที่มากเกินไปจนเอียน, หวานเลี่ยน" },
    { word: "coalesce", type: "v.", meaning: "รวมกัน, หลอมรวม" },
    { word: "coax", type: "v.", meaning: "เกลี้ยกล่อม" },
    { word: "coda", type: "n.", meaning: "บทสรุป, ส่วนท้าย" },
    { word: "cogent", type: "adj.", meaning: "น่าเชื่อถือ, มีเหตุผล" },
    { word: "cognizant", type: "adj.", meaning: "ตระหนักรู้, รับรู้" },
    { word: "collate", type: "v.", meaning: "เรียงลำดับ, ตรวจสอบความถูกต้อง" },
    { word: "commensurate", type: "adj.", meaning: "ได้สัดส่วน, เท่าเทียมกัน" },
    { word: "compendium", type: "n.", meaning: "บทสรุป, คู่มือ" },
    { word: "complaisant", type: "adj.", meaning: "อ่อนน้อม, ชอบเอาใจ" },
    { word: "complementary", type: "adj.", meaning: "ซึ่งส่งเสริมกัน" },
    { word: "complicity", type: "n.", meaning: "การสมรู้ร่วมคิด" },
    { word: "compunction", type: "n.", meaning: "ความสำนึกผิด" },
    { word: "concatenation", type: "n.", meaning: "การเชื่อมโยงเป็นลูกโซ่" },
    { word: "conclave", type: "n.", meaning: "การประชุมลับ" },
    { word: "concomitant", type: "adj.", meaning: "ที่มาพร้อมกัน, ที่เกิดขึ้นควบคู่กัน" },
    { word: "concord", type: "n.", meaning: "ความกลมกลืน, ข้อตกลง" },
    { word: "conduit", type: "n.", meaning: "ท่อ, ช่องทาง" },
    { word: "conflate", type: "v.", meaning: "หลอมรวม, รวมกัน" },
    { word: "congenial", type: "adj.", meaning: "เป็นมิตร, เข้ากันได้ดี" },
    { word: "conjecture", type: "n., v.", meaning: "การคาดเดา, คาดเดา" },
    { word: "connive", type: "v.", meaning: "ร่วมมือ (ในการกระทำผิด), สมรู้ร่วมคิด" },
    { word: "connoisseur", type: "n.", meaning: "ผู้เชี่ยวชาญ (ด้านศิลปะ/อาหาร)" },
    { word: "connote", type: "v.", meaning: "บอกเป็นนัย" },
    { word: "conscribe", type: "v.", meaning: "เกณฑ์ทหาร" },
    { word: "consecrate", type: "v.", meaning: "ทำให้ศักดิ์สิทธิ์" },
    { word: "consign", type: "v.", meaning: "มอบหมาย, ส่งมอบ" },
    { word: "consternation", type: "n.", meaning: "ความตกใจกลัว, ความวิตกกังวล" },
    { word: "constituent", type: "n., adj.", meaning: "องค์ประกอบ, ผู้เลือกตั้ง" },
    { word: "construe", type: "v.", meaning: "ตีความ" },
    { word: "consummate", type: "adj., v.", meaning: "สมบูรณ์แบบ, ทำให้สมบูรณ์" },
    { word: "contemporaneous", type: "adj.", meaning: "เกิดขึ้นในเวลาเดียวกัน" },
    { word: "contentious", type: "adj.", meaning: "เป็นที่ถกเถียง, ชอบโต้แย้ง" },
    { word: "contravene", type: "v.", meaning: "ขัดแย้งกับ, ฝ่าฝืน" },
    { word: "contrite", type: "adj.", meaning: "สำนึกผิด" },
    { word: "contumacious", type: "adj.", meaning: "ดื้อรั้น, ไม่ยอมเชื่อฟัง" },
    { word: "conundrum", type: "n.", meaning: "ปริศนา, ปัญหาที่ยากจะแก้ไข" },
    { word: "converge", type: "v.", meaning: "บรรจบกัน, มุ่งเข้าหากัน" },
    { word: "convoluted", type: "adj.", meaning: "ซับซ้อน, ยุ่งเหยิง" },
    { word: "copious", type: "adj.", meaning: "มากมาย, อุดมสมบูรณ์" },
    { word: "corroborate", type: "v.", meaning: "ยืนยัน, สนับสนุน (หลักฐาน)" },
    { word: "cosmopolitan", type: "adj.", meaning: "ซึ่งประกอบด้วยหลายเชื้อชาติ, ทันสมัย" },
    { word: "coterie", type: "n.", meaning: "กลุ่มคนสนิท, พวกพ้อง" },
    { word: "countermand", type: "v.", meaning: "ยกเลิกคำสั่ง" },
    { word: "craven", type: "adj.", meaning: "ขี้ขลาด" },
    { word: "credulous", type: "adj.", meaning: "หูเบา, เชื่อง่าย" },
    { word: "culminate", type: "v.", meaning: "ถึงจุดสูงสุด, สิ้นสุดลง" },
    { word: "culpable", type: "adj.", meaning: "สมควรถูกตำหนิ, มีความผิด" },
    { word: "cursory", type: "adj.", meaning: "หยาบๆ, คร่าวๆ" },
    { word: "dearth", type: "n.", meaning: "ความขาดแคลน" },
    { word: "debacle", type: "n.", meaning: "ความล้มเหลวโดยสิ้นเชิง, หายนะ" },
    { word: "debilitate", type: "v.", meaning: "ทำให้อ่อนแอ" },
    { word: "debunk", type: "v.", meaning: "เปิดโปงความเท็จ" },
    { word: "decimate", type: "v.", meaning: "ทำลายส่วนใหญ่" },
    { word: "decorum", type: "n.", meaning: "มารยาท, ความเหมาะสม" },
    { word: "deference", type: "n.", meaning: "ความเคารพ, การยอมตาม" },
    { word: "deleterious", type: "adj.", meaning: "เป็นอันตราย" },
    { word: "delineate", type: "v.", meaning: "อธิบายอย่างละเอียด, วาดโครงร่าง" },
    { word: "demagogue", type: "n.", meaning: "นักการเมืองที่ปลุกระดมประชาชน" },
    { word: "denigrate", type: "v.", meaning: "ทำให้เสื่อมเสียชื่อเสียง" },
    { word: "denizen", type: "n.", meaning: "ผู้อยู่อาศัย" },
    { word: "deprecate", type: "v.", meaning: "คัดค้าน, ดูหมิ่น" },
    { word: "derelict", type: "adj., n.", meaning: "ถูกทอดทิ้ง, ทรัพย์สินที่ถูกทอดทิ้ง" },
    { word: "deride", type: "v.", meaning: "เยาะเย้ย, ดูถูก" },
    { word: "derogatory", type: "adj.", meaning: "ดูหมิ่น, ดูถูก" },
    { word: "desiccate", type: "v.", meaning: "ทำให้แห้ง, ดูดความชื้น" },
    { word: "desultory", type: "adj.", meaning: "ไม่มีจุดหมาย, สะเปะสะปะ" },
    { word: "detrimental", type: "adj.", meaning: "เป็นอันตราย" },
    { word: "devoid", type: "adj.", meaning: "ปราศจาก" },
    { word: "diaphanous", type: "adj.", meaning: "บางใส, โปร่งแสง" },
    { word: "diatribe", type: "n.", meaning: "การตำหนิอย่างรุนแรง" },
    { word: "dichotomy", type: "n.", meaning: "การแบ่งออกเป็นสองส่วนที่ตรงข้ามกัน" },
    { word: "didactic", type: "adj.", meaning: "ที่มุ่งให้การสอน" },
    { word: "diffident", type: "adj.", meaning: "ไม่มั่นใจในตนเอง, ขี้อาย" },
    { word: "dilettante", type: "n.", meaning: "ผู้ที่ทำสิ่งต่างๆ อย่างผิวเผิน" },
    { word: "disabuse", type: "v.", meaning: "ทำให้เข้าใจถูกต้อง" },
    { word: "discomfit", type: "v.", meaning: "ทำให้รู้สึกอึดอัด/กระสับกระส่าย" },
    { word: "disparate", type: "adj.", meaning: "แตกต่างกันอย่างสิ้นเชิง" },
    { word: "disparage", type: "v.", meaning: "ดูถูก, ดูหมิ่น" },
    { word: "dispassionate", type: "adj.", meaning: "ปราศจากอคติ, ไม่ใช้อารมณ์" },
    { word: "dissident", type: "n., adj.", meaning: "ผู้เห็นต่าง" },
    { word: "dissipate", type: "v.", meaning: "ทำให้กระจัดกระจาย, ใช้จ่ายสุรุ่ยสุร่าย" },
    { word: "dissonance", type: "n.", meaning: "ความไม่เข้ากัน, ความขัดแย้ง" },
    { word: "distend", type: "v.", meaning: "ขยายตัว, บวม" },
    { word: "divest", type: "v.", meaning: "ถอนการลงทุน, ปลดเปลื้อง" },
    { word: "dogmatic", type: "adj.", meaning: "ดื้อรั้นในหลักคำสอน, หัวรั้น" },
    { word: "doleful", type: "adj.", meaning: "เศร้าโศก" },
    { word: "dormant", type: "adj.", meaning: "เฉื่อยชา, ไม่เคลื่อนไหว" },
    { word: "dubious", type: "adj.", meaning: "น่าสงสัย, ไม่น่าเชื่อถือ" },
    { word: "duplicity", type: "n.", meaning: "ความหลอกลวง, การแสดงสองหน้า" },
    { word: "ebullient", type: "adj.", meaning: "ร่าเริงมีชีวิตชีวา" },
    { word: "eclectic", type: "adj.", meaning: "ซึ่งเลือกสรรสิ่งที่ดีที่สุดจากแหล่งต่างๆ" },
    { word: "edifying", type: "adj.", meaning: "ซึ่งให้ความรู้/ศีลธรรม" },
    { word: "efface", type: "v.", meaning: "ลบออก, ทำให้จางหายไป" },
    { word: "effervescent", type: "adj.", meaning: "มีชีวิตชีวา, ร่าเริง" },
    { word: "efficacious", type: "adj.", meaning: "มีประสิทธิภาพ" },
    { word: "effrontery", type: "n.", meaning: "ความไร้ยางอาย" },
    { word: "egregious", type: "adj.", meaning: "เลวร้ายมาก, โดดเด่นในทางไม่ดี" },
    { word: "elegiac", type: "adj.", meaning: "เศร้าโศก (เกี่ยวกับความตาย/ความสูญเสีย)" },
    { word: "elicit", type: "v.", meaning: "ดึงข้อมูล, กระตุ้น" },
    { word: "elucidate", type: "v.", meaning: "อธิบายให้ชัดเจน" },
    { word: "emanate", type: "v.", meaning: "เปล่งออกมา, กำเนิดจาก" },
    { word: "emend", type: "v.", meaning: "แก้ไข (ข้อผิดพลาดในข้อความ)" },
    { word: "emissary", type: "n.", meaning: "ผู้ส่งสาร, ทูต" },
    { word: "emollient", type: "adj., n.", meaning: "ที่ทำให้ผิวนุ่ม, ครีมบำรุงผิว" },
    { word: "enervate", type: "v.", meaning: "ทำให้หมดกำลัง" },
    { word: "enfranchise", type: "v.", meaning: "ให้สิทธิ์ในการเลือกตั้ง" },
    { word: "engender", type: "v.", meaning: "ก่อให้เกิด, สร้างขึ้น" },
    { word: "ephemeral", type: "adj.", meaning: "ชั่วคราว, ไม่ยั่งยืน" },
    { word: "epigram", type: "n.", meaning: "บทกวีสั้นๆ คมคาย" },
    { word: "epitome", type: "n.", meaning: "แบบอย่างที่ดีเยี่ยม, สรุปย่อ" },
    { word: "equanimity", type: "n.", meaning: "ความสงบเยือกเย็น" },
    { word: "equivocal", type: "adj.", meaning: "กำกวม, ไม่ชัดเจน" },
    { word: "erudite", type: "adj.", meaning: "คงแก่เรียน, มีความรู้มาก" },
    { word: "eschew", type: "v.", meaning: "หลีกเลี่ยง" },
    { word: "esoteric", type: "adj.", meaning: "ลึกลับ, เข้าใจยาก (สำหรับคนวงใน)" },
    { word: "eulogy", type: "n.", meaning: "คำยกย่อง (โดยเฉพาะผู้ตาย)" },
    { word: "euphemism", type: "n.", meaning: "การใช้ถ้อยคำที่สุภาพแทนคำที่ไม่สุภาพ" },
    { word: "euphoria", type: "n.", meaning: "ความรู้สึกสุขสบายอย่างยิ่ง" },
    { word: "evanescent", type: "adj.", meaning: "จางหายไปง่าย, ไม่ยั่งยืน" },
    { word: "evince", type: "v.", meaning: "แสดงให้เห็นอย่างชัดเจน" },
    { word: "exacerbate", type: "v.", meaning: "ทำให้แย่ลง" },
    { word: "exasperate", type: "v.", meaning: "ทำให้โมโห, ทำให้หงุดหงิด" },
    { word: "excoriate", type: "v.", meaning: "วิพากษ์วิจารณ์อย่างรุนแรง" },
    { word: "exculpate", type: "v.", meaning: "พิสูจน์ว่าบริสุทธิ์" },
    { word: "execrable", type: "adj.", meaning: "เลวร้ายมาก, น่ารังเกียจ" },
    { word: "exigent", type: "adj.", meaning: "เร่งด่วน, ต้องการความสนใจทันที" },
    { word: "exonerate", type: "v.", meaning: "พ้นจากข้อกล่าวหา, ทำให้พ้นผิด" },
    { word: "expatiate", type: "v.", meaning: "พูด/เขียนอย่างละเอียด" },
    { word: "expiate", type: "v.", meaning: "ชดใช้บาป" },
    { word: "expunge", type: "v.", meaning: "ลบออก, ขีดฆ่า" },
    { word: "extant", type: "adj.", meaning: "ที่ยังคงมีอยู่" },
    { word: "extol", type: "v.", meaning: "ยกย่องสรรเสริญ" },
    { word: "extrapolate", type: "v.", meaning: "อนุมานจากข้อมูลที่มีอยู่" },
    { word: "extricate", type: "v.", meaning: "ปลดปล่อย, ทำให้หลุดพ้น" },
    { word: "facetious", type: "adj.", meaning: "ตลกโปกฮา, ไม่จริงจัง" },
    { word: "fallacious", type: "adj.", meaning: "ผิดพลาด, หลอกลวง" },
    { word: "fatuous", type: "adj.", meaning: "โง่เขลา, ไร้สาระ" },
    { word: "fealty", type: "n.", meaning: "ความจงรักภักดี" },
    { word: "fecund", type: "adj.", meaning: "อุดมสมบูรณ์, มีลูกดก" },
    { word: "feign", type: "v.", meaning: "แกล้งทำ, เสแสร้ง" },
    { word: "felicitous", type: "adj.", meaning: "เหมาะสม, น่ายินดี" },
    { word: "fervid", type: "adj.", meaning: "กระตือรือร้นอย่างแรงกล้า" },
    { word: "fetid", type: "adj.", meaning: "มีกลิ่นเหม็นเน่า" },
    { word: "fiat", type: "n.", meaning: "คำสั่ง, กฤษฎีกา" },
    { word: "fiduciary", type: "adj., n.", meaning: "เกี่ยวกับความไว้วางใจ, ผู้ดูแลผลประโยชน์" },
    { word: "figurative", type: "adj.", meaning: "เป็นอุปมาอุปไมย" },
    { word: "flaccid", type: "adj.", meaning: "อ่อนปวกเปียก, หย่อนยาน" },
    { word: "flagellate", type: "v.", meaning: "เฆี่ยน, ตี" },
    { word: "florid", type: "adj.", meaning: "แดงก่ำ, หรูหราฟุ่มเฟือย" },
    { word: "flout", type: "v.", meaning: "ดูถูก, ไม่เคารพ (กฎ)" },
    { word: "foible", type: "n.", meaning: "ข้อเสียเล็กๆ น้อยๆ, จุดอ่อน" },
    { word: "foment", type: "v.", meaning: "ยุยง, ปลุกปั่น" },
    { word: "forbearance", type: "n.", meaning: "ความอดกลั้น" },
    { word: "forestall", type: "v.", meaning: "ป้องกันไว้ก่อน" },
    { word: "forlorn", type: "adj.", meaning: "โดดเดี่ยว, หดหู่" },
    { word: "forsake", type: "v.", meaning: "ละทิ้ง, ทอดทิ้ง" },
    { word: "fortuitous", type: "adj.", meaning: "โดยบังเอิญ, โชคดี" },
    { word: "fractious", type: "adj.", meaning: "เจ้าอารมณ์, ควบคุมยาก" },
    { word: "frenetic", type: "adj.", meaning: "บ้าคลั่ง, กระสับกระส่าย" },
    { word: "fulminate", type: "v.", meaning: "ประณามอย่างรุนแรง" },
    { word: "fustian", type: "n., adj.", meaning: "ผ้ากำมะหยี่, คำพูดโอ้อวด" },
    { word: "gainsay", type: "v.", meaning: "ปฏิเสธ, โต้แย้ง" },
    { word: "garner", type: "v.", meaning: "รวบรวม, เก็บเกี่ยว" },
    { word: "garrulous", type: "adj.", meaning: "ช่างพูด, พูดมาก" },
    { word: "genial", type: "adj.", meaning: "เป็นมิตร, ใจดี" },
    { word: "gerrymander", type: "v.", meaning: "แบ่งเขตเลือกตั้งเพื่อผลประโยชน์ทางการเมือง" },
    { word: "gregarious", type: "adj.", meaning: "ชอบเข้าสังคม" },
    { word: "guile", type: "n.", meaning: "เล่ห์เหลี่ยม, ความเจ้าเล่ห์" },
    { word: "hackneyed", type: "adj.", meaning: "ซ้ำซาก, ใช้จนเบื่อ" },
    { word: "hallowed", type: "adj.", meaning: "ศักดิ์สิทธิ์" },
    { word: "harangue", type: "n., v.", meaning: "การปราศรัยที่ดุดัน, ปราศรัยดุดัน" },
    { word: "hegemony", type: "n.", meaning: "อำนาจนำ, การครอบงำ" },
    { word: "hermetic", type: "adj.", meaning: "ปิดสนิท, ลึกลับ" },
    { word: "heterodox", type: "adj.", meaning: "นอกรีต, นอกแบบแผน" },
    { word: "histrionic", type: "adj.", meaning: "โอ้อวด, ชอบแสดง (เกินจริง)" },
    { word: "hoary", type: "adj.", meaning: "เก่าแก่, ผมหงอก" },
    { word: "homily", type: "n.", meaning: "คำเทศนา, การสั่งสอน" },
    { word: "homogeneous", type: "adj.", meaning: "เป็นเนื้อเดียวกัน" },
    { word: "hyperbole", type: "n.", meaning: "การกล่าวเกินจริง" },
    { word: "iconoclast", type: "n.", meaning: "ผู้ทำลายรูปเคารพ, ผู้ที่ต่อต้านความเชื่อดั้งเดิม" },
    { word: "ignominious", type: "adj.", meaning: "น่าอับอาย" },
    { word: "imbroglio", type: "n.", meaning: "สถานการณ์ที่ซับซ้อนและยุ่งเหยิง" },
    { word: "impecunious", type: "adj.", meaning: "ยากจน" },
    { word: "imperious", type: "adj.", meaning: "เผด็จการ, ชอบออกคำสั่ง" },
    { word: "impertinent", type: "adj.", meaning: "ไม่สุภาพ, ไม่เคารพ" },
    { word: "impervious", type: "adj.", meaning: "ไม่สามารถผ่านเข้าไปได้, ไม่ได้รับผลกระทบ" },
    { word: "impetuous", type: "adj.", meaning: "หุนหันพลันแล่น, ใจร้อน" },
    { word: "impinge", type: "v.", meaning: "กระทบกระเทือน, ละเมิด" },
    { word: "implacable", type: "adj.", meaning: "ไม่สามารถประนีประนอมได้, ไม่ยอมอ่อนข้อ" },
    { word: "imponderable", type: "adj., n.", meaning: "ที่ประเมินค่าไม่ได้, สิ่งที่ประเมินค่าไม่ได้" },
    { word: "importune", type: "v.", meaning: "รบเร้า, ขอร้องซ้ำๆ" },
    { word: "imprecation", type: "n.", meaning: "คำสาปแช่ง" },
    { word: "impudent", type: "adj.", meaning: "ไร้ยางอาย, ทะลึ่ง" },
    { word: "impugn", type: "v.", meaning: "โต้แย้ง, ตั้งข้อสงสัย" },
    { word: "impute", type: "v.", meaning: "กล่าวหา, โทษว่าเป็นความผิด" },
    { word: "inchoate", type: "adj.", meaning: "ที่เพิ่งเริ่มต้น, ที่ยังไม่สมบูรณ์" },
    { word: "incipient", type: "adj.", meaning: "ที่เริ่มปรากฏ, แรกเริ่ม" },
    { word: "incongruous", type: "adj.", meaning: "ไม่เข้ากัน, ไม่สอดคล้องกัน" },
    { word: "inculcate", type: "v.", meaning: "ปลูกฝัง, สอน" },
    { word: "inculpate", type: "v.", meaning: "กล่าวหา, ทำให้รู้สึกผิด" },
    { word: "indefatigable", type: "adj.", meaning: "ไม่รู้จักเหน็ดเหนื่อย" },
    { word: "indigenous", type: "adj.", meaning: "พื้นเมือง, ดั้งเดิม" },
    { word: "indolent", type: "adj.", meaning: "เกียจคร้าน, เฉื่อยชา" },
    { word: "ineffable", type: "adj.", meaning: "ที่ไม่อาจบรรยายได้" },
    { word: "ineluctable", type: "adj.", meaning: "หลีกเลี่ยงไม่ได้" },
    { word: "inept", type: "adj.", meaning: "ไร้ความสามารถ, งุ่มง่าม" },
    { word: "inert", type: "adj.", meaning: "เฉื่อยชา, ไม่เคลื่อนไหว" },
    { word: "inexorable", type: "adj.", meaning: "ไม่หยุดยั้ง, ไม่ยอมเปลี่ยนแปลง" },
    { word: "infallible", type: "adj.", meaning: "ไม่ผิดพลาด" },
    { word: "infantile", type: "adj.", meaning: "เหมือนเด็กทารก, ไร้เดียงสา" },
    { word: "infernal", type: "adj.", meaning: "เกี่ยวกับนรก, น่ารังเกียจ" },
    { word: "infiltrate", type: "v.", meaning: "แทรกซึม" },
    { word: "infirmity", type: "n.", meaning: "ความอ่อนแอ, ความเจ็บป่วย" },
    { word: "inflated", type: "adj.", meaning: "พองตัว, สูงเกินจริง" },
    { word: "inimical", type: "adj.", meaning: "เป็นอันตราย, เป็นศัตรู" },
    { word: "iniquitous", type: "adj.", meaning: "อยุติธรรม, ชั่วร้าย" },
    { word: "innocuous", type: "adj.", meaning: "ไม่เป็นอันตราย" },
    { word: "inscrutable", type: "adj.", meaning: "เข้าใจยาก, ลึกลับ" },
    { word: "insidious", type: "adj.", meaning: "เจ้าเล่ห์, มีเล่ห์เหลี่ยม" },
    { word: "insinuate", type: "v.", meaning: "บอกเป็นนัยในทางลบ" },
    { word: "insipid", type: "adj.", meaning: "จืดชืด, ไม่มีรสชาติ" },
    { word: "insouciant", type: "adj.", meaning: "ไม่กังวล, ไม่แยแส" },
    { word: "insular", type: "adj.", meaning: "แคบ, โดดเดี่ยว" },
    { word: "insurgent", type: "n., adj.", meaning: "ผู้ก่อการกบฏ" },
    { word: "interdict", type: "v., n.", meaning: "ห้าม, การห้าม" },
    { word: "internecine", type: "adj.", meaning: "ซึ่งทำลายล้างซึ่งกันและกัน" },
    { word: "interpose", type: "v.", meaning: "แทรกแซง, ขัดขวาง" },
    { word: "intransigent", type: "adj.", meaning: "ไม่ยอมประนีประนอม" },
    { word: "intrepid", type: "adj.", meaning: "กล้าหาญ, ไม่เกรงกลัว" },
    { word: "inured", type: "adj.", meaning: "เคยชินกับความยากลำบาก" },
    { word: "invective", type: "n.", meaning: "คำด่าทอ, คำประณาม" },
    { word: "inveigh", type: "v.", meaning: "ประท้วงอย่างรุนแรง" },
    { word: "inveigle", type: "v.", meaning: "หลอกล่อ, ชักจูงด้วยเล่ห์เหลี่ยม" },
    { word: "inveterate", type: "adj.", meaning: "ฝังรากลึก, ติดเป็นนิสัย" },
    { word: "invidious", type: "adj.", meaning: "น่าอิจฉา, ก่อให้เกิดความอิจฉา" },
    { word: "irascible", type: "adj.", meaning: "เจ้าอารมณ์, โกรธง่าย" },
    { word: "irresolute", type: "adj.", meaning: "ลังเล, ไม่แน่วแน่" },
    { word: "itinerant", type: "adj., n.", meaning: "ซึ่งเดินทางไปมา, ผู้เดินทาง" },
    { word: "jaundiced", type: "adj.", meaning: "มีอคติ, อิจฉา" },
    { word: "jejune", type: "adj.", meaning: "จืดชืด, ไม่น่าสนใจ" },
    { word: "jettison", type: "v.", meaning: "ทิ้ง (สิ่งที่ไม่จำเป็น), โยนทิ้ง" },
    { word: "jocose", type: "adj.", meaning: "ตลกขบขัน" },
    { word: "juggernaut", type: "n.", meaning: "กองกำลังที่ไม่อาจหยุดยั้งได้" },
    { word: "juxtapose", type: "v.", meaning: "วางเคียงข้างกันเพื่อเปรียบเทียบ" },
    { word: "kudos", type: "n.", meaning: "เกียรติยศ, คำชมเชย" },
    { word: "lachrymose", type: "adj.", meaning: "ชอบร้องไห้, น่าเศร้า" },
    { word: "laconic", type: "adj.", meaning: "พูดน้อย, กระชับ" },
    { word: "languid", type: "adj.", meaning: "อ่อนแรง, เซื่องซึม" },
    { word: "largesse", type: "n.", meaning: "ความใจกว้าง, เงินบริจาค" },
    { word: "latent", type: "adj.", meaning: "แฝงอยู่, ซ่อนเร้น" },
    { word: "laud", type: "v.", meaning: "ยกย่องสรรเสริญ" },
    { word: "laudable", type: "adj.", meaning: "น่าสรรเสริญ" },
    { word: "legerdemain", type: "n.", meaning: "กลอุบาย, ความคล่องแคล่ว" },
    { word: "lethargy", type: "n.", meaning: "ความเฉื่อยชา, การขาดพลังงาน" },
    { word: "levity", type: "n.", meaning: "ความคะนอง, ความไม่จริงจัง" },
    { word: "libertine", type: "n.", meaning: "ผู้ที่มีชีวิตอิสระทางศีลธรรม (ในทางไม่ดี)" },
    { word: "limpid", type: "adj.", meaning: "ใสสะอาด, ชัดเจน" },
    { word: "litany", type: "n.", meaning: "บทสวด, รายการที่ยาวและน่าเบื่อ" },
    { word: "lithe", type: "adj.", meaning: "อ่อนช้อย, คล่องแคล่ว" },
    { word: "livid", type: "adj.", meaning: "โกรธจัด, ซีดเผือด" },
    { word: "lugubrious", type: "adj.", meaning: "เศร้าโศก, หม่นหมอง" },
    { word: "luminous", type: "adj.", meaning: "สว่างจ้า, เปล่งแสง" },
    { word: "machination", type: "n.", meaning: "แผนการชั่วร้าย, การวางอุบาย" },
    { word: "macroscopic", type: "adj.", meaning: "มองเห็นได้ด้วยตาเปล่า" },
    { word: "magnanimous", type: "adj.", meaning: "ใจกว้าง, มีน้ำใจ" },
    { word: "maim", type: "v.", meaning: "ทำให้พิการ" },
    { word: "malaise", type: "n.", meaning: "ความรู้สึกไม่สบาย, ความไม่สบายใจ" },
    { word: "malapropism", type: "n.", meaning: "การใช้คำผิดความหมายโดยไม่ตั้งใจ (มักสร้างเสียงหัวเราะ)" },
    { word: "malfeasance", type: "n.", meaning: "การประพฤติมิชอบ (โดยเจ้าหน้าที่ของรัฐ)" },
    { word: "malinger", type: "v.", meaning: "แกล้งป่วยเพื่อหลีกเลี่ยงงาน" },
    { word: "malleable", type: "adj.", meaning: "ตีขึ้นรูปได้, ปรับเปลี่ยนได้" },
    { word: "mandate", type: "v.", meaning: "มอบอำนาจ, สั่ง" },
    { word: "manifold", type: "adj.", meaning: "มากมาย, หลากหลาย" },
    { word: "maudlin", type: "adj.", meaning: "อ่อนไหวเกินไป, สะอื้น" },
    { word: "maverick", type: "n.", meaning: "คนนอกคอก, ผู้ไม่ยอมตามใคร" },
    { word: "maxim", type: "n.", meaning: "คติพจน์, สุภาษิต" },
    { word: "meander", type: "v.", meaning: "คดเคี้ยว, เตร็ดเตร่" },
    { word: "melancholy", type: "n., adj.", meaning: "ความโศกเศร้า, เศร้าโศก" },
    { word: "mellifluous", type: "adj.", meaning: "ไพเราะ (เสียง), หวานหู" },
    { word: "mendacious", type: "adj.", meaning: "โกหก, ไม่ซื่อสัตย์" },
    { word: "meretricious", type: "adj.", meaning: "ฉูดฉาดแต่ไร้ค่า, ลวงตา" },
    { word: "metamorphosis", type: "n.", meaning: "การเปลี่ยนแปลงรูปร่าง/ลักษณะ" },
    { word: "meticulous", type: "adj.", meaning: "พิถีพิถัน, ละเอียดถี่ถ้วน" },
    { word: "minatory", type: "adj.", meaning: "คุกคาม" },
    { word: "minutiae", type: "n.", meaning: "รายละเอียดเล็กๆ น้อยๆ" },
    { word: "misanthrope", type: "n.", meaning: "ผู้เกลียดชังมนุษย์" },
    { word: "miscreant", type: "n.", meaning: "คนชั่วร้าย, อาชญากร" },
    { word: "misnomer", type: "n.", meaning: "ชื่อที่ไม่เหมาะสม" },
    { word: "modicum", type: "n.", meaning: "จำนวนเล็กน้อย" },
    { word: "mollify", type: "v.", meaning: "ทำให้ใจเย็นลง, ปลอบโยน" },
    { word: "monolithic", type: "adj.", meaning: "เป็นเนื้อเดียวกัน, ใหญ่โตและแข็งแกร่ง" },
    { word: "moribund", type: "adj.", meaning: "ที่กำลังจะตาย, ที่ใกล้จะสิ้นสุด" },
    { word: "morose", type: "adj.", meaning: "หงุดหงิด, ซึมเซา" },
    { word: "multifarious", type: "adj.", meaning: "หลากหลาย, มากมาย" },
    { word: "munificent", type: "adj.", meaning: "ใจกว้าง, ให้ด้วยความเต็มใจ" },
    { word: "myriad", type: "n., adj.", meaning: "จำนวนมากมายนับไม่ถ้วน" },
    { word: "nadir", type: "n.", meaning: "จุดต่ำสุด" },
    { word: "nascent", type: "adj.", meaning: "ที่เพิ่งเริ่มต้นพัฒนา" },
    { word: "nefarious", type: "adj.", meaning: "ชั่วร้าย, อัปยศ" },
    { word: "neophyte", type: "n.", meaning: "ผู้เริ่มต้น, ผู้มาใหม่" },
    { word: "nexus", type: "n.", meaning: "จุดเชื่อมโยง, ศูนย์กลาง" },
    { word: "noisome", type: "adj.", meaning: "มีกลิ่นเหม็น, เป็นอันตราย" },
    { word: "nonchalant", type: "adj.", meaning: "ไม่แยแส, ไม่สะทกสะท้าน" },
    { word: "nonplus", type: "v.", meaning: "ทำให้สับสนงุนงงจนทำอะไรไม่ถูก" },
    { word: "noxious", type: "adj.", meaning: "เป็นพิษ, เป็นอันตราย" },
    { word: "obdurate", type: "adj.", meaning: "ดื้อรั้น, ใจแข็ง" },
    { word: "obfuscate", type: "v.", meaning: "ทำให้สับสน, ทำให้คลุมเครือ" },
    { word: "oblique", type: "adj.", meaning: "เฉียง, ไม่ตรงไปตรงมา" },
    { word: "obsequious", type: "adj.", meaning: "ประจบสอพลอ" },
    { word: "obstreperous", type: "adj.", meaning: "ส่งเสียงดัง, ควบคุมยาก" },
    { word: "obviate", type: "v.", meaning: "ขจัด, ทำให้ไม่จำเป็น" },
    { word: "occlude", type: "v.", meaning: "ปิดกั้น, อุดตัน" },
    { word: "officious", type: "adj.", meaning: "ชอบจุ้นจ้าน, ชอบสอดแทรก" },
    { word: "oligarchy", type: "n.", meaning: "คณาธิปไตย (การปกครองโดยคนกลุ่มน้อย)" },
    { word: "omniscient", type: "adj.", meaning: "รอบรู้ทุกสิ่ง" },
    { word: "onerous", type: "adj.", meaning: "หนักหน่วง, เป็นภาระ" },
    { word: "onus", type: "n.", meaning: "ภาระหน้าที่, ความรับผิดชอบ" },
    { word: "opulent", type: "adj.", meaning: "มั่งคั่ง, หรูหรา" },
    { word: "oracular", type: "adj.", meaning: "คลุมเครือ, เป็นปริศนา (เหมือนคำทำนาย)" },
    { word: "oscillate", type: "v.", meaning: "แกว่งไปมา, สั่น" },
    { word: "ostensible", type: "adj.", meaning: "ที่อ้างว่าเป็น, ดูเหมือนว่า" },
    { word: "ostracize", type: "v.", meaning: "ขับไล่ออกจากสังคม" },
    { word: "overt", type: "adj.", meaning: "เปิดเผย, ชัดเจน" },
    { word: "palatable", type: "adj.", meaning: "อร่อย, เป็นที่ยอมรับได้" },
    { word: "palliative", type: "adj., n.", meaning: "บรรเทา (อาการ/ปัญหา), ยาบรรเทา" },
    { word: "palpable", type: "adj.", meaning: "ชัดเจน, สัมผัสได้" },
    { word: "panacea", type: "n.", meaning: "ยาครอบจักรวาล, วิธีแก้ปัญหาทั้งหมด" },
    { word: "paradigm", type: "n.", meaning: "แบบอย่าง, กระบวนทัศน์" },
    { word: "paradoxical", type: "adj.", meaning: "ที่ขัดแย้งในตัวเอง" },
    { word: "paragon", type: "n.", meaning: "แบบอย่างที่สมบูรณ์แบบ" },
    { word: "pariah", type: "n.", meaning: "คนนอกคอก, คนที่ถูกสังคมรังเกียจ" },
    { word: "parochial", type: "adj.", meaning: "ใจแคบ, เกี่ยวกับโบสถ์ท้องถิ่น" },
    { word: "parsimonious", type: "adj.", meaning: "ตระหนี่, มัธยัสถ์เกินไป" },
    { word: "partisan", type: "adj., n.", meaning: "ที่เข้าข้างฝ่ายใดฝ่ายหนึ่ง, ผู้สนับสนุน" },
    { word: "paucity", type: "n.", meaning: "ความขาดแคลน" },
    { word: "peccadillo", type: "n.", meaning: "ความผิดเล็กๆ น้อยๆ" },
    { word: "pecuniary", type: "adj.", meaning: "เกี่ยวกับการเงิน" },
    { word: "pedantic", type: "adj.", meaning: "จู้จี้จุกจิก (เกี่ยวกับกฎ/รายละเอียด)" },
    { word: "pejorative", type: "adj.", "meaning": "ดูหมิ่น, เหยียดหยาม" },
    { word: "penchant", type: "n.", meaning: "ความชอบ, แนวโน้ม" },
    { word: "penitent", type: "adj., n.", meaning: "สำนึกผิด, ผู้สำนึกผิด" },
    { word: "penury", type: "n.", meaning: "ความยากจนข้นแค้น" },
    { word: "perfidious", type: "adj.", meaning: "ไม่ซื่อสัตย์, ทรยศ" },
    { word: "perfunctory", type: "adj.", meaning: "ทำลวกๆ, ทำอย่างไม่ใส่ใจ" },
    { word: "perilous", type: "adj.", meaning: "อันตราย" },
    { word: "peripatetic", type: "adj.", meaning: "ซึ่งเดินทางไปมา, ซึ่งเดินทาง" },
    { word: "perjury", type: "n.", meaning: "การให้การเท็จ" },
    { word: "permeate", type: "v.", meaning: "ซึมซาบ, แพร่กระจาย" },
    { word: "pernicious", type: "adj.", meaning: "เป็นอันตรายอย่างร้ายแรง, ร้ายกาจ" },
    { word: "perpetuate", type: "v.", meaning: "ทำให้คงอยู่ตลอดไป" },
    { word: "perspicacious", type: "adj.", meaning: "เฉียบแหลม, มีไหวพริบ" },
    { word: "pertinacious", type: "adj.", meaning: "ดื้อรั้น, ยืนกราน" },
    { word: "peruse", type: "v.", meaning: "อ่านอย่างละเอียด" },
    { word: "pervade", type: "v.", meaning: "แผ่ซ่าน, แพร่กระจายไปทั่ว" },
    { word: "petulant", type: "adj.", meaning: "เจ้าอารมณ์, หงุดหงิดง่าย" },
    { word: "philistine", type: "n.", meaning: "ผู้ที่ไม่สนใจศิลปะ/วัฒนธรรม" },
    { word: "phlegmatic", type: "adj.", meaning: "ใจเย็น, ไม่ตื่นเต้นง่าย" },
    { word: "picaresque", type: "adj.", meaning: "เกี่ยวกับตัวละครที่มีการผจญภัยแบบโกงๆ" },
    { word: "pied", type: "adj.", meaning: "มีหลายสี" },
    { word: "piety", type: "n.", meaning: "ความศรัทธา, ความเลื่อมใส" },
    { word: "pillage", type: "v.", meaning: "ปล้นสะดม" },
    { word: "pique", type: "n., v.", meaning: "ความขุ่นเคือง, ทำให้ขุ่นเคือง" },
    { word: "placate", type: "v.", meaning: "ทำให้ใจเย็นลง, ปลอบประโลม" },
    { word: "placid", type: "adj.", meaning: "สงบ, เงียบสงบ" },
    { word: "platitude", type: "n.", meaning: "คำพูดซ้ำซาก, คำพูดธรรมดาๆ" },
    { word: "plethora", type: "n.", meaning: "ความมากมายเกินไป" },
    { word: "plummet", type: "v.", meaning: "ดิ่งลงอย่างรวดเร็ว" },
    { word: "poignant", type: "adj.", meaning: "สะเทือนใจ, ซาบซึ้ง" },
    { word: "polemic", type: "n.", meaning: "การโต้แย้งอย่างรุนแรง" },
    { word: "polyglot", type: "n., adj.", meaning: "ผู้พูดได้หลายภาษา, หลายภาษา" },
    { word: "ponderous", type: "adj.", meaning: "อุ้ยอ้าย, หนักอึ้ง, น่าเบื่อ" },
    { word: "portent", type: "n.", meaning: "ลางบอกเหตุ" },
    { word: "postulate", type: "v., n.", meaning: "สมมติ, ข้อสมมติฐาน" },
    { word: "potable", type: "adj.", meaning: "ดื่มได้" },
    { word: "pragmatic", type: "adj.", meaning: "ปฏิบัติได้จริง" },
    { word: "precarious", type: "adj.", meaning: "ไม่มั่นคง, อันตราย" },
    { word: "preclude", type: "v.", meaning: "ป้องกัน, ขัดขวาง" },
    { word: "precocious", type: "adj.", meaning: "แก่แดด, ฉลาดเกินวัย" },
    { word: "precursor", type: "n.", meaning: "ผู้บุกเบิก, สิ่งที่มาก่อน" },
    { word: "predilection", type: "n.", meaning: "ความชอบเป็นพิเศษ" },
    { word: "premonition", type: "n.", meaning: "ลางสังหรณ์" },
    { word: "prescient", type: "adj.", meaning: "หยั่งรู้, มองการณ์ไกล" },
    { word: "prevaricate", type: "v.", meaning: "พูดอ้อมค้อม, บ่ายเบี่ยง" },
    { word: "primordial", type: "adj.", meaning: "ดั้งเดิม, แรกเริ่ม" },
    { word: "pristine", type: "adj.", meaning: "บริสุทธิ์, ยังไม่ได้ถูกแตะต้อง" },
    { word: "profligate", type: "adj., n.", meaning: "ใช้จ่ายสุรุ่ยสุร่าย, คนสุรุ่ยสุร่าย" },
    { word: "progeny", type: "n.", meaning: "ลูกหลาน, ผลผลิต" },
    { word: "proliferate", type: "v.", meaning: "แพร่หลายอย่างรวดเร็ว" },
    { word: "promulgate", type: "v.", meaning: "ประกาศใช้, เผยแพร่" },
    { word: "propensity", type: "n.", meaning: "แนวโน้ม, ความโน้มเอียง" },
    { word: "propitiate", type: "v.", meaning: "เอาใจ, ทำให้สงบ" },
    { word: "propriety", type: "n.", meaning: "ความเหมาะสม, มารยาท" },
    { word: "prosaic", type: "adj.", meaning: "ธรรมดา, น่าเบื่อ" },
    { word: "proscribe", type: "v.", meaning: "สั่งห้าม, เนรเทศ" },
    { word: "protagonist", type: "n.", meaning: "ตัวเอก" },
    { word: "protean", type: "adj.", meaning: "สามารถปรับเปลี่ยนได้หลายรูปแบบ" },
    { word: "protract", type: "v.", meaning: "ยืดเวลาออกไป" },
    { word: "provident", type: "adj.", meaning: "รอบคอบ, ประหยัด" },
    { word: "provisional", type: "adj.", meaning: "ชั่วคราว" },
    { word: "proximity", type: "n.", meaning: "ความใกล้ชิด" },
    { word: "prudent", type: "adj.", meaning: "รอบคอบ, สุขุม" },
    { word: "puerile", type: "adj.", meaning: "เหมือนเด็ก, ไร้สาระ" },
    { word: "pugnacious", type: "adj.", meaning: "ชอบต่อสู้, ชอบทะเลาะ" },
    { word: "pulchritude", type: "n.", meaning: "ความสวยงาม" },
    { word: "punctilious", type: "adj.", meaning: "พิถีพิถัน, ละเอียดถี่ถ้วน" },
    { word: "pundit", type: "n.", meaning: "ผู้เชี่ยวชาญ, นักวิจารณ์" },
    { word: "pungent", type: "adj.", meaning: "มีกลิ่นฉุน, เผ็ดร้อน" },
    { word: "purloin", type: "v.", meaning: "ขโมย" },
    { word: "pusillanimous", type: "adj.", meaning: "ขี้ขลาด" },
    { word: "quandary", type: "n.", meaning: "ภาวะกลืนไม่เข้าคายไม่ออก, ความลำบากใจ" },
    { word: "quell", type: "v.", meaning: "ปราบปราม, ทำให้สงบ" },
    { word: "querulous", type: "adj.", meaning: "ขี้บ่น, ชอบบ่น" },
    { word: "quixotic", type: "adj.", meaning: "เพ้อฝัน, ไม่สมจริง" },
    { word: "quotidian", type: "adj.", meaning: "ธรรมดา, เกิดขึ้นทุกวัน" },
    { word: "rancid", type: "adj.", meaning: "เหม็นหืน" },
    { word: "rancor", type: "n.", meaning: "ความอาฆาตพยาบาท" },
    { word: "rapacious", type: "adj.", meaning: "โลภ, โลภมาก" },
    { word: "rarefied", type: "adj.", meaning: "หายาก, ประณีต" },
    { word: "recalcitrant", type: "adj.", meaning: "ดื้อรั้น, ไม่เชื่อฟัง" },
    { word: "recant", type: "v.", meaning: "ถอนคำพูด" },
    { word: "recidivism", type: "n.", meaning: "การกลับไปกระทำความผิดซ้ำ" },
    { word: "recondite", type: "adj.", meaning: "ลึกซึ้ง, เข้าใจยาก" },
    { word: "refractory", type: "adj.", meaning: "ดื้อรั้น, ไม่ตอบสนอง" },
    { word: "refulgent", type: "adj.", meaning: "สุกใส, เปล่งปลั่ง" },
    { word: "refute", type: "v.", meaning: "หักล้าง, พิสูจน์ว่าผิด" },
    { word: "relegate", type: "v.", meaning: "ลดตำแหน่ง, ลดระดับ" },
    { word: "remiss", type: "adj.", meaning: "ประมาท, สะเพร่า" },
    { word: "remonstrate", type: "v.", meaning: "ทักท้วง, คัดค้าน" },
    { word: "repast", type: "n.", meaning: "อาหาร, มื้ออาหาร" },
    { word: "replete", type: "adj.", meaning: "เต็มเปี่ยม, สมบูรณ์" },
    { word: "reprobate", type: "n., adj.", meaning: "คนชั่วร้าย, เลวทราม" },
    { word: "repudiate", type: "v.", meaning: "ปฏิเสธ, ไม่ยอมรับ" },
    { word: "rescind", type: "v.", meaning: "ยกเลิก (กฎหมาย/ข้อตกลง)" },
    { word: "resilient", type: "adj.", meaning: "ยืดหยุ่น, ฟื้นตัวเร็ว" },
    { word: "resplendent", type: "adj.", meaning: "รุ่งโรจน์, งดงาม" },
    { word: "restive", type: "adj.", meaning: "กระสับกระส่าย, ไม่สงบ" },
    { word: "reticent", type: "adj.", meaning: "เก็บตัว, ไม่ค่อยพูด" },
    { word: "retrograde", type: "adj., v.", meaning: "ถอยหลัง, เสื่อมถอย" },
    { word: "ribald", type: "adj.", meaning: "หยาบคาย, หยาบโลน" },
    { word: "rife", type: "adj.", meaning: "แพร่หลาย, เต็มไปด้วย (สิ่งไม่ดี)" },
    { word: "ruminative", type: "adj.", meaning: "ครุ่นคิด, ไตร่ตรอง" },
    { word: "sacrosanct", type: "adj.", meaning: "ศักดิ์สิทธิ์และไม่อาจละเมิดได้" },
    { word: "sagacious", type: "adj.", meaning: "ฉลาด, มีไหวพริบ" },
    { word: "salient", type: "adj.", meaning: "โดดเด่น, สำคัญ" },
    { word: "salubrious", type: "adj.", meaning: "ส่งเสริมสุขภาพ" },
    { word: "sanctimonious", type: "adj.", meaning: "ทำเป็นเคร่งศาสนา, เจ้าเล่ห์" },
    { word: "sanguine", type: "adj.", meaning: "ร่าเริง, มองโลกในแง่ดี" },
    { word: "sardonic", type: "adj.", meaning: "เย้ยหยัน, เสียดสี" },
    { word: "satiate", type: "v.", meaning: "ทำให้พอใจอย่างเต็มที่" },
    { word: "savoir-faire", type: "n.", meaning: "ความคล่องแคล่วทางสังคม" },
    { word: "scathing", type: "adj.", meaning: "วิพากษ์วิจารณ์อย่างรุนแรง" },
    { word: "scintillating", type: "adj.", meaning: "เฉลียวฉลาด, มีชีวิตชีวา" },
    { word: "scrupulous", type: "adj.", meaning: "พิถีพิถัน, มีศีลธรรม" },
    { word: "sedulous", type: "adj.", meaning: "ขยันหมั่นเพียร" },
    { word: "seminal", type: "adj.", meaning: "สำคัญ, เป็นจุดเริ่มต้น" },
    { word: "sentient", type: "adj.", meaning: "มีความรู้สึก, มีสติ" },
    { word: "servile", type: "adj.", meaning: "ประจบสอพลอ, เหมือนทาส" },
    { word: "sinecure", type: "n.", meaning: "ตำแหน่งที่ได้เงินง่ายแต่ไม่ต้องทำงานมาก" },
    { word: "slander", type: "n., v.", meaning: "การหมิ่นประมาทด้วยวาจา, หมิ่นประมาทด้วยวาจา" },
    { word: "sojourn", type: "n., v.", meaning: "การพำนักชั่วคราว, พำนักชั่วคราว" },
    { word: "solace", type: "n., v.", meaning: "การปลอบโยน, ปลอบโยน" },
    { word: "solicitous", type: "adj.", meaning: "กังวลใจ, เอาใจใส่" },
    { word: "somnambulist", type: "n.", meaning: "ผู้เดินละเมอ" },
    { word: "sophistry", type: "n.", meaning: "การใช้เหตุผลที่ผิดเพื่อหลอกลวง" },
    { word: "sophomoric", type: "adj.", meaning: "ยังไม่เป็นผู้ใหญ่, ตื้นเขิน" },
    { word: "spate", type: "n.", meaning: "จำนวนมาก (ที่เกิดขึ้นอย่างรวดเร็ว)" },
    { word: "specious", type: "adj.", meaning: "ดูเหมือนถูกแต่ไม่จริง, น่าหลงเชื่อ" },
    { word: "splenetic", type: "adj.", meaning: "อารมณ์เสีย, ขุ่นเคือง" },
    { word: "spurious", type: "adj.", meaning: "ปลอม, ไม่แท้จริง" },
    { word: "staid", type: "adj.", meaning: "สงบเสงี่ยม, เคร่งขรึม" },
    { word: "stentorian", type: "adj.", meaning: "เสียงดังกึกก้อง" },
    { word: "stigma", type: "n.", meaning: "ตราบาป, ความอัปยศ" },
    { word: "stipulate", type: "v.", meaning: "กำหนดเงื่อนไข, ระบุ" },
    { word: "stoic", type: "adj., n.", meaning: "อดทน, ผู้ที่อดทน" },
    { word: "strident", type: "adj.", meaning: "เสียงดังบาดหู, แข็งกร้าว" },
    { word: "sublime", type: "adj.", meaning: "สูงส่ง, ยอดเยี่ยม" },
    { word: "subterfuge", type: "n.", meaning: "อุบาย, กลอุบาย" },
    { word: "succinct", type: "adj.", meaning: "กระชับ, รัดกุม" },
    { word: "suffuse", type: "v.", meaning: "แผ่กระจายไปทั่ว, คลุม" },
    { word: "supercilious", type: "adj.", meaning: "เย่อหยิ่ง, วางท่า" },
    { word: "superfluous", type: "adj.", meaning: "มากเกินความจำเป็น" },
    { word: "superimpose", type: "v.", meaning: "วางซ้อนทับกัน" },
    { word: "supplant", type: "v.", meaning: "เข้ามาแทนที่" },
    { word: "surreptitious", type: "adj.", meaning: "ลับๆ ล่อๆ, แอบซ่อน" },
    { word: "sybarite", type: "n.", meaning: "ผู้ที่รักความหรูหราฟุ่มเฟือย" },
    { word: "sycophant", type: "n.", meaning: "คนประจบสอพลอ" },
    { word: "tacit", type: "adj.", meaning: "โดยนัย, ไม่ได้กล่าวโดยตรง" },
    { word: "taciturn", type: "adj.", meaning: "เงียบขรึม, ไม่ค่อยพูด" },
    { word: "tangential", type: "adj.", meaning: "นอกประเด็น, ไม่เกี่ยวข้องโดยตรง" },
    { word: "tantamount", type: "adj.", meaning: "เท่ากัน, เท่ากับ" },
    { word: "tautology", type: "n.", meaning: "การใช้คำซ้ำซ้อนโดยไม่จำเป็น" },
    { word: "temerity", type: "n.", meaning: "ความบ้าบิ่น, ความกล้าหาญที่ขาดสติ" },
    { word: "temperance", type: "n.", meaning: "ความพอประมาณ, การไม่ดื่มสุรา" },
    { word: "tenable", type: "adj.", meaning: "ที่สามารถป้องกันได้, ที่สมเหตุสมผล" },
    { word: "tenacious", type: "adj.", meaning: "เหนียวแน่น, ยึดมั่น" },
    { word: "tenuous", type: "adj.", meaning: "บอบบาง, ไม่มั่นคง" },
    { word: "terse", type: "adj.", meaning: "ห้วน, กระชับ" },
    { word: "timorous", type: "adj.", meaning: "ขี้กลัว, ประหม่า" },
    { word: "tirade", type: "n.", meaning: "การตำหนิอย่างยาวนานและรุนแรง" },
    { word: "titular", type: "adj.", meaning: "ในนาม, เป็นเพียงตำแหน่ง" },
    { word: "torpid", type: "adj.", meaning: "เฉื่อยชา, เซื่องซึม" },
    { word: "tortuous", type: "adj.", meaning: "คดเคี้ยว, ซับซ้อน" },
    { word: "tractable", type: "adj.", meaning: "ว่าง่าย, ควบคุมได้" },
    { word: "transcendent", type: "adj.", meaning: "เหนือกว่า, ยอดเยี่ยม" },
    { word: "transient", type: "adj., n.", meaning: "ชั่วคราว, ไม่ถาวร" },
    { word: "travesty", type: "n.", meaning: "การบิดเบือนที่น่าขบขัน, การล้อเลียน" },
    { word: "trenchant", type: "adj.", meaning: "คมคาย, เฉียบขาด" },
    { word: "truculent", type: "adj.", meaning: "ก้าวร้าว, ดุร้าย" },
    { word: "truncate", type: "v.", meaning: "ตัดให้สั้นลง" },
    { word: "turgid", type: "adj.", meaning: "บวม, อวดอ้าง" },
    { word: "turpitude", type: "n.", meaning: "ความเลวทราม, ความชั่วร้าย" },
    { word: "ubiquitous", type: "adj.", meaning: "มีอยู่ทุกหนทุกแห่ง" },
    { word: "unctuous", type: "adj.", meaning: "ประจบสอพลอ, หวานเลี่ยน" },
    { word: "undulating", type: "adj.", meaning: "เป็นคลื่น, เป็นลูกคลื่น" },
    { word: "unfettered", type: "adj.", meaning: "เป็นอิสระ, ไม่มีข้อจำกัด" },
    { word: "untenable", type: "adj.", meaning: "ที่ไม่สามารถรักษาไว้ได้, ไม่สมเหตุสมผล" },
    { word: "upbraid", type: "v.", meaning: "ตำหนิ, ดุด่า" },
    { word: "urbane", type: "adj.", meaning: "สุภาพ, มีมารยาท" },
    { word: "vacillate", type: "v.", meaning: "ลังเล, โลเล" },
    { word: "vacuous", type: "adj.", meaning: "ว่างเปล่า, ไร้สาระ" },
    { word: "valorous", type: "adj.", meaning: "กล้าหาญ" },
    { word: "vapid", type: "adj.", meaning: "จืดชืด, ไม่มีชีวิตชีวา" },
    { word: "vehement", type: "adj.", meaning: "รุนแรง, ดุเดือด" },
    { word: "venal", type: "adj.", meaning: "รับสินบน, ทุจริต" },
    { word: "venerate", type: "v.", meaning: "เคารพ, นับถือ" },
    { word: "veracity", type: "n.", meaning: "ความสัตย์จริง, ความถูกต้อง" },
    { word: "verbose", type: "adj.", meaning: "เยิ่นเย้อ, ใช้คำฟุ่มเฟือย" },
    { word: "verdant", type: "adj.", meaning: "เขียวชอุ่ม" },
    { word: "verisimilitude", type: "n.", meaning: "ความสมจริง" },
    { word: "veritable", type: "adj.", meaning: "ที่แท้จริง, อย่างแท้จริง" },
    { word: "vex", type: "v.", meaning: "ทำให้รำคาญ, ทำให้หงุดหงิด" },
    { word: "vexatious", type: "adj.", meaning: "ก่อกวน, น่ารำคาญ" },
    { word: "vicarious", type: "adj.", meaning: "ที่รู้สึกเหมือนได้ทำเอง (จากการดู/อ่าน)" },
    { word: "vicissitude", type: "n.", meaning: "การเปลี่ยนแปลงขึ้นๆ ลงๆ (ในชีวิต)" },
    { word: "vigilant", type: "adj.", meaning: "ระมัดระวัง, ตื่นตัว" },
    { word: "vilify", type: "v.", meaning: "ใส่ร้าย, ทำให้เสียชื่อเสียง" },
    { word: "vindicate", type: "v.", meaning: "พิสูจน์ว่าบริสุทธิ์, ปกป้อง" },
    { word: "virulent", type: "adj.", meaning: "เป็นพิษร้ายแรง, ร้ายกาจ" },
    { word: "visceral", type: "adj.", meaning: "จากสัญชาตญาณ, จากความรู้สึกภายใน" },
    { word: "vitriolic", type: "adj.", meaning: "ประชดประชัน, แดกดัน" },
    { word: "vituperate", type: "v.", meaning: "ด่าว่าอย่างรุนแรง" },
    { word: "vociferous", type: "adj.", meaning: "เสียงดัง, โวยวาย" },
    { word: "volatile", type: "adj.", meaning: "ระเหยง่าย, เปลี่ยนแปลงเร็ว" },
    { word: "voluminous", type: "adj.", meaning: "มีปริมาณมาก" },
    { word: "voracious", type: "adj.", meaning: "ตะกละ, อยากรู้อยากเห็นอย่างมาก" },
    { word: "waive", type: "v.", meaning: "สละสิทธิ์, ยอมแพ้" },
    { word: "wanton", type: "adj.", meaning: "ไร้เหตุผล, มุ่งร้าย" },
    { word: "warrant", type: "v.", meaning: "รับประกัน, รับรอง" },
    { word: "wary", type: "adj.", meaning: "ระมัดระวัง" },
    { word: "wax", type: "v.", meaning: "เพิ่มขึ้น, ขยายใหญ่ขึ้น (พระจันทร์เต็มดวง)" },
    { word: "welter", type: "n.", meaning: "ความยุ่งเหยิง, การม้วนตัว" },
    { word: "whimsical", type: "adj.", meaning: "แปลกประหลาด, เล่นตลก" },
    { word: "wield", type: "v.", meaning: "ใช้อำนาจ, ถือ (อาวุธ)" },
    { word: "wistful", type: "adj.", meaning: "โหยหา, คิดถึง" },
    { word: "zealot", type: "n.", meaning: "ผู้คลั่งไคล้, ผู้ที่แสดงความกระตือรือร้นเกินไป" },
    { word: "zenith", type: "n.", meaning: "จุดสูงสุด, จุดสุดยอด" },
    { word: "zephyr", type: "n.", meaning: "ลมอ่อนๆ" },
];
