export interface Word {
    word: string;
    meaning: string;
}

const words = {
    easy: [
        { word: "cat", meaning: "สัตว์เลี้ยงลูกด้วยนมขนาดเล็กที่มีขนนุ่ม" },
        { word: "dog", meaning: "สัตว์เลี้ยงลูกด้วยนมที่กินเนื้อ มักมีจมูกยาว" },
        { word: "sun", meaning: "ดวงดาวที่โลกโคจรรอบ" },
        { word: "sky", meaning: "ท้องฟ้าและอวกาศที่มองเห็นได้จากโลก" },
        { word: "run", meaning: "เคลื่อนที่เร็วกว่าการเดิน" },
        { word: "eat", meaning: "นำอาหารเข้าปาก เคี้ยว และกลืน" },
        { word: "bed", meaning: "เฟอร์นิเจอร์ที่ใช้สำหรับนอนหลับหรือพักผ่อน" },
        { word: "car", meaning: "ยานพาหนะที่วิ่งบนถนน มักมีล้อสี่ล้อ ขับเคลื่อนด้วยเครื่องยนต์หรือมอเตอร์ไฟฟ้า" },
        { word: "key", meaning: "ชิ้นส่วนโลหะขนาดเล็กที่ถูกทำให้พอดีกับกุญแจ" },
        { word: "red", meaning: "สีที่อยู่ปลายสเปกตรัมถัดจากสีส้มและตรงข้ามกับสีม่วง" },
        { word: "blue", meaning: "สีที่อยู่ระหว่างสีเขียวและสีม่วง" },
        { word: "pen", meaning: "เครื่องมือสำหรับเขียนหรือวาดด้วยหมึก" },
        { word: "cup", meaning: "ภาชนะรูปชามขนาดเล็กสำหรับดื่ม" },
        { word: "hat", meaning: "สิ่งที่ใช้สวมศีรษะเพื่อให้ความอบอุ่น เป็นแฟชั่น หรือเป็นส่วนหนึ่งของเครื่องแบบ" },
        { word: "box", meaning: "ภาชนะที่มีฐานและด้านข้างแบนราบ มักเป็นรูปสี่เหลี่ยมและมีฝาปิด" },
        { word: "book", meaning: "งานเขียนหรือสิ่งพิมพ์ที่ประกอบด้วยหน้ากระดาษที่เย็บหรือติดกันและมีปก" },
        { word: "tree", meaning: "พืชยืนต้นที่มีลำต้นแข็งและเติบโตสูง" },
        { word: "ball", meaning: "วัตถุทรงกลมหรือรูปไข่ที่ใช้เตะ โยน หรือตีในเกม" },
        { word: "hand", meaning: "ส่วนปลายแขนถัดจากข้อมือ รวมถึงฝ่ามือ นิ้วมือ และนิ้วหัวแม่มือ" },
        { word: "foot", meaning: "ส่วนของขาใต้ข้อเท้าที่ใช้ยืนและเดิน" },
        { word: "fish", meaning: "สัตว์น้ำเลือดเย็นที่ไม่มีแขนขา มีเหงือกและครีบ" },
        { word: "bird", meaning: "สัตว์เลือดอุ่นที่ออกลูกเป็นไข่ มีขน ปีก และจะงอยปาก" },
        { word: "moon", meaning: "ดาวบริวารตามธรรมชาติของโลก มองเห็นได้ในเวลากลางคืนจากแสงสะท้อนจากดวงอาทิตย์" },
        { word: "star", meaning: "จุดสว่างบนท้องฟ้ายามค่ำคืนซึ่งเป็นดวงดาวขนาดใหญ่ที่อยู่ห่างไกลเหมือนดวงอาทิตย์" },
        { word: "rain", meaning: "น้ำที่กลั่นตัวจากบรรยากาศและตกลงมาเป็นหยด" }
    ],
    medium: [
        { word: "apple", meaning: "The round fruit of a tree of the rose family." },
        { word: "banana", meaning: "A long curved fruit which grows in clusters and has soft pulpy flesh and yellow skin when ripe." },
        { word: "orange", meaning: "A large round juicy citrus fruit with a tough bright reddish-yellow rind." },
        { word: "computer", meaning: "An electronic device for storing and processing data." },
        { word: "keyboard", meaning: "A panel of keys that operate a computer or typewriter." },
        { word: "mountain", meaning: "A large natural elevation of the earth's surface rising abruptly from the surrounding level." },
        { word: "ocean", meaning: "A very large expanse of sea." },
        { word: "beautiful", meaning: "Pleasing the senses or mind aesthetically." },
        { word: "language", meaning: "The method of human communication, either spoken or written." },
        { word: "example", meaning: "A thing characteristic of its kind or illustrating a general rule." },
        { word: "weather", meaning: "The state of the atmosphere at a place and time as regards heat, dryness, sunshine, wind, rain, etc." },
        { word: "journey", meaning: "An act of traveling from one place to another." },
        { word: "friend", meaning: "A person whom one knows and with whom one has a bond of mutual affection." },
        { word: "morning", meaning: "The period of time between midnight and noon." },
        { word: "evening", meaning: "The period of time at the end of the day, usually from about 6 p.m. to bedtime." },
        { word: "bicycle", meaning: "A vehicle composed of two wheels held in a frame one behind the other, propelled by pedals and steered with handlebars attached to the front wheel." },
        { word: "guitar", meaning: "A stringed musical instrument with a fretted fingerboard, typically incurved sides, and six or twelve strings, played by plucking or strumming." },
        { word: "kitchen", meaning: "A room or area equipped for preparing and cooking food." },
        { word: "library", meaning: "A building or room containing collections of books, periodicals, and sometimes films and recorded music for people to read, borrow, or refer to." },
        { word: "telephone", meaning: "A system for transmitting voices over a distance using wire or radio, by converting acoustic vibrations to electrical signals." },
        { word: "television", meaning: "A system for transmitting visual images and sound that are reproduced on screens, chiefly used to broadcast programs for entertainment, information, and education." },
        { word: "umbrella", meaning: "A device consisting of a circular canopy of cloth on a folding metal frame supported by a central rod, used as protection against rain or sometimes sun." },
        { word: "vacation", meaning: "An extended period of leisure and recreation, especially one spent away from home or in traveling." },
        { word: "window", meaning: "An opening in the wall or roof of a building or vehicle, fitted with glass or other transparent material in a frame to admit light or air and allow people to see out." },
        { word: "adventure", meaning: "An unusual and exciting, typically hazardous, experience or activity." },
        { word: "celebrate", meaning: "Acknowledge (a significant or happy day or event) with a social gathering or enjoyable activity." },
        { word: "discover", meaning: "Find (something or someone) unexpectedly or in the course of a search." },
        { word: "education", meaning: "The process of receiving or giving systematic instruction, especially at a school or university." },
        { word: "exercise", meaning: "Activity requiring physical effort, carried out to sustain or improve health and fitness." },
        { word: "family", meaning: "A group consisting of parents and children living together in a household." },
        { word: "government", meaning: "The governing body of a nation, state, or community." },
        { word: "happiness", meaning: "The state of being happy." },
        { word: "important", meaning: "Of great significance or value; likely to have a profound effect on success, survival, or well-being." },
        { word: "knowledge", meaning: "Facts, information, and skills acquired by a person through experience or education; the theoretical or practical understanding of a subject." },
        { word: "laughter", meaning: "The action or sound of laughing." },
        { word: "memory", meaning: "The faculty by which the mind stores and remembers information." },
        { word: "music", meaning: "Vocal or instrumental sounds (or both) combined in such a way as to produce beauty of form, harmony, and expression of emotion." },
        { word: "nature", meaning: "The phenomena of the physical world collectively, including plants, animals, the landscape, and other features and products of the earth, as opposed to humans or human creations." },
        { word: "opportunity", meaning: "A set of circumstances that makes it possible to do something." },
        { word: "patience", meaning: "The capacity to accept or tolerate delay, trouble, or suffering without getting angry or upset." },
        { word: "question", meaning: "A sentence worded or expressed so as to elicit information." },
        { word: "science", meaning: "The intellectual and practical activity encompassing the systematic study of the structure and behavior of the physical and natural world through observation and experiment." },
        { word: "strength", meaning: "The quality or state of being strong, in particular." },
        { word: "success", meaning: "The accomplishment of an aim or purpose." },
        { word: "technology", meaning: "The application of scientific knowledge for practical purposes, especially in industry." },
        { word: "together", meaning: "With or in proximity to another person or people." },
        { word: "tradition", meaning: "The transmission of customs or beliefs from generation to generation, or the fact of being passed on in this way." },
        { word: "universe", meaning: "All existing matter and space considered as a whole; the cosmos." },
        { word: "welcome", meaning: "An instance or manner of greeting someone." },
        { word: "yesterday", meaning: "On the day before today." }
    ],
    hard: [
        { word: "phenomenon", meaning: "A fact or situation that is observed to exist or happen, especially one whose cause or explanation is in question." },
        { word: "onomatopoeia", meaning: "The formation of a word from a sound associated with what is named." },
        { word: "procrastinate", meaning: "Delay or postpone action; put off doing something." },
        { word: "ubiquitous", meaning: "Present, appearing, or found everywhere." },
        { word: "serendipity", meaning: "The occurrence and development of events by chance in a happy or beneficial way." },
        { word: "ephemeral", meaning: "Lasting for a very short time." },
        { word: "eloquent", meaning: "Fluent or persuasive in speaking or writing." },
        { word: "nostalgia", meaning: "A sentimental longing or wistful affection for the past." },
        { word: "benevolent", meaning: "Well meaning and kindly." },
        { word: "idiosyncrasy", meaning: "A mode of behavior or way of thought peculiar to an individual." },
        { word: "juxtaposition", meaning: "The fact of two things being seen or placed close together with contrasting effect." },
        { word: "conscientious", meaning: "Wishing to do one's work or duty well and thoroughly." },
        { word: "exacerbate", meaning: "Make (a problem, bad situation, or negative feeling) worse." },
        { word: "quintessential", meaning: "Representing the most perfect or typical example of a quality or class." },
        { word: "cacophony", meaning: "A harsh, discordant mixture of sounds." },
        { word: "aberration", meaning: "A departure from what is normal, usual, or expected, typically one that is unwelcome." },
        { word: "acquiesce", meaning: "Accept something reluctantly but without protest." },
        { word: "anachronism", meaning: "A thing belonging or appropriate to a period other than that in which it exists." },
        { word: "boisterous", meaning: "Noisy, energetic, and cheerful; rowdy." },
        { word: "capitulate", meaning: "Cease to resist an opponent or an unwelcome demand; surrender." },
        { word: "cognizant", meaning: "Having knowledge or being aware of." },
        { word: "debilitate", meaning: "Make (someone) weak and infirm." },
        { word: "efficacious", meaning: "Successful in producing a desired or intended result; effective." },
        { word: "fastidious", meaning: "Very attentive to and concerned about accuracy and detail." },
        { word: "gregarious", meaning: "(Of a person) fond of company; sociable." },
        { word: "harangue", meaning: "A lengthy and aggressive speech." },
        { word: "iconoclast", meaning: "A person who attacks cherished beliefs or institutions." },
        { word: "incandescent", meaning: "Emitting light as a result of being heated." },
        { word: "lachrymose", meaning: "Tearful or given to weeping." },
        { word: "magnanimous", meaning: "Very generous or forgiving, especially toward a rival or someone less powerful than oneself." },
        { word: "maverick", meaning: "An unorthodox or independent-minded person." },
        { word: "nefarious", meaning: "(Typically of an action or activity) wicked or criminal." },
        { word: "obfuscate", meaning: "Render obscure, unclear, or unintelligible." },
        { word: "paradigm", meaning: "A typical example or pattern of something; a model." },
        { word: "pejorative", meaning: "Expressing contempt or disapproval." },
        { word: "querulous", meaning: "Complaining in a petulant or whining manner." },
        { word: "recalcitrant", meaning: "Having an obstinately uncooperative attitude toward authority or discipline." },
        { word: "sanguine", meaning: "Optimistic or positive, especially in an apparently bad or difficult situation." },
        { word: "taciturn", meaning: "(Of a person) reserved or uncommunicative in speech; saying little." },
        { word: "unctuous", meaning: "Excessively or ingratiatingly flattering; oily." },
        { word: "vex", meaning: "Make (someone) feel annoyed, frustrated, or worried, especially with trivial matters." },
        { word: "zealous", meaning: "Having or showing zeal." },
        { word: "abnegation", meaning: "The action of renouncing or rejecting something." },
        { word: "beguile", meaning: "Charm or enchant (someone), sometimes in a deceptive way." },
        { word: "candor", meaning: "The quality of being open and honest in expression; frankness." },
        { word: "dearth", meaning: "A scarcity or lack of something." },
        { word: "ebullient", meaning: "Cheerful and full of energy." },
        { word: "fatuous", meaning: "Silly and pointless." },
        { word: "garrulous", meaning: "Excessively talkative, especially on trivial matters." },
        { word: "hegemony", meaning: "Leadership or dominance, especially by one country or social group over others." },
        { word: "ignominious", meaning: "Deserving or causing public disgrace or shame." },
        { word: "jejune", meaning: "Naive, simplistic, and superficial." },
        { word: "ken", meaning: "One's range of knowledge or sight." },
        { word: "legerdemain", meaning: "Skillful use of one's hands when performing conjuring tricks." },
        { word: "mellifluous", meaning: "(Of a voice or words) sweet or musical; pleasant to hear." },
        { word: "nascent", meaning: "(Especially of a process or organization) just coming into existence and beginning to display signs of future potential." },
        { word: "obsequious", meaning: "Obedient or attentive to an excessive or servile degree." },
        { word: "palliate", meaning: "Make (a disease or its symptoms) less severe or unpleasant without removing the cause." },
        { word: "quagmire", meaning: "A soft boggy area of land that gives way underfoot." },
        { word: "rancor", meaning: "Bitterness or resentfulness, especially when long-standing." },
        { word: "salient", meaning: "Most noticeable or important." },
        { word: "tantamount", meaning: "Equivalent in seriousness to; virtually the same as." },
        { word: "utilitarian", meaning: "Designed to be useful or practical rather than attractive." },
        { word: "vilify", meaning: "Speak or write about in an abusively disparaging manner." },
        { word: "wanton", meaning: "(Of a cruel or violent action) deliberate and unprovoked." },
        { word: "xenophobia", meaning: "Dislike of or prejudice against people from other countries." },
        { word: "yoke", meaning: "A wooden crosspiece that is fastened over the necks of two animals and attached to the plow or cart that they are to pull." },
        { word: "zenith", meaning: "The time at which something is most powerful or successful." },
        { word: "acumen", meaning: "The ability to make good judgments and quick decisions, typically in a particular domain." },
        { word: "belligerent", meaning: "Hostile and aggressive." },
        { word: "circumspect", meaning: "Wary and unwilling to take risks." },
        { word: "demagogue", meaning: "A political leader who seeks support by appealing to popular desires and prejudices rather than by using rational argument." },
        { word: "epiphany", meaning: "A moment of sudden revelation or insight." },
        { word: "fortuitous", meaning: "Happening by accident or chance rather than design." },
        { word: "invective", meaning: "Insulting, abusive, or highly critical language." },
        { word: "mercurial", meaning: "Subject to sudden or unpredictable changes of mood or mind." },
        { word: "ostensible", meaning: "Stated or appearing to be true, but not necessarily so." },
        { word: "pernicious", meaning: "Having a harmful effect, especially in a gradual or subtle way." },
        { word: "rescind", meaning: "Revoke, cancel, or repeal (a law, order, or agreement)." },
        { word: "sycophant", meaning: "A person who acts obsequiously toward someone important in order to gain advantage." },
        { word: "turpitude", meaning: "Depraved or wicked behavior or character." },
        { word: "vicissitude", meaning: "A change of circumstances or fortune, typically one that is unwelcome or unpleasant." },
        { word: "winsome", meaning: "Attractive or appealing in appearance or character." },
        { word: "alacrity", meaning: "Bris_k and cheerful readiness." },
        { word: "clandestine", meaning: "Kept secret or done secretively, especially because illicit." },
        { word: "diaphanous", meaning: "(especially of fabric) light, delicate, and translucent." },
        { word: "erudite", meaning: "Having or showing great knowledge or learning." },
        { word: "fecund", meaning: "Producing or capable of producing an abundance of offspring or new growth; fertile." },
        { word: "grandiloquent", meaning: "Pompous or extravagant in language, style, or manner, especially in a way that is intended to impress." },
        { word: "impetuous", meaning: "Acting or done quickly and without thought or care." },
        { word: "kismet", meaning: "Destiny; fate." },
        { word: "moribund", meaning: "(of a person) at the point of death." },
        { word: "pithy", meaning: "(of language or style) concise and forcefully expressive." },
        { word: "quixotic", meaning: "Exceedingly idealistic; unrealistic and impractical." },
        { word: "rife", meaning: "(especially of something undesirable or harmful) of common occurrence; widespread." },
        { word: "staid", meaning: "Sedate, respectable, and unadventurous." },
        { word: "truculent", meaning: "Eager or quick to argue or fight; aggressively defiant." },
        { word: "umbrage", meaning: "Offense or annoyance." },
        { word: "vociferous", meaning: "Vigorous and forceful in speech." }
    ],
    expert: [
        { word: "abstruse", meaning: "Difficult to understand; obscure." },
        { word: "antediluvian", meaning: "Of or belonging to the time before the biblical Flood." },
        { word: "antipathy", meaning: "A deep-seated feeling of dislike; aversion." },
        { word: "arcane", meaning: "Understood by few; mysterious or secret." },
        { word: "ascetic", meaning: "Characterized by severe self-discipline and abstention from all forms of indulgence." },
        { word: "assiduous", meaning: "Showing great care and perseverance." },
        { word: "auspicious", meaning: "Conducive to success; favorable." },
        { word: "avuncular", meaning: "Kind and friendly toward a younger or less experienced person." },
        { word: "bawdy", meaning: "Dealing with sexual matters in a comical way; humorously indecent." },
        { word: "bilk", meaning: "Obtain or withhold money from (someone) by deceit or without justification; cheat or defraud." },
        { word: "bombastic", meaning: "High-sounding but with little meaning; inflated." },
        { word: "brackish", meaning: "(of water) slightly salty, as is the mixture of river water and seawater in estuaries." },
        { word: "bucolic", meaning: "Relating to the pleasant aspects of the countryside and country life." },
        { word: "burnish", meaning: "Polish (something, especially metal) by rubbing." },
        { word: "cabal", meaning: "A secret political clique or faction." },
        { word: "calumny", meaning: "The making of false and defamatory statements about someone in order to damage their reputation; slander." },
        { word: "capricious", meaning: "Given to sudden and unaccountable changes of mood or behavior." },
        { word: "castigate", meaning: "Reprimand (someone) severely." },
        { word: "caustic", meaning: "Able to burn or corrode organic tissue by chemical action." },
        { word: "celerity", meaning: "Swiftness of movement." },
        { word: "chary", meaning: "Cautiously or suspiciously reluctant to do something." },
        { word: "chicanery", meaning: "The use of trickery to achieve a political, financial, or legal purpose." },
        { word: "churlish", meaning: "Rude in a mean-spirited and surly way." },
        { word: "circuitous", meaning: "(of a route or journey) longer than the most direct way." },
        { word: "clairvoyant", meaning: "A person who claims to have a supernatural ability to perceive events in the future or beyond normal sensory contact." },
        { word: "clemency", meaning: "Mercy; lenience." },
        { word: "coalesce", meaning: "Come together and form one mass or whole." },
        { word: "coda", meaning: "A concluding event, remark, or section." },
        { word: "cogent", meaning: "(of an argument or case) clear, logical, and convincing." },
        { word: "comeliness", meaning: "The quality of being pleasant to look at; attractiveness." },
        { word: "commensurate", meaning: "Corresponding in size or degree; in proportion." },
        { word: "compendium", meaning: "A collection of concise but detailed information about a particular subject, especially in a book or other publication." },
        { word: "complaisant", meaning: "Willing to please others; obliging; agreeable." },
        { word: "conflagration", meaning: "An extensive fire which destroys a great deal of land or property." },
        { word: "congeal", meaning: "Solidify or coagulate, especially by cooling." },
        { word: "connoisseur", meaning: "An expert judge in matters of taste." },
        { word: "continence", meaning: "The ability to control movements of the bowels and bladder; self-restraint." },
        { word: "contrite", meaning: "Feeling or expressing remorse or penitence; affected by guilt." },
        { word: "convivial", meaning: "(of an atmosphere or event) friendly, lively, and enjoyable." },
        { word: "corporeal", meaning: "Relating to a person's body, especially as opposed to their spirit." },
        { word: "corroborate", meaning: "Confirm or give support to (a statement, theory, or finding)." },
        { word: "cosset", meaning: "Care for and protect in an overindulgent way." },
        { word: "countenance", meaning: "A person's face or facial expression." },
        { word: "craven", meaning: "Contemptibly lacking in courage; cowardly." },
        { word: "credulous", meaning: "Having or showing too great a readiness to believe things." },
        { word: "cupidity", meaning: "Greed for money or possessions." },
        { word: "curmudgeon", meaning: "A bad-tempered or surly person." },
        { word: "cynosure", meaning: "A person or thing that is the center of attention or admiration." },
        { word: "daunt", meaning: "Make (someone) feel intimidated or apprehensive." },
        { word: "decorum", meaning: "Behavior in keeping with good taste and propriety." },
        { word: "deign", meaning: "Do something that one considers to be beneath one's dignity." },
        { word: "demur", meaning: "Raise doubts or objections or show reluctance." },
        { word: "denigrate", meaning: "Criticize unfairly; disparage." },
        { word: "denizen", meaning: "An inhabitant or occupant of a particular place." },
        { word: "derision", meaning: "Contemptuous ridicule or mockery." },
        { word: "desiccate", meaning: "Remove the moisture from (something); cause to become completely dry." },
        { word: "desuetude", meaning: "A state of disuse." },
        { word: "desultory", meaning: "Lacking a plan, purpose, or enthusiasm." },
        { word: "detritus", meaning: "Waste or debris of any kind." },
        { word: "diatribe", meaning: "A forceful and bitter verbal attack against someone or something." },
        { word: "didactic", meaning: "Intended to teach, particularly in having moral instruction as an ulterior motive." },
        { word: "diffident", meaning: "Modest or shy because of a lack of self-confidence." },
        { word: "dilatory", meaning: "Slow to act." },
        { word: "dilettante", meaning: "A person who cultivates an area of interest, such as the arts, without real commitment or knowledge." },
        { word: "dirge", meaning: "A lament for the dead, especially one forming part of a funeral rite." },
        { word: "disabuse", meaning: "Persuade (someone) that an idea or belief is mistaken." },
        { word: "discomfit", meaning: "Make (someone) feel uneasy or embarrassed." },
        { word: "disparate", meaning: "Essentially different in kind; not allowing comparison." },
        { word: "dissemble", meaning: "Conceal one's true motives, feelings, or beliefs." },
        { word: "dissolute", meaning: "Lax in morals; licentious." },
        { word: "distaff", meaning: "Of or concerning women." },
        { word: "dither", meaning: "Be indecisive." },
        { word: "diurnal", meaning: "Of or during the day." },
        { word: "doggerel", meaning: "Verse or words that are badly written or expressed." },
        { word: "dogmatic", meaning: "Inclined to lay down principles as incontrovertibly true." },
        { word: "droll", meaning: "Curious or unusual in a way that provokes dry amusement." },
        { word: "dulcet", meaning: "(especially of sound) sweet and soothing." },
        { word: "dupe", meaning: "Deceive; trick." },
        { word: "dynamo", meaning: "A machine for converting mechanical energy into electrical energy; a generator." },
        { word: "effrontery", meaning: "Insolent or impertinent behavior." },
        { word: "effulgent", meaning: "Shining brightly; radiant." },
        { word: "egregious", meaning: "Outstandingly bad; shocking." },
        { word: "encomium", meaning: "A speech or piece of writing that praises someone or something highly." },
        { word: "endemic", meaning: "(of a disease or condition) regularly found among particular people or in a certain area." },
        { word: "enervate", meaning: "Cause (someone) to feel drained of energy or vitality; weaken." },
        { word: "engender", meaning: "Cause or give rise to (a feeling, situation, or condition)." },
        { word: "ennui", meaning: "A feeling of listlessness and dissatisfaction arising from a lack of occupation or excitement." },
        { word: "ensconce", meaning: "Establish or settle (someone) in a comfortable, safe, or secret place." },
        { word: "ersatz", meaning: "(of a product) made or used as a substitute, typically an inferior one, for something else." },
        { word: "eschew", meaning: "Deliberately avoid using; abstain from." },
        { word: "esoteric", meaning: "Intended for or likely to be understood by only a small number of people with a specialized knowledge or interest." },
        { word: "euphemism", meaning: "A mild or indirect word or expression substituted for one considered to be too harsh or blunt when referring to something unpleasant or embarrassing." },
        { word: "euphoria", meaning: "A feeling or state of intense excitement and happiness." },
        { word: "evanescent", meaning: "Soon passing out of sight, memory, or existence; quickly fading or disappearing." },
        { word: "exculpate", meaning: "Show or declare that (someone) is not guilty of wrongdoing." },
        { word: "execrable", meaning: "Extremely bad or unpleasant." },
        { word: "exigent", meaning: "Pressing; demanding." },
        { word: "expatiate", meaning: "Speak or write at length or in detail." },
        { word: "expiate", meaning: "Atone for (guilt or sin)." },
        { word: "expurgate", meaning: "Remove matter thought to be objectionable or unsuitable from (a book or account)." },
        { word: "extemporaneous", meaning: "Spoken or done without preparation." },
        { word: "extirpate", meaning: "Root out and destroy completely." },
        { word: "fallacious", meaning: "Based on a mistaken belief." },
        { word: "farrago", meaning: "A confused mixture." },
        { word: "feckless", meaning: "Lacking initiative or strength of character; irresponsible." },
        { word: "feculent", meaning: "Of or containing dirt, sediment, or waste matter." },
        { word: "fetter", meaning: "A chain or manacle used to restrain a prisoner, typically placed around the ankles." },
        { word: "fiat", meaning: "A formal authorization or proposition; a decree." },
        { word: "filigree", meaning: "Ornamental work of fine (typically gold or silver) wire formed into delicate tracery." },
        { word: "flag", meaning: "Become tired, weaker, or less enthusiastic." },
        { word: "flippant", meaning: "Not showing a serious or respectful attitude." },
        { word: "florid", meaning: "Having a red or flushed complexion." },
        { word: "flout", meaning: "Openly disregard (a rule, law or convention)." },
        { word: "foment", meaning: "Instigate or stir up (an undesirable or violent sentiment or course of action)." },
        { word: "forbearance", meaning: "Patient self-control; restraint and tolerance." },
        { word: "forestall", meaning: "Prevent or obstruct (an anticipated event or action) by taking action ahead of time." },
        { word: "fractious", meaning: "(typically of children) irritable and quarrelsome." },
        { word: "fulminate", meaning: "Express vehement protest." },
        { word: "fulsome", meaning: "Complimentary or flattering to an excessive degree." },
        { word: "furtive", meaning: "Attempting to avoid notice or attention, typically because of guilt or a belief that discovery would lead to trouble; secretive." },
        { word: "gambol", meaning: "Run or jump about playfully." },
        { word: "garner", meaning: "Gather or collect (something, especially information or approval)." },
        { word: "guile", meaning: "Sly or cunning intelligence." },
        { word: "habiliments", meaning: "Clothing." },
        { word: "hallow", meaning: "Honor as holy." },
        { word: "hapless", meaning: "(especially of a person) unfortunate." },
        { word: "harbinger", meaning: "A person or thing that announces or signals the approach of another." },
        { word: "hedonism", meaning: "The pursuit of pleasure; sensual self-indulgence." },
        { word: "hermetic", meaning: "(of a seal or closure) complete and airtight." },
        { word: "hoary", meaning: "Grayish white." },
        { word: "husband", meaning: "Use (resources) economically; conserve." },
        { word: "ignoble", meaning: "Not honorable in character or purpose." },
        { word: "imbroglio", meaning: "An extremely confused, complicated, or embarrassing situation." },
        { word: "immolate", meaning: "Kill or offer as a sacrifice, especially by burning." },
        { word: "impecunious", meaning: "Having little or no money." },
        { word: "imperious", meaning: "Assuming power or authority without justification; arrogant and domineering." },
        { word: "implacable", meaning: "Unable to be placated." },
        { word: "importune", meaning: "Harass (someone) persistently for or to do something." },
        { word: "impugn", meaning: "Dispute the truth, validity, or honesty of (a statement or motive); call into question." },
        { word: "impute", meaning: "Represent (something, especially something undesirable) as being done, caused, or possessed by someone; attribute." },
        { word: "inchoate", meaning: "Just begun and so not fully formed or developed; rudimentary." },
        { word: "incontrovertible", meaning: "Not able to be denied or disputed." },
        { word: "inculcate", meaning: "Instill (an attitude, idea, or habit) by persistent instruction." },
        { word: "indolent", meaning: "Wanting to avoid activity or exertion; lazy." },
        { word: "ineluctable", meaning: "Unable to be resisted or avoided; inescapable." },
        { word: "inexorable", meaning: "Impossible to stop or prevent." },
        { word: "ingenuous", meaning: "(of a person or action) innocent and unsuspecting." },
        { word: "iniquity", meaning: "Immoral or grossly unfair behavior." },
        { word: "insipid", meaning: "Lacking flavor." },
        { word: "insouciant", meaning: "Showing a casual lack of concern; indifferent." },
        { word: "interregnum", meaning: "A period when normal government is suspended, especially between successive reigns or regimes." },
        { word: "intractable", meaning: "Hard to control or deal with." },
        { word: "intransigent", meaning: "Unwilling or refusing to change one's views or to agree about something." },
        { word: "intrepid", meaning: "Fearless; adventurous (often used for rhetorical or humorous effect)." },
        { word: "inundate", meaning: "Overwhelm (someone) with things or people to be dealt with." },
        { word: "inure", meaning: "Accustom (someone) to something, especially something unpleasant." },
        { word: "invidious", meaning: "(of an action or situation) likely to arouse or incur resentment or anger in others." },
        { word: "irascible", meaning: "Having or showing a tendency to be easily angered." },
        { word: "itinerant", meaning: "Traveling from place to place." },
        { word: "jettison", meaning: "Throw or drop (something) from an aircraft or ship." },
        { word: "jocose", meaning: "Playful or humorous." },
        { word: "juggernaut", meaning: "A huge, powerful, and overwhelming force or institution." },
        { word: "kowtow", meaning: "Act in an excessively subservient manner." },
        { word: "lambaste", meaning: "Criticize (someone or something) harshly." },
        { word: "largesse", meaning: "Generosity in bestowing money or gifts upon others." },
        { word: "lassitude", meaning: "A state of physical or mental weariness; lack of energy." },
        { word: "libertine", meaning: "A person, especially a man, who behaves without moral principles or a sense of responsibility, especially in sexual matters." },
        { word: "limpid", meaning: "(of a liquid) free of anything that darkens; completely clear." },
        { word: "loquacious", meaning: "Tending to talk a great deal; talkative." },
        { word: "lubricious", meaning: "Offensively displaying or intended to arouse sexual desire." },
        { word: "lucid", meaning: "Expressed clearly; easy to understand." },
        { word: "lugubrious", meaning: "Looking or sounding sad and dismal." },
        { word: "machination", meaning: "A plot or scheme." },
        { word: "madrigal", meaning: "A part-song for several voices, especially one of the Renaissance period, typically arranged in elaborate counterpoint and without instrumental accompaniment." },
        { word: "malinger", meaning: "Exaggerate or feign illness in order to escape duty or work." },
        { word: "malleable", meaning: "(of a metal or other material) able to be hammered or pressed permanently out of shape without breaking or cracking." },
        { word: "maudlin", meaning: "Self-pityingly or tearfully sentimental, often through drunkenness." },
        { word: "mendacious", meaning: "Not telling the truth; lying." },
        { word: "mendicant", meaning: "Given to begging." },
        { word: "mettlesome", meaning: "(of a person or animal) full of spirit and courage." },
        { word: "misanthrope", meaning: "A person who dislikes humankind and avoids human society." },
        { word: "mitigate", meaning: "Make less severe, serious, or painful." },
        { word: "mollify", meaning: "Appease the anger or anxiety of (someone)." },
        { word: "multifarious", meaning: "Many and of various types." },
        { word: "mundane", meaning: "Lacking interest or excitement; dull." },
        { word: "myopic", meaning: "Nearsighted." },
        { word: "nadir", meaning: "The lowest point in the fortunes of a person or organization." },
        { word: "nebulous", meaning: "In the form of a cloud or haze; hazy." },
        { word: "neophyte", meaning: "A person who is new to a subject, skill, or belief." },
        { word: "nettle", meaning: "Irritate or annoy (someone)." },
        { word: "noisome", meaning: "Having an extremely offensive smell." }
    ]
};

// Function to get words based on difficulty
export const getWords = (difficulty: string): Word[] => {
    switch (difficulty) {
        case 'easy':
            return words.easy;
        case 'medium':
            return words.medium;
        case 'hard':
            return words.hard;
        case 'expert':
            return words.expert;
        default:
            return words.medium; // Default to medium
    }
};

// Function to shuffle an array
const shuffleArray = <T>(array: T[]): T[] => {
    const newArray = [...array];
    for (let i = newArray.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [newArray[i], newArray[j]] = [newArray[j], newArray[i]];
    }
    return newArray;
};

// Function to get a shuffled list of words for a game session
export const getGameSessionWords = (difficulty: string): Word[] => {
    const wordList = getWords(difficulty);
    return shuffleArray(wordList);
}; 